### ISSUE TITLE
Tab indicator incorrectly positioned if width changes (e.g. scrollbars)

### ISSUE THREAD

**Issue by MAProsper** [Dogfalo/materialize#5914] opened 2018-05-12 15:24 UTC
Imagine a tab filled with content that needs a scrollbar to view it, then add a second short tab without much content and therefore no scrollbar.

  _#5803 might be another example of this bug._

## Expected Behavior
Clicking tabs should update the tab indicator correctly, underlining the current one.

## Current Behavior
Changing between tabs that cause the width to change (for example adding or removing a scrollbar) the indicator is incorrectly positioned. Triggering `tabs.updateTabIndicator()` will not fix the issue, but clicking the current tab again yes.

## Possible Solution
Call the code responsible of the indicator after the tabs have been switched.

## Steps to Reproduce
1. Access this [CodePen](https://codepen.io/maprosper/pen/NMMQVJ) example.
2. Switch between tabs, indicator will be placed incorrectly.

## Context
While filling up information in my website and testing it I notice the bug. Which only occured on tabs with different amounts of content, being trigger by scrollbars appearing and disappearing.

## Environment
* Version used: v1.0.0-beta
* Browser Name and version: Chrome 66.0.3359.139 (Build oficial) (64 bits)
* Operating System and version: Windows 10 Home, 1803

**Comment by acburst** [comment] 2018-05-14 23:27
Duplicate of #5868

**Closed as completed** 2018-05-15 14:51 UTC
