### ISSUE TITLE
select doesn't display properly in modal

### ISSUE THREAD

**Issue by spencer4of6** [Dogfalo/materialize#2827] opened 2016-02-22 16:18 UTC
The select dropdown should (in my opinion) display outside the modal, rather than causing the modal to scroll.

https://jsfiddle.net/spencer4of6/bgp03L02/

**Comment by Ragsboss** [comment] 2016-03-03 21:05
+1, even we are affected by this bug.

**Comment by apolzon** [comment] 2016-03-29 19:13
+1, this became an issue when the custom dropdown ul was moved to be next to the origin instead of attached to the body element.

The workaround I'm currently using is to detect when the origin is inside `.modal-content` and adjust the `windowHeight` variable to reflect the modal height instead:
https://github.com/apolzon/materialize/commit/5017272c6fe58ad06738edc05312d3121f3d302b

**Comment by waspinator** [comment] 2017-03-16 20:19
any chance there could be an option to add the drop down into the body, as they do with https://silviomoreto.github.io/bootstrap-select/examples/#container

**Comment by tomscholz** [comment] 2017-07-21 19:42
Duplicate of https://github.com/Dogfalo/materialize/issues/2557

**Closed by tomscholz** 2017-07-21 19:42 UTC
Labels: component:Modal, component:Select
