### ISSUE TITLE
Fixed Action Button Fix Reactiong Area

### ISSUE THREAD

**Issue by Isprago** [Dogfalo/materialize#1305] opened 2015-05-06 10:29 UTC
This button displays other buttons on mousover.

But when you mousover the red rectangle, the other buttons haven't to be displayed, but for now the buttons are displayed.

I think the correct performance is:
- The other buttons are displayed when you mouseover or click the green rectangle (the button).
- After that, the other buttons are displayed while the mouse is over the blue rectangle.
- When you mousover the red rectangle, nothing happens.

![ficedbreac](https://cloud.githubusercontent.com/assets/9127964/7491565/b86dca86-f3ea-11e4-94e6-c8db851c3501.PNG)
![pag2](https://cloud.githubusercontent.com/assets/9127964/7491648/8d7b10bc-f3eb-11e4-9d12-ff2dad4ad1bf.PNG)

**Comment by michelreyes** [comment] 2015-05-06 11:59
Even when you put your mouse over the invisible UL container the floatin buttons appear.
Other, when the invisible UL is over other app elements those elements can click or controller

**Comment by michelreyes** [comment] 2015-05-06 12:00
Even when you put your mouse over the invisible UL container the floatin buttons appear.
Other, when the invisible UL is over other app elements those elements can click or controller

**Comment by michelreyes** [comment] 2015-05-06 12:53
I config the code to solve the problem like this
On button.js

var fabOptions = $('.fab__options');
    var fabOptionsHeight = fabOptions.outerHeight();
    fabOptions.css({
        top: fabOptionsHeight
    });

On: Mouse enter
--------------------
fabOptions.velocity(
       {opacity:1}, {duration:0}
      )
      .velocity(
        { top: '-'+fabOptionsHeight+'px' }, { duration: 80 }
      );

On: Mouse leave
---------------------
fabOptions.velocity(
          { opacity: 0 }, { duration: 0, delay: 200 }
        ).velocity(
          { top: fabOptionsHeight }, { duration: 0, delay: 201 }
        );

It's not the best option bat it solve the problem I hope the development team solve it in other better way.

**Comment by Dogfalo** [comment] 2015-05-06 16:35
We may change the behavior, but this is how the FAB works on inbox.google.com right now.

**Comment by Isprago94** [comment] 2015-05-06 16:58
Well, I had problems when I tried to scroll down/up website on my smartphone because I dragged down over this area, so the UL was being showed instead scroll the website.

If the correct behavoir is like on inbox.google.com I will try change the UI to prevent.

**Comment by michelreyes** [comment] 2015-05-06 22:49
Dogfalo you say:
We may change the behavior

When did you will make that change?

**Comment by Dogfalo** [comment] 2015-05-08 18:29
Duplicate of #729

**Closed by Dogfalo** 2015-05-08 18:29 UTC
