### ISSUE TITLE
Preselected in collapsible no longer works

### ISSUE THREAD

**Issue by MastaBaba** [Dogfalo/materialize#4397] opened 2017-03-25 15:14 UTC
### Description
In a collapsible, applying 'active' as a class to a preselected item no longer opens that item by default.

### Repro Steps
Check the official website, see the appropriate section under 'Collapsible'.

This works in 0.98.0, not in 0.98.1.

**Comment by acburst** [comment] 2017-03-26 04:45
Duplicate of #4375

**Closed** 2017-03-26 23:53 UTC
