### ISSUE TITLE
#sidenav-overlay { z-index: 996; }

### ISSUE THREAD

**Issue by 772test** [Dogfalo/materialize#5819] opened 2018-04-13 23:17 UTC
#sidenav-overlay {
    z-index: 996;
}
NOT
#sidenav-overlay {
    z-index: 997;
}
Simple typo i think... year later

**Comment by tomscholz** [comment] 2018-04-17 23:53
Please take a look at our issue submission guidelines. In order to keep our issues organized make sure to write a detailed write up about the issue with screenshots or code examples. Also I believe, that this is a duplicate of #3844

**Closed** 2018-04-18 16:55 UTC
