### ISSUE TITLE
jQuery 3 compatibility?

### ISSUE THREAD

**Issue by isaachinman** [Dogfalo/materialize#3240] opened 2016-06-10 18:10 UTC
So [jQuery 3 has finally been released](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/). I've just tried updating via npm and running a bundle with the Materialize script, there are breakages.

Not sure how well-supported Materialize is anymore, but I'm wondering if there are plans to make it jQuery 3 compatible, or if you guys would be open to a PR?

**Comment by carlosperate** [comment] 2016-06-10 20:22
Duplicate of:https://github.com/Dogfalo/materialize/issues/3201

**Closed** 2016-06-19 00:24 UTC
