### ISSUE TITLE
Column Offset Being Overridden

### ISSUE THREAD

**Issue by mattrixk** [Dogfalo/materialize#2328] opened 2015-11-19 00:07 UTC
materialize-v0.97.3

A pretty glaring issue...

eg: I need a 'col s6' to be in the middle of the row, so I use 'offset-3':

![materializecss_offset1](https://cloud.githubusercontent.com/assets/15916338/11258448/d97682a4-8ea4-11e5-9ad4-e4693e358bdf.png)
(screenshot from Firebug)

This works fine on the http://materializecss.com/ website, but not on my local machine.

Unfortunately, the s6 has a left margin of zero, and as it comes after the offset in the style sheet, it overrides the margin on the offset.

![materializecss_offset2](https://cloud.githubusercontent.com/assets/15916338/11258461/f2813f50-8ea4-11e5-95d1-686590e63103.png)
(screenshot from Firebug, but same problem exists in Chrome)

The ghpages-materialize.css being used on the http://materializecss.com/ website is identical to the one in the materialize-v0.97.3.zip download file, except it is missing the [margin-left: 0;] on every <.row .col.xx> *. 

If I remove the [margin-left: 0;] from every <.row .col.xx>, then it all works as it's supposed to (at least as far as I can tell).

I just thought I should bring this to your attention for the next release.

[note: I would add a codepen, but they are using v0.97.0 of the css, and it doesn't have this issue.]
*And has a bunch of extra page styling at the bottom, but that is inconsequential to the issue.

**Comment by acburst** [comment] 2015-11-19 01:48
#2325, #2323, #2316, #2313, #2312, #2308.

Please people, try and use the search bar in issues first and search through closed issues. I will keep this issue open in hopes that more people don't keep opening issues.

To reiterate, fixed in d5db2a3. So if you need a fix asap you can either rollback your version, or get our github master version. We are working hard on squashing these bugs but a release won't happen for at least a week. We are setting up more elaborate tests with Jasmine and integrating with Travis CI to help but this will also take some time. 

(Sorry @mattrixk if this seems personal. It is not, we've just seen this issue many times. I do appreciate the effort and quality of your issue tho :))

**Comment by mattrixk** [comment] 2015-11-19 02:09
Ahh, wow. Oops. Sorry about that @acburst . That really is a lot of raised issues isn't it? I did a search for "offset" but didn't find anything, so I raised my own. I didn't think to try any closed issues.

Also, don't worry, no offence was taken, but I do feel a bit of a boob now. I shall endeavour to search more thoroughly in the future.

**Comment by Keltah** [comment] 2015-11-21 17:37
Oups, sorry @acburst , first time on GitHub!

**Comment by bojidar-bg** [comment] 2015-12-08 16:07
Maybe the problem is that nobody searches for `offset column`, but instead for `offset grid`?

**Comment by acburst** [comment] 2015-12-21 02:56
New release is out!

**Closed by acburst** 2015-12-21 02:56 UTC
