### ISSUE TITLE
Can't click button on swipeable tabs

### ISSUE THREAD

**Issue by edisoni1995** [Dogfalo/materialize#4711] opened 2017-05-21 14:53 UTC
I am using swipeable tabs and inside one tab i have a button. I have used jquery to make some actions when the button is clicked but i can't get the event fired. Is there any way to use click events in swipeable tabs ?

**Comment by DanielRuf** [comment] 2017-05-22 05:57
Probably duplicate of https://github.com/Dogfalo/materialize/issues/4380

**Closed** 2017-05-22 08:07 UTC
