### ISSUE TITLE
New Feature: User in SideNav

### ISSUE THREAD

**Issue by ano95** [Dogfalo/materialize#2713] opened 2016-01-28 11:32 UTC
I would like to add user information and actions (logout, profile...) to the sidenav.
[Like here](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content)

**Comment by Dogfalo** [comment] 2016-01-31 04:34
Duplicate of #1322

**Closed by Dogfalo** 2016-01-31 04:34 UTC
