### ISSUE TITLE
Facing non smooth transform.

### ISSUE THREAD

**Issue by roxcity** [Dogfalo/materialize#4833] opened 2017-06-18 16:42 UTC
The transforms are not smooth. I am using angular2-materialize in my angular project. I don't know what's causing this laggy transform when using slideable tabs, modals, etc.

**Comment by DanielRuf** [comment] 2017-06-18 17:20
@roxcity a bit more information would be helpful. Which version materialize and angular2.materialize do you use and on which devices are the transforms slow?

**Comment by roxcity** [comment] 2017-06-18 18:19
@DanielRuf I did exactly like this: https://github.com/InfomediaLtd/angular2-materialize#installing-and-configuring-angular2-materialize-with-webpack. Transforms are sometimes smooth but mostly not. I am using laptop.

**Comment by DanielRuf** [comment] 2017-06-18 18:25
@roxcity do you have any real example where the transitions are not smooth? Something that we can test in a simple codepen? So we can make sure where this comes from and what the cause is.

**Comment by krosoftware** [comment] 2017-06-18 20:12
I see a problem by opening SideNav (your original example from here: http://materializecss.com/side-nav.html - but only when I use full screen.
With other words - when my browser is on full screen (Chrome) I see flickering when I click on "Side Nav demo" Button.
When I don't use full screen or when I use Edge (on any screen size) - flickering is gone.

**Comment by DanielRuf** [comment] 2017-06-18 20:18
@krosoftware this sounds like a different issue. Please open a new issue and a codepen to reproduce / demonstrate this behavior if this is the case.

**Comment by krosoftware** [comment] 2017-06-19 05:39
@DanielRuf just resize your Chrome browser to ~75% size and navigate to http://materializecss.com/side-nav.html and click on "Side Nav demo" Button - SideNav is opened smooth and fine.
Then resize your browser window to 100% (click on maximize on upper right corner) and click on "Side Nav demo" Button again - you will see flickering by SideNav opening.

**Comment by roxcity** [comment] 2017-06-20 15:36
Looks like I need to compile angular for smooth transform. Its only flickering when I use it during development. Its works fine in production.

**Comment by DanielRuf** [comment] 2017-06-20 17:06
So it is not related to Materialize as it seems.
If this is the case close the issue.

**Closed** 2017-06-20 17:13 UTC
