### ISSUE TITLE
CORS Issue with loading WebFont

### ISSUE THREAD

**Issue by WillsB3** [Dogfalo/materialize#3033] opened 2016-04-12 20:34 UTC
Hi,

I've been trying to get Materialize working in my Web App however the WebFont doesn't seem to be loading from the CDN.

For example: http://output.jsbin.com/xulohapoxe/1/?output. As you can see in the console there are errors relating to CORS.

Have I missed something?

Thanks

**Comment by uok** [comment] 2016-04-13 11:52
seems like duplicate of #2989

**Comment by Dogfalo** [comment] 2016-05-07 19:25
This problem is resolved now as the font is being hosted on CDNJS at the right path

**Closed by Dogfalo** 2016-05-07 19:25 UTC
