### ISSUE TITLE
Select does not update, when your change it from JS

### ISSUE THREAD

**Issue by Saiberbest** [Dogfalo/materialize#466] opened 2015-01-15 12:44 UTC
I do some changes in this function:
```javascript
$.fn.material_select = function () {
      $(this).each(function(){
        $select = $(this);
        if ( $select.hasClass('browser-default') || $select.hasClass('initialized')) {
          var span = $select.parent().children('span');
          var uniqueID = span.attr('data-activates');
          var options = $('#' + uniqueID);
          options.empty();
          //return; // Continue to next (return false breaks out of entire loop)
        }else{
         var uniqueID = 'select-options-'+guid();
         var options = $('<ul id="' + uniqueID+'" class="dropdown-content select-dropdown"></ul>');
         var wrapper = $('<div class="select-wrapper"></div>');
        }


        var selectOptions = $select.children('option');
        if ($select.find('option:selected') !== undefined) {
          var label = $select.find('option:selected');
        }
        else {
          var label = options.first();
        }


        // Create Dropdown structure
        selectOptions.each(function () {
          // Add disabled attr if disabled
          options.append($('<li class="' + (($(this).is(':disabled')) ? 'disabled' : '') + '"><span>' + $(this).html() + '</span></li>'));
        });


        options.find('li').each(function (i) {
          var $curr_select = $select;
          $(this).click(function () {
            // Check if option element is disabled
            if (!$(this).hasClass('disabled')) {
              $curr_select.find('option').eq(i).prop('selected', true);
              // Trigger onchange() event
              if (typeof($curr_select.context.onchange) === "function") {
                $curr_select[0].onchange();
              }
              $curr_select.prev('span.select-dropdown').html($(this).text());
            }
          });

        });
        if ( $select.hasClass('browser-default') || $select.hasClass('initialized')) {
          span.html(label.html());
        }else{
          // Wrap Elements
          $select.wrap(wrapper);
          // Add Select Display Element
          var $newSelect = $('<span class="select-dropdown ' + (($select.is(':disabled')) ? 'disabled' : '')
                           + '" data-activates="' + uniqueID +'">' + label.html() + '</span>');
          $select.before($newSelect);
          $('body').append(options);
          // Check if section element is disabled
          if (!$select.is(':disabled')) {
            $newSelect.dropdown({"hover": false});
          }
          $select.addClass('initialized');
        }      

      });
    };
```

**Comment by svartalf** [comment] 2015-01-15 15:24
Maybe you should create pull request for it? At least diff with highlighted changes will be more useful ;)

**Comment by carlosperate** [comment] 2015-01-23 00:01
This seems to be relevant to issue https://github.com/Dogfalo/materialize/issues/452
A pull request would definitely be appreciated.

**Comment by Dogfalo** [comment] 2015-01-23 17:53
duplicate of #452

**Closed by Dogfalo** 2015-01-23 17:53 UTC
