### ISSUE TITLE
icons for sub-buttons on floating button menu is offset in safari and mobile safari 

### ISSUE THREAD

**Issue by appjitsu** [Dogfalo/materialize#2111] opened 2015-10-02 10:07 UTC
I am working on a meteor project and I am using the latest version of https://github.com/poetic/meteor-materialize-sass. They say it's the actual css that is causing the issue.

When I test in the emulator for mobile safari and normal desktop safari, the icons for the sub-buttons on a floating button menu is offset.

<img width="64" alt="screen shot 2015-10-02 at 3 41 48 am" src="https://cloud.githubusercontent.com/assets/10903600/10242622/c0abd7f0-68b7-11e5-917c-679dc8c2537f.png">

Looks OK for desktop Chrome, Android and Firefox.

Sample code:

```
<div class="fixed-action-btn active" style="bottom: 45px; right: 24px;">
     <a class="btn-floating btn-large red">
      <i class="mdi-content-add"></i>
   </a>
  <ul>
       <li>
           <a href="#" class="btn-floating red" title="New Application" style="transform: scaleY(1) scaleX(1) translateY(0px); opacity: 1;">
                <i class="material-icons">note_add</i>
           </a>
      </li>
   ....
  </ul>
</div>
```

**Comment by appjitsu** [comment] 2015-10-02 10:09
I temporarily fixed this with:

    // fix sub-button icons on the floating button menus for mobile safari
    @media only screen and (min-device-width: 768px) and (max-device-width: 1024px),
    only screen and (max-device-width: 480px)
    {
        i.material-icons {
            position: absolute;
            left: 9px;
        }
    }

**Comment by martindidiego** [comment] 2015-10-03 01:46
Looks fine on my end. Desktop Safari 9.0 and Mobile Safari iOS 9.0.1. 

![img_1590](https://cloud.githubusercontent.com/assets/14933234/10260914/f8aa7962-694e-11e5-9b83-e8527848efaf.jpg)

**Comment by appjitsu** [comment] 2015-10-03 02:08
Then maybe that meteor package needs to be updated?

**Comment by HarveyKandola** [comment] 2015-10-15 22:15
This bug still exists with v0.97.1 running on OSX El Capitan, Safari v9 -- CSS snippet from @appjitsu fixes Safari Desktop browser if you target the specific browser:

```
@supports (overflow:-webkit-marquee) and (justify-content:inherit)
{
    i.material-icons
    {
        position: absolute;
        left: 7px;
    }
}
```

Horrible "fix".

**Comment by tomscholz** [comment] 2017-04-01 23:41
@DanielRuf Can you confirm this? Otherwise I would close this issue :)

**Comment by DanielRuf** [comment] 2017-04-02 10:01
@tomscholz unfortunately I do not have any environment or device with Safari by Apple so I can not test it so easily. If it works as intended and the issue is solved, we can safely close this issue here.

**Comment by tomscholz** [comment] 2017-04-02 10:14
@DanielRuf Perfect 👌

**Closed by tomscholz** 2017-04-02 10:14 UTC
