### ISSUE TITLE
Zoomed in Material Box does not adapt to orientation changes

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#510] opened 2015-01-22 10:52 UTC
If you tap on a picture and change from portrait to landscape orientation, the picture will remain unchanged in size, although there's plenty of space to the right and bottom.

If you change from landscape to portrait, it won't fit anymore and if you try to pan, you will zoom out / close the material box.

![screenshot_2015-01-22-11-49-34](https://cloud.githubusercontent.com/assets/1309249/5854345/1c318766-a22d-11e4-9d4d-b3e948add790.png)

**Comment by kmmbvnr** [comment] 2016-11-23 06:31
Isn't this duplicate of #502?

**Comment by CoDEmanX** [comment] 2016-11-24 20:35
No, this one is about the image not using up the available space, the other issue is about temporary loss of the correct aspect ratio (during animation).

**Comment by tomscholz** [comment] 2017-04-02 23:51
When a material box is open and you flip your phone it closes.

**Closed by tomscholz** 2017-04-02 23:51 UTC
