### ISSUE TITLE
Select Dropdown exceeds screen height

### ISSUE THREAD

**Issue by hueyy** [Dogfalo/materialize#1276] opened 2015-04-30 13:27 UTC
When the materialised `<select>` is near/at the bottom of the screen, its dropdown can exceed the screen. This is especially so for smaller screen sizes (more likely to happen):
![dropdown](http://i.imgur.com/ZjaDqGim.png)

Also seen on [materializecss.com](materializecss.com)

![screenshot1](http://i.imgur.com/wJKXr6lm.png)
![screenshot2](http://i.imgur.com/4fVcWI3m.png)
I suggest reversing placing the `<select>` above the option in such cases, as is done by Google:

![contacts1](http://i.imgur.com/HEirl3Km.png)
![contacts2](http://i.imgur.com/kWYWemVm.png)

**Comment by olivier67** [comment] 2015-05-02 11:34
+1

**Comment by btecu** [comment] 2015-05-04 00:24
Same problem on a computer (not phone).

**Comment by csapir** [comment] 2015-05-05 00:06
+1 on computer. dropdown extends below screen.

**Comment by akyunus** [comment] 2015-05-07 07:21
+1 how to limit the height of dropdown?

**Comment by getupkid203** [comment] 2015-05-15 08:29
U can set a fixed height on the dropdown itself and set overflow-y to hidden.

**Comment by ciencia** [comment] 2015-05-18 15:19
Seems to be a dupe of Issue #780

**Comment by bbshopadmin** [comment] 2015-07-01 22:52
+1

**Comment by meichenblatt** [comment] 2015-08-03 23:25
+1

**Comment by w0rldart** [comment] 2015-10-21 14:50
+1

**Comment by viniciusparedes** [comment] 2015-11-03 04:39
+1
Any solution?

**Comment by acburst** [comment] 2015-11-03 06:40
This has been added in 88f6ddd93a183b298d0bfaa56f02624c5da55bab.

It is available on master and will be live in the next release.

**Closed by acburst** 2015-11-03 06:40 UTC

**Comment by khlJunior** [comment] 2015-11-13 12:50
Ok, now it goest to top when the height is bigger than the window size, but if i have a lot of options the select will just grow to top and hide the options.

There's a way to add a scroll inside the select?

**Comment by acburst** [comment] 2015-11-13 19:18
I can look into adding a max-height

**Comment by khlJunior** [comment] 2015-11-13 20:38
I didnt saw the max height, and in my case the max-height will not solve my proble. So, in my case my fix saves me because of my code. I will take a look on the max-height. Thanks! :) Sorry.

**Comment by fehmathais** [comment] 2015-12-09 18:16
+1, I'm looking for news

**Comment by DanielRuf** [comment] 2020-05-29 11:04
This is still relevant for the latest v1-dev as it seems.

**Comment by caglarorhan** [comment] 2020-06-02 21:48
+1
