### ISSUE TITLE
Feature Request: allow HTML in tooltips

### ISSUE THREAD

**Issue by k4kfh** [Dogfalo/materialize#2064] opened 2015-09-21 16:33 UTC
I'd like to see the ability to use normal HTML in a tooltip, particularly because it would mean you would be able to use buttons. I could make a UI where I could hover over something and an "EDIT" or "CLOSE" button would appear. I think this would be useful, anyone else?

**Comment by TyrionGraphiste** [comment] 2015-09-21 17:52
You just have to change the line 59 into the tooltip.js file to :

    newTooltip.children('span').html(origin.attr('data-tooltip'));

**Comment by carlosperate** [comment] 2015-09-23 16:37
Duplicate of https://github.com/Dogfalo/materialize/issues/1537.

**Closed by carlosperate** 2015-09-23 16:37 UTC

**Comment by drusepth** [comment] 2017-02-24 17:09
Curious: why is this not the default behavior?

**Comment by k4kfh** [comment] 2017-02-24 17:11
I'm not really sure, that's what I was wondering. Seems easier to have a
way to *disable *it than to enable it.
