### ISSUE TITLE
Searchbar on navbar broken on Google Chrome

### ISSUE THREAD

**Issue by guilpejon** [Dogfalo/materialize#3250] opened 2016-06-13 04:18 UTC
I noticed this error in the documentation page, search bar section (http://materializecss.com/navbar.html). 
I'm attaching a picture of the error below, but basically the search input (when clicked) is floating above the place where it was supposed to be, and I was able to reproduce this error in my project too.

Digging around the HTML, I noticed that this can be fixed with two `height: 100%`. One on the `<form>` tag, and another one on the `<div class="input-field">` right below it.

Don't know what is the right way to fix this, but I can try to add this solution to the code if someone points me the way.

BTW, I'm using version 51.0.2704.84 (64-bit) of Google Chrome, and the form works fine on Safari and Firefox.

<img width="883" alt="captura de tela 2016-06-13 as 1 08 20 am" src="https://cloud.githubusercontent.com/assets/871362/15996920/bc224718-3103-11e6-901f-988c3ab453d3.png">

**Comment by Kail0** [comment] 2016-06-15 09:11
Duplicate of #3161

**Closed** 2016-07-01 03:12 UTC
