### ISSUE TITLE
material_select broken in 0.97.2

### ISSUE THREAD

**Issue by jfretin** [Dogfalo/materialize#2265] opened 2015-11-09 09:24 UTC
Material select was working fine in **0.97.1**.

I just updated to **0.97.2**, and it's broken. 

The select is replaced by the materialized one:
![selection_048](https://cloud.githubusercontent.com/assets/120841/11030077/ecc5af1e-86cb-11e5-918b-06404290e7a1.jpg)

But it doesn't seem to generate the ```<ul>```:
![selection_049](https://cloud.githubusercontent.com/assets/120841/11030079/ef92cd6c-86cb-11e5-8a40-8d63c5c6fe1e.jpg)

There is no javascript error in the js console.

**Comment by Xsandor** [comment] 2015-11-09 15:38
+1, I have the same problem.

**Comment by PGBI** [comment] 2015-11-09 19:04
I also had the same problem. I fixed it by moving the scripts tags from the head to the body. This doesn't make sense, but it worked for me.

select broken:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/js/materialize.min.js"></script>
</head>
<body>

<select>
    <option value="option1">option1</option>
    <option value="option2">option2</option>
    <option value="option3">option3</option>
</select>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>
</body>
</html>
```

select working:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">
</head>
<body>

<select>
    <option value="option1">option1</option>
    <option value="option2">option2</option>
    <option value="option3">option3</option>
</select>

<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/js/materialize.min.js"></script>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>
</body>
</html>
```

Tested with Safari mac only.

**Comment by acburst** [comment] 2015-11-10 04:32
hmm. This seems very weird to me. Its working on my end. Can you post your code and your browser / OS?

**Comment by acburst** [comment] 2015-11-10 05:22
We'll see if we can fix the meteor issues and release a patch soon

**Comment by vivekkandhvar** [comment] 2015-11-11 17:56
All the selects are now broken and I tired the solution given in the above link. Didn't help. Can you please release a fix ASAP?

**Comment by s7dhansh** [comment] 2015-11-14 10:14
https://github.com/Dogfalo/materialize/pull/2294 fixes it.

**Comment by acburst** [comment] 2015-11-14 17:34
@vivekkandhvar Can you describe your setup more? It works for me locally so I can't fix something I can't reproduce.

**Comment by s7dhansh** [comment] 2015-11-15 04:08
@acburst are you using meteor? 
A normal html file has 'body'  almost definitely, so the code where ul is being appended to the body works. But in meteor, the concept of body is a little different. It works on templates, and the body is not necessary. So, that particular command may fail. Hence I used the older (0.97.1) trick where it was being appended just before the select element in my PR #2294.

**Comment by vivekkandhvar** [comment] 2015-11-15 04:51
@acburst The application I am developing, has couple of Forms which contains a lot of select elements used. I was using 0.97.1 and things work well. I just upgraded to 0.97.2, and select freezes. Not clickable and even multi select never worked. Any help is appreciated.

**Comment by s7dhansh** [comment] 2015-11-15 05:43
@vivekkandhvar till the PR gets reviewd, you can use my forked repo as a git submodule in the packages directory of your meteor app.

**Comment by acburst** [comment] 2015-11-15 08:44
Fixed in 6dcb033. Try this. Thanks @s7dhansh for the fix.

**Closed** 2015-12-13 18:48 UTC

**Comment by rubenmedios** [comment] 2016-02-16 23:47
This help me to run select components in firefox, need click over the select component twice for work.

I update jquery and materialize versions and work well. Thanks

**Comment by brandiqa** [comment] 2016-03-10 22:10
The solution that worked for me is by calling the 'material_select' function after the options data has been loaded.

`Template.[name].rendered = function() {
	this.autorun(function() {
		var optionsCursor = OptionsList.find().count();
		if(optionsCursor > 0){
			 $('select').material_select();
		}
	});
};
`

**Comment by digitalxpIT** [comment] 2016-12-02 12:25
Could you explain how to use your code solution?!

**Comment by brandiqa** [comment] 2016-12-02 13:12
Hope this helps: The code I wrote above was to fix an issue where the select input was not getting populated during rendering.
OptionsList is simply a Mongo model populated via bootstrap.js
