### ISSUE TITLE
Drag Out Menu Broken

### ISSUE THREAD

**Issue by mattcdowning** [Dogfalo/materialize#406] opened 2015-01-06 19:56 UTC
Saw a few people with the same issue on https://gitter.im/Dogfalo/materialize so I thought I'd open an issue.

The drag out menu is broken on the Materializecss.com site. I can't get it to work on my own either.

Thanks for the fantastic framework!

**Comment by Dogfalo** [comment] 2015-01-06 19:58
Duplicate of #239
It was disabled due to an iOS bug. We will work on a fix soon. And thanks!

**Closed by Dogfalo** 2015-01-06 19:58 UTC
