### ISSUE TITLE
Material Boxed doesn't work with Slider images

### ISSUE THREAD

**Issue by braginteractive** [Dogfalo/materialize#543] opened 2015-01-28 04:14 UTC
As the title says, the image pop/modal doesn't work with slider images.

**Comment by akyunus** [comment] 2015-05-07 05:16
+1 with thumbnails in slider

**Comment by tomscholz** [comment] 2017-04-03 17:29
Duplicate of https://github.com/Dogfalo/materialize/issues/1515

**Closed by tomscholz** 2017-04-03 17:29 UTC
