### ISSUE TITLE
Dropdown is blinking in Firefox 38+

### ISSUE THREAD

**Issue by zorobabel** [Dogfalo/materialize#1471] opened 2015-06-02 21:49 UTC
This is not happening in Chrome.

The error in action:

https://drive.google.com/open?id=0Bw0PGSiSoSieUEFzMHZWMUx5aVE&authuser=0

**Comment by Kithio** [comment] 2015-06-07 12:56
I'm running 28.0.5 and I can say that it doesn't occur for me. You running latest version?

**Comment by zorobabel** [comment] 2015-06-08 05:32
Of course, did you see the vid?

**Comment by williwambu** [comment] 2015-06-11 16:52
I have the same problem on firefox 38.0 when hover is set to true.

**Comment by danieljaniga** [comment] 2015-06-23 11:53
same problem here

**Comment by reesebiz** [comment] 2015-09-04 01:12
I'm experiencing the same issue in Firefox 40.0.3

**Comment by williwambu** [comment] 2015-09-06 08:21
I think it was fixed in the latest release.

**Comment by sasharili** [comment] 2015-09-24 07:27
I'm also experiencing this issue in FF 40.0.3

**Comment by zorobabel** [comment] 2015-09-24 15:37
It's no fixed bro

**Comment by Kithio** [comment] 2015-09-24 15:48
I think the problem is it activates the animation on MouseDown and Up, Not 100% sure about it to be completely honest since I haven't had time to look through the code, but by simple testing that's what it looks like

**Comment by acburst** [comment] 2015-10-11 20:38
Fixed in 88f6ddd

**Closed by acburst** 2015-10-11 20:38 UTC

**Comment by zorobabel** [comment] 2016-02-21 21:38
@acburst Great, thanks!
