### ISSUE TITLE
Select element not rendering

### ISSUE THREAD

**Issue by najubhai** [Dogfalo/materialize#2282] opened 2015-11-11 23:17 UTC
So I have the code similar to this: https://jsfiddle.net/a2cruf18/
I am importing both the css and js files after jquery but for some reason the select doesnt render on any browser.
What am I doing wrong?

**Comment by OminStyle** [comment] 2015-11-12 00:02
Read over documentation under Forms -> Select -> Initialization: http://materializecss.com/forms.html#select

I believe you forgot to add the following:
```
$(document).ready(function() {
    $('select').material_select();
  });
```

**Comment by najubhai** [comment] 2015-11-12 00:07
@OminStyle Nope, its there.

**Comment by OminStyle** [comment] 2015-11-12 00:13
Okay... there's a separate javascript section for a reason.
You forgot to close the parentheses.

**Comment by acburst** [comment] 2015-11-12 01:14
Duplicate of #2265

**Closed** 2015-11-12 01:56 UTC

**Comment by najubhai** [comment] 2015-11-12 03:13
```
<!DOCTYPE html>
<html>

<head>
    <title>PursueAbroad Test</title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="css/materialize.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <!-- <p>Hai</p>
    <select id="eduSelect" name="Education Level">
        <option>Associate</option>
        <option>Bachelor</option>
        <option>Master</option>
        <option>Doctoral</option>
    </select> -->
    <div class="input-field col s12">
        <select multiple>
            <option value="" selected>Choose your option</option>
            <option value="1">Option 1</option>
            <option value="2">Option 2</option>
            <option value="3">Option 3</option>
        </select>
        <label>Materialize Multiple Select</label>
    </div>
    <button id="submitSearch">SUBMIT</button>
    <div id="searchResults"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <script src="js/materialize.js"></script>
    <script src="js/pursue.js"></script>
</body>

</html>
```

Here's my code. @OminStyle The typo existed in the pastebin but not in the source. Even after you fix that syntax error, it still doesn't work. I have it exactly like:
```
$(document).ready(function() {
    $('select').material_select();
});
```
in the pursue.js file.

Also, please don't mark a ticket closed just because you think the issue was solved.

**Comment by acburst** [comment] 2015-11-12 03:45
Have you checked out the duplicate issue? You can search through existing issues to find similar ones to your own.

**Comment by najubhai** [comment] 2015-11-12 03:51
@acburst I did, thats why I posted the code above to show that I tried the mentioned solution but to no avail. Another user confirmed that the solution didn't work.

**Comment by acburst** [comment] 2015-11-12 05:35
I commited a fix on master. Have you tried the latest code?

**Comment by najubhai** [comment] 2015-11-12 05:55
Yes, the code is from the master branch as of 3 hours ago.

**Comment by Dogfalo** [comment] 2015-11-12 05:59
The issue is still a duplicate, you can post on the other thread about your
problem

On Wed, Nov 11, 2015 at 9:55 PM, Najm Sheikh <notifications@github.com>
wrote:

> Yes, the code is from the master branch as of 3 hours ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2282#issuecomment-156010123>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by artodeschini** [comment] 2018-05-03 23:24
try it 
works with me 
I use materialize 1.0.0-beta 

 document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var options = document.querySelectorAll('option');
            var instances = M.FormSelect.init(elems, options);
          });
