### ISSUE TITLE
Android Chrome: Scrolling while side menu is open

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#417] opened 2015-01-07 22:34 UTC
This is, as far as I know, only an issue in Chrome for Android, due to the behaviour of the address bar. This is not an issue when the window size of a desktop browser changes while the menu is out, that's why I have added "chrome for android" on the title.

Basically, if the navbar side menu is open, you can still scroll the page (as you can in other browsers using the scrollbars). However, because the address bar for chrome moves up with the page, the menu and fadeout effect are locked to the original position and dimensions. Hopefully the screenshot below should illustrate what I mean:

![2015-01-07 22 22 14](https://cloud.githubusercontent.com/assets/4189262/5654622/acb0bf9a-96bc-11e4-86a0-b8b6446bf5c5.png)

**Comment by Dogfalo** [comment] 2015-01-07 22:36
We know about this, but I am actually not sure that we can fix this. If there is a way, please let us know.

**Comment by carlosperate** [comment] 2015-01-07 23:00
The onscroll DOM event can be bind using javascript when the menu is opened (I did a kick test and it is fired as soon as you start touch scrolling on android chrome), then it can be used to dynamically change the size of the elements shown.

**Comment by Dogfalo** [comment] 2015-01-07 23:36
The element is `position: fixed` and already spans the entire screen, so the size of the element is not the issue. I am fairly sure this is caused by something chrome is doing to improve scroll performance.

**Comment by acburst** [comment] 2015-01-14 19:18
fixed in fe3e5d3aee4e9b5b59309a5480966d7df68ee502

**Closed by acburst** 2015-01-14 19:18 UTC
