### ISSUE TITLE
No compatible binary build found for this package [Meteor]

### ISSUE THREAD

**Issue by hazz1925** [Dogfalo/materialize#5043] opened 2017-07-30 11:32 UTC
Hi,

I am getting below error while adding materialize to meteor using `meteor add materialize:materialize`

```
=> Errors while adding packages:

While checking for materialize:materialize@0.100.1:
error: No compatible binary build found for this package. Contact the package author and ask them to
publish it for your platform.
```

I am using
Meteor version: 1.5
OS: MacOS Sierra

**Comment by tomscholz** [comment] 2017-07-30 12:48
Duplicate of https://github.com/Dogfalo/materialize/issues/5010

**Closed** 2017-07-30 12:47 UTC
