### ISSUE TITLE
Relatively positioning for tooltips

### ISSUE THREAD

**Issue by dylansteele8** [Dogfalo/materialize#719] opened 2015-02-19 07:27 UTC
I had a problem where the tooltips for icons were showing up where the icons would have been if I had not positioned them relatively (i.e. icons were relatively positioned to top-right corner, but tooltips were appearing at the bottom).

**Comment by Dogfalo** [comment] 2015-04-16 07:45
Duplicate of #692

**Closed by Dogfalo** 2015-04-16 07:45 UTC
