### ISSUE TITLE
Input Active Line Bleed

### ISSUE THREAD

**Issue by danielhickman** [Dogfalo/materialize#886] opened 2015-03-11 01:50 UTC
On Chrome on a 4K display this line shows up to the right of an active input. It doesn't happen on my 1080p display or on Firefox; only 4K (UHD technically) on Google Chrome.
![untitled](https://cloud.githubusercontent.com/assets/5341898/6588942/0d0b4fda-c756-11e4-986d-9972a21ae8c2.png)

**Comment by Dogfalo** [comment] 2015-03-11 02:06
Are you at 100% zoom?

**Comment by danielhickman** [comment] 2015-03-11 02:11
Yes.

**Comment by danielhickman** [comment] 2015-03-11 02:15
Chrome on my UHD display often displays fixed headers one pixel below the top so I can see the content scroll past through the gap. If you look closely at https://www.youtube.com/watch?v=yRgc4LbVs28 you can see that the FAB before animating displays with four gaps too. I think it is because Chrome is not pixel perfect for UHD+ displays. I was only wondering if you had any fix for it. The inputs at materialdesignblog.com/material-design-button-animation/#reply-title show fine (but they aren't MaterializeCSS and the background color changes for some reason)

**Comment by Dogfalo** [comment] 2015-03-13 17:58
I don't have a UHD display to test this on, so maybe you could try to fix it :) That would be helpful.

**Comment by danielhickman** [comment] 2015-03-14 00:20
Okay I'll do my best. I was working on a prototype of a more native looking
side menu too I would like to show you and see what you think.

**Comment by danielhickman** [comment] 2015-03-14 01:33
In Chrome if you are zoomed in a bunch or have a UHD (or maybe it's the text scaling UHD screens need) the box-shadow bleeds to either the right or left. It looks better to have this:
```css
  border-bottom: 2px solid #26a69a;
```
than this:
```css
border-bottom: 2px solid #26a69a;
-webkit-box-shadow: 0 1px 0 0 #26a69a;
 -moz-box-shadow: 0 1px 0 0 #26a69a;
box-shadow: 0 1px 0 0 #26a69a;
```
on Chrome.

**Comment by danielhickman** [comment] 2015-03-14 03:57
What I did: https://github.com/danielhickman/materialize/commit/aa98c5f34b08acca4dc5e76ce9ecee0579928576
I am not the best at CSS so I am wondering why you used a border and a box shadow. Was if for an animation? I didn't notice a difference.

**Comment by Dogfalo** [comment] 2015-03-14 04:03
Border pushes up the element

**Comment by danielhickman** [comment] 2015-03-14 04:06
Oh hmmm I don't know if it could be fixed besides getting rid of the shadow because Chrome just sucks at them it seems.

**Comment by kmmbvnr** [comment] 2015-03-25 10:11
I have same on mobile.

![2015-03-25 15 55 50](https://cloud.githubusercontent.com/assets/282529/6822318/a258947a-d300-11e4-8f67-91c623485632.png)

Issue could be reproduced on usual screen with style body { transform: scale(0.9) }

And could be fixed by using negative values for box-shadow property - http://stackoverflow.com/questions/5460129/drop-shadow-only-bottom-css3

    - box-shadow: 0 1px 0 0 #26a69a;
    + box-shadow: 0 2px 0 -1px #26a69a;

**Comment by hmeerlo** [comment] 2015-07-03 14:58
+1 for @kmmbvnr that solution works for me as well. I do a translate on a div to center it and then the box shadow of focused input fields bleed on the side. Very annoying.

**Closed** 2017-07-12 03:46 UTC
Labels: bug, has-pr
