### ISSUE TITLE
Latest update breaks my site

### ISSUE THREAD

**Issue by alisalaah** [Dogfalo/materialize#2519] opened 2015-12-21 17:08 UTC
Just started a blank meteor project with only your package and get:

Uncaught ReferenceError: require is not defined
global-imports.js:12 Uncaught TypeError: Cannot read property 'Materialize' of undefined
template.project.js:2 Uncaught ReferenceError: Template is not defined
project.js:9 Uncaught ReferenceError: Meteor is not defined

**Comment by alisalaah** [comment] 2015-12-21 17:12
For now using this to downgrade fixes everything:

meteor add materialize:materialize@=0.97.3

**Comment by damienleri** [comment] 2015-12-21 18:58
I think that (older) version has broken fonts, though: 

https://github.com/Dogfalo/materialize/issues/2217

**Comment by paulwalker** [comment] 2015-12-21 20:53
This is a problem with jspm as well

**Comment by Dogfalo** [comment] 2015-12-22 04:53
Duplicate of #2516

**Closed by Dogfalo** 2015-12-22 04:53 UTC
