### ISSUE TITLE
navbar-fixed not compatible with mobile collapse button

### ISSUE THREAD

**Issue by ktrnka** [Dogfalo/materialize#1631] opened 2015-06-29 19:55 UTC
I'm trying to have navbar-fixed and also a mobile collapse button.

The fixed navbar works great on large. On small/medium when you click the hamburger you only get "Current trends" because the side drawer is trapped inside the navbar-fixed height. 

```
<div class="navbar-fixed">
<nav>
<div class="nav-wrapper">
    <a href="index.html" class="brand-logo hide-on-med-and-up">Over 9000</a>
    <a href="index.html" class="brand-logo hide-on-small-only">Over 9000: Popular anime</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="active"><a href="index.html">Current trends</a></li>
        <li class=""><a href="winter2015.html">Winter 2015</a></li>
        <li class=""><a href="about.html">About</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
        <li class="active"><a href="index.html">Current trends</a></li>
        <li class=""><a href="winter2015.html">Winter 2015</a></li>
        <li class=""><a href="about.html">About</a></li>
    </ul>
</div>
</nav>
</div>
...
<script>
$(".button-collapse").sideNav();
</script>
```

Live site: http://www.over9000.me/  I'm disabling navbar-fixed so it might be commented out when you load the page.

**Comment by carlosperate** [comment] 2015-06-30 19:55
I can confirm I am also having issues with this.

**Comment by ClarkZinzow** [comment] 2016-10-27 08:14
If you are fine with forcing the height of the sidenav to that of the viewport, then adding `min-height: 100vh;` to the `.side-nav` CSS rule, along with removing `overflow: hidden` from the `nav` CSS rule, will do the trick.  I.e., having the following in your personal stylesheet will suffice:

```
.side-nav {
  min-height: 100vh;
}

nav {
  overflow: inherit;
}
```

Given that the current version of the `nav` CSS rule in materialize.min.css does set `overflow: hidden`, if one wished to always force the height of the sidenav to be the height of the viewport, adding `min-height: 100vh;` to materialize.min.css should do it (with the existing `height` declarations serving as fallbacks for IE8 and Opera Mini:  [Browser Support](http://caniuse.com/#search=vh).)

**Comment by tomscholz** [comment] 2017-04-05 15:06
Everything works perfectly fine for me here: https://codepen.io/tomscholz/pen/yMrxMv
Also your link is broken. I will close this issue now, feel free to reopen it if it is still necessary.

**Closed by tomscholz** 2017-04-05 15:06 UTC

**Comment by CyclingLand** [comment] 2017-12-23 09:45
this works for me
```HTML
<header>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper" style="background-color:dodgerblue;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"> <a href="#!" class="brand-logo"><img src="Logo CyclingLand(transparant).png" style="width:65px;height:auto"></a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#intro">Intro</a></li>
          	    <li><a href="#about">Over mij</a></li>
         	    <li><a href="youtube.html">YouTube</a></li>
                </ul>
            </div>
        </nav>
    </div>
   <!-- Sidenav -->
    <ul class="side-nav" id="mobile-demo">
        <li><a href="#intro">Intro</a></li>
        <li><a href="#about">Over mij</a></li>
        <li><a href="youtube.html">YouTube</a></li>
    </ul>
</header>
```
Preview:
https://cyclingland.github.io
