### ISSUE TITLE
Time and Datetime Picker

### ISSUE THREAD

**Issue by kaufmo** [Dogfalo/materialize#610] opened 2015-02-04 12:17 UTC
Hello,

do you plan to integrate a time picker? And then a combination from date and time?

Best regards
Alex

**Comment by kaufmo** [comment] 2015-02-04 12:19
Eventually like this http://simeonc.github.io/md-date-time/ ?

**Comment by serkandurusoy** [comment] 2015-02-07 19:11
:+1:

**Comment by Dogfalo** [comment] 2015-02-07 20:48
Duplicate of #473

**Closed by Dogfalo** 2015-02-07 20:48 UTC

**Comment by goatandsheep** [comment] 2017-07-20 15:39
@Dogfalo how does one use the datetime picker?

**Comment by Thanood** [comment] 2017-07-20 15:42
Look here: http://materializecss.com/forms.html#date-picker
And here: http://materializecss.com/forms.html#time-picker

😃

**Comment by tomscholz** [comment] 2017-07-20 15:42
Have a look at the documentation at [http://materializecss.com/forms.html#time-picker](http://materializecss.com/forms.html#time-picker)

**Comment by goatandsheep** [comment] 2017-07-20 15:51
Thanks for the quick reply, but a unified [datetime object](https://www.w3schools.com/html/html_form_input_types.asp#Input Type Datetime-local) is different and important because otherwise it's a lot of effort to join the date and time into a single timestamp.

**Comment by Thanood** [comment] 2017-07-20 20:08
@goatandsheep That's tricky.. 😃 

Material design pickers seem to launch one after the other if date/time is used at the same time. I guess I would start the datepicker, wait for it to finish - there's an `onClose` callback which is not mentioned in Materialize docs but in pickadate docs. And start the timepicker from there.

The timepicker is actually a modified [clockpicker](http://weareoutman.github.io/clockpicker/) which has a `show` method..

**Comment by andrechavesg** [comment] 2020-03-29 22:04
Just got into the same issue here and following the ideia suggested by Thanood i've implemented with jquery the initialization of timepicker after datepicker's onClose:

```
function initDatetimePicker() {
    $(document).find('.datepicker').each(function(index,datepicker) {
        let self = $(datepicker);
        let dateValue = null;

        self.timepicker({
            twelveHour: false,
            autoClose: true,
        })

        self.datepicker({
            format: 'dd-mm-yyyy',
            autoClose: true,
            onClose:function() {
                dateValue = $(self).val()
            }
        });

        self.on("click",() => {
            $(this).val("")
            dateValue = null
        })

        self.on("change",() => {
            let time = $(this).val()

            if(dateValue && time)
                $(this).val(dateValue+" "+time)
        })
    })
}

$(document).ready(function(){
    initDatetimePicker()
});
```

Hope helps somebody

**Comment by victornassif** [comment] 2020-06-05 15:08
@andrechavesg it helped me. Tks
