### ISSUE TITLE
select is not applying validate style

### ISSUE THREAD

**Issue by harrysonguimaraes** [Dogfalo/materialize#1390] opened 2015-05-21 00:41 UTC
How to apply .validate style to select elements?
That is how my form looks like when i select an item and input some text in the other inputs. It's kind inconsistence with my other inputs.
![captura de tela 2015-05-20 as 21 39 30](https://cloud.githubusercontent.com/assets/5912680/7739547/eb747a2a-ff38-11e4-9479-61e8b3dfca1e.png)

**Comment by kestutis-stalmokas** [comment] 2015-05-21 03:38
I have the same problem with checkboxes too. Actual `<input>` elements are moved off the screen, but they should only be invisible.

**Comment by fernandoPalaciosGit** [comment] 2015-07-19 09:39
To improvise a solution, change the position of ordered elements into **.select-wrap, online 2786,** put it after select input:
```javascript
$select.after($newSelect);
$newSelect.after(dropdownIcon);
```
and now You can selector css
```css
select.invalid ~ .select-dropdown {
      border-bottom: 1px solid #F44336;
}
```

**Comment by cbruyndoncx** [comment] 2015-07-22 10:26
I'm using this hack incombination with civem.js (custom html5 error messages in multi-language - not just browser language).
The small difference is in the css, civem.js flags validation error with the .error class, so the css becomes
[code]
select.error ~ .select-dropdown {
      border-bottom: 1px solid #F44336;
}
[/code]

**Comment by syberknight** [comment] 2016-02-21 22:29
FYI...
i found a solution @ http://stackoverflow.com/a/34809423/1247334

yes, it's a workaround & i don't know if it's the best way to go about it or not, but it's the ONLY way i've been able to get my Materialize Selects to validate.

i use Jquery Validate, & just copy/pasted it in right after my "Rules" & "Messages" & worked right off the bat. then the css styling was all i had to tweak a little.
-2¢

**Comment by gharia** [comment] 2016-07-30 06:28
It may be late, but I have created one hack for it. Please see the detail explanation at [http://stackoverflow.com/questions/34248898/how-to-validate-select-option-for-materialize-dropdown/38671029#38671029](http://stackoverflow.com/questions/34248898/how-to-validate-select-option-for-materialize-dropdown/38671029#38671029)

**Comment by gharia** [comment] 2016-07-30 09:44
I also had the same issue, I was able to solve it with a hack whic I have mentioned in detail at [http://stackoverflow.com/questions/34248898/how-to-validate-select-option-for-materialize-dropdown/38671029#38671029](http://stackoverflow.com/questions/34248898/how-to-validate-select-option-for-materialize-dropdown/38671029#38671029)

**Comment by GorgonsMaze** [comment] 2016-09-19 03:02
Anyone find a solution that actually changes the validation styling once an option is selected, much like every other input field does once the input field has the required value/text inside of it.

**Comment by bibislayer** [comment] 2017-01-06 15:59
I'm using this but really not sure is the best practice =>
in app.component.ts 
<pre>
ngDoCheck() {
    let selectorValid = $('.select-wrapper:has(select.ng-dirty.ng-valid)');
    if(selectorValid.length > 0){
      selectorValid.removeClass('ng-untouched ng-pristine ng-invalid');
      selectorValid.addClass('ng-dirty ng-valid');
    }
    let selectorInvalid = $('.select-wrapper:has(select.ng-dirty.ng-invalid)');
    if(selectorInvalid.length > 0){
      selectorInvalid.removeClass('ng-untouched ng-pristine ng-invalid');
      selectorInvalid.addClass('ng-dirty ng-invalid');
    }
  }
</pre>

**Comment by rodrigorrl** [comment] 2017-06-05 02:38
@harrysonguimaraes Tenho o mesmo problema. Conseguiu resolver?

**Comment by Dogfalo** [comment] 2017-07-19 22:03
fixed in 97c450bb23c02dca2016b3e6bf72717ce25024c2

**Closed by Dogfalo** 2017-07-19 22:03 UTC
Labels: enhancement

**Comment by eduardoalcantara** [comment] 2021-11-29 16:54
The problem is actually with the rendered `input` that replaces the `select` element. It is irrelevant that this select is hidden or not. The Materialize CSS engine does not verify if your select element is required or has the `validate` class. I don't know why they didn't put that code I will show you below, but that will solve the problem if you put it in a JavaScript file in your page:

    $(document).ready(function(){
        $('select').formSelect(); 
        const _requiredSelects = $("select[required].validate");
        _requiredSelects.parent().find('input').addClass('validate').attr('required', 'required');
        _requiredSelects.keypress(function() { 
            return false; 
        });
        _requiredSelects.change(function($event) { 
            const _select = $event.target;
            const _value = $(_select).val();
            const _input = $(_select).parent().find('input');
            _input.removeAttr('readonly', '');
            _input.val(_select.options[_select.options.selectedIndex].label);
            if (_value != '') {
                _input.addClass('valid');
                _input.removeClass('invalid');
            } else {
                _input.addClass('invalid');
                _input.removeClass('valid');
            }
        });
        _requiredSelects.each(function(){
            const _this = $(this);
            const _helper = _this.parent().parent().find('.helper-text');
            if (_helper !== undefined) {
                const _input = _this.parent().find('input');
                _helper.insertAfter(_input);
            }
        });
    });

**Comment by eduardoalcantara** [comment] 2021-11-29 17:39
```javascript
$(document).ready(function(){
    $('.tooltipped').tooltip(); // dica que aparece quando o usuário põe o mouse em cima do componente
    $('select').formSelect(); // montagem de campos <select> com material design
    // isto corrige o problema de renderização em campos select que exigem validação quando o campo é de preenchimento obrigatório
    const _requiredSelects = $("select[required].validate");
    _requiredSelects.parent().find('input').addClass('validate').attr('required', true)
    .keydown(function($event) { 
        return $event.keyCode == 9;
    });
    _requiredSelects.change(function($event) { 
        const _select = $event.target;
        const _value = $(_select).val();
        const _input = $(_select).parent().find('input');
        _input.removeAttr('readonly', '');
        _input.val(_select.options[_select.options.selectedIndex].label);
        if (_value != '') {
            _input.addClass('valid');
            _input.removeClass('invalid');
        } else {
            _input.addClass('invalid');
            _input.removeClass('valid');
        }
    });
    _requiredSelects.each(function(){
        const _this = $(this);
        const _helper = _this.parent().parent().find('.helper-text');
        if (_helper !== undefined) {
            const _input = _this.parent().find('input');
            _helper.insertAfter(_input);
        }
    });
});

```
