### ISSUE TITLE
Closing drawer with swipe bug

### ISSUE THREAD

**Issue by mitas1** [Dogfalo/materialize#4171] opened 2017-02-02 12:24 UTC
After closing a drawer with swipe on a mobile device, dark overlay does not disappear.

![screen](https://cloud.githubusercontent.com/assets/22389946/22549282/e369f47e-e94a-11e6-94ec-ee84be94c2e7.png)

**Comment by Dogfalo** [comment] 2017-02-02 15:57
Duplicate of #4046

**Comment by mitas1** [comment] 2017-02-02 16:37
I think this is a different issue. Can you explain why it is marked as duplicate? #4046 seems to be a problem with nesting and `z-index`, but I am talking about problems with touch events. In certain cases, after closing a drawer with swipe, it happens that the drawer closes but dark overlay `div` with `id=sidenav-overlay` does not disappear.

**Comment by Dogfalo** [comment] 2017-02-02 17:50
True, I mistakenly thought they were related at first.

**Comment by matthewsalan** [comment] 2017-02-05 18:41
Can confirm the grey overlay is still present after swiping to close the mobile sideNav.

**Comment by mitas1** [comment] 2017-02-10 09:48
Duplicate of #3872

**Comment by jarekbb** [comment] 2017-02-14 12:49
I have the same problem  :( (ver. 0.98.0)

**Comment by tomscholz** [comment] 2017-05-02 14:40
As @mitas1 said, this is a duplicate of https://github.com/Dogfalo/materialize/issues/3872

**Closed by tomscholz** 2017-05-02 14:40 UTC
Labels: bug
