### ISSUE TITLE
margin-left: 0; in _grid.scc line 107, shouldn't be there?

### ISSUE THREAD

**Issue by Ansien12** [Dogfalo/materialize#2498] opened 2015-12-17 22:37 UTC
```
@while $i <= $num-cols {
    $perc: unquote((100 / ($num-cols / $i)) + "%");
    &.l#{$i} {
        width: $perc;
        margin-left: 0;
    }
```

The margin-left causes all large offsets (ex: offset-l2) to not work.

![image](https://cloud.githubusercontent.com/assets/1700132/11884096/aaecccc0-a517-11e5-9b6d-f2364c708d3f.png)
It's overwriting the offset for some reason.

**Comment by acburst** [comment] 2015-12-18 06:05
Duplicate of #2328

**Closed by acburst** 2015-12-18 06:05 UTC

**Comment by m00k1e** [comment] 2016-04-21 20:28
Hello!

 

New message, please read <http://integritybpo.com/uniform.php?udhh>

 

hello@mookiecreative.com
