### ISSUE TITLE
datepicker error with chrome 73

### ISSUE THREAD

**Issue by erict54757** [Dogfalo/materialize#6323] opened 2019-04-01 19:22 UTC
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

## Steps to Reproduce (for bugs)

1.
2.

## Context
DatePicker will instantly close on select in materialize-css version 0.100.2. in browser chrome 73.

a fix is to add a settimeout in line 7084 of dist/materialize js. 
snippet of fix: 
    // Separated for IE
    function handleFocusToOpenEvent(event) {

      // Stop the event from propagating to the doc.
      event.stopPropagation();

      // If it’s a focus event, add the “focused” class to the root.
      if (event.type == 'focus') {
        P.$root.addClass(CLASSES.focused);
      }

      // And then finally open the picker.
     setTimeout(function(){ P.open();},50)
    }

    // Return a new picker instance.
    return new PickerInstance();
  } //PickerConstructor

* Version used:
* Browser Name and version:chrome 73
* Operating System and version (desktop):desktop only experiences this issue

**Comment by DanielRuf** [comment] 2019-04-02 05:32
Hi, this is a duplicate of the previously closed issues.

See https://github.com/Dogfalo/materialize/issues?q=is%3Aissue+is%3Aclosed

**Comment by DanielRuf** [comment] 2019-04-02 05:35
> a fix is to add a settimeout

This is not a fix but a hack as this will put all invocations on the timer stack and block the JS. Please check debouncing and throttling.

**Closed** 2019-04-02 06:00 UTC
