### ISSUE TITLE
search bar in navbar has some problem 

### ISSUE THREAD

**Issue by santhosh77h** [Dogfalo/materialize#3184] opened 2016-05-20 14:29 UTC
https://plnkr.co/edit/ZrHEdhN2eCAP0dysybmP?p=preview 
text box is not aligned properly.
i have attached the plunker

**Comment by ardianta** [comment] 2016-05-20 16:40
No problem in jsbin [http://jsbin.com/codufe/edit?html,output](http://jsbin.com/codufe/edit?html,output). I think you should import material font.

**Comment by acburst** [comment] 2016-05-21 18:55
Duplicate of 3161

**Closed** 2016-05-21 18:55 UTC
