### ISSUE TITLE
The select-value isn't updating

### ISSUE THREAD

**Issue by MichaelDeBoey** [Dogfalo/materialize#2843] opened 2016-02-26 20:40 UTC
I'm using the Angular 2 two-way binding on the select.
When I select another value in the list, that doesn't reflect to the select, so my ngModel isn't updating.
When i use the `browser-default` class all works fine, but I offcourse want to see the materialized select :smile:

**Comment by Deniscapp** [comment] 2016-03-09 20:54
I am having the same problem. Any solutions so far? :/

**Comment by Thanood** [comment] 2016-03-09 21:33
With Aurelia I needed to raise a CustomEvent to make that happen.

```javascript
let event = new CustomEvent('change', {
    detail: someData,
    bubbles: true
  });
element.dispatchEvent(event);
```

Maybe that also works for Angular 2.

**Comment by carlosperate** [comment] 2016-03-09 21:44
Materialize creates a new element for the select, so Angular is probably updating the original hidden one. You can destroy and/or recreate the selects which should refresh it. Have a search on the issue tracker, this has been brought up a couple of times, so there might be solutions already explained in those.

**Comment by tceydeliler** [comment] 2016-03-30 12:37
I have same problem. Thats why I had to use browser default. Not good looking :(

**Comment by Thanood** [comment] 2016-03-30 12:42
Is the custom event "trick" mentioned above not working?

**Comment by tceydeliler** [comment] 2016-03-30 13:17
Honestly I am not java familiar.
Need to describe where i put this trick

**Comment by Thanood** [comment] 2016-03-30 13:43
Well, the select component issues a jQuery ```change``` event.

You would have to adapt this to the framework you use (if any).

Somewhere after initialization, try to put this:
```javascript
jQuery('.my-select').on('change', function() {
  var event = new CustomEvent('change', {
    detail: {}, // this is optional, you could for example put the selected option here
    bubbles: true
  });
  element.dispatchEvent(event);
});
```

Replace ```.my-select'``` with the selector for your select.

See this CodePen as an example:
http://codepen.io/anon/pen/yOovGw

**Comment by tceydeliler** [comment] 2016-03-30 14:04
ahh, sorry,
I think I misunderstood.
My problem is;
I cant set the value as selected  that read from database when I use materialize-select. have u any idea about that?

**Comment by Thanood** [comment] 2016-03-30 14:12
Oh no, I think that I completely misunderstood the issue.
I have no "real" idea, sorry. But I think you would have to manipulate the original select and then refresh the Materialize.

**Comment by quentinHydrobat** [comment] 2016-06-13 16:02
Wow, i got the issue on safari and firefox /: Please someone put this in the next version.

**Comment by ammichael** [comment] 2016-08-16 23:02
I'm using Materialize with Angular, and @Thanood solutions worked fine for me:

```
$('select').on('change', function(e) {
          var selected = e.currentTarget.selectedOptions[0].value;
          $scope.obj.key = selected
});
```

**Comment by jarodium** [comment] 2016-09-25 13:19
I'm not using any framework besides jQuery.
I have solved the issue by issuing $('select').material_select() again as stated in the docs.
I use jquery to $("select").val(1) and then material_select()

I think Materialize could provide us a method to set the value or monitor the change and update it for us?

**Comment by quentinHydrobat** [comment] 2016-09-26 07:04
Good point,
@TODO : Overriding `.val()` method so if it's for a materialized `<select>`, update it. 
Agree ?

**Comment by SimHacker** [comment] 2017-01-20 19:38
This is probably caused by the fact that selects often ignore user input, as described in this bug report I filed:
https://github.com/Dogfalo/materialize/issues/4098

Please re-open that issue, and mark this as a duplicate. I described and fixed an input event tracking problem that causes select menus to ignore the item you select, if you don't click on it very quickly, or if you press down and drag.

To demonstrate this, try popping up the menu by clicking (because pressing and dragging does not work, and starts a text selection gesture, which is another bug), then point at an item different than the currently selected item, then click very quickly. If you click quickly enough, it works. Then try clicking on another item than the one you just selected, but more slowly so you're holding the button or finger down for about half a second to a second. (Not a press-and-hold gesture, which is slower, but just a slow click, which is very common for people to do.) Notice that the menu pops down at the instant you press down on the button or touch the screen, but the onclick handler that reports the selected item is never called. That is the bug I reported and fixed, but it was closed unfortunately because the developers don't see it as a bug. But it certainly is.

**Comment by Dogfalo** [comment] 2017-01-20 22:00
It sounds like @Thanood may be right in that we are not firing the browser onchange event properly. Will look into this.

**Comment by hir3npatel** [comment] 2017-02-06 10:10
I agree, I use brython and listen on the select elements onchange event, which does not get fired since I put materialize select inputs into the page. Using "browser-default" works though. My use case requires that I can listen on select inputs onchange event, and that I can add options to select boxes dynamically. It would be great if materialize did these, thanks.

**Comment by doubleOrt** [comment] 2017-06-24 16:15
So, i have the same problem. It is weird that this issue is still open after more than one year.

**Comment by tomscholz** [comment] 2017-08-12 17:12
Duplicate of #4562

**Closed by tomscholz** 2017-08-12 17:12 UTC
Labels: bug, component:Select
