### ISSUE TITLE
More Cooler Templates ?

### ISSUE THREAD

**Issue by Lucas-Qi** [Dogfalo/materialize#2258] opened 2015-11-07 08:56 UTC
Hi buddies, 

I find this framework is very good, and there are many showcases on the website ---- they are cool. 

However, there are only 2 "starter templates" which have sources. I wonder if there are sources for the "cooler" websites like the showcases? 

Because the 2 "starter templates" are too simple for a cooler website. 

How can I find more templates with sources using Materialize?

Thank you!

**Comment by seanfrasure** [comment] 2015-11-16 14:43
+1

**Comment by tomscholz** [comment] 2017-04-02 00:23
Duplicate of:https://github.com/Dogfalo/materialize/issues/650

**Closed by tomscholz** 2017-04-02 00:23 UTC
