### ISSUE TITLE
lean-overlay class not getting added when modal is opened

### ISSUE THREAD

**Issue by anandrikka** [Dogfalo/materialize#4028] opened 2016-12-25 08:09 UTC
when clicked on button modal is getting opened but with no lean-overlay class and modal is also not getting closed when clicked outside

`<a className="btn waves-effect modal-trigger waves-light w100" data-target="movie-trailer">
                                Watch Trailer
                             <i className="fa fa-youtube-play left" aria-hidden="true"/>
                                </a><div id="movie-trailer" className="modal">
                        <div id="modal1" clclassNameass="modal">
                        <div className="modal-content">
                            <h4>Modal Header</h4>
                            <p>A bunch of text</p>
                        </div>
                        </div>   
                    </div>`

In reactjs 

`$(document).ready(function() {
            $('.modal-trigger').leanModal({
                dismissible: true,
                opacity: .5,
                in_duration: 300,
                out_duration: 200,
            });
        });`

**Comment by acburst** [comment] 2016-12-26 22:35
Duplicate of #3865

**Closed by acburst** 2016-12-26 22:35 UTC
