### ISSUE TITLE
Can materialize be used in production? What about the durability of this product?

### ISSUE THREAD

**Issue by Clemzd** [Dogfalo/materialize#1580] opened 2015-06-24 08:00 UTC
Hi guys!

I saw that the team is a group of students and 2 of them began to work at Google for 1 month as UX designer :
https://www.linkedin.com/pub/alvin-wang/9b/21a/559
https://www.linkedin.com/pub/alan-chang/73/160/319/fr

As I would like to use this Framework in production, I'm wondering if they'll still have time to work on their framework. Otherwise the durability of this project seems to be compromised.

Thanks a lot!

**Comment by kaliel86** [comment] 2015-06-24 09:16
I'm using it in prod for a personnal project. Even if not finished i think it's the best starter kit for material design actually. You'll have to code some more scss to fit your needs, but feel free to PR :)

**Comment by Clemzd** [comment] 2015-06-24 11:24
Ok, thank you.
But will they have time to work on the Framewok in the future as the team is a group of students?

**Comment by filtercake** [comment] 2015-06-24 11:28
@Clemzd I don't understand the question. Why would people commit to spend their spare time on your production safety?

**Comment by Clemzd** [comment] 2015-06-24 11:32
I'm not talking about my production.
I'm talking about fixings bugs of the Framework, maintain the support on the different browsers. Those tasks are handled by Materialize Team, right ?

**Comment by filtercake** [comment] 2015-06-24 11:38
In my understanding an open source project like Materialize works like this: Maintainers *might* fix stuff themselves if their personal usecase is in question. But mostly they take care of community and guide PRs to merging.

If you got the initial framework for free, why wouldn't you fix bugs yourself and send a PR but instead ask for the maintainers to fix it?

**Comment by robert-hoffmann** [comment] 2015-06-24 11:47
@filtercake because in a professional environement, you usually do not adopt a framework unless it is stable and actively maintained, since one often maintains multiple projects and the project can move from team to team where team members are not necessarily fully familiarized with this or that framework, so you wan't it to be plug and play as much as possible to be able to upgrade it, yet not focus on the framewor, but instead on the product you are building.

IE. jQuery since years you can put it in a project and when a new version comes out just overwrite with the latest, and usually you do not have to worry about compatibility and stuff because the team made sure almost everything was tested heavily before release.

**Comment by filtercake** [comment] 2015-06-24 12:28
@robert-hoffmann I don't want to argue about this, that is why I phrased my statements as questions. I am totally aware what many people consider "normal" and "professional" behaviour in this regard and I think it's broken :) but let's continue that somewhere else if you're interested...

**Comment by Clemzd** [comment] 2015-06-24 12:32
@filtercake i agree with @robert-hoffmann I will not have time to spend and fix the bugs alone because I'm working in a professional environnement. 

The fact is the better css material design framework i've found so far is Materialize. I'm pretty sure new ones will come up in the next few years. But currently I think it is the best and that's why I'd like to know if the team plan to maintain it within the 2-3 next years.

**Comment by robert-hoffmann** [comment] 2015-06-24 13:26
@Clemzd All things said ..with over 10K watchers and 1K+ forks, i do not think you have to worry about things being maintained. Probably more with breaking changes as the project matures and adds/removes/reorganizes features.

For example i just saw a thread asking why old fonts where left in the project since they moved to google fonts.

If i where you (and i'm not) i'd either just use this project as-is in a single project (as a live test) to it's full extent and not worry too much about the rest. Or just sit things out for 6-12months and see how things evolve.

Still some feedback from the devs would be nice to get a clearer picture of what the roadmap is.

**Comment by jcapogna** [comment] 2015-06-24 22:56
I'm using this in a production product as this seems to be the most popular Material design framework currently out there. I'm hoping that it continues to receive development and get to a really mature and full-featured 1.0. If not, I'll probably end up forking it as internal project.

**Comment by Dogfalo** [comment] 2015-06-26 02:40
@robert-hoffmann the old fonts were left in the project because we want to phase out the fon'ts slowly rather than remove the dependency immediately which would break people's sites.

**Comment by acburst** [comment] 2015-06-26 03:01
Hey guys, We definitely do have less time since we left college and started working. Our intentions are to maintain and keep this project alive, but we are going to be more open towards pull requests as this would be the most efficient use of our time. Once things settle down around work we can look into working more on Materialize. We hope you guys understand. 

Keep submitting issues, giving feedback, and pull requesting! We appreciate all of it.

**Comment by corbindavenport** [comment] 2015-06-27 03:43
Just my two cents, Materialize is a pretty production-ready framework. It's not the best with older browsers, but it has amazing compatibility compared to Google's [Polymer framework](https://www.polymer-project.org/0.5/resources/compatibility.html) and looks about as nice.

I use Materialize in my app [Nimbus](https://github.com/corbindavenport/nimbus) and I've only had to change my code once while upgrading the framework (when they changed the format of the toast function a bit). Materialize lets me target a fairly generous amount of web browsers and works well :)

**Comment by rafszul** [comment] 2015-06-28 05:40
@Clemzd is this professional environment with capital "P" or just "p"? will it remain as such in 3-4 years time or are you planning upgrade/downgrade? ;-P take it easy.

jokes aside i do appreciate the problem highlighted here, which is why i would like to propose renaming this thread before closing it. i would give it an informative title like: "can i have the cake and eat it?"

thumbs up to @filtercake and @robert-hoffmann

**Comment by robert-hoffmann** [comment] 2015-06-28 09:18
@rafszul i you give me some cake, i would definitely want to eat it ^^

**Comment by robert-hoffmann** [comment] 2015-06-28 09:35
@Dogfalo All this talk, and you saying you guys are now working and figuring out how to balance work-life and this cool project kinda reminds me when @jereisig left jquery to pursue other things.

A great reflex i think he had is moving jquery to a foundation (first dojo) and the jquery. Maybe you can reach out to him and ask him some questions on how this kind of stuff works.

I know from a project i maintained for a few years that some big companies and open-source projects also ask crazy questions like "are you the some code owner", or do you have some kind of disclaimer in place for contributors to make sure the IP is problem free, before they even dare including you code in some kind of distribution.

In any case, going the foundation route could maybe be a good idea in this case. Reach out to @jereisig, i'm sure he'll be more than happy to answer a few questions. Or if you want more media coverage, someone like paul irish would probably jump at the idea of getting his name associated with a project like this.

Anyways, just some food for thought.

Great project guys !

**Comment by UriahsDev** [comment] 2015-06-28 17:38
@acburst @Dogfalo Since you guys will have less time since you started working, dont you think you should put materialize's website on github also? so as features are added the website could grow without there being additions without reference. Thanks.

**Comment by carlosperate** [comment] 2015-06-28 17:43
@UriahsDev Look at the repository, everything is right there, and seems to be hosted in github pages.

**Comment by UriahsDev** [comment] 2015-06-28 18:25
@carlosperate silly me! i knew that i totally forgot :3 got caught up in the conversation

**Comment by Clemzd** [comment] 2015-07-08 11:46
OMG ! Google just released their Material Design Framework : https://github.com/google/material-design-lite.

**Comment by jcapogna** [comment] 2015-07-08 18:04
@Clemzd  I looked through this last night. It's definitely lightweight and doesn't offer anywhere near the level of functionality that Materialize offers. I am wondering if Google will add functionality to it or not, because a lot of the missing functionality exists as part of the material elements in Polymer.

**Comment by najubhai** [comment] 2015-07-08 22:24
I have used Materialize in two simple websites for clients. As long as you don't have it setup to import the latest version, you'll be fine.

**Comment by carlosperate** [comment] 2015-07-20 18:31
Bringing back what @robert-hoffmann suggested a while ago, it looks like the Materialize team is in some serious need for community management support.

We all understand that you guys can only work on this on your spare time, and I'm not trying to sound ungrateful, as clearly this is a great project we have all benefited from. But issues are piling up, pull requests are taking weeks to be reviewed, or are incorrectly reviewed, or aren't reviewed at all! and there is barely any real support offered.

Have you guys planned how to deal with this issue at all? Right now it just feels like you struggle to barely support more than a couple issues a week.

**Comment by Dogfalo** [comment] 2015-07-21 06:36
We are looking into recruiting some people to help manage issues and pull requests. @carlosperate we appreciate your contributions throughout the lifetime of this project, and think you could greatly impact this project. If you are interested in helping us out, send us an email at materializeframework@gmail.com

**Comment by felixcheruiyot** [comment] 2015-08-27 11:25
@Dogfalo followed up this conversation from the top. 

Is it possible to get a roadmap of pending features the team would like to add for the next release? 

Also, it might be helpful if we find a way of prioritizing the issues. We can chip in and work on them based on priority.

**Comment by Dogfalo** [comment] 2015-08-31 00:54
If it helps, we can mark certain issues to be completed for next release and then if we have consistent contributions from the open source community, it could help out the project a lot.

**Comment by felixcheruiyot** [comment] 2015-09-01 15:41
I think that will be helpful. You can mark those that have high demand and you feel they are achievable. I am looking at the code, I hope to help in a couple of them.

**Comment by mitar** [comment] 2015-10-21 06:37
How many people have commit access to this project? Maybe for starters it would be useful to enlarge the group with commit bit?

**Comment by menasheh** [comment] 2017-02-22 19:14
I found this by searching Google for "Should I use Materizlizecss in production?"

There are 1000 issues and 300 pull requests and I can't imagine searching through all thos properly to determine if someone else already asked my issue or even has a pr for it.

That's the only thing stopping me from using materialize at the moment.

**Comment by tomscholz** [comment] 2017-04-01 23:07
I will close this issue for now. We are currently working on cleaning up old and duplicate issues.

**Closed by tomscholz** 2017-04-01 23:07 UTC

**Comment by menasheh** [comment] 2017-04-24 18:59
closed without answering or indicating if there's anything wrong with it or what exactly it is a duplicate of.

**Comment by fega** [comment] 2017-04-24 19:30
This is a general question and as you can see, we are working on issue closing and fixing bugs with pull request.
