### ISSUE TITLE
Roboto woff files missing from bower.json

### ISSUE THREAD

**Issue by ColtonProvias** [Dogfalo/materialize#1085] opened 2015-04-03 03:16 UTC
Roboto-Regular.woff2, Roboto-Light.woff2, Roboto-Regular.woff, and Roboto-Light.woff are missing in bower.json and thus grunt-bower doesn't include them.

**Comment by boustanihani** [comment] 2015-04-03 10:10
Duplicate of https://github.com/Dogfalo/materialize/issues/1075

**Comment by Dogfalo** [comment] 2015-04-05 19:06
Fixed in ade42fcc325e246868d7e98d2762067374677a43

**Closed by Dogfalo** 2015-04-05 19:06 UTC
