### ISSUE TITLE
How to validate select input?

### ISSUE THREAD

**Issue by faizplus** [Dogfalo/materialize#1861] opened 2015-08-06 08:01 UTC
I just want to use HTML5 required attribute to make a select box required but it is not working in materializecss select. Please help!

It also raises error on console 
An invalid form control with name='name_of_input' is not focusable.

**Comment by JimishF** [comment] 2015-08-06 12:18
I have faced same problem, and i resolved it by comparing select box value with its Label name in before submit function.

**Comment by Dogfalo** [comment] 2015-08-06 23:32
This is how html works, you must have an empty value for the first option
for required to work

**Comment by chi-bd** [comment] 2015-12-23 03:56
>you must have an empty value for the first option

No, this is another problem. Please test this patch.
```javascript
$(document).ready(function() {
    $("select").material_select();

    // for HTML5 "required" attribute
    $("select[required]").css({display: "inline", height: 0, padding: 0, width: 0});
}
```

**Comment by rhuanbarreto** [comment] 2016-04-23 02:47
@chi-bd can you explain why this patch works?

**Comment by chi-bd** [comment] 2016-04-23 14:14
(link to #2028)
This is "Egg of Columbus".
Meterial-select makes the original &lt;select&gt; DOM hidden("display: none").
The other hand, validation message of HTML5 isn't output when the validation target DOM is hidden(at least IE & Chrome).
To cope with both, the CSS of &lt;select&gt; will set to display by size "0".

**Comment by TomFreudenberg** [comment] 2017-01-25 14:29
Hi @chi-bd thanks for post

I have made some improvements, now it look pretty nice to me.

``` javascript
    $('select[required]').css({
      display: 'inline',
      position: 'absolute',
      float: 'left',
      padding: 0,
      margin: 0,
      border: '1px solid rgba(255,255,255,0)',
      height: 0, 
      width: 0,
      top: '2em',
      left: '3em'
    });
```

Cheers
Tom

**Comment by atomtm** [comment] 2017-02-09 13:10
The patches provided leave a red dot under the <select> element on FF ESR 45.7.0 (Debian Jessie 8)

**Comment by TomFreudenberg** [comment] 2017-02-09 13:16
Hi @atomtm 

could you check if this is happened at the forms on https://meetus.koella.com also?

I can't see any red dot so far but don't use Debian currently.

**Comment by atomtm** [comment] 2017-02-09 13:24
@TomFreudenberg 
![select](https://cloud.githubusercontent.com/assets/6628454/22785145/b9327bd6-eedb-11e6-925a-dc11909fe0b8.png)
perhaps you have to zoom a bit to clearly see it .

**Comment by TomFreudenberg** [comment] 2017-02-09 13:31
Yeah, see that ... 

I guess this might be the "active" indicator from FF to show "you are on the field" and just catch some nasty pixels ...

Okay ... I can reproduce this on FF 50 on MacOS as well (not on Chrome nor Safari) ... Just click into the field "First Name" and "Shift-TAB" (use keyboard) to select previous field. Within this action ... there is also a dot ... 

Seems to be on FF only

**Comment by atomtm** [comment] 2017-02-09 14:07
@TomFreudenberg Opera leaves a small triangle. http://imgur.com/a/y6CNf.

**Comment by TomFreudenberg** [comment] 2017-02-09 14:37
Hm ... so that needs more / better adjustment or fix ...

**Comment by atomtm** [comment] 2017-02-09 17:02
If you come up with something else please let me know !

**Comment by hylke94** [comment] 2017-03-17 13:27
When does this come to the base code?

**Comment by shanehoban** [comment] 2017-06-26 10:17
Adding `opacity: 0` to Tom's fix gets rid of that red circle in FF

```
$('select[required]').css({
      display: 'inline',
      position: 'absolute',
      float: 'left',
      padding: 0,
      margin: 0,
      border: '1px solid rgba(255,255,255,0)',
      height: 0, 
      width: 0,
      top: '2em',
      left: '3em',
      opacity: 0
    });
```

**Comment by Dogfalo** [comment] 2017-07-19 22:06
fixed in 97c450b

**Closed by Dogfalo** 2017-07-19 22:06 UTC
Labels: bug, component:Select

**Comment by mrdnote** [comment] 2017-10-19 09:46
I also had to add pointerEvents: 'none'; to the css override, else the old select was still clickable!

My workaround for the select validation:
http://jsfiddle.net/b8frk03m/1/

**Comment by AJLeonardi** [comment] 2018-07-29 16:40
This issue appears to be present in rc2. 

When I add required to my select,  I get this message In the console  (same as the original issue report): 
An invalid form control with name='name_of_input' is not focusable.

The browser wants to add the validation message to the <select> and it can't because it's hidden. 

Dropping this bit of @mrdnote 's code into my page fixed it.
```
$('select[required]').css({
      display: 'inline',
      position: 'absolute',
      float: 'left',
      padding: 0,
      margin: 0,
      border: '1px solid rgba(255,255,255,0)',
      height: 0,
      width: 0,
      top: '2em',
      left: '3em',
      opacity: 0,
      pointerEvents: 'none'
    });
```

**Comment by baccarg** [comment] 2018-08-07 23:14
Confirm.  Still here in RC2

**Comment by baccarg** [comment] 2018-08-07 23:14
@Dogfalo check this . TY!

**Comment by nikolaysm** [comment] 2018-10-16 09:58
+1

**Comment by 4selin** [comment] 2018-12-10 11:49
still no validation for select input?

**Comment by findsarfaraz** [comment] 2018-12-10 16:19
no validation for select input.

**Comment by daslani** [comment] 2019-01-09 21:50
@Dogfalo seems like the npm registry 1.0.0 package doesn't include this while the GitHub repo master does. Is it something that can be done reasonable easily?

**Comment by FriedNails** [comment] 2019-03-12 22:33
😢

**Comment by austinbachman** [comment] 2019-03-29 16:48
Any updates here? Still exists on 1.0.0.

**Comment by rlugge** [comment] 2019-04-02 17:46
Can confirm, still an issue on 1.0.0 even with a 'default' disabled answer available.

**Comment by honkeat** [comment] 2019-07-10 03:49
The problem persists. html5 required not working still for select input, showing the same problem.

**Comment by BenBitDesign** [comment] 2019-07-15 07:02
@Dogfalo This issue seems to persist still. Same is happening for me.

**Comment by icavalheiro** [comment] 2020-03-24 20:06
Fix appears to be there for 0.100 but not for 1.0

**Comment by coendr** [comment] 2021-03-30 12:23
if people still need a fix i use this:
$(document).ready(function () {
            $('select').formSelect();
            $('select[required]').css({
                display: 'inline',
                position: 'absolute',
                float: 'left',
                padding: 0,
                margin: 0,
                border: '1px solid rgba(255,255,255,0)',
                height: 0,
                width: 0,
                top: '3em',
                left: '7.5em',
                opacity: 0
            });

**Comment by eduardoalcantara** [comment] 2021-11-29 16:54
**DEFINITIVE SOLUTION:**
The problem is actually with the rendered `input` that replaces the `select` element. It is irrelevant that this select is hidden or not. The Materialize CSS engine does not verify if your select element is required or has the `validate` class. I don't know why they didn't put that code I will show you below, but that will solve the problem if you put it in a JavaScript file in your page:

    $(document).ready(function(){
        $('select').formSelect(); 
        const _requiredSelects = $("select[required].validate");
        _requiredSelects.parent().find('input').addClass('validate').attr('required', 'required');
        _requiredSelects.keypress(function() { 
            return false; 
        });
        _requiredSelects.change(function($event) { 
            const _select = $event.target;
            const _value = $(_select).val();
            const _input = $(_select).parent().find('input');
            _input.removeAttr('readonly', '');
            _input.val(_select.options[_select.options.selectedIndex].label);
            if (_value != '') {
                _input.addClass('valid');
                _input.removeClass('invalid');
            } else {
                _input.addClass('invalid');
                _input.removeClass('valid');
            }
        });
        _requiredSelects.each(function(){
            const _this = $(this);
            const _helper = _this.parent().parent().find('.helper-text');
            if (_helper !== undefined) {
                const _input = _this.parent().find('input');
                _helper.insertAfter(_input);
            }
        });
    });

**Comment by eduardoalcantara** [comment] 2021-11-29 17:38
```javascript
$(document).ready(function(){
    $('.tooltipped').tooltip(); // dica que aparece quando o usuário põe o mouse em cima do componente
    $('select').formSelect(); // montagem de campos <select> com material design
    // isto corrige o problema de renderização em campos select que exigem validação quando o campo é de preenchimento obrigatório
    const _requiredSelects = $("select[required].validate");
    _requiredSelects.parent().find('input').addClass('validate').attr('required', true)
    .keydown(function($event) { 
        return $event.keyCode == 9;
    });
    _requiredSelects.change(function($event) { 
        const _select = $event.target;
        const _value = $(_select).val();
        const _input = $(_select).parent().find('input');
        _input.removeAttr('readonly', '');
        _input.val(_select.options[_select.options.selectedIndex].label);
        if (_value != '') {
            _input.addClass('valid');
            _input.removeClass('invalid');
        } else {
            _input.addClass('invalid');
            _input.removeClass('valid');
        }
    });
    _requiredSelects.each(function(){
        const _this = $(this);
        const _helper = _this.parent().parent().find('.helper-text');
        if (_helper !== undefined) {
            const _input = _this.parent().find('input');
            _helper.insertAfter(_input);
        }
    });
});

```

**Comment by DanDanilyuk** [comment] 2024-01-03 21:41
Here is an example without JQuery:
``` Javascript
const selectElems = document.querySelectorAll('select[required]');
selectElems.forEach(selectElem => {
  selectElem.style.display = 'inline';
  selectElem.style.position = 'absolute';
  selectElem.style.float = 'left';
  selectElem.style.padding = 0;
  selectElem.style.margin = 0;
  selectElem.style.border = '1px solid rgba(255,255,255,0)';
  selectElem.style.height = 0;
  selectElem.style.width = 0;
  selectElem.style.top = '2em';
  selectElem.style.left = '3em';
  selectElem.style.opacity = 0;

  M.FormSelect.init(selectElem);
});
```
