### ISSUE TITLE
Modal doesn't close nav

### ISSUE THREAD

**Issue by corbindavenport** [Dogfalo/materialize#448] opened 2015-01-12 22:40 UTC
If you have a modal div that launches from a nav menu, the nav menu stays in place. The proper function would be to close the menu on modal launch.

Example:
```
<nav>
	<div class="nav-wrapper">
		<a href="#" class="brand-logo">Hello World</a>
		<ul id="nav-mobile" class="right side-nav">
			<li><a class="open-trigger open" href="#">Open</a></li>
		</ul>
		<a class="button-collapse" href="#" data-activates="nav-mobile"><i class="mdi-navigation-menu"></i></a>
	</div>
</nav>

<div id="open" class="modal">
	<h4>Open</h4>
</div>
<script>

$(document).ready(function(){
	$('.open-trigger').leanModal();
});
</script>
```

**Comment by Dogfalo** [comment] 2015-01-17 15:26
Duplicate of  #427

**Closed by Dogfalo** 2015-01-17 15:26 UTC
