### ISSUE TITLE
Customize and Download Materialize

### ISSUE THREAD

**Issue by Abdulmanan0315** [Dogfalo/materialize#5104] opened 2017-08-13 17:07 UTC
Hi,
I am using materialize in many of my projects and it is beautiful .Now i am here for a new feature, as in bootstrap they gave US an option to customize bootstrap ,choose what we want to download [https://getbootstrap.com/docs/3.3/customize/](url) .Similarly, i want that feature in materialize because i want to use some parts of your framework like inputs ,waves effect etc. That will help me and also other people.
Thank you!

**Comment by tomscholz** [comment] 2017-08-13 17:22
Duplicate of #2888

**Closed by tomscholz** 2017-08-13 17:22 UTC
