### ISSUE TITLE
select should not call e.preventDefault() on ESC -- if the select is not active

### ISSUE THREAD

**Issue by bebor** [Dogfalo/materialize#4856] opened 2017-06-21 15:04 UTC
### Description
i am using the select inside a dialog, and on `ESC` i want to close the dialog.
if the select is focused, it catches the ESC-event first, handles it just fine. in case the select was active, i want the select to be closed (thats what happens) and the dialog should not close.
but if the select is already closed, then the ESC-event should lead to closing the dialog (my part).
on my part i can check if the ESC-event has `defaultPrevented`
BUT: in the keyDown handler for `select` you call `e.preventDefault();` always, later in code you trigger `close` if ESC was hit.
if the select is not active, then ESC -> does not need to close the select, and in this case the event (imho) should not be `defaultPrevented`. meaning:
e.preventDefault() should not be called, when ESC was hit, but the select is not active (so `close` does nothing)

code reference: https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L692-L763

**Comment by DanielRuf** [comment] 2017-06-21 16:24
Hm, do you mean `stopPropagation()` and delegated events and tried it with this?

**Comment by DanielRuf** [comment] 2017-06-21 16:29
@bebor can you provide a codepen for us which shows the issue and describe it a bit clearer? Because I did not fully understand what the issue is.

With active you mean open / focus / active?

So far it sounds like a special usecase. The escape closes when it is pressed which is ok.

**Comment by bebor** [comment] 2017-06-21 16:38
my point is this:
* `select` is a child of `dialog` (lets imagine any kind of)
* on that `dialog` i catch `keydown` event, and if it is a ESC *and* the event has not `defaultPrevented===false`, i close the dialog

**now the situation [A]**
* the select is not activated (does not show the dropdown), and the user hits ESC
* this code https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L710 causes `defaultPrevented===true` -- but in fact, the select's keydownHandler has not done anything
* result: the dialog gets not closed (but it should)

**now situation [B]**
* the select is active (does show dropdown), and the user hits ESC
* this code https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L750 causes the select's dropdown to close (thats what excpected)
* in this case, the event will have `defaultPrevented===true` -- which is correct, and the dialog will not close

so what what i suggest is not to call event `preventDefault()` if the keyDownHandler does nothing (like in situation A: where he did not `close`  anything, since the select did not have any active dropdown, which should be closed

this of course would need some reorganization of the `onKeyDown` function.

does it make sense? 
p.s. there may be other scenarios in conflict with my intentions, thats why i describe these particular situations

**Comment by DanielRuf** [comment] 2017-06-21 18:43
Generally a codepen would be great.

> on that dialog i catch keydown event, and if it is a ESC and the event has not defaultPrevented===true, i close the dialog

Can you show us your current code so we can test this and find a viable solution?

See https://codepen.io/anon/pen/KqqdXr. There are event listeners on the dialog and the select(s).
Romoving any of these makes not much sense imho. The esc key always triggers a close of the modal which is ok and the expected behavior.

In your case you may need `jQuery.off/on()` and `stopPropagation();`

**Comment by bebor** [comment] 2017-06-22 07:22
see https://codepen.io/anon/pen/dRRVoQ

i should have mentioned i use aurelia-dialog, not materializecss modal, but that should not be any different for what i demonstrate

**Comment by Thanood** [comment] 2017-06-22 08:11
If I click anywhere else in the modal after closing the select (with `ESC`), the modal is closed.
Interesting..

**Comment by acburst** [comment] 2017-07-12 20:39
It has to do with the focus. If the select is still focused, it is catching all the keydown events. You need to defocus the select to have your inputs work again. This is the default interaction with select elements so that you can reopen the select if need be.

**Closed** 2017-07-18 22:21 UTC
