### ISSUE TITLE
Icon buttons

### ISSUE THREAD

**Issue by remzr7** [Dogfalo/materialize#2577] opened 2016-01-01 23:34 UTC
What about adding icon buttons like http://www.material-ui.com/#/components/icon-buttons

**Comment by tomscholz** [comment] 2017-04-02 00:34
Try this https://codepen.io/tomscholz/pen/XMrBJe
Duplicate of: https://github.com/Dogfalo/materialize/issues/227

**Closed by tomscholz** 2017-04-02 00:34 UTC
