### ISSUE TITLE
Waves effect on circular button broken on Safari

### ISSUE THREAD

**Issue by JoeAzar** [Dogfalo/materialize#1809] opened 2015-07-27 23:54 UTC
![square-waves](https://cloud.githubusercontent.com/assets/5893544/8920614/34fb6984-3499-11e5-8707-b2dd99ae1449.png)

See title and attached image.

**Comment by carlosperate** [comment] 2015-07-28 00:04
This seems to be a duplicate of https://github.com/Dogfalo/materialize/issues/1607
Let me know if it is not and I'll reopen the issue.

**Closed by carlosperate** 2015-07-28 00:04 UTC

**Comment by JoeAzar** [comment] 2015-07-28 00:09
Yeah it definitely is. Sorry about that, didn't see the other one.
