### ISSUE TITLE
Not working preselected from collapsible

### ISSUE THREAD

**Issue by trydalcoholic** [Dogfalo/materialize#4468] opened 2017-04-01 07:12 UTC
After the page is loaded class active removed from collapsible-header.
If I'm not mistaken, the site in the examples section of the accordion with a pre-open sections, too not work.
http://materializecss.com/collapsible.html

**Comment by tomscholz** [comment] 2017-04-01 08:32
Duplicate of #4375

**Closed by tomscholz** 2017-04-01 08:32 UTC
