### ISSUE TITLE
Swipeable tabs carousel height limited to 400px

### ISSUE THREAD

**Issue by gillesbs** [Dogfalo/materialize#4159] opened 2017-01-30 15:00 UTC
The `.carousel` `div` is limited to a `height` of `400px`.
Sometimes, an ever smaller `height` is forced with a `style` attribute.
This is actually to small for the content I want to show under the tabs.
The issue:
Why is it limited to `400px`? How can I fix this?

Thank you for your response.

**Comment by mchalakov** [comment] 2017-02-03 12:51
Duplicate of #4148

**Comment by mchalakov** [comment] 2017-02-03 12:55
The problem is that the swipeable tabs are style by the carousel css. Reference #4148 .
In materialize.css change:
`.tabs-content.carousel { height: 100%; overflow-x:hidden; overflow-y: scroll; } .tabs-content.carousel .carousel-item { width: 100%; height: 100%; } html,body{ overflow:hidden; height:100%; }`

**Comment by Blaconix** [comment] 2017-03-01 08:42
This doesn't work for me. I'm currently having the same issue, and when adding the above css, the tab content just gets height 0.

**Comment by ServCinc** [comment] 2017-03-02 21:49
@Blaconix @gillesbs 

Set the height and width properties of the selector `.tabs-content.carousel .carousel-item` to whatever you want the width and height to be. 

Then in a document ready function, change the height of the container to be whatever the height of the content is with a statement similar to: 
`document.querySelector('.tabs-content.carousel').style.height = "100%";`

**Comment by itggot-arvid-nilber** [comment] 2017-03-08 19:37
Am I the only one who doesn't even find the `.tabs-content.carousel` .carousel-item line in the css file? I have the latest version...

**Comment by Blaconix** [comment] 2017-03-08 21:02
I just used this:
`.tabs-content.carousel .carousel-item {
    height: 100%;
}`

In my custom css file.

**Comment by lyh424** [comment] 2017-03-09 01:16
I've set .tabs-content.carousel, .tabs-content.carousel .carousel-item { height: 400px;} but .tabs-content-carousel is still being set to 340px. Do you know why this is the case? I have to use !important to force the sizing.

**Comment by fega** [comment] 2017-04-15 23:02
Duplicate of #4148

**Closed by fega** 2017-04-15 23:02 UTC
Labels: bug, css

**Comment by Braed** [comment] 2017-04-29 00:05
Can we get a carousel for text? I'm really struggling to make this work - I'd like to use it for an auto-scrolling kinda testimonial-type thing. Speaking of which, why isn't there autoscroll??

**Comment by Braed** [comment] 2017-04-29 00:14
[How can i make the slider use auto height?](http://prntscr.com/f22cvv)
Also, [is there a way to add padding or something between slides?](http://prntscr.com/f22cd7)

**Comment by fega** [comment] 2017-05-02 13:56
@Braed give me some basic codepens and I will try to help you

**Comment by Braed** [comment] 2017-05-02 20:01
I don't know what you want me to codepen, but i just want a carousel with text, but with padding so that the text doesn't touch from slide to slide, and with auto height so that the carousel can change height from item to item. I don't want to use 400px (or any absolute value) for the height.

http://codepen.io/anon/pen/pPwKXy

**Comment by ericlormul** [comment] 2017-05-02 22:59
I also spot another weird thing when using swipeable tabs. When you try add an img tag into a tab. The carousel's height becomes 0, making the carousel disappear. 

To reproduce it,
add '<img src="path" alt="" />' into any tab, in @Braed 's codepen, http://codepen.io/anon/pen/pPwKXy

**Comment by Braed** [comment] 2017-05-03 12:55
I'd also like to see the indicators become something we can add ourselves.  
Take a look at my wireframe [here](http://prntscr.com/f3m86z) and you can see that i'd like the indicators to be in the heading and not overlaying the carousel. Granted, that's easy enough with absolute positioning and media queries to retain responsiveness, but it would be nice to have these as something we could add ourselves, where we wanted them, and then just use data tags to link them to specific carousels.
I'm likely asking far too much of this framework at this point, but if anyone knows a more efficient way to do this than with absolute positioning, let me know!

**Comment by Braed** [comment] 2017-05-03 13:03
Also, on a more realistic note, can we expect to see carousels given auto-scroll soon? Every other carousel has this and although it's relatively easy to implement with JS, why is it not already a feature?

**Comment by dibyanshusinha** [comment] 2017-05-22 17:17
Isn't it  bug that image issue followed by that limited width. 
Why is this closed ?? Is there a way around ??
I was trying to create a testimonial using carousel and I can't find any easy way to do it. I needed just one logo on top with some text below it. Now I can't have the image in carousel-slider and the fixed height 400px is just too large for my case.
Thanks

**Comment by Badlapje** [comment] 2017-06-26 21:39
same question: why is this closed?  It's still an issue.  I can't read the text in the tabs, nor can i find out why it happens at all.

I can set the height at 100%, but even so it won't go above 520px in height.  No idea why that is :(

**Comment by AugmentBLU** [comment] 2017-07-19 11:58
I'm getting the same 0 height issue. Any real fixes for this as it's style in the dom is set to height: 0 so no matter the CSS rule, it does not work.

**Comment by Maqsyo** [comment] 2017-07-19 12:00
Please look here:
https://github.com/Dogfalo/materialize/issues/4982

**Comment by gusbemacbe** [comment] 2017-07-19 19:23
I followed the suggestions of @Blaconix and @, and nothing worked.

**Comment by CodingWeb** [comment] 2017-07-26 03:14
Fix:

.tabs-content.carousel .carousel-item {
   width: 100%;
   height: 280px;
}

**Comment by Jujunol** [comment] 2017-09-28 19:02
This shouldn't be closed, this is still an Issue.
@Maqsyo The issue isn't anything to do with full width

**Comment by tomscholz** [comment] 2017-09-28 19:18
I agree, this shouldn't be closed. Please reopen...

**Comment by silviosoto** [comment] 2017-10-15 20:48
Facil !!! 
con Jquery
 $(".carousel").css({ "height": "100%"});

RESUELTO

**Comment by Jujunol** [comment] 2017-10-16 15:53
@silviosoto I'm not sure what else you might be doing but that didn't seem to work for me

**Comment by silviosoto** [comment] 2017-10-24 05:23
modifies the height of the property or with another height
my, I tube the problem and solve it by modifying the order in which the css files called the order is as follows:
1. materialize.css file
2. you.css

**Comment by CybMeta** [comment] 2017-12-08 10:58
New to materializecss and this is the first big issue I'v found. I don't even understand the reason of having a fixed height for the carousel (or swipeable tabs as well). Can anyone explain the reason behind this behaviour? Why it is necessary at least?

**Comment by mevansLA** [comment] 2018-01-11 21:20
Anyone stumbling across this...
`.tabs-content.carousel .carousel-item {
  height:auto;
}`

**Comment by preston206** [comment] 2018-03-15 07:04
I tried most of the ideas in this thread but none worked. The only way I could get it to work is hard coding the height. Not a great solution. Where is the support?

**Comment by treztreiz** [comment] 2018-05-10 06:58
This is a dirty fix but it does work. :)

Add this to your .css file
`.tabs-content.carousel .carousel-item { height:auto; }`

Then this to your .js file (jquery)
```
$(function(){
    resizeTab();
    $( window ).resize(function() { resizeTab(); });
});
function resizeTab(){
    var maxHeight = 0;
    $('.carousel-item').each(function(){ 
         if($(this).height() > maxHeight) maxHeight = $(this).height(); 
    });
    $(".tabs-content").css('height',maxHeight+'px');
}
```

This js resize the tabs parent to the tallest child on its initialization, and when the window is resized.

**Comment by gillesbs** [comment] 2018-06-29 16:39
Thank you very much for this solution, finally one that works! It is not excellent, but good enough for what I planned to do with it.

**Comment by Enoch2k2** [comment] 2018-11-15 19:55
> This is a dirty fix but it does work. :)
> 
> Add this to your .css file
> .tabs-content.carousel .carousel-item { height:auto; }
> 
> Then this to your .js file (jquery)
> 
> $(function(){
>     resizeTab();
>     $( window ).resize(function() { resizeTab(); });
> });
> function resizeTab(){
>     var maxHeight = 0;
>     $('.carousel-item').each(function(){ 
>          if($(this).height() > maxHeight) maxHeight = $(this).height(); 
>     });
>     $(".tabs-content").css('height',maxHeight+'px');
> }
> This js resize the tabs parent to the tallest child on its initialization, and when the window is resized.

With that last fix, i noticed that when each tab is a different size with cards and rows, that it takes in the size with the most rows and adjusts all of the tabs. I made a few alterations to the javascript so it bases the height to what is being show at the time.

CSS is the same

Javascript
```
<script>
  $(document).ready(function(){
    $('.tabs').tabs({swipeable: true, onShow: resizeTab});
    
    $( window ).resize(function() { resizeTab(); });
  });

  function resizeTab(){
    var maxHeight = 0;
    if($('.carousel-item.active').height() > maxHeight) maxHeight = $('.carousel-item.active').height(); 
    $(".tabs-content").css('height',maxHeight+'px');
  }
</script>
```

**Comment by TH75020** [comment] 2018-11-20 09:52
I've just tried it. It works perfectly.
Thank you very much.

**Comment by mxdpeep** [comment] 2019-01-18 10:37
I have found that THIS solution is better for lazy loading of images:

`$(".carousel.carousel-slider").css("height", $(".carousel-item.active>img").height() + "px")`

**Comment by Craicerjack** [comment] 2019-02-25 16:23
> $(".carousel").css({ "height": "100%"});

I had a collapsible list in my tab that would push items off the bottom of the page. 
A combination of:
```
$(".carousel").css({ "height": "100%"});
.tabs-content.carousel.carousel-slider .carousel-item.active{
    position: relative;
} 
```
seems to have fixed it for me

**Comment by idiglove** [comment] 2019-07-19 00:27
> > $(".carousel").css({ "height": "100%"});
> 
> I had a collapsible list in my tab that would push items off the bottom of the page.
> A combination of:
> 
> ```
> $(".carousel").css({ "height": "100%"});
> .tabs-content.carousel.carousel-slider .carousel-item.active{
>     position: relative;
> } 
> ```
> 
> seems to have fixed it for me

Actually this is the simplest answer!

```
.tabs-content.carousel.carousel-slider .carousel-item.active{
    position: relative;
}

//and I added this
.tabs-content {
    height: auto !important;
    min-height: 100%;
}

```

**Comment by blackbomb404** [comment] 2022-08-07 03:45
Just rewrote the resizeTab function in pure JS, as i'm not using JQuery:

```
function resizeTab(){
    let maxHeight = 0;
    const carouselItems = document.querySelectorAll('.carousel-item');

    let currentItemHeight;
    carouselItems.forEach(item => {
        currentItemHeight = getComputedStyle(item).height;
        currentItemHeight = currentItemHeight.substring(0, currentItemHeight.indexOf('px')); // just removing the 'px' at the end
        if(currentItemHeight > maxHeight)
            maxHeight = currentItemHeight; 
    });

    document.querySelector('.carousel').style.height = maxHeight +'px';
}
```
