### ISSUE TITLE
Noob Question: Use materialize's jQuery plugin with Webpack

### ISSUE THREAD

**Issue by VioletVivirand** [Dogfalo/materialize#3676] opened 2016-09-21 07:32 UTC
Hi Guys! Nice to meet you! Here is my noob question:

I'm working on a demo with Materialize, Vue.js, and Webpack. Here is a vue file:

``` vue
<template>
  <div class="container">
    <div class="row">
      <div class="input-field col s12">
        <select multiple>
          <option value="" disabled selected>Choose your option</option>
          <option value="tea">Tea</option>
          <option value="coffee">Coffee</option>
          <option value="juice">Juice</option>
        </select>
        <label>Materialize Multiple Select</label>
      </div>
    </div>
  </div>
</template>
<script>
import jquery from 'jquery/dist/jquery'
var $ = jquery
import 'materialize-css/dist/js/materialize.js'

$(document).ready(function () {
  $('select').material_select()
})
</script>
<style>
</style>
```

And Select component doesn't show up. Here is the message returns by the console:

```
Uncaught TypeError: $(...).material_select is not a function
```

But when I enter these command in the console manually:

``` javascript
$('select').material_select()
```

It works! The Select component shows up!

Can anybody help me to correct the code? Many thanks!

And here is my `webpack.config.js`:

``` javascript
var webpack = require('webpack');

module.exports = {
  // entry point of our application
  entry: './main.js',
  // where to place the compiled bundle
  output: {
    path: __dirname,
    filename: 'build.js'
  },
  module: {
    // `loaders` is an array of loaders to use.
    // here we are only configuring vue-loader
    loaders: [
      {
        test: /\.vue$/, // a regex for matching all files that end in `.vue`
        loader: 'vue'   // loader to use for matched files
      },
      { 
        test: /\.css$/, 
        loader: 'style-loader!css-loader'
      },
      { 
        test: /\.png$/, 
        loader: 'url-loader?limit=100000'
      },
      { 
        test: /\.jpg$/, 
        loader: 'file-loader'
      },
      {
        test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, 
        loader: 'url?limit=10000&mimetype=application/font-woff'
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, 
        loader: 'url?limit=10000&mimetype=application/octet-stream'
      },
      {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, 
        loader: 'file'
      },
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, 
        loader: 'url?limit=10000&mimetype=image/svg+xml'
      }
    ]
  }
};
```

**Comment by patrys** [comment] 2016-09-29 13:46
This is because `materialize-css` lists `jquery` and `hammerjs` as its dependencies instead of peer dependencies. The result is that `materialize-css` gets its own private copy of `jquery` independent from what the rest of your project uses. I would say that it's a serious bug.

**Comment by patrys** [comment] 2016-09-30 13:53
See #3707 for a related issue. A temporary workaround is to force all `jquery` references to resolve to the same file in your `webpack.config.js`:

```javascript
  resolve: {
    alias: {
      'jquery': path.resolve(__dirname, '/jquery/dist/jquery.js')
    }
  },
```

**Comment by fega** [comment] 2017-04-09 01:24
duplicate of #3707

**Closed by fega** 2017-04-09 01:24 UTC
