### ISSUE TITLE
New List Feature

### ISSUE THREAD

**Issue by penguoir** [Dogfalo/materialize#4716] opened 2017-05-22 17:50 UTC
Hi, everyone!

I'm working on a [new feature](https://github.com/penguoir/materialize-list) and I'm almost done. Wondering if I should finish off (organise sass and such) and submit a pull request or if I've missed anything.

Thanks for the help!

**Comment by tomscholz** [comment] 2017-05-22 19:16
@DanielRuf this looks good to me on mobild, but can you have a look at this and give some feedback too?

**Comment by penguoir** [comment] 2017-05-22 20:17
I just realised that collections is really similar to this.

**Comment by DanielRuf** [comment] 2017-05-22 21:30
@penguoir but lists as you implemented are still missing, see https://github.com/Dogfalo/materialize/issues/4553

**Comment by tomscholz** [comment] 2017-05-23 09:15
@penguoirI think collections are a little bit out of scope from the material design spec. Maybe you could rewrite the collections with your lists. I really think this could fit into this framework

**Comment by penguoir** [comment] 2017-05-23 10:09
Cool. Is there a specific way to add a component to the framework?

**Comment by DanielRuf** [comment] 2017-05-23 10:32
It's recommended to fork Msterialize, create a new feature branch, add the files in sass/ and js/ and docs in /jade, add the files to the Gruntfile, test locally and push it to GitHub and open a new pull request for this.

**Comment by penguoir** [comment] 2017-05-26 07:28
I've made the [pull request](https://github.com/Dogfalo/materialize/pull/4727)

**Comment by penguoir** [comment] 2017-05-26 07:31
I think it would be a good idea to integrate lists as I implemented them and slowly deprecate the collections component.

**Comment by djensen47** [comment] 2017-06-05 20:58
> I think it would be a good idea to integrate lists as I implemented them and slowly deprecate the collections component.

Agreed. It's a little confusing that it is currently called collections when the Material Design spec refers to lists. It's also a good idea to deprecate so that existing sites or libraries that depend on Materialize have time to adjust.

**Comment by tomscholz** [comment] 2017-06-19 17:21
The discussion has moves to the pr

**Comment by djensen47** [comment] 2017-06-19 17:24
Um, but the issue is not resolved. There isn't a way to lock a conversation without closing?

**Comment by tomscholz** [comment] 2017-06-19 17:31
;)

**Comment by tomscholz** [comment] 2017-06-19 17:32
Changed my mind. Closing this one and keeping [this one ](https://github.com/Dogfalo/materialize/issues/2837)open.

**Closed by tomscholz** 2017-06-19 17:32 UTC
