### ISSUE TITLE
Collapsible 'active' not working on 0.98.1

### ISSUE THREAD

**Issue by gillesbs** [Dogfalo/materialize#4518] opened 2017-04-10 18:34 UTC
### Description
Considering the collapsible component: when adding the class 'active' next to collapsible-header, the box doesn't open since Materialize version 0.98.1.

**Comment by tomscholz** [comment] 2017-04-10 18:54
Duplicate of #4375
Fixed in b336331

**Closed by tomscholz** 2017-04-10 18:54 UTC
