### ISSUE TITLE
Request: Remove styles from heavy-lifting elements like 'nav'

### ISSUE THREAD

**Issue by sposhe** [Dogfalo/materialize#1959] opened 2015-08-25 23:01 UTC
Having a lot of styles applied to basic elements means a lot of Materialize styles have to be manually reset in order to use something like a `nav` element freely. Not just on the element itself, but on all of the child elements as well, such as `ul`, `li`, and `a`.

Using classes instead of the vanilla elements to style things would allow for easy semantic usage of these elements where needed. So a Materialize navigation would change from—
```html
<nav>
  ...
</nav>
```
—to—
```html
<nav class="materialize">
  ...
</nav>
```

This will allow Materialize to be used more easily as a foundation to be built upon, rather than just an out-of-the-box solution.

**Comment by schorsch** [comment] 2015-08-26 06:36
+1

**Comment by carlosperate** [comment] 2015-08-26 09:57
Duplicate of: https://github.com/Dogfalo/materialize/issues/1659

**Closed by carlosperate** 2015-08-26 09:57 UTC
