### ISSUE TITLE
clicking / touching search bar in docs on mobile closes sidenav

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#5677] opened 2018-02-19 06:20 UTC
When I touch the search bar it directly closes the sidenav. Also scrolling moves it too much.

**Comment by developeranirudhprabhu** [comment] 2018-02-20 07:19
Can you give codepen for this and also steps to reproduce the issue?

**Comment by DanielRuf** [comment] 2018-02-20 07:23
Just take a look at the current docs at http://next.materializecss.com ;-)

**Comment by developeranirudhprabhu** [comment] 2018-02-20 08:11
Its reproducible on actual device. Not on simulation through chrome. Will try to check it

**Comment by acburst** [comment] 2018-02-20 18:03
Good catch. This is an unintended side effect of us closing the sidenav on window resize. On mobile devices, bringing up the keyboard resizes the window. I've now changed it so the sidenav only closes on horizontal window resizes.

Fixed in aa2997a8

**Closed by acburst** 2018-02-20 18:03 UTC
