### ISSUE TITLE
Incorrect displaying error message for input with initial state of validation as invalid

### ISSUE THREAD

**Issue by lozovoyv** [Dogfalo/materialize#3608] opened 2016-09-04 13:29 UTC
When I load page with predefined initial state of input as invalid and empty value error text displays incorrect, same as https://github.com/Dogfalo/materialize/issues/2028. If input gets focus and then looses it without any changes in value, state is triggered to default.
If value not empty it works fine.
UPD. If placeholder exists it works too, even it's value is empty (placeholder="")

<p data-height="265" data-theme-id="light" data-slug-hash="ALjWYr" data-default-tab="html,result" data-user="lozovoyv" data-embed-version="2" class="codepen">See the Pen <a href="http://codepen.io/lozovoyv/pen/ALjWYr/">ALjWYr</a> by LozovoyV (<a href="http://codepen.io/lozovoyv">@lozovoyv</a>) on <a href="http://codepen.io">CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by GuillaumeMasselot** [comment] 2016-11-15 13:10
Hi guys, any news about this issue ?
I have it too and this is a very annoying issue on a very common component.

**Comment by Thanood** [comment] 2016-11-15 13:39
TBH, Im not sure what else to expect from adding the `invalid` css class to the label.
Materialize validation is essentially HTML5 validation. If you remove `invalid` and enter an invalid email address into the pen, it gets "invalid". Works as expected IMO.

You may want to try the `required` attribute to check for empty input on form submit.
Or add the `invalid` class when it's empty using a script during form submit.

**Comment by GuillaumeMasselot** [comment] 2016-11-15 14:54
Yep but is the error message supposed to move when the upper label does ?
It's a weird behavior imho

**Comment by Thanood** [comment] 2016-11-15 15:01
I see, hmm..
The error text is "tied" to the label (which is not yet `transformX`ed)..

So it's not supposed to move but technically it's supposed to be in the right place to begin with. :smiley:

**Comment by GuillaumeMasselot** [comment] 2016-11-15 15:09
Well, thanks a lot for your answers. I hope this will be fixed in a near future !

**Comment by belgacea** [comment] 2016-11-28 19:15
+1
Using [css](https://github.com/Dogfalo/materialize/issues/2028#issuecomment-139772348) until a fix is out..

**Comment by fega** [comment] 2017-04-16 03:37
I agree with @Thanood, I cannot understand why put invalid as predefined...

**Comment by lozovoyv** [comment] 2017-04-19 09:36
@fega It useful for server side validation. For example, field is required in some cases when I need query database or something else. I get POST values, check for it correctness and if it is not correct I return back to page with form with user entered data and error messages.

**Comment by Dogfalo** [comment] 2018-02-28 01:28
The issue where the error text moves with the label has been fixed in v1-dev, however the behaviour where the error is showing is working as intended due to the fact that you added the invalid class.

**Closed by Dogfalo** 2018-02-28 01:28 UTC
Labels: bug
