### ISSUE TITLE
dropdown alignment issues

### ISSUE THREAD

**Issue by bnayagrawal** [Dogfalo/materialize#5085] opened 2017-08-08 13:36 UTC
The alignment works when hover is set true, but doesn't when it is set false.

**Comment by penguoir** [comment] 2017-08-08 19:48
I can't reproduce this issue. Could you share a codepen that would show the problem?

**Comment by bnayagrawal** [comment] 2017-08-10 18:19
Try playing with alignment and hover options.
https://codepen.io/bnayagrawal/pen/wqJxbz

**Comment by Dogfalo** [comment] 2017-10-04 23:11
Fixed in v1-dev

**Closed by Dogfalo** 2017-10-04 23:11 UTC
Labels: confirmed
