### ISSUE TITLE
Autocomplete with chips doesn't display properly

### ISSUE THREAD

**Issue by fongfan999** [Dogfalo/materialize#4624] opened 2017-04-29 15:29 UTC
### Description
Autocomplete with chips works very well **unless** I types the keywords **exactly**. How can I solve this issue?

#### Without the exact keywords 
![good](https://cloud.githubusercontent.com/assets/13912857/25556688/f9bb9416-2d2a-11e7-83ed-4d0552b19120.png)
#### With the exact keywords 
![bad](https://cloud.githubusercontent.com/assets/13912857/25556690/fe51aa38-2d2a-11e7-90cd-b7619d39d9cb.png)

**Comment by tomscholz** [comment] 2017-04-29 15:34
Which version are you using? Duplicate of https://github.com/Dogfalo/materialize/issues/4228

**Closed by tomscholz** 2017-04-29 15:34 UTC
Labels: component:Autocomplete

**Comment by fongfan999** [comment] 2017-04-29 15:50
I'm using version `0.98.2`. And the screenshots were taken on the Materialize [homepage](http://materializecss.com/chips.html)

**Comment by rodrigosantosweb** [comment] 2017-05-17 03:16
I have the same problem.

**Comment by guilhermemaranhao** [comment] 2017-08-08 01:47
Hello guys,

I don't know if I'm facing the same problem. I have the tag "notebook". the autocomplete works until "noteboo", when I enter the "k", the tag simply doesn't appear.

That's how I'm declaring my autocomplete component:

```
$('.chips-autocomplete').material_chip({
            autocompleteOptions: {
                data: tagoptions.autoCompleteData,
                limit: Infinity,
                minLength: 1
            },
            secondaryPlaceholder: 'Adicione a tag',
            placeholder: '+Tag',
            data: tagoptions.data
        });
```
The `tagoptions.autoCompleteData` object is defined as:
```
{
  eraser:null,
  notebook:null,
  pencil: null
}
```
The `tagoptions.data` is an array of chips:
```
[{
  id,
  tag
}]
```

Is it a real problem or am I missing something?

Thank you,

Guilherme
