### ISSUE TITLE
dropdown options does not get picked 

### ISSUE THREAD

**Issue by vpezeshkian** [Dogfalo/materialize#3499] opened 2016-08-11 17:44 UTC
only `data-[attribute]` works for dropdowns.
the code below does not work anymore.
```javascript

  $('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: false, // Displays dropdown below the button
      alignment: 'left' // Displays dropdown with edge aligned to the left of button
    }
  );

**Comment by acburst** [comment] 2016-08-11 19:43
Duplicate of 3417

**Closed by acburst** 2016-08-11 19:43 UTC
