### ISSUE TITLE
Search bar close button behavior in IE 10 and 11

### ISSUE THREAD

**Issue by nicholeapo** [Dogfalo/materialize#3681] opened 2016-09-22 11:21 UTC
The close button that clears the text in the search input seems to be behaving like in the screenshot; it enlarges when starting to type in search term.
[http://imgur.com/a/nsqlm](http://imgur.com/a/nsqlm)

**Comment by tomscholz** [comment] 2017-04-01 23:14
Seems to be a duplicate of:
https://github.com/Dogfalo/materialize/issues/3681 & https://github.com/Dogfalo/materialize/issues/1486
Please use https://github.com/Dogfalo/materialize/issues/1544 for future discussion

**Closed by tomscholz** 2017-04-01 23:14 UTC
