### ISSUE TITLE
Make font paths configurable

### ISSUE THREAD

**Issue by hctom** [Dogfalo/materialize#578] opened 2015-01-31 20:47 UTC
Currently the font paths are hard-coded in the following SASS files:
* components/_roboto.scss
* components/_icons-material-design.scss

It would be nice, if those implementations use SASS variables, so everybody can change those paths  when integrating Materialize in another project.

Thanx in advance

hctom

**Comment by Dogfalo** [comment] 2015-01-31 20:49
Duplicate of #527

**Closed by Dogfalo** 2015-01-31 20:49 UTC

**Comment by hctom** [comment] 2015-01-31 20:54
Wow... that answer was fast ;) Sorry that I did not find this issue I duplicated... but my issue does not only concern the icon font, but the Roboto font as well, which is not covered in #527.

**Comment by Dogfalo** [comment] 2015-01-31 20:54
Don't worry. We will fix both

**Comment by hctom** [comment] 2015-01-31 20:55
+1 thanx!

**Comment by Dogfalo** [comment] 2015-01-31 21:05
Fixed in 07f54009c47ec490a49d67d981f355c338b13a7f
