### ISSUE TITLE
Allow dropdown to open above the button and not only below it

### ISSUE THREAD

**Issue by ciencia** [Dogfalo/materialize#903] opened 2015-03-13 12:06 UTC
In our app we have a data grid and buttons below it to manage the grid (add, delete, modify). The button for adding elements triggers a dropdown, but those buttons are near the end of the document, so you normally have those buttons at the bottom of the screen. If you click on the button, the drop down is expanded to the bottom, so it gets outside the screen, forcing the user to scroll down to see the complete dropdown.

In this situation would be awesome to have an option to expand that dropdown to the top instead of to the bottom.

Apparently, it would require only to add a top option when using velocity in this case.

**Comment by Dogfalo** [comment] 2015-03-13 16:13
Duplicate of #780

**Closed by Dogfalo** 2015-03-13 16:13 UTC
