### ISSUE TITLE
Dropdown showing cursor in iphone safari

### ISSUE THREAD

**Issue by ismailfarooq** [Dogfalo/materialize#2598] opened 2016-01-05 15:37 UTC
Please check (select) dropdown it showing cursor of input in iphone safari

**Comment by TyrionGraphiste** [comment] 2016-01-05 18:53
It's fixed in my PR : https://github.com/Dogfalo/materialize/pull/2514

**Comment by cristianfierro** [comment] 2016-02-10 21:07
Is there a fix for this?

**Comment by minias** [comment] 2016-06-16 01:49
The same phenomenon occurred in the iPhone 6S Chrome 51.0.2704.64.
![selectbox_focus](https://cloud.githubusercontent.com/assets/4125264/16103049/fcaf8bca-33af-11e6-883b-94e7a3387173.png)

**Comment by maechler** [comment] 2017-07-11 09:07
This also happens in Internet Explorer 11 and earlier. The problem is that materializecss renders an input field to display the selected option's text. The dropdown gets shown when that input field is focused. As far as I know IE renders that focus cursor always above everything else. I guess the best fix would be to not use the input field to display the selected option's text.

**Comment by storm1er** [comment] 2017-07-11 19:26
Maybe we could focusout displayed input on focusin without hiding dropdown ?

**Comment by maechler** [comment] 2017-07-12 09:39
@storm1er That could also be a solution. But that would break the navigation by keys, that part would have to be rewritten too.

**Comment by Dogfalo** [comment] 2017-07-12 19:18
Just checked this and it doesn't seem to be happening on iOS safari or chrome

**Closed by Dogfalo** 2017-07-12 19:18 UTC
Labels: browser-bug

**Comment by maechler** [comment] 2017-07-12 20:05
@Dogfalo it does, I just verified the bug on iOS 10.3.2 and iPhone 6S. In addition it is also a problem in internet explorer. Please reopen that issue or refer to a duplicate issue if there is one. 

![img_7857](https://user-images.githubusercontent.com/4113819/28137456-a07bdb6a-674d-11e7-9464-5756c8531939.PNG)

**Comment by maechler** [comment] 2017-07-13 05:05
I would suggest to position the input field off screen with `position: absolute; left: -9999px;` and then render the selected option to a normal div that is styled like an input field. That keeps the select box focusable using navigation by keys and also removes the blinking cursor. In addition all the `focus` and `blur` events can stay the same.

**Comment by Dogfalo** [comment] 2017-07-13 05:09
https://github.com/Dogfalo/materialize/issues/3790
