### ISSUE TITLE
multiple cards with card reveal

### ISSUE THREAD

**Issue by peiphb02** [Dogfalo/materialize#1633] opened 2015-06-30 08:11 UTC
Hi!
I have multiple cards on one page in pinterest style. Now I would like to use the card-reveal feature and tried it the way like it is described in the documentation. All of my cards contain an image. The image therefore has the class "activator". Unfortunately if I click on an image of one card, not only the card-reveal div of this card is shown but also the card-reveal divs of every other card shows up as well. I just want to show the card-reveal div of the one card I clicked on...

Is it a bug of the materialize javascript, or can I achieve the behavior I want through some parameters?
Thanks!

**Comment by KevinStirling** [comment] 2015-07-02 04:53
Hi, also having the same issue. I have two cards and they open at the same time, no matter which one is pressed. Was trying to find a way to hack a work around but ended up wasting an hour to no avail :/

**Comment by spencerkordecki** [comment] 2015-07-02 16:18
Looked into this a bit and it looks like something along the lines or replacing `$(this).find('.card-reveal')` with `$(this).find('.card-reveal').eq($(this).parents('.card').index())` should do the trick in cards.js. The click action is searching for a `.card-reveal` but is not specifying which one and thus both reveals are getting triggered.

**Comment by acburst** [comment] 2015-07-03 01:06
Can you post a codepen? I've seen this issue before where the user was wrapping their card reveals in a larger card which caused the issue. But a codepen would help me pinpoint this issue better

**Comment by spencerkordecki** [comment] 2015-07-03 13:56
http://codepen.io/anon/pen/jPZdXW

It also looks like this may be linked to the functionality of having a singular card with content changed out in navigation. When I took the cards that were having the issue out of any containing `<div>`s, the cards seemed to work as intended with individual reveals.

**Comment by acburst** [comment] 2015-07-12 01:10
Fixed in 17bf474

**Closed by acburst** 2015-07-12 01:10 UTC

**Comment by najubhai** [comment] 2015-07-19 23:13
I am still having this issue in the latest 0.97 release. Any workaround to this?

**Comment by acburst** [comment] 2015-07-20 00:09
Its fixed on the master github version. You can pull from that or you can wait until the next release.
