### ISSUE TITLE
SideNav flickers back and forth when swiping up or down on overlay

### ISSUE THREAD

**Issue by redboul** [Dogfalo/materialize#4648] opened 2017-05-05 09:21 UTC
### Description
Hi,  
when swipping up or down on the sidenav overlay, the menu disappears but when tapping on the screen, it reappears to disappear...

It seems to comes from [sideNav.js#L189](https://github.com/Dogfalo/materialize/blob/v0.98.2/js/sideNav.js#L189):
```javascript
menu.css('transform', 'translateX(' + (x - options.menuWidth) + 'px)');
```
where menu is translated out...

### Repro Steps

On a mobile device (or Chrome Dev Tools with device toolbar activated with mobile device): 
- open http://materializecss.com/
- open menu
- swipe up or down on the overlay: _The menu disappear_
- tap somewhere on the page: _The menu flickers back_

I am currently trying to find a workaround

Nice work btw

**Comment by redboul** [comment] 2017-05-05 09:31
Actually, when swipping from the overlay, `x` equals 0, therefore it translates the menu out but does not close it correctly.
the workaround would be to give `x` a fallback value to `300`. The code would change to:
```javascript
menu.css('transform', 'translateX(' + ((x || 300) - options.menuWidth) + 'px)');
```
**FYI**: it only occurs when the menu is open on the left edge.

If it is something suitable I would make a PR.

Regards

**Comment by tomscholz** [comment] 2017-05-05 10:29
Duplicate of https://github.com/Dogfalo/materialize/issues/4082, would you mind to post you discoveries over at that issue? Anyhow I will close this issue for now

**Closed by tomscholz** 2017-05-05 10:29 UTC

**Comment by redboul** [comment] 2017-05-05 10:58
sorry about that didn't look for `side-nav` but `sidenav` in issue list
