### ISSUE TITLE
forms problems chrome 73

### ISSUE THREAD

**Issue by rubenscd** [Dogfalo/materialize#6311] opened 2019-03-15 16:38 UTC
forms don't work in Google Chrome 73.0... materializecss v0.100.2

**date picker & tag select**

try in http://archives.materializecss.com/0.100.2/forms.html

**Comment by DavinderPRO** [comment] 2019-03-16 09:08
date picker closing automatically after opening.

**Comment by DanielRuf** [comment] 2019-03-16 17:23
This is a regression in Chrome.

See https://bugs.chromium.org/p/chromium/issues/detail?id=941910 and https://github.com/amsul/pickadate.js/issues/1138

**Comment by DanielRuf** [comment] 2019-03-16 17:25
Please keep in mind that v0.x is not developed anymore. We are on v1.x now.

**Closed** 2019-03-17 23:00 UTC

**Comment by azharuddinsayed** [comment] 2019-03-18 07:43
Few things which are working in  v0.x is not working in v1.x so please guide me , i have only issue with drop down with v0.x , how i can resolve the issue

**Comment by ivicaned** [comment] 2019-03-26 18:20
it would be really helpful to have some quick fix for materialize 0.100.2, because we can't upgrade to 1.000 immediately.

**Comment by DanielRuf** [comment] 2019-03-26 18:49
You can patch this using `patch-package`.

**Comment by crispdata** [comment] 2019-03-27 06:19
What is the way out for pickadate in chrome 73?

**Comment by DanielRuf** [comment] 2019-03-27 06:35
@crispdata see https://github.com/amsul/pickadate.js/commit/9282a8021c47e39d1aee72d69557d6e4ee68034d

But set the value to `100` or a bit higher.

**Comment by crispdata** [comment] 2019-03-27 06:44
@DanielRuf 

$('.fromdatepicker').pickadate({
        format: 'yyyy-mm-dd',
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15, // Creates a dropdown of 15 years to control year
        onSet: function (ele) {
            if (ele.select) {
                var chosen_date = $('.fromdatepicker').val();
                $('.todatepicker').pickadate('picker').set('min', chosen_date);
                $(".todatepicker").removeAttr('disabled');
                this.close();
            }
        },
        onClose: function () {
            //$('.datepicker').blur();
            $(document.activeElement).blur()
        }
    });

This is the code I am using for pickadate
Can you please tell me what changes I can do in this code to making it works in Chrome 73?

**Comment by DanielRuf** [comment] 2019-03-27 06:52
Please see https://github.com/amsul/pickadate.js/pull/1140, you have to change the source of the pickadate component.

**Comment by zeeshanaligold** [comment] 2019-04-19 19:38
@crispdata
The solution is to filter the target with the parent:
if ( target != ELEMENT && target != document && target != P.$root.parent()[0] && event.which != 3 )

**Comment by amanagarwal2189** [comment] 2019-05-01 14:35
@DanielRuf is it being planned to push 1.0.0 of materialize to Atmosphere? the last update to materialize on Atmosphere was on Aug 26, 2017.

**Comment by DanielRuf** [comment] 2019-05-01 15:15
@amanagarwal2189 I do not know, I am not a maintainer of this project and was just one of a few longtime contributors.

**Comment by amanagarwal2189** [comment] 2019-05-01 16:04
@DanielRuf ah. Thank you for the response. Any way to communicate this to the Maintainers? I did log an issue. But I don't know the turnaround time for it.

**Comment by guianzollin** [comment] 2019-07-09 23:52
One alternative for select is delete this code in materialize.js

`$(this).trigger('open', ['focus']);`

**Comment by DanielRuf** [comment] 2019-07-10 03:44
Not really a solution for a regression caused by Chrome tbh.

**Comment by guianzollin** [comment] 2019-07-10 13:32
Not really a solution, but is an alternative while the solution is not available

**Comment by mcapraveen4082** [comment] 2019-10-14 12:14
No need to change any file just use below code after initialization.
$('.datepicker').on('mousedown',function(event){
    event.preventDefault();
});
