### ISSUE TITLE
Select with multiple is not align well

### ISSUE THREAD

**Issue by brisfernando** [Dogfalo/materialize#5155] opened 2017-08-28 16:24 UTC
In the documentation, the select dropdown with multiple is not align well..
https://goo.gl/photos/ev2EMErHAgfu9juP6

Thank you..

**Comment by DanielRuf** [comment] 2017-08-29 20:50
https://github.com/Dogfalo/materialize/commit/81ab9ba3654fdbaca88d0f18a1a7f7998424e725

I'll prepare a PR.

**Comment by Dogfalo** [comment] 2017-08-29 20:54
Duplicate of #5083

**Closed by Dogfalo** 2017-08-29 20:54 UTC
Labels: component:Select
