### ISSUE TITLE
"ready" callback not working when modal is opened dynamically

### ISSUE THREAD

**Issue by doubleOrt** [Dogfalo/materialize#4932] opened 2017-07-04 04:27 UTC
Before you open the modal dynamically, if you use a trigger button then everything works fine. However after you open it dynamically, the "ready" callback won't be called, and the trigger button won't call the "ready" callback anymore when clicked.

[Codepen illustrating the issue](https://codepen.io/doubleOrt/pen/pwVVeE)

**Comment by gityopie** [comment] 2017-07-04 07:00
Hi @doubleOrt 

I think, you need you call the method manually when you open your modal.
for example:
```
$('#my_modal').modal('open', {
    ready: function(modal, trigger) {
      alert('ready!');
      console.log(modal, trigger);
    },
    complete: function() {
      alert('completed!');
    }
});
```
[jsfiddle](https://jsfiddle.net/ewukp0xc/)

**Comment by storm1er** [comment] 2017-07-04 07:34
But what if you need to set options before opening it
_(why ? depends on context, exemple : async request)_

+1, this is a bug

**Comment by tomscholz** [comment] 2017-07-04 07:38
Duplicate of https://github.com/Dogfalo/materialize/issues/4876
Thanks @storm1er for pointing that out

**Closed by tomscholz** 2017-07-04 07:38 UTC

**Comment by doubleOrt** [comment] 2017-07-04 11:06
@gityopie Oh i never knew about this second parameter, i tried passing a function as the second parameter but not this. Why is the documentation not updated with these things ? You guys know that you can only be as good as your documentation, right ?

**Comment by doubleOrt** [comment] 2017-07-04 11:08
@tomscholz Could you take a look at [this Gist](https://gist.github.com/doubleOrt/b36e014a35ff7d86af94ef0aab69c223), it consists of an issue (#4925) was discussing with one of your creators 2 days ago, but he's had no response.
