### ISSUE TITLE
Wrong behavior for the expansion of the fixed float action button (FAB) in Internet Explorer 11

### ISSUE THREAD

**Issue by ChemBioScripting** [Dogfalo/materialize#2708] opened 2016-01-26 01:30 UTC
Hello, I have noticed that, using Internet Explorer 11 (Windows 8.1), the fixed floating action button (FAB), used with the .fixed-action-btn.horizontal classes, not expands from right to left (as in firefox and chrome) but from left to right: the result is that, by placing the FAB near the right edge of the screen, in Internet Explorer 11, on float button click, the menu is not visible. You can test the examples "Horizontal FAB" and "Click-only FAB" by visiting the relative [page](http://materializecss.com/buttons.html). Removing the "horizontal" class, the behavior is similar to Firefox and Chrome instead. I don't know whether there has already been implemented the ability to decide the direction of horizontal (towards the "right" or the "left") and vertically (towards the '"up" or "down") expansion. Thank you

**Comment by Dogfalo** [comment] 2016-01-26 04:03
It is working for me. Can you show the console error if there is one?

On Mon, Jan 25, 2016 at 5:30 PM, Riccardo Volpe <notifications@github.com>
wrote:

> Hello, I have noticed that, using Internet Explorer 11 (Windows 81), the
> fixed floating action button (FAB), used with the
> fixed-action-btnhorizontal classes, not expands from right to left (as in
> firefox and chrome) but from left to right: the result is that, by placing
> the FAB near the right edge of the screen, in Internet Explorer 11, on
> float button click, the menu is not visible You can test the examples
> "Horizontal FAB" and "Click-only FAB" by visiting the relative page (
> http://materializecsscom/buttonshtml) Removing the "horizontal" class,
> the behavior is similar to Firefox and Chrome instead I don't know whether
> there has already implemented the ability to decide the direction of
> horizontal (towards the "right" or the "left") and vertically (towards the
> '"up" or "down") expansion Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2708>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by ChemBioScripting** [comment] 2016-01-26 12:31
Thanks for replying. There isn't any console error. I created a video to show what happens: https://drive.google.com/file/d/0B3Jd36tJc-X7V2NjYkJsdWQzRlk/view?usp=sharing

**Comment by Thanood** [comment] 2016-01-26 13:23
I can confirm this.
Setting ```left: inherit;``` (instead of ```left: initial;```) for ```.fixed-action-btn.horizontal ul``` seems to fix this for IE.

**Comment by ChemBioScripting** [comment] 2016-01-26 23:36
Thank you very much, Thanood! The use of `left: inherit;`, instead of `left: initial;`, for `.fixed-action-btn.horizontal ul`, seems to fix it. There is only one little difference in IE11 vs Firefox or Chrome, as you can see in this [gif](https://drive.google.com/file/d/0B3Jd36tJc-X7TGY3SW9EdjVRX3c/view?usp=sharing): a cut of one pixel, in IE11, for the `ul li` elements (with blue background-color, in the gif), which cuts the blue circle in the bottom, in IE11... As you can see, the problem not involves the icon inside the `li` element, but only the blue circle. Thank you!

**Comment by Dogfalo** [comment] 2016-01-27 06:22
I'll reopen this so we don't forget to fix this.

**Comment by ChemBioScripting** [comment] 2016-01-27 12:38
Perfect! Yesterday I forked your repository and have done the correction with a pull request, after the commit to my repository; I hope it's the correct way to fork a repository; it's the first time for me! Thank you @Dogfalo

**Comment by moridianmess** [comment] 2016-02-01 19:35
I can confirm that this is still an issue in IE10. It seems to be fixed by changing left: inherit; to left: auto;

![post](https://cloud.githubusercontent.com/assets/2845386/12728677/e4af0d84-c91a-11e5-99eb-46ae6566dd40.png)
![pre](https://cloud.githubusercontent.com/assets/2845386/12728678/e4bd52a4-c91a-11e5-9982-06fada0428e1.png)

**Comment by acburst** [comment] 2016-03-07 00:28
Fixed in d901d66

**Closed by acburst** 2016-03-07 00:28 UTC

**Comment by Sandeep819** [comment] 2016-05-30 11:37
Hello, i'm trying to use horizontal Fixed-Action-Button (FAB) in my code but the hover effect aligns vertically only.. i made every other component working but I never had any issues with materialize.css framework.. But this thing is stopping my work. Can u help me. And also click-to-toggle class is also not working.

**Comment by Sandeep819** [comment] 2016-05-30 12:17
Solved..

**Comment by subash-bose** [comment] 2016-06-22 10:38
@Sandeep819 : could you please explain how you solved this issue. I am also facing the same issue but couldn't able to solve it.

**Comment by Sandeep819** [comment] 2016-06-23 00:51
The reason why it isn't working is that, it is missing one of the materialize css cdn file link or jquery plugin link or initialization jquery code of that component. I missed the jquery plugin link in my code. That's why it misbehaved..  Checkout carefully..  Hope this helps.
