### ISSUE TITLE
date picker not working with jquery 2.2 (maybe other js features too ?)

### ISSUE THREAD

**Issue by MathieuDerelle** [Dogfalo/materialize#2808] opened 2016-02-17 13:58 UTC
I'm new to materialize and I'm not sure if it's documented anywhere.

I was using jquery 2.2 and couldn't make date picker work. Changed it to jQuery 1.12 and everything was fine.

**Comment by spencer4of6** [comment] 2016-02-17 20:11
I'm having the same issue. Here is a jsfiddle of the issue:

https://jsfiddle.net/spencer4of6/wbf6tx2j/

Switching it to jQuery 2.1.4 worked fine. Also, it seems to work on IE for me with jQuery 2.2, but not Firefox or Chrome.

**Comment by MacGyer** [comment] 2016-02-19 09:27
+ 1

**Comment by Thanood** [comment] 2016-02-19 10:05
I'm pretty sure this is a jQuery issue, since it also affects completely unrelated libraries, f.i. KendoUI. I'm just trying to avoid jQuery 2.2 for now.

**Comment by blackfyre** [comment] 2016-03-01 13:47
Can confirm the problem with jquery version 2.2.1, reverting to 2.1.4 solves it.

**Comment by Dogfalo** [comment] 2016-03-01 16:00
I've taken a brief look before but it gave no errors so I'm not sure what
the problem is yet

**Comment by nikhil-pandey** [comment] 2016-03-03 07:57
Clicking on the date picker input field doesn't work with jQuery v2.2.1. However, if i choose the input field using `Tab` key and hit `space`, picker appears and works fine.

**Comment by Dogfalo** [comment] 2016-03-08 03:43
Duplicate of #2688

**Closed by Dogfalo** 2016-03-08 03:43 UTC
