### ISSUE TITLE
collapsible-header add class "active" invalid

### ISSUE THREAD

**Issue by lxsea20150901** [Dogfalo/materialize#4543] opened 2017-04-15 03:28 UTC
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by DanielRuf** [comment] 2017-04-15 05:55
You mean that the active collapsible is not automatically opened? This is already known and fixed in the master branch.

**Comment by DanielRuf** [comment] 2017-04-15 05:56
See https://github.com/Dogfalo/materialize/commit/b336331e851d5903ce684b55cfd3049042d87b28

**Closed** 2017-04-15 06:23 UTC

**Comment by lxsea20150901** [comment] 2017-04-16 06:42
Downloaded from the official website of the source code has such a problem, from the above GitHub copy of this error

**Comment by lxsea20150901** [comment] 2017-04-16 06:45
Could you speak Chinese? English need to translate for a long time.

**Comment by tomscholz** [comment] 2017-04-16 09:01
I am not able to reproduce it in v0.98.2
