### ISSUE TITLE
Select max-height overflow

### ISSUE THREAD

**Issue by Mikeismynick** [Dogfalo/materialize#4770] opened 2017-06-06 13:28 UTC
Hi, there is some problem with select menu, i think this closed issue is also about this https://github.com/Dogfalo/materialize/issues/3252

### Description

Height of select menu overflow body, this happened if u have second select, and click to it don't close the first one

### Repro Steps

1. open "first menu", open "second menu" (scroll for body will appear) and scroll down.

gif - https://gyazo.com/4cab9f9abb521d6b1ebcd22b1c4812d3
codepen - https://codepen.io/Mikeismynick/pen/PjqZZV

**Comment by DanielRuf** [comment] 2017-06-17 14:55
The issue is, that there is an animation when a select / dropdown is closed. Setting the duration parameter of this and removing a setTimeout "fixes" this.

See the following comparison (left side is the original file, right side is the modified file).

![image](https://user-images.githubusercontent.com/827205/27253893-79ea37e6-537d-11e7-9d87-a4d8ce524b88.png)


You can test the change here: https://codepen.io/anon/pen/owBGBj

It comes from the dropdown component which is also used for selects: https://github.com/Dogfalo/materialize/blob/2746daeed242088a298fd4b0b06f6ce2c2242f6a/js/dropdown.js

@tomscholz @acburst How should we fix this? I fear the change on the right side is not how it should be as this "removes" the fadeOut animation (we could also use `hide()`).

**Comment by DanielRuf** [comment] 2017-06-17 15:11
Temporary fix / workaround for your usecase: set `outDuration: 225 ` to 0.

**Comment by Dogfalo** [comment] 2017-10-10 00:45
Fixed in v1-dev

**Closed by Dogfalo** 2017-10-10 00:45 UTC

**Comment by DanielRuf** [comment] 2017-10-10 03:44
@Dogfalo can you link us to the specific commit?
