### ISSUE TITLE
Suggestion on Fixed Action Button 

### ISSUE THREAD

**Issue by muhajirframe** [Dogfalo/materialize#1572] opened 2015-06-23 11:30 UTC
Hi.. Thank you this great framework.
I just wanna suggest a simple change about the fixed action button. 
![testos](https://cloud.githubusercontent.com/assets/12745166/8305054/a92241ae-19d5-11e5-84f4-201cfc146b65.png)
When i move my mouse over the red area it will trigger the child of that button. But it's a alot of space, and it's bothering if you use small screen device. So maybe you can fix it . Thanks :D

**Comment by kabaka** [comment] 2015-06-25 18:04
This is a duplicate of #729

**Closed** 2015-06-26 03:12 UTC
