### ISSUE TITLE
Problem with custom error messages on empty input fields

### ISSUE THREAD

**Issue by Clearwood** [Dogfalo/materialize#4436] opened 2017-03-29 14:20 UTC
### Description
To check if a confirmation field contains the same value than the main input field I am using a very small javascript function which just compares both values on keyup and if they missmatch adds the invalid class to the second input which should confirm the new password. 
The problem is that if the confirmation input field is empty it displays the custom error message at an incorrect position when the invalid class is applied to such an empty input field.

### Repro Steps
Use the codepen I provided and just input something in the first input field.

### Screenshots / Codepen
http://codepen.io/clearwood/pen/BWGBaB
![screenshot 72](https://cloud.githubusercontent.com/assets/11144110/24459068/f0be758e-149a-11e7-95f9-ea84bd051d68.png)

**Comment by DanielRuf** [comment] 2017-03-29 15:48
An empty input field does not get the active class which applies the transform.
So far this is by design.

You have a special case (which is not so special), linked inputs where the validation of the seconds input is triggered by the first or another input. Normally the empty inputs are not directly validated, just on submit or when something is typed.

Try this codepen, not sure if this is what you meant: http://codepen.io/anon/pen/JWeoBr

**Comment by Clearwood** [comment] 2017-03-29 16:37
Thank you very much for this way to fix it for me, i just wonder if there ever should be a time when the success or error message should not be in place directly beyond the input field, so I would like to bring into discussion whether this position should be fixed for those message on input fields and not changed during the transformation.

**Comment by DanielRuf** [comment] 2017-03-29 16:48
Could depend on how the Material Design guidelines of Google define this and if not how it should work. I did not check how it should be. The CSS transformation is applied to the labels (the error / success message seems to be in a label too).

**Comment by NonameSLdev** [comment] 2017-04-07 07:39
@DanielRuf But it is a problem because only the main label should be transformed, and the error/success label shouldn't be affected by this (it should be in it's "transformed" style by default). Perhaps we could just make a separate label for the error/success message, or we could keep it the way it is and move the main label to the `:before` and apply the transformation on it.

**Comment by DanielRuf** [comment] 2017-04-07 07:43
@NonameSLdev right, splitting it makes somehow sense as the transform on the label creates problems as we see.

**Comment by fega** [comment] 2017-04-07 16:16
@NonameSLdev it should solve also #2697 and #4506

**Comment by bmass02** [comment] 2017-09-08 02:41
@DanielRuf Could we update ```forms.js``` to correctly/completely use HTML5 form validations ([HTML5 ValidityState](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState)? So changing ```element[0].validity.badInput``` to ```element[0].validity.valid``` or ```element[0].checkValidity()``` would then allow a developer to use ```setCustomValidity(error)``` to set the state of the input label. Then some logic could be added to take the error message ```input.validationMessage``` and set it to the label's 'data-error' attribute. I'd be happy to make a PR with these changes, but I figured discussing it first would be better.

**Comment by acburst** [comment] 2017-10-09 20:14
Error and success messages have been decoupled from the label element in aa03660 on the v1-dev branch. These styling issues will be fixed for v1

**Closed by acburst** 2017-10-09 20:14 UTC
Labels: bug
