### ISSUE TITLE
Waves buttons are extremely blurry every here and there

### ISSUE THREAD

**Issue by gdoron** [Dogfalo/materialize#3963] opened 2016-12-01 20:57 UTC
I didn't do anything special, you check it out on [yooocan.com](https://yooocan.com).
**Sometimes** the buttons are extremely blurry! 
![image](https://cloud.githubusercontent.com/assets/6141009/20812128/17fa99e0-b819-11e6-9221-291bacead2ab.png)

Refreshing the page usually work:

![image](https://cloud.githubusercontent.com/assets/6141009/20812181/4dbc7a4e-b819-11e6-9105-55ddd22fe4a6.png)

Any clue why does it happen?

**Comment by tomscholz** [comment] 2016-12-02 12:37
Can't reproduce the error. Have you tried using another browser already?

**Comment by gdoron** [comment] 2016-12-02 13:39
Since it's reproduced seldomly, it doesn't surprise me you could not reproduced it.
I only saw it on chrome since I only use chrome.
But I saw it on another developer too (again chrome).

Sorry, but that's all I got.

**Comment by benelliott** [comment] 2016-12-09 11:17
I'm encountering this too, especially on buttons created using the Material Icons font. It seems to only occur on Chrome and seems like it's a browser rendering issue.

**Comment by kmmbvnr** [comment] 2016-12-09 11:24
Can't reproduce.

Chrome Version 55.0.2883.75 (64-bit) Linux

**Comment by benelliott** [comment] 2016-12-09 11:31
I can reproduce this with Chrome 54.0.2840.99 and 55.0.2883.75 on Windows 7 x64 (more than one machine). It seems to be a problem with the `will-change` attribute as overriding it (e.g. with `will-transform: initial !important`) solves the issue for me.

**Comment by benelliott** [comment] 2016-12-09 11:45
I can reproduce this issue in a [Fiddle](https://jsfiddle.net/0fjxtxdp/1/). It seems the border-radius transition is crucial for me. Adding
```
.waves-effect {
  will-change: initial !important;
}
```
Removes the blur.

**Comment by gdoron** [comment] 2016-12-09 13:51
@benelliott any idea why I see it just every here and there?
Same machine and browser.

Anyway, @Dogfalo probably should be aware to your findings.

Thanks a ton!

**Comment by benelliott** [comment] 2016-12-09 15:04
Nope - do you have a lot of animations on container elements in your page? That seemed to be crucial to reproducing the error to me.

Out of curiosity, does the button look blurry to you on my fiddle?

No worries - I found your issue after looking for a solution myself!

**Comment by gdoron** [comment] 2016-12-09 15:09
@benelliott yes it is blurry, 100% of the times, which made me wonder why.
And no, I don't have animations.
You can check https://yooocan.com and see for yourself.

**Comment by benelliott** [comment] 2016-12-09 15:11
None of your buttons are blurry for me! :confused:

**Comment by gdoron** [comment] 2016-12-09 15:19
@benelliott Somehow, I'm not sad hearing that 😄 
Thanks buddy!

**Comment by Dogfalo** [comment] 2016-12-23 23:10
Fixed in 53eaec4. 

I removed the `will-change` as it sometimes causes weird issues like this. Also watch out for `transform: translate3d` which also can cause this issue.

**Closed by Dogfalo** 2016-12-23 23:10 UTC
