### ISSUE TITLE
With animate.css the side-nav goes in the background of slider

### ISSUE THREAD

**Issue by tiwariabhig** [Dogfalo/materialize#5250] opened 2017-10-04 17:25 UTC
## When I include animate.css (library) the side-nav goes in background of image slider.
Here is what did I include...

`<link href="css/animate.css" rel="stylesheet" type="text/css"/>
        <script src="js/jquery.min.js" type="text/javascript"></script>
        <link href="css/main.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script:700|Pacifico|Play|Pontano+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ropa+Sans" rel="stylesheet">`

` <nav>
                <div class="nav-wrapper animated pulse">
                    <a href="#" class="brand-logo"><img src="images/logo.png" alt="logo image"></a>
                    <a href="#" data-activates="mobile-nav" class="button-collapse"><i class="fa fa-bars fa-2x" style="color: #fb6d6d;"></i></a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                    <ul class="side-nav" id="mobile-nav">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </nav>`

![screenshot 38](https://user-images.githubusercontent.com/16822592/31189862-0d240738-a957-11e7-90fd-4c0d32d1e98f.png)

**Comment by tomscholz** [comment] 2017-10-04 17:37
Would you mind to create a codepen? That would make it easier for us to quickly analyze the problem :)

**Comment by tomscholz** [comment] 2017-10-04 17:37
Just make sure to fill out the ISSUE_TEMPLATE properly

**Comment by tomscholz** [comment] 2017-10-04 17:41
@Dogfalo Could you label this as thirdparty?

**Comment by tiwariabhig** [comment] 2017-10-05 07:14
Yeah sure I'am uploading to codepen and will post link here soon.  :)

**Comment by tiwariabhig** [comment] 2017-10-05 07:31
<p data-height="265" data-theme-id="0" data-slug-hash="JrMYNJ" data-default-tab="html,result" data-user="abhigabhig" data-embed-version="2" data-pen-title="JrMYNJ" class="codepen">See the Pen <a href="https://codepen.io/abhigabhig/pen/JrMYNJ/">JrMYNJ</a> by Abhigyan Tiwari (<a href="https://codepen.io/abhigabhig">@abhigabhig</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

**Comment by tiwariabhig** [comment] 2017-10-05 07:32
https://codepen.io/abhigabhig/pen/JrMYNJ/ is codepen link :)

**Comment by tiwariabhig** [comment] 2017-10-05 07:36
On line 11 I added animate.css cdn and on line 27 I added animated and pulse classes to animate.
Result of this is the side-nav either goes in background or width is too less and non clickable...
Though I've planned not to use animate.css. There was also  a problem `#sidenav-overlay` was above the sidenav so it wasn't clickable. I solved it by z-index. 
Thanks :)

**Comment by tomscholz** [comment] 2017-10-05 08:22
Duplicate of #3844

**Comment by tiwariabhig** [comment] 2017-10-05 15:19
But solutions provided for #3844 don't work when I include animate.css :/

**Comment by tomscholz** [comment] 2017-10-05 15:59
It does.
https://codepen.io/tomscholz/pen/BwJmGe?editors=1010

**Closed** 2017-10-05 20:15 UTC
