### ISSUE TITLE
Dropdown Button with Icon inside

### ISSUE THREAD

**Issue by georgeroubie** [Dogfalo/materialize#4418] opened 2017-03-28 12:44 UTC
When you click a dropdown button with icon inside, it does not open the dropdown content. You can test it and live here: http://materializecss.com/dropdown.html . Change the html from developer tools and add an icon.

This happend after the update to 0.98.1

**Comment by tomscholz** [comment] 2017-03-28 12:58
Duplicate of https://github.com/Dogfalo/materialize/issues/4409
And fixed in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4

**Comment by georgeroubie** [comment] 2017-03-28 13:03
Ok thank you!

**Comment by tomscholz** [comment] 2017-03-28 14:08
Please close this issue then...

**Closed** 2017-03-29 07:49 UTC
