### ISSUE TITLE
Mobile hamburger menu not working

### ISSUE THREAD

**Issue by said50** [Dogfalo/materialize#3957] opened 2016-11-29 18:05 UTC
### Description
Hello, when I implement the mobile hamburger menu in my site, it doesn't fully work. When I resize my window, the hamburger menu does show up and I can click on it, but everything is grayed out. See the codepen to see what I mean. (here's a screenshot http://i.imgur.com/tGIFWNE.png in case it doesn't reproduce the issue correctly).

Here is my codepen
http://codepen.io/said50/pen/PbJMwg

**Comment by tomscholz** [comment] 2016-11-29 18:21
@said50 There you go: https://codepen.io/tomscholz/pen/ZBXgKy
Everything is explained here https://github.com/Dogfalo/materialize/issues/3844
 ;)

**Comment by said50** [comment] 2016-11-29 18:44
@tomscholz thanks, it works in the codepen, but aside from moving the class="side-nav" outside the nav, what else have you done since it doesn't work on my site. Also, you put the JS in the JS part of codepen, does this mean that I also have to do that? Thanks.

**Comment by tomscholz** [comment] 2016-11-29 18:58
@said50 Sorry for that ^^ No, you don't have to move the JS. But yes, there's more. You have to move the "sidenav" outside the "navbar-fixed". Hope this helps

**Comment by said50** [comment] 2016-11-29 19:00
@tomscholz thanks it works, somehow Brackets Live Mode didn't display it correctly. Anyways thanks a lot!

**Comment by tahatyc** [comment] 2016-12-14 09:53
The problem is with the z-index of the sidenav-overlay and mobile-menu. You can see that the mobile-menu has bigger z-index than sidenav-overlay, but the parents of the mobile-menu holder has no z-index or lower than the overlay. That's why you can see the overlay over the mobile side menu.

**Comment by developeranirudhprabhu** [comment] 2016-12-29 09:51
@tomscholz Can you share the URL where we can see this?

**Comment by tomscholz** [comment] 2017-04-02 22:19
@developeranirudhprabhu Which url do you mean? 
@said50 Duplicate of https://github.com/Dogfalo/materialize/issues/3844

**Closed by tomscholz** 2017-04-02 22:19 UTC
