### ISSUE TITLE
Select position

### ISSUE THREAD

**Issue by raisiqueira** [Dogfalo/materialize#2210] opened 2015-10-26 23:06 UTC
The selects are buggy when inserted into a card
![dropdown](https://cloud.githubusercontent.com/assets/2914170/10745038/06e5ec10-7c1d-11e5-9272-414d7db9c967.png)

**Comment by mccraveiro** [comment] 2015-10-27 02:55
@raisiqueira I've done a jsfiddle reproducing this issue: http://jsfiddle.net/mccraveiro/3egt8n9f/4/
And also a quick fix: http://jsfiddle.net/mccraveiro/6kn0z8jc/1/
The problem here is that the card component has `overflow: hidden`. However, this fix may break other things.

**Comment by raisiqueira** [comment] 2015-10-27 11:32
Okay, thanks, I'll do some more tests and see if will break the layout elsewhere.

**Comment by damienwebdev** [comment] 2015-10-29 17:58
This was marked as closed by @Dogfalo in #1250, he said it would be fixed in the latest release, which I'm not so sure it was. Hopefully we can get a comment on this.

**Comment by acburst** [comment] 2015-10-31 02:34
Yeh, I don't remember the reason for not taking off overflow hidden. I've removed it for now but if it causes problems we may need to revert.

c6d6788

**Closed by acburst** 2015-10-31 02:34 UTC
