### ISSUE TITLE
Cards layout

### ISSUE THREAD

**Issue by mishantrop** [Dogfalo/materialize#2674] opened 2016-01-18 22:06 UTC
It is ok?
```
<div class="col s12 m4">
	<div class="card">
	  <div class="card-image">
		<img src="images/sample-1.jpg">
		<span class="card-title">Название карточки</span>
	  </div>
	  <div class="card-content">
		<p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
	  </div>
	  <div class="card-action">
		<a href="#">Ссылка здесь</a>
	  </div>
	</div>
</div>
```
![Cards](https://pp.vk.me/c621618/v621618028/2b15c/vv_VMvkcT0k.jpg)

**Comment by lovekaizen** [comment] 2016-01-21 16:47
This is quite a common issue with grid elements that have varying heights based on their content. 

I had a similar when developing gemsavvy.tips using Materialize - for last year's Rails Rumble.

You could either set an appropriate `height` value across media queries for your cards - so the columns line up correctly, or consider implementing something like masonry.js if your content is really varied.

**Comment by CesarGonzalezM** [comment] 2016-01-22 12:06
Been too many times with this behaviour, and always using a "masonry" solution with column-count at container.

Is there any other solution with different heights?

**Comment by cfreear** [comment] 2016-01-22 16:12
There's an excellent jquery plugin for this called [matchheight.js](https://github.com/liabru/jquery-match-height) that even works with rows. Try it out.

**Comment by mishantrop** [comment] 2016-01-23 00:52
@lovekaizen, @CesarGonzalezM suitable plugin (masonry), I choose it, thanks.

**Comment by Dogfalo** [comment] 2016-01-23 04:28
As this is not a bug, I am going to close this issue, but feel free to discuss.

**Closed by Dogfalo** 2016-01-23 04:28 UTC

**Comment by legion40216** [comment] 2022-02-11 20:01
Facing the same problem you can try place each card elements in a separate row class.
kinda shocked materialize hasnt solved this issue
