### ISSUE TITLE
Tabs indicator being set incorrectly due to imprecise jQuery .width() use

### ISSUE THREAD

**Issue by stickboywarren** [Dogfalo/materialize#3532] opened 2016-08-17 16:22 UTC
The calcRightPos function to determine the right attribute for the tabs indicator utilizes the jQuery .width() function:  https://github.com/Dogfalo/materialize/blob/master/js/tabs.js#L25.  jQuery's width function is imprecise in it's result.  For example, we are using percents to specify the width of the tabs.  The width of the active tab (el) when checking in dev tools is 643.52, but el.width() returns 644.  The extra .5 pixels causes the calcRightPos to return a -.5px.  This in turn causes the width of the content of the ul.tabs container to exceed the container width, which then makes the scrollbar appear:

https://dl.dropboxusercontent.com/u/184528/screenshot.png

A simple fix is to use the JS getBoundingClientRect() function:

`var calcRightPos = function(el) {
        return $tabs_width - el.position().left - el[0].getBoundingClientRect().width - $this.scrollLeft();
      };`

It might be smart to use getBoundingClientRect() for everywhere width() is used ($tabs_width).

**Comment by jacobq** [comment] 2017-03-30 21:11
I'm not sure if this is the same problem, but when I run the sample tabs code & markup in Firefox (45.8.0) it looks fine, but in Chrome (57.0.2987.110) the indicator width does not match the tab width.

I added a grey background to illustrate this here:

http://output.jsbin.com/jujeju/9

![tab](https://cloud.githubusercontent.com/assets/1633459/24526342/70a1e90c-1563-11e7-9bae-f190570b43e9.png)

**Comment by jacobq** [comment] 2017-04-03 19:15
@Dogfalo this is a pretty severe issue for me. Is there a fix planned? If not, would you accept a PR?

**Comment by tomscholz** [comment] 2017-04-03 19:21
@jacobq We always welcome pull requests :)

**Comment by acburst** [comment] 2017-04-03 20:13
@jacobq it seems to be working fine on chrome for me. Is it happening at all screen sizes? What OS are you using?

**Comment by jacobq** [comment] 2017-04-03 20:16
I am using Linux.

**Comment by jacobq** [comment] 2017-04-03 21:57
Tested screen widths from 373px to 2182px and the problem occurs in all cases.

**Comment by jacobq** [comment] 2017-04-04 16:31
Just did some more testing with [this code](https://output.jsbin.com/jujeju/19) and found that in Linux, in Chrome (Version 57.0.2987.133 (64-bit)) only:

* The `<a>` child of the tab `<li>` element has its `.outerWidth()` consistently 48px (its left & right padding) more than `.getBoundingClientRect().width`. This is not the case in Firefox (ESR / 45.8.0) or on Windows browsers that I tried (recent Chrome, FF, and Edge). 
* If I force the padding to 0 the problem goes away
* If I use jQuery 2.2.4 instead of 3.2.1 the problem goes away

**Comment by jacobq** [comment] 2017-04-05 15:19
Just an update: I traced this to a regression in jQuery between 3.1.1 and 3.2.0. See https://github.com/jquery/jquery/issues/3611

**Comment by Dogfalo** [comment] 2017-10-11 19:14
Tabs no longer relies on jQuery so this issue will be fixed in v1

**Closed by Dogfalo** 2017-10-11 19:14 UTC
Labels: bug
