### ISSUE TITLE
Broken 'Hamburger' Positioning on Mobile V1.0.0-beta

### ISSUE THREAD

**Issue by WillTheVideoMan** [Dogfalo/materialize#5767] opened 2018-03-26 20:43 UTC
Mobile 'hamburger' navigation is mis-positioned on mobile versions of materialise css. This is most clearly visible on the mobile version of the Materialize landing page [itself](http://materializecss.com/).

![image](https://user-images.githubusercontent.com/29780384/37932512-94510be0-3140-11e8-80cd-998999ac5104.png)

## Expected Behavior

Navigation should appear closer to the top left portion of the screen on thinner screens.

## Current Behavior

Navigation appears halfway between the header division and the main body. Generally quite odly positioned. This behaviour is only seen with screen widths below 415px, where the 'hamburger' begins to overlap with the header area.

## Steps to Reproduce (for bugs)

1. Visit [http://materializecss.com/](http://materializecss.com/).
2. Inspect Element and enter responsive viewer (chrome), or alternatively resize browser.
3. Observe the 'hamburger' nav as it crosses the threshold width of 415px.

## Possible Fix
Move 'hamburger' above/below title after a certain breakpoint?

## Your Environment

* Version used: V1.0.0-beta
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mobile

**Comment by smileytechguy** [comment] 2018-03-27 17:53
I too observe a similar issue, with the following visual:
![image](https://user-images.githubusercontent.com/8005215/37985184-2196b560-31c6-11e8-880c-78ec244f81bc.png)
And a condensed version of my code
![image](https://user-images.githubusercontent.com/8005215/37985242-3b3ebd6e-31c6-11e8-8788-2ce429c9c865.png)

**Comment by cristovaov** [comment] 2018-03-28 13:35
Hi @WillTheVideoMan and @smileytechguy ,

You need to add the mobile collapse button inside the `nav-wrapper`.
See here for an example: http://materializecss.com/navbar.html#mobile-collapse

The docs for the `Sidenav` in the JavaScript section needs a correction.

**Comment by smileytechguy** [comment] 2018-03-28 17:38
Fixes it, thanks!  @WillTheVideoMan this can be closed; I will submit a PR in a few to correct the docs (if I can D:)

**Comment by Dogfalo** [comment] 2018-03-29 00:55
This seems to have been caused by a compilation error in the documentation, this will be fixed the next docs site update on the 1st of April

**Closed by Dogfalo** 2018-03-29 00:55 UTC
