### ISSUE TITLE
Fixed Navbar with Mobile Collapse broken in 0.97.8

### ISSUE THREAD

**Issue by drewkennelly** [Dogfalo/materialize#3844] opened 2016-11-01 00:14 UTC
When using a Fixed Navbar and Mobile Collapse together, the overlay that normally covers the rest of the screen is now also covering the SideNav, which makes the links un-clickable. I tested it without the fixed navbar and there is no issue.

This was not a problem 0.97.7

Screenshot attached of the bug, as well as the code used (I replaced my code with the exact code from the documentation to rule out any possibility that my menu was the cause).

    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo">Logo</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html">Sass</a></li>
                    <li><a href="badges.html">Components</a></li>
                    <li><a href="collapsible.html">Javascript</a></li>
                    <li><a href="mobile.html">Mobile</a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="sass.html">Sass</a></li>
                    <li><a href="badges.html">Components</a></li>
                    <li><a href="collapsible.html">Javascript</a></li>
                    <li><a href="mobile.html">Mobile</a></li>
                </ul>
            </div>
        </nav>
    </div>

![screen shot 2016-11-01 at 11 09 37 am](https://cloud.githubusercontent.com/assets/279851/19875792/f0fd7a04-a023-11e6-8633-d10ce5136123.png)

**Comment by ProProPro1** [comment] 2016-11-01 11:24
It Works Fine, You Need To Have Your Code To This: `
        <header>
        <div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo">Logo</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a href="mobile.html">Mobile</a></li>
            </ul>
        </div>
    </nav>
</div>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a href="mobile.html">Mobile</a></li>
            </ul>
</header>`

The Problem Is That You Put The Side Nav Inside Of The <nav> and the <div class="navbar-fixed"></div>

**Comment by drewkennelly** [comment] 2016-11-01 11:27
The code I have comes directly from http://materializecss.com/navbar.html#mobile-collapse

**Comment by ProProPro1** [comment] 2016-11-01 11:28
Then That Means That The Developers Didn't Document It Properly

**Comment by ProProPro1** [comment] 2016-11-01 11:29
This Is How The Result Looks Like From My Code:

![dww](https://cloud.githubusercontent.com/assets/20212891/19888412/c79b62ec-a02e-11e6-803d-e7caeecc8628.jpg)

**Comment by ProProPro1** [comment] 2016-11-01 11:31
http://materializecss.com/buttons.html

Their FAB-To-Toolbar Documentation Isn't Clearly Documented Aswell

**Comment by ProProPro1** [comment] 2016-11-01 11:56
As You Can See The Code Of Their Documentation Site. They Don't Have The Side-Nav Inside Of The `<nav> ` Either.

![ger](https://cloud.githubusercontent.com/assets/20212891/19888974/78bfa576-a032-11e6-91fc-2571664eee15.jpg)

**Comment by tomscholz** [comment] 2016-11-01 17:48
This just looks better @ProProPro1 

```html

<header>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper"> <a href="#!" class="brand-logo">Logo</a> <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html">Sass</a></li>
                    <li><a href="badges.html">Components</a></li>
                    <li><a href="collapsible.html">Javascript</a></li>
                    <li><a href="mobile.html">Mobile</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
    </ul>
</header>
```

**Comment by tomscholz** [comment] 2016-11-01 17:51
@acburst @Dogfalo From SEO sight seen is this really bad.

**Comment by darckyn** [comment] 2016-11-01 19:33
I have the same error :(

**Comment by lastnoob** [comment] 2016-11-09 14:53
Bump, this is an issue. Yeah you can work around it like mentioned before, but its bad for seo as @tomscholz said already

**Comment by tomscholz** [comment] 2016-11-29 18:22
@ProProPro1  https://github.com/Dogfalo/materialize/issues/3844#issuecomment-257544844 Then make it better ;)

**Comment by developeranirudhprabhu** [comment] 2017-01-01 06:54
@acburst @Dogfalo Can you check and close the ticket

**Comment by markimarc** [comment] 2017-02-28 09:45
Still no fix for this?
This is really annoying when you have an one-page site.

**Comment by dkrish** [comment] 2017-03-15 16:46
@tomscholz didn't seem to work for me at all, even when copied exactly on a new file. just turned off the overlay for now

**Comment by tomscholz** [comment] 2017-03-15 16:57
@dkrish can you post a codepen with your code?

**Comment by oppenheimermd** [comment] 2017-03-16 16:27
for now, this is my fix:
```
#sidenav-overlay {
    margin-left: 300px;
}
```

**Comment by BinaryFair** [comment] 2017-03-20 04:11
Here is a fix that I used:
`
#sidenav-overlay {
    z-index: 1;
}
`

**Comment by tomscholz** [comment] 2017-04-02 23:14
@BraxtonFair Your solutions works poorly. 
![bildschirmfoto 2017-04-03 um 01 12 53](https://cloud.githubusercontent.com/assets/20381749/24591829/d9af210e-180a-11e7-8b32-366135da6be3.png)

**Comment by ptmaroct** [comment] 2017-04-21 14:22
So, I fixed this. 
.navbar-fixed {
z-index: 999;
}

Yes, that's it. The default value of z-index is 998 or something. Change that to 999 and you're good to go.

**Comment by tomscholz** [comment] 2017-04-21 14:26
@ptmaroct This is results in this:https://github.com/Dogfalo/materialize/issues/3844#issuecomment-291022165

**Comment by GoldenSlam** [comment] 2017-04-29 23:13
I ended up just changing the left style from 0 to 300px:

#sidenav-overlay {
   left: 300px;
}

**Comment by asmeikal** [comment] 2017-05-23 20:30
The issue is related to the fact that when dealing with nested elements, it prevails the z-index of the parent, [here is an example](https://jsfiddle.net/asmeikal/rLqzmv37/).

In v0.97.7 `.navbar-fixed` had a z-index of 998 and `.sidenav-overlay` was set to 997, so both the fixed navbar and the sidenav were displayed on top of the overlay (so the result is what @tomscholz showed in https://github.com/Dogfalo/materialize/issues/3844#issuecomment-291022165). [This shows v0.97.7 behaviour](https://jsfiddle.net/asmeikal/ofa4uug9/2).

In v0.97.8 the z-index of both the fixed navbar and the overlay was set to 997, and the overlay gets displayed on top both fixed navbar and sidenav. [This shows v0.97.8 behaviour](https://jsfiddle.net/asmeikal/ofa4uug9/).

A possible workaround is appending the overlay to the parent of the sidenav, instead than to the body. I haven't throughout tested it though, it could cause problems if the navbar is not fixed.

**Comment by hyorkim11** [comment] 2017-05-24 05:29
`#sidenav-overlay { z-index: 1; }`
worked for me PERFECTLY. thanks!

**Comment by DanielRuf** [comment] 2017-05-24 14:35
Wasn't this solved by moving the sidenav ul outside of its wrappers?

In this case we just have to document this and provide the right examples.

**Comment by koushikmln** [comment] 2017-06-06 06:14
what is the current and best fix for this?

**Comment by LeafHacker** [comment] 2017-06-06 19:42
@koushikmln The current workaround is in [comment 6](https://github.com/Dogfalo/materialize/issues/3844#issuecomment-257638569). The one with 25 :+1:, 6 :tada: and 4 :heart:...

**Comment by tomscholz** [comment] 2017-06-18 19:59
Whoops didn't mean to

**Comment by Badlapje** [comment] 2017-07-06 14:04
The same fix also works to implement a mobile navbar paired with a dropdown.  Same disadvantages too: still need to override the z-index of the sidenav-overlay to 1 and seo is affected.

**Comment by DanielRuf** [comment] 2017-07-06 15:52
@Badlapje how is SEO affected by this?

@tomscholz the problem with the overlay is the issue where so far your solution works (moving the nav outside of its wrappers).

Should we either fix the z-index values or update the docs with the wrapper solution?

**Comment by LeafHacker** [comment] 2017-07-10 16:17
It probably makes more sense to fix the underlying `z-index` issue, unless that causes bigger issues.

I assume that way `.side-nav` would work correctly both within and outside of `.navbar-fixed`?

In an ideal world, we wouldn't need two `<ul>`s for this, since from a markup perspective it makes little sense to duplicate the nav list.

**Comment by Slimmmo** [comment] 2017-07-13 06:16
I'm not sure if this is the same issue but I've been trying to use [introjs](http://introjs.com/) inside the `sidenav fixed` and experiencing issues with the z-index that has brought me to this issue.

What I found was if I removed both the `position: fixed` and `will-change: transform` from the `side-nav` then it would work properly. Anyone else found the same thing?

**Comment by LeafHacker** [comment] 2017-07-14 16:15
Hm, I thought I'd written another comment on this but it looks like it never sent.

When `.side-nav` is a child of `.navbar-fixed`, no matter what you set `.side-nav`'s `z-index` to, it seems to be positioned _within_ its parent `.navbar-fixed`.

This is the main cause of this bug.

The `#sidenav-overlay` and `.navbar-fixed` both share a `z-index` of `997`. This is so that they are always above page content. Since the `#sidenav-overlay` is later in the markup, it goes above `.navbar-fixed` (which I believe is intended, since this places the overlay above the scrolling header).

Some people have suggested modifying the z-index of either `.navbar-fixed` or `#sidenav-overlay` so that `.navbar-fixed` is above `#sidenav-overlay`, however this would mean that the scrolling header would also be above the overlay.

Unless we find a work around for children of a `fixed` element with `z-index` set being positioned relative/within that parent (on the z axis, anyway), the only clean solution I can see is to ensure that `.side-nav` **is not** a child of `.navbar-fixed`.

We also can't move the `.navbar-fixed > nav` outside of `.navbar-fixed` because it is crucial to the materialize positioning, however you could create a seperate `nav > .side-nav` structure outside of `.navbar-fixed` if you like.

**Comment by bretonio** [comment] 2017-10-08 20:46
Quite right &mdash; remove `navbar-fixed` and the issue goes away. And yes, the adjustment to `#sidenav-overlay` resolves the issue when  the fixed navbar is switched on. So this has been a fruitful google and I thank you all.

**Comment by kurotsukikaitou** [comment] 2017-10-22 16:45
@bretonio Or... You could just move the left-nav to the outside of fixed-nav div like solution on answer number 6 by @tomscholz ... 🤔

**Comment by precizie** [comment] 2017-10-25 08:15
Hi guys!

This is the HTML fix no CSS or anything else:

> 
    <div class="navbar-fixed">
        <nav class="blue" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="#" class="brand-logo">
                    <div class="logo center-block"></div>
                </a>
                <ul class="right hide-on-med-and-down">
                    <li><a id="" href="#">Link</a></li>
                    <li><a id="" href="#">Link</a></li>
                    <li><a href="#" target="_blank">Link</a></li>
                    <li><a href="#" target="_blank">Link</a></li>
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            </div>
        </nav>
    </div>
    <ul id="nav-mobile" class="side-nav">
        <li><a id="" href="#">Link</a></li>
        <li><a id="" href="#">Link</a></li>
        <li><a href="#" target="_blank">Link</a></li>
        <li><a href="#" target="_blank">Link</a></li>
    </ul>
>

**Comment by jessegilbride** [comment] 2017-11-01 01:22
Happy birthday to this issue.

**Comment by Dogfalo** [comment] 2017-11-01 01:53
Please refrain from posting comments and pictures that do not pertain to the discussion.

**Comment by Dogfalo** [comment] 2018-01-25 22:28
Documentation has been updated in 7d94806e47695bd796cc3ebab0c4b792d766c778 to make the HTML placement more clear

**Closed by Dogfalo** 2018-01-25 22:28 UTC
Labels: bug, css, docs

**Comment by Thlenzi** [comment] 2018-02-18 18:40
I'm using this after all .css called..

#sidenav-overlay {
background-color: rgba(0,0,0,0.0);
}

**Comment by DanielRuf** [comment] 2018-02-18 18:51
This is not a solution imho.

**Comment by jeroenoverman** [comment] 2018-05-15 10:11
The solution works for my link items in the sidenav. But I also have a div user-view to show the users name and logout button This user view is clickable but not shown correctly. See image and code below. 
The user view is not clear..
Any thoughts?

```<div class="navbar-fixed">
  <nav class="blue darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo center">TripKeeper</a>
      @auth
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <li class="{{ Route::is('home') ? 'active' : null }}"><a href="/">Overview</a></li>
        <li class="{{ Route::is('trips.*') ? 'active' : null }}"><a href="/trips">Trips</a></li>
        <li class="{{ Route::is('fillups.*') ? 'active' : null }}"><a href="/fillups">Fillups</a></li>
        <li class="{{ Route::is('location.*') ? 'active' : null }}"><a href="/location">Location</a></li>
      </ul>
      <ul class="right hide-on-med-and-down">
        <a class="right-align" href="{{ route('logout') }}"
          onclick="event.preventDefault();
          document.getElementById('logout-form').submit();">
          Logout
        </a>
      </ul>
      @endauth
    </div>
  </nav>
</div>
@auth
<ul id="nav-mobile" class="sidenav">
  <li>
    <div class="user-view blue darken-1">
      <a><h5>{{Auth::user()->name}}</h5></a>
      <a class="right-align" href="{{ route('logout') }}"
          onclick="event.preventDefault();
          document.getElementById('logout-form').submit();">
          Logout
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
      </form>
    </div>
  </li>
  <li class="{{ Route::is('home') ? 'active' : null }}"><a href="/">Overview</a></li>
  <li class="{{ Route::is('trips.*') ? 'active' : null }}"><a href="/trips">Trips</a></li>
  <li class="{{ Route::is('fillups.*') ? 'active' : null }}"><a href="/fillups">Fillups</a></li>
  <li class="{{ Route::is('location.*') ? 'active' : null }}"><a href="/location">Location</a></li>
</ul>
@endauth
```
![userview](https://user-images.githubusercontent.com/13645157/39959687-a592cfe8-5615-11e8-8bc9-dfce43911896.PNG)

**Comment by peppeg** [comment] 2018-10-20 00:16
late 2018, problem still present and not documented!
Solution works 💃 
thanks!

**Comment by DanielRuf** [comment] 2018-10-23 08:07
> late 2018, problem still present and not documented!
> Solution works 💃
> thanks!

0.x releases are not supported anymore. 1.x is the new release. Please create a new issue and a codepen which reproduces the issue.

**Comment by chrisAXZA** [comment] 2022-12-18 18:58
The year is 2022: no gas, no fire wood, no complete Materialize documentation.
@tomscholz gratias !

**Comment by DanielRuf** [comment] 2022-12-18 20:45
@chrisAXZA me and @tomscholz were simple contributors and had not many rights. The problem is with the current maintainers @Dogfalo and @acburst who did not want to work with us to bring things forward.

So some people (including me) created an actively maintained fork at https://github.com/materializecss/materialize, every contributor is very welcome there and longterm contributors get more rights there.

We tried once more to get the original maintainers involved (see https://github.com/materializecss/materialize/discussions/263) or at least get the ok to forward / link to us but as you can see at https://github.com/materializecss/materialize/discussions/263 this was without success.

**Comment by chrisAXZA** [comment] 2022-12-19 11:16
Thanks for the response.

Unfortunate indeed, perhaps in the long-run a dedicated webpage comprising additional document (ie. materialize-documentation.io), which to be frank is non-existent on materializecss.com (a trivial sidenav issue demands the inquiry to an impressive amount of stackoverflow and github-issue pages).

Busy as they might be, also unfortunate that [@Dogfalo](https://github.com/Dogfalo) and [@acburst](https://github.com/acburst) did not at least respond with regards to your inquiries.
