### ISSUE TITLE
selects and modals

### ISSUE THREAD

**Issue by jsduffy** [Dogfalo/materialize#1713] opened 2015-07-10 16:06 UTC
Modal containers with dropdowns in them do not display the dropdown over the modal container.  In the example shown below, the select dropdown expands past the modal footer instead of on top of the modal footer.  This does not happen if you use the browser default class.

gif here:
http://i.gyazo.com/1c579dd389fb844920227f7a9451980c.gif

**Comment by carlosperate** [comment] 2015-07-10 16:17
This issue is briefly discussed in https://github.com/Dogfalo/materialize/issues/138, but it is probably good to have it a separate issue here as that one is originally targetting z-indexes, and his is to do with the way the materialize select in bind to the parent element.

**Comment by uok** [comment] 2015-07-12 21:20
possible dupe of #1527

**Comment by fega** [comment] 2017-04-10 23:18
@jsduffy could you check if this is still an issue in the las version? also, could you share a codepen of it?

**Comment by geocine** [comment] 2017-04-13 18:56
bug still persist on **0.98.1** https://codepen.io/geocine/pen/GmgpeE

**Comment by fega** [comment] 2017-04-14 18:32
duplicate of #1385

**Closed by fega** 2017-04-14 18:32 UTC
Labels: bug
