### ISSUE TITLE
Syntax Error on navbar.html page

### ISSUE THREAD

**Issue by tmd-uk** [Dogfalo/materialize#732] opened 2015-02-21 16:13 UTC
__Syntax Error__ 

Two **i** components for Mobile Collapse Button on [navbar.html](http://materializecss.com/navbar.html#mobile-collapse) have an invalid syntax, both SASS links have an extra unnecessary **closing i**  
```html
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="#!" class="brand-logo">Logo</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
             <i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="sass.html">Sass **</i>** </a></li>
          <li><a href="components.html">Components</a></li>
          <li><a href="javascript.html">Javascript</a></li>
          <li><a href="mobile.html">Mobile</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="sass.html">Sass **</i>** </a></li>
          <li><a href="components.html">Components</a></li>
          <li><a href="javascript.html">Javascript</a></li>
          <li><a href="mobile.html">Mobile</a></li>
        </ul>
      </div>
    </div>
  </nav>
```

Just thought you should know.

**Comment by Dogfalo** [comment] 2015-02-21 16:23
Duplicate of #731

**Closed by Dogfalo** 2015-02-21 16:23 UTC
