### ISSUE TITLE
Internet Explorer not responding after modal close

### ISSUE THREAD

**Issue by DetlefPeters** [Dogfalo/materialize#5017] opened 2017-07-24 09:38 UTC
Can be reproduced with current materialize website (http://materializecss.com/modals.html), so this might be an issue of latest v.0.100:

When closing the modal, IE throws an error `SCRIPT438`, saying that `remove `is not supported
All javascript stops working immediately after this runtime error, you need to hit F5 to get it back to work.

This possibly refers to one of these code lines in `modal.js`
L258 `this.$overlay[0].remove();` or
L319 `this.$el[0].classList.remove('open');`

**Comment by Dogfalo** [comment] 2017-07-24 09:43
What version of IE?

**Comment by jeroenqui** [comment] 2017-07-24 09:49
I can confirm this with Internet Explorer version 11.483.15063.0

**Comment by DetlefPeters** [comment] 2017-07-24 09:59
Yes, same version on my PC. This should be the current version installed on Windows 10.
MS Edge does not have this error, only IE11

**Comment by Thanood** [comment] 2017-07-24 12:06
The error happens here: https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L258
It was introduced with this commit: https://github.com/Dogfalo/materialize/commit/2220501f05c8cb086060f0e2fa596d37aea4d7ed 10 days ago.

**Comment by DetlefPeters** [comment] 2017-07-24 12:27
AFAIK you must call `removeChild(element)` on the element's parent instead of `remove()` on the element, isn't it?

**Comment by Thanood** [comment] 2017-07-24 12:28
As far as I can see, yes.
Or change `this.$overlay[0].remove();` to `this.$overlay.remove();` 😃

**Comment by Dogfalo** [comment] 2017-07-24 19:50
Fixed in bf73cbd4fde3e5bb071f407343e689fb2272da32

**Closed by Dogfalo** 2017-07-24 19:50 UTC
Labels: browser-bug

**Comment by vad-zuev** [comment] 2017-07-28 15:25
just updated to Materialize v. 0.100.1 which contains the fix, still getting the same errror *SCRIPT438* in IE 11.0.9600.18738. Everybody hates IE, but we are forced to support the crap since many of our customers don't have anything else at their disposal ><  Any possible workarounds?

**Comment by DetlefPeters** [comment] 2017-07-28 15:30
AFAIK the script error bug was fixed AFTER the release of v0.100.1, so you have to wait for the next release (like I do at the moment)...

**Comment by Smelkopski** [comment] 2017-08-11 10:27
https://github.com/Dogfalo/materialize/commit/bf73cbd4fde3e5bb071f407343e689fb2272da32 fixed modal closing in IE11, but there is still problem with vertical scroll. When modal is opened, the scroll disappears and is not restored after modal is closed. Works correctly in Chrome.

**Comment by jsgagne** [comment] 2017-08-23 09:30
I get SCRIPT438 error too... Is there a way to fix that manually ?
