### ISSUE TITLE
dropdown alignment bug

### ISSUE THREAD

**Issue by baraamashaal** [Dogfalo/materialize#2052] opened 2015-09-18 15:39 UTC
take a look at this [codepen](http://codepen.io/baraamashaal/pen/wKGYxx)

**Comment by msolters** [comment] 2015-09-18 17:30
This is a duplicate of #2039.  Consider [this fix](https://jsfiddle.net/oa181eks/) which is already submitted against master in PR #2042

**Comment by acburst** [comment] 2015-09-19 23:12
Closed but will add this codepen link to the other issue

**Closed by acburst** 2015-09-19 23:12 UTC
