### ISSUE TITLE
Date time picker suggestion 

### ISSUE THREAD

**Issue by karsumit94** [Dogfalo/materialize#5892] opened 2018-05-03 07:38 UTC
Instead of having a big popup for time and date desktop users like to have a small popup for date time.
I am using [Air datepicker](http://t1m0n.name/air-datepicker/docs/ ) to solve the issue. If you can come up with something supercool that will be good to have

**Comment by ray007** [comment] 2018-05-03 11:26
Better ask for options to adjust the styling of the current picker I think.
No need to get another lib...

**Comment by karsumit94** [comment] 2018-05-03 11:29
Yes that's what... i am not asking to use that library... but for reference i have shared the link... maybe something like that

**Comment by Dogfalo** [comment] 2018-05-03 19:05
Duplicate of #5526

**Closed by Dogfalo** 2018-05-03 19:05 UTC
