### ISSUE TITLE
Grid offset doesn't work any more

### ISSUE THREAD

**Issue by dmagunov** [Dogfalo/materialize#2312] opened 2015-11-16 23:04 UTC
![screen-shot-2015-11-17-at-1 02 52-am- 3](https://cloud.githubusercontent.com/assets/3579475/11197596/2223265e-8cc7-11e5-882e-5b1a89bff5b3.jpg)

**Comment by lid3rs** [comment] 2015-11-17 00:02
Confirmed

**Comment by acburst** [comment] 2015-11-17 00:26
Duplicate of #2308

**Closed by acburst** 2015-11-17 00:26 UTC
