### ISSUE TITLE
[Question] Does this project adheres to semantic versioning?

### ISSUE THREAD

**Issue by chris-fa** [Dogfalo/materialize#3933] opened 2016-11-22 20:27 UTC
### Description
I just refactored a piece of code to use `bower` instead of the CDN for local development, changing from `0.97.4` to `0.97.8` (patch version if you follow [semantic versioning](http://semver.org/)), and everything crashes now due to the removal of `leanModal()`

### Repro Steps
1. Update  your `materialize.js` from `0.97.4` to `0.97.8`
2. ???
3. Profit

**Comment by yanickrochon** [comment] 2016-11-22 21:05
Unfortunately, no. Thus, this is a duplicate of #3865.

Hopefully, code reviews and proper versioning will follow :smile:

**Comment by acburst** [comment] 2016-11-23 18:48
Duplicate

**Closed by acburst** 2016-11-23 18:48 UTC
