### ISSUE TITLE
HTML5 range - Throwing Error messages for each step

### ISSUE THREAD

**Issue by 00chris00** [Dogfalo/materialize#2137] opened 2015-10-08 11:48 UTC
I wanted to use your HTML5 range but its throwing an error for each step while changing the position. This error occurs even on your example page(http://materializecss.com/forms.html). I talked irontiger in your  Gitter chat room and he tested it on opera and edge:

Chromium: 
Uncaught TypeError: Cannot read property '0' of undefined

Firefox:
TypeError: b.originalEvent.touches is undefined

edge: 
Unable to get property '0' of undefined or null reference
materialize.min.js (8,23786)

Opera:
Uncaught TypeError: Cannot read property '0' of undefined

It seems that this code segment is causing the troubles (line 2713):

       if (e.pageX === undefined || e.pageX === null) { //mobile
          left = e.originalEvent.touches[0].pageX - $(this).offset().left;
        }

It identifies a desktop as mobile and messes things up.

The range still works but slows down the whole page. It would be nice if you could fix this!

Best,
chris

**Comment by dianujnima** [comment] 2015-10-15 22:09
Hi,
I was having the same issue i solved it in following way its fixed no error and its working as well. Hope it will solve the issue for you as well.

    if(e.originalEvent.touches){
	  left = e.originalEvent.touches[0].pageX - $(this).offset().left;
    }else{
	  left = e.pageX - $(this).offset().left;
    }

Regards,
Dianuj Nima

**Comment by acburst** [comment] 2015-10-15 22:39
This is a duplicate of #2072. This has already been fixed in a commit and will be in the next release.

**Closed by acburst** 2015-10-15 22:39 UTC
