### ISSUE TITLE
Progress Tracker?

### ISSUE THREAD

**Issue by feldrim** [Dogfalo/materialize#3114] opened 2016-05-02 14:39 UTC
In [this article](https://uxplanet.org/progress-trackers-in-ux-design-4319cef1c600#.6zde7fm1q), [Nick Babich](https://medium.com/@101) has written about vertical and horizontal progress trackers. Given the examples by material design, it'd be nice to implement as a new component.

![alt text](https://d262ilb51hltx0.cloudfront.net/max/800/1*5AjSCpe2lJXAGOQ-J9KVpw.png "A wrong example of using noth vertical and horizontal progress trackers")

**Comment by Dogfalo** [comment] 2016-05-04 00:50
Duplicate of #2414

**Closed by Dogfalo** 2016-05-04 00:50 UTC
