### ISSUE TITLE
[Suggestion] Get rid of jQuery

### ISSUE THREAD

**Issue by ForsakenHarmony** [Dogfalo/materialize#3922] opened 2016-11-19 22:40 UTC
There's a general rule that frameworks should stay un-opinionated 
http://youmightnotneedjquery.com/

jQuery might be used by many sites but that still doesn't mean it should be used in a Framework

This will also make the amount of code that has to be loaded for non-jQuery sites smaller

I'm not saying that you should immediately make a transition, but it's still a valid concern

Would a PR removing jQuery even get accepted?
EDIT: If I were to make a PR with it is what I meant, I don't want to waste time on it

**Comment by andreujuanc** [comment] 2016-11-20 00:39
Love this.

**Comment by yanickrochon** [comment] 2016-11-20 02:45
My opinion is that jQuery may help reduce the size of this framework. Some components do use jQuery, some don't. And I think the size to be smaller if all components did use jQuery.

In fact, jQuery does allow simple plugin integration with DOM elements, such as `$(selector).modal(options)` and we can listen to events similarly. Getting rid of jQuery would mean that applications using jQuery would require 1) using different APIs when using Materialize and other third party components, or 2) relying on a third-party project to have adaptors for Materialize to jQuery... meaning that, not only Materialize's code size will increase, but more code will be needed to bring back the simpler API that jQuery provides. Ridiculous!

I get that some people argue that jQuery is wrong, or slow or blah, blah, blah. I just don't buy it. Unless you really need split second optimization, speed is irrelevant in this case, and *it does* offer a more linear API, with many features already implemented (element size, bounds, inline CSS and classes, events management, user data attached to DOM, etc.) As for the size, jQuery is 86k minified, compared with Materialize at 142k minified (note that, as I said, Materialize could even be smaller if it properly used jQuery, compared to the opposite if not).

-1 for me.

**Comment by kmmbvnr** [comment] 2016-11-20 03:43
I strongly disagree. Removing jQuery could increase maintenance and new feature adding costs. 

Even Bootstrap the most popular css framework depends on jQuery and it seems pretty fine.

**Comment by fega** [comment] 2016-11-20 15:24
I agree, sadly, materialize is heavily bloated with functionalities like parallax. That should be separated.

**Comment by kmmbvnr** [comment] 2016-11-23 09:39
Btw, this is duplicate of #877

**Comment by Razi91** [comment] 2016-11-26 21:55
Why not modularize it and let developer compile only modules they need in their projects?

**Comment by ForsakenHarmony** [comment] 2016-11-30 22:09
if removing jQuery is not an option then there has to be official support for react / angular / ...

**Comment by smileytechguy** [comment] 2016-11-30 22:39
@ForsakenHarmony angular and react would bloat this library way more than just jquery

**Comment by ForsakenHarmony** [comment] 2016-11-30 23:29
I'm not saying that angular or react should be the supported library, just that they don't mix well with jQuery

**Comment by kriscooke** [comment] 2016-12-04 19:20
**This is really about modularization.**

I think many people's objections may stem from the fact that they do not wish to use or have jQuery available in _their projects_ just because they consume Materialize. In an age of tree-shaking and customized builds, people expect their dependencies not to dictate monolithic global exports into their project.

For example, I don't mind that much if Materialize wants to depend on jQuery. However, in my project's build I expect to be able to produce:
- A reduced project build containing only the Materialize components my project actually uses.
- [A reduced subset of jQuery](https://github.com/jquery/jquery#modules) corresponding to only what is used by those Materialize components (or evenMaterialize as a whole).
- A Materialize build which imports jQuery in such a way that `$` and `jQuery` are not in my project's global namespace. This is important because I don't want my team to start using jQuery simply because they found it hanging around as a global - it's a secondary dependency of Materialize, not an explicit dep of my project - which is not well-expressed by the requirement to globally import jQuery in the document `<head>`.

As a stepping stone that I think could assuage many people's concerns over jQuery here and in  #877 :
- This project could distribute a custom build of jQuery
- Or otherwise as an even nearer-term solution, give people the needed info to produce their own reduced jQuery builds. 

What's needed to do this is an **up-to-date list of jQuery modules that Materialize absolutely depends upon and/or can safely be excluded from the jQuery build**.

**Comment by developeranirudhprabhu** [comment] 2017-01-02 12:29
@Dogfalo whats your opinion?

**Comment by SimHacker** [comment] 2017-01-20 19:25
yanickrochon wrote: "My opinion is that jQuery may help reduce the size of this framework."

Uuuuh, at the expense of adding a much larger framework, and necessarily tying you to it even if you want to use a different framework. 

The fact that you just don't buy it doesn't mean that it isn't actually true that jQuery is slow and bloated and complex. It is. And many people have moved on from it to better frameworks. So it's a terrible idea to require it in addition to whatever other frameworks people choose to use, and much better if Materialize can stand on its own, independent of any other framework.

**Comment by tomscholz** [comment] 2017-04-03 00:20
Duplicate of https://github.com/Dogfalo/materialize/issues/877

**Closed by tomscholz** 2017-04-03 00:20 UTC
