### ISSUE TITLE
modals not un-dismissible

### ISSUE THREAD

**Issue by AbdiViklas** [Dogfalo/materialize#4955] opened 2017-07-10 14:45 UTC
I can't seem to make my modals non-dismissible. Ideally, I'd like to have most modals dismissible and one one particular one not. I've tried both initializing as 
```
$(document).ready(function () {
  $('.modal').modal();
  $("#update-modal").modal({
    dismissible: false
  });
});
```
And simply
```
$(document).ready(function () {
  $('.modal').modal({
    dismissible: false
  });
});
```
... but in both cases all modals still seem to be dismissible.

**Comment by superamadeus** [comment] 2017-07-10 16:47
Hm, I came for the same problem but I actually cannot reproduce it :/
Here's a pen of it working appropriately with the latest CDN version of Materialize.
[pen](https://codepen.io/anon/pen/dRQVRJ)

**Comment by AbdiViklas** [comment] 2017-07-10 20:19
Interesting! The button-triggered modal does indeed not dismiss. But I find that if I add `$("#modal1").modal("open");` to your code, the programatically-triggered one is still dismissible: https://codepen.io/AbdiViklas/pen/qjQoMv

**Comment by acburst** [comment] 2017-07-11 00:04
Duplicate of #4909. Let me know if the fix mentioned in that issue solves this.

**Closed** 2017-07-19 23:16 UTC
Labels: component:Modal
