### ISSUE TITLE
Menu Dropdown getting cutoff by edge of screen

### ISSUE THREAD

**Issue by birchlore** [Dogfalo/materialize#4244] opened 2017-02-15 22:50 UTC
My navbar dropdown is getting [cutoff](https://s11.postimg.org/on932kyrn/Screen_Shot_2017_02_15_at_2_42_15_PM.png) by the edge of the screen. I haven't added any custom styling:

```
<!-- Profile Dropdown Structure -->
<ul id="settingDrop" class="dropdown-content">  
  <div class="info">
   <p>My name</p>
  </div>
  <li class="divider"></li>
  <li>Admin Path</li>
</ul>
```

I can see in the console that an absolute style & position is being applied once I click the dropdown trigger. The menu is given an absolute position of `left: 1100px`. If I manually adjust this to `left: 1000px` then the dropdown fits on the screen.

Anyone seen this issue before?

**Comment by acburst** [comment] 2017-02-16 05:50
Can you recreate this bug in a codepen? It would be helpful for debugging

**Comment by mbelis** [comment] 2017-03-20 23:12
That happens to me too. When I click the ellipsis icon (see example), it appears the navbar with a scrollbar hiding some letters. https://codepen.io/anon/pen/WpMgJg

**Comment by fega** [comment] 2017-05-02 13:51
Duplicate of #4244,

Thanks

**Closed by fega** 2017-05-02 13:51 UTC
Labels: bug
