### ISSUE TITLE
Distorted UI: Navbar search

### ISSUE THREAD

**Issue by samdeesh** [Dogfalo/materialize#1889] opened 2015-08-11 06:30 UTC
The close icon is displaced, outside from the navbar 

![image](https://cloud.githubusercontent.com/assets/8951753/9191566/65385fca-4020-11e5-9c32-a3876c1e1b8b.png)

**Comment by carlosperate** [comment] 2015-08-11 09:15
This is a duplicate of https://github.com/Dogfalo/materialize/issues/1669, which has been fixed on master after the 0.97.0 release.

**Closed by carlosperate** 2015-08-11 09:15 UTC

**Comment by samdeesh** [comment] 2015-08-12 17:27
This is a screenshot from http://materializecss.com/navbar.html chack the search bar example

**Comment by carlosperate** [comment] 2015-08-12 17:33
The docs should be fine in the master branch, the website will be updated when a new version is released, as otherwise the documentation and the API would be out of sync.
