### ISSUE TITLE
Problem with Searh Bar in NavBar

### ISSUE THREAD

**Issue by imraphox** [Dogfalo/materialize#3198] opened 2016-05-23 18:33 UTC
![screen shot 2016-05-23 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/1952434/15480361/8cea174a-20fb-11e6-8f5e-9e1ca73838cb.png)

on focus not work properly.

**Comment by kaytrance** [comment] 2016-05-25 10:57
See #3117

**Comment by acburst** [comment] 2016-05-25 20:14
Duplicate of #3161

**Closed by acburst** 2016-05-25 20:14 UTC
