### ISSUE TITLE
Issue with star_rate icon in icons.html

### ISSUE THREAD

**Issue by Clechay** [Dogfalo/materialize#1964] opened 2015-08-26 21:15 UTC
star_rate icon on this page is offset to the left http://materializecss.com/icons.html
Tested with Google Chrome 45.0.2454.46 beta-m (64-bit) and Firefox Developer Edition 42.0a2 (2015-08-26) in single core mode, both running under Windows 10
![screenshot 15](https://cloud.githubusercontent.com/assets/10584949/9506286/7de5dfba-4c47-11e5-8959-c2113c082872.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/10584949/9506287/7de64824-4c47-11e5-832e-dce9b3aa1558.png)

**Comment by carlosperate** [comment] 2015-08-26 21:25
Duplicate of https://github.com/Dogfalo/materialize/issues/1860.

**Closed by carlosperate** 2015-08-26 21:25 UTC
