### ISSUE TITLE
Navbar dropdown doesn't work if you click the icon

### ISSUE THREAD

**Issue by Braed** [Dogfalo/materialize#4500] opened 2017-04-06 02:03 UTC
### Description
If you click the icon within the navbar dropdown link, the dropdown doesn't open.

### Screenshots / Codepen
I don't think a Codepen is needed here, as this applies to the documentation dropdowns too.
http://materializecss.com/navbar.html#navbar-dropdown
http://prntscr.com/eszqjd

**Comment by fega** [comment] 2017-04-06 02:31
Yeah, confirmed.

I tried in my own web page and it works as expected, so I guess is something with the doc's markup

**Comment by apancutt** [comment] 2017-04-06 09:25
I'm having the same problem on 0.98.1 when using just an icon as the dropdown activator.

Adding `data-stoppropagation="true"` is a workaround.

https://codepen.io/anon/pen/evadwb

**Comment by tomscholz** [comment] 2017-04-06 09:44
Duplicate of https://github.com/Dogfalo/materialize/issues/4409, https://github.com/Dogfalo/materialize/issues/4418  and https://github.com/Dogfalo/materialize/issues/4442
And fixed in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4

**Closed by tomscholz** 2017-04-06 09:44 UTC
Labels: bug, docs
