### ISSUE TITLE
Unordered lists show up without any styling

### ISSUE THREAD

**Issue by AdityaAnand1** [Dogfalo/materialize#2582] opened 2016-01-02 18:37 UTC
The following means that by default all unordered lists appear without styling:

``` css

ul {
  list-style-type: none; }

```

Perhaps this property should have a narrower focus?

**Comment by lebart** [comment] 2016-01-13 13:45
+1

**Comment by keeferrourke** [comment] 2016-05-04 02:54
+1 unordered lists with bullet markers are an important part of a lot of information displays; obviously this exists so navbars, etc. don't have bullets, but a narrower focus would be a really great improvement.

**Comment by huberic** [comment] 2016-05-16 10:53
Definitely an important one; I'm more than a little surprised this is a problem at all.

**Comment by acburst** [comment] 2016-05-17 03:12
You can add the browser-default class or enable it in your own css.

http://materializecss.com/helpers.html#browser-default

**Comment by sfcgeorge** [comment] 2016-05-23 13:03
Probably shouldn't be closed, this doesn't actually work. The `browser-default` class only resets the list style type on the `ul` but it was disabled at higher specificity on the `ul li`. It is nuts that a framework would disable styling of lists, it really should be a part of the typography page.

```css
/* Materialize overly specific disable */
ul li {
  list-style-type: none;
}

/* not specific enough to put default back */
ul.browser-default {
  list-style-type: initial;
}
```

If you're set on keeping the nuts default, the `browser-default` class could be fixed thusly:

```css
ul.browser-default li {
  list-style-type: initial;
}
```

**Comment by phu** [comment] 2016-05-24 00:09
Thanks for that, @sfcgeorge. It'll definitely be helpful.

**Comment by silverdr** [comment] 2016-09-06 16:50
So - if I may ask - what is the preferred way of getting properly nesting, bulleted lists?

**Comment by phu** [comment] 2016-09-06 22:36
@silverdr: It's my impression there isn't one; it seems not to be a concern here. I ended up with this in a custom CSS file; it's pretty arbitrary, but it gets the job done, and should at least show one way to improve the non-workaround provided.

```css
ul.browser-default {
  padding-left: 30px;
  margin-top: 10px;
  margin-bottom: 15px;
}
ul.browser-default li {
  list-style-type: initial;
}
```

It enables bullets and nesting, but only when `browser-default` is applied to _all_ `ul`'s, which may be obvious but I thought worth mentioning. Note that since this explicitly specifies the `list-style-type`, it doesn't give the default different-styles-at-nested-layers discs, which might be possible but wasn't a priority for me.

**Comment by acburst** [comment] 2016-09-07 00:53
Fixed in 7906874

**Comment by silverdr** [comment] 2016-09-07 11:00
@acburst yes - that seems like a better way to handle the issue.

**Comment by kilianso** [comment] 2016-12-06 09:02
@acburst using the css :not selector isn't a solution for production because of it's browser support. http://caniuse.com/#search=%3Anot

**Comment by invious** [comment] 2016-12-10 00:30
This isn't fixed in `0.97.8`. I had to add this CSS to ovverride it:

```
ul:not(.browser-default) {
	padding-left: 30px;
	margin-top: 10px;
	margin-bottom: 15px;
}

ul:not(.browser-default) li {
    list-style-type: disc;
}
```

and nested lists still don't work! How do I get good old nested lists to work?

**Comment by rgreer4** [comment] 2016-12-19 22:47
It's working fine for me in v0.97.8.   Are you doing this?

`<ul class="browser-default">
    <li>test</li>
    <li>test</li>
    <ul class="browser-default">
        <li>test</li>
    </ul>
</ul>`

That is without any other css -- should look like a normal list.

**Comment by retorquere** [comment] 2017-02-01 14:29
I've tried to get this to work [here](http://jsfiddle.net/bkbuee24/) but I'm still getting an unstyled list.

**Comment by rgreer4** [comment] 2017-02-01 15:36
I changed the CSS version to 0.97.8 in the fiddle, and it seems work (well,
better...its still not ideal).

https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css

-Rick

**Comment by retorquere** [comment] 2017-02-01 18:31
Yep, that did it. Good enough for me, I don't see anything I can't live with and plenty I wouldn't want to do without 👍

**Comment by JayHoltslander** [comment] 2017-06-16 22:18
Currently creating a Wordpress theme utilizing Materialize and discovered this .browser-default issue while editing content and trying to put in a `<ul>`. Quite inconvenient if someone who just wants to write content suddenly has to edit the code to add classes to the list.

I'm going to have to disable this.

**Comment by JayHoltslander** [comment] 2017-06-16 22:32
My Wordpress fix for this was:

**SCSS**
````
section[id*="post-"] .card {
	ul {list-style-type: initial; padding-left: 30px; margin-top: 10px; margin-bottom: 15px;}
	li {list-style-type: initial;}
}
````
The selector allows for the `<ul>` to remain unstyled everywhere else but when a list appears in my theme's content area within `<section id="post-1234"><div class="card"> ... </div></section>` it get's normal list styling.

**Comment by keeferrourke** [comment] 2017-06-16 22:37
Is there a good reason that `ul` styling is globally stripped at all? The `browser-default` classes seems like a bad solution when the bullets could *only* be stripped from elements that should not display them (such as navbars, tabs, etc.)

**Comment by jtebert** [comment] 2017-09-07 17:45
^ I'm with this guy. The default behavior of lists being no bullets and no indentation doesn't make any sense from a content perspective. Adding the option to specify the `browser-default` class is also an inelegant solution. For example, lists generated by Markdown (my current use case) must be somehow hackily edited in order to display list a normal list.

**Comment by tomscholz** [comment] 2017-09-07 17:58
Whoops, closing again. See this comment for information regrading this topic https://github.com/Dogfalo/materialize/issues/5004#issuecomment-326652456

**Closed by tomscholz** 2017-09-07 17:58 UTC

**Comment by phu** [comment] 2017-09-07 21:15
Maybe I'm missing something, but I don't see anything relevant in that thread.

**Comment by tomscholz** [comment] 2017-09-07 21:35
See this comment https://github.com/Dogfalo/materialize/issues/5004#issuecomment-326627742
We will move away from styling native elements and `.browser-default`. I understand, that it is really frustrating, but it is currently very unlikely that this will ship with v1. If you want, you can create a PR, which fixes this. In this case I would make the PR against the `v1-dev` branch...

**Comment by mrdnote** [comment] 2017-11-08 14:52
Tom, great product, but indeed please remove browser-default asap. We have a site where users can add their own content thru an in-page html editor, we cant expect end user to add "browser-default" classes to their lists right?

Any idea when this will be included in a release?

**Comment by kurotsukikaitou** [comment] 2018-03-09 12:24
Now I realize that this approach is somehow .... weird. I mean, why do we have to define .browser-default to revert back? I just add CKEditor and found that when user editing anything within the editor, unordered list will not have bullets (and not indented too).

**Comment by JayHoltslander** [comment] 2018-03-20 04:38
Almost a year later and here I am again looking for the fix that I did last time. (Sigh)
So frustrating.

**Comment by Dogfalo** [comment] 2018-03-20 04:42
@JayHoltslander We'll be fixing this after 1.0 release. We understand this can be a frustrating problem.

**Comment by ray007** [comment] 2018-03-20 07:43
Isn't it harder to fix after 1.0 since it would be a breaking change?
Just restyling all `ul` elements is just bad style, that's what classes are for.

**Comment by JayHoltslander** [comment] 2018-03-20 18:52
For others... my fix this time.

#### HTML
````html
<div class="card-content browser-default-uls">
  ...
</div>
````
#### SCSS
````scss
.browser-default-uls {
  ul {
    padding-left: 30px;
    margin-top: 10px;
    margin-bottom: 15px;
    li {
      list-style-type: disc!important;
      ul {
        li {list-style-type: circle!important;}
      }
    }
  }
}
````

**Comment by jvillemare** [comment] 2018-05-31 15:42
For those looking for a simple fix, I just use:

```
<ul class="browser-default">
   <li>...</li>
   ...
</ul>

**Comment by ray007** [comment] 2018-06-04 06:21
I still think overriding all lists and requiring the user to add `browser-default` is evil.

**Comment by kurotsukikaitou** [comment] 2018-06-04 12:47
I can't override the third party library I used. So adding `browser-default` is not an option.

**Comment by JayHoltslander** [comment] 2019-04-01 22:45
> @JayHoltslander We'll be fixing this after 1.0 release. We understand this can be a frustrating problem.

Was looking for this one in the [Feature Request Board](https://github.com/Dogfalo/materialize/projects/3) and didn't see it.

**Comment by jvillemare** [comment] 2019-04-02 13:37
> > @JayHoltslander We'll be fixing this after 1.0 release. We understand this can be a frustrating problem.
> 
> Was looking for this one in the [Feature Request Board](https://github.com/Dogfalo/materialize/projects/3) and didn't see it.

Only collaborators of this repo can add it there. @acburst, may we please get one last quick look at this issue? Still seems to be a problem for some devs.

**Comment by b3u** [comment] 2019-07-05 19:24
@Dogfalo sorry to but in, but it's past 1.0 release. The cdn version is still broken for me.

**Comment by ricoms** [comment] 2020-06-25 03:12
I rather have the default behavior with the default use. I believe Materialize choice on changing the expected behavior of a common and important text structure is basically wrong. 

Explaining my case, I've built a GitHub page in which many people will need to input content. Most of them using simple Markdown syntax. As they understand basics Markdown and many of them use unordered list, which is an important text structure, I would not require or teach them all (or teach them all) on how to use HTML, define style or class of any type to its unordered list.

What I did is to change `materialize.css` and `materialize.min.css` from `:not(.browser-default)` to `.materialize`. The result is below:

```
ul.materialize {
  padding-left: 0;
  list-style-type: none;
}

ul.materialize > li {
  list-style-type: none;
}
```

This way, the navbar, which I implement, will use `materialize` class. And this leaves the default behavior when my content creators want to use markdown unordered lists.

**Comment by nateleavitt** [comment] 2021-03-25 23:34
I'm currently having an issue with this. Our customers also provide content through a wysiwyg editor and their lists are not styled.  I agree with the general sentiment to not override default `ul` and `li` elements.

**Comment by DivyanshSareen** [comment] 2021-09-30 10:46
<ol style="list-style: disc;"></ol> works for me

**Comment by DivyanshSareen** [comment] 2021-09-30 10:46
`<ol style="list-style: disc;">` works for me

**Comment by DanFeather** [comment] 2022-11-16 21:22
I have found so many good reasons to use Materialize, but I'm really stumped as to why the release version (1.0.0) still breaks the unordered list's natural style, requiring a workaround to restore the expected formatting. I know there are reasons to use a set of items as something that doesn't look like a list, but a list should, by default, look like a list. Those cases where it's desirable to take on a different look are special cases, and that's what classes (or targeted CSS rules) are for. And as I read back through years of comments, complaints, and workarounds about this issue, I find the promise that "this will be fixed in the 1.0 release." But it's not. What gives?

**Comment by argenos** [comment] 2024-02-16 10:36
I'm not sure why this is closed, since the issue is still present. I cannot add `browser-default` to lists since I am using jekyll. Is there an open issue for v1.0.0 tracking this?
