### ISSUE TITLE
Select multiple width outgroups don't update properly

### ISSUE THREAD

**Issue by moduleitor** [Dogfalo/materialize#4652] opened 2017-05-05 14:04 UTC
I'm using your awesome Materializecss in one project... but when I put a Select multiple, width outgroups, and change the options state dynamically, the select only change the state of the first options check.

Here is the code:

-------------------------------------------------------------------------------------
**HTML+BLADE(Laravel 5.3) ($optgroups is array)**
`{{ Form::select('subhashtags_select', $optgroups, null, ['multiple' => true] ) }} <label>SubHashtags</label>`

-------------------------------------------------------------------------------------
**The result HTML:**
`<select multiple="1" name="subhashtags_select"><optgroup label="Group 1"><option value="50">Item 1</option><option value="51">Item 2</option><option value="52">Item 3</option><option value="53">Item 4</option><option value="54">Item 5</option><option value="55">Item 6</option><option value="56">Item 7</option><option value="57">Item 8</option><option value="58">Item 9</option></optgroup><optgroup label="Group 2"><option value="30">Item 10</option><option value="31">Item 11</option><option value="32">Item 12</option></optgroup></select> <label class="subhashtags_select">SubHashtags</label>`

-------------------------------------------------------------------------------------
**JAVASCRIPT:**
$.each([50,52,30,31], function(key, value){
$('select[name=subhashtags_select]').find('option[value='+value+']').prop('selected', true);

});

$('select[name=subhashtags_select]').material_select("update");

-------------------------------------------------------------------------------------
On refresh the select, only the two first items in the array change to selected... Do you know if it is any bug? or I'm missing something?

Thanks!!!

**Comment by aschoenebeck** [comment] 2017-05-05 14:23
I had the same problem and fixed it with changing the materialize.js. See here: https://github.com/Dogfalo/materialize/issues/2913#issuecomment-299214730

I will create a pull request soon.

**Comment by tomscholz** [comment] 2017-05-05 14:39
Duplicate of https://github.com/Dogfalo/materialize/issues/2913

**Closed by tomscholz** 2017-05-05 14:39 UTC

**Comment by aschoenebeck** [comment] 2017-05-06 22:55
Fixed with PR: https://github.com/Dogfalo/materialize/pull/4656

**Comment by moduleitor** [comment] 2017-05-07 11:10
Thanks!!! It's works!!! X)

Only when you select the options, on the select show only two options in
the text. Wherever,  all options are checked in the checboxes X)

I try to fixed with onchange event.

Thanks a lot!!!
