### ISSUE TITLE
Issue with Meteor 1.2 & Materialize v0.97.1

### ISSUE THREAD

**Issue by docgecko** [Dogfalo/materialize#2077] opened 2015-09-23 07:20 UTC
I just upgraded to the latest version of Meteor and this Materialize package causes errors.  If I remove the package, my app works fine again.  Here are the errors that show up in the console:

Uncaught TypeError: Cannot set property 'guid' of undefined(anonymous function) @ materialize_materialize.js:10(anonymous function) @ materialize_materialize.js:15(anonymous function) @ materialize_materialize.js?852eb8ab99e3508edd310071537cb33698a58a2b:47(anonymous function) @ materialize_materialize.js?852eb8ab99e3508edd310071537cb33698a58a2b:56
global-imports.js?42ba686d5ec5de5008618b324d34de30700ad7e2:44

Uncaught TypeError: Cannot read property 'Materialize' of undefined(anonymous function) @ global-imports.js?42ba686d5ec5de5008618b324d34de30700ad7e2:44

Many thanks for any help.  Cheers,

D.

**Comment by Crenshinibon** [comment] 2015-09-23 07:46
Same here!

**Comment by mbanting** [comment] 2015-09-23 09:10
Same here. Downgrading to 0.97.0 works.
Thanks!

**Comment by docgecko** [comment] 2015-09-23 09:38
Yeap, 0.97.0 works fine, thanks!

**Comment by SoilChang** [comment] 2015-09-23 11:29
same here. the whole app broke.

**Comment by carlosperate** [comment] 2015-09-23 16:15
Duplicate of https://github.com/Dogfalo/materialize/issues/2037.

**Closed by carlosperate** 2015-09-23 16:15 UTC
