### ISSUE TITLE
Button waves do not disappear after click

### ISSUE THREAD

**Issue by parthibanloganathan** [Dogfalo/materialize#2667] opened 2016-01-16 12:09 UTC
Here is an example of a button that was pressed. As you can see, the lightening due to the wave does not disappear after click. The button is defined as `<button id="uploadphoto" class="waves-effect waves-light btn">Upload Photo</button>`

The same issues does not occur when using the [materialize:materialize](https://atmospherejs.com/materialize/materialize) package. This suggests that it is an issue with the Sass compilation. I compiled [v0.97.5](http://materializecss.com/getting-started.html) Sass with [fourseven:scss](https://atmospherejs.com/fourseven/scss) for Meteor. It may be an issue with Libsass incompatibility with older indented sass syntax as mentioned in the README of [fourseven/meteor-scss](https://github.com/fourseven/meteor-scss).

![screen shot 2016-01-16 at 7 04 37 pm](https://cloud.githubusercontent.com/assets/1872894/12372328/a5fd7b04-bc84-11e5-9662-9e37d1f9c74e.png)

**Comment by wunderg** [comment] 2016-01-18 20:12
I have the same problem

**Comment by chifreaigle** [comment] 2016-01-18 21:23
Yeah, this is happened to me too, to reproduce this issue, you have to create a btn with waves on and click it for a long time, this btn should have some thing like "#" in the href, i mean this bnt dont teleport you to another page this can be seen in the web page as example chifrebird.blogspot.com(nav bar ; doesn't apply on the Home btn cause it refresh the page) if you hver over the btn again the effect will be gone.

**Comment by ZykezIX** [comment] 2016-01-19 03:59
A brief preface here: I'm not using SASS, so this may be unhelpful for @parthibanloganathan , but I figured I'd offer my two cents here in the hopes that it might help.

I noticed something very similar when testing our new design against various devices and browsers. Particularly with Microsoft's new Edge Browser & Internet explorer. As @chifreaigle mentioned, the occurrence was easiest to reproduce by clicking for a long time (or very rapidly!), although occasionally it would occur from a single click. 

I replaced all occurrences of <a href="#".... with <a href="javascript:void(0)"... and this appears to have corrected the issue in my particular case. Have you given that a try? Might be an easy fix ;-) 

At any rate, I hope this helps someone! Kudos to the Materialize team for their work on this framework! Thanks!

**Comment by parthibanloganathan** [comment] 2016-02-10 01:21
Found a solution by building from source. See https://github.com/Dogfalo/materialize/issues/2651. The packaged distribution seems to be buggy.

**Comment by heneryville** [comment] 2016-02-18 05:11
This hasn't be the case for me, but has just started appearing.

**Comment by ExoMemphiz** [comment] 2017-05-29 22:49
If people are having trouble with this, follow heneryville's advice.

I was importing the files in multiple pages in my React app, but because App renders regardless for me, and then renders other components (that were also importing materializecss) the buttons were having the weird effect of staying coloured, but after going through all my components and pages and removing the imports, it works!

Thank you, @heneryville :)

**Comment by fega** [comment] 2017-05-30 14:38
so it looks that this Issue is related with a duplicate event listener, Materialize shouldn't duplicate it.

**Comment by Dogfalo** [comment] 2017-06-24 22:15
Fixed by #4474

**Closed by Dogfalo** 2017-06-24 22:15 UTC
Labels: bug, component:Waves

**Comment by moh3n9595** [comment] 2017-09-28 07:39
I have same problem and I not duplicated Materialize! (using Ionic 2)
index.ts : 

```
  <link rel="stylesheet" href="plugin/materialize.min.css">
  <script src="plugin/jquery-3.2.1.min.js"></script>
  <script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
```
app.module.ts : 
```
import 'materialize-css';
import { MaterializeModule } from 'angular2-materialize';
 imports: [

    MaterializeModule,

  ]
```

**Comment by MaxBittker** [comment] 2017-10-02 20:04
^Raven.install instruments click events by default, as a workaround you can turn click breadcrumbs off with this config option: 
```
autoBreadcrumbs: {
    'dom': false
}
```
otherwise, you may want to reverse the oder you call raven.install() 
and include the materializecss click handlers

**Comment by SOSANA** [comment] 2018-03-10 17:29
@ExoMemphiz by any chance do you have a repo I could check out on how you wired up the jquery with a react app? I am currently in the process of doing this and was curious the best approach to apply this as I thought this was a conflict with react apps as components are being rendered in the react virtual-dom vs actual dom so a little confused on how to approach applying this to a react app...

Also ripple/wave effects seem not to work besides the default and I think this related to me not requiring jquery and initilizing it but not 100% this is my problem just yet. I also posted a question regarding this on gitter.

anyone else can chime in and add their two cents that would be great @Dogfalo

**Comment by OzzyTheGiant** [comment] 2018-11-29 04:00
> You'll get this behavior if you've included the materialize javascript more than once on the page.

If you're on angular and you can't use ngx-materialize (because it hasn't been updated to be compatible with materialize-css 1.0), and you need to M.Init() some components, remove materialize.min.js from your scripts in the angular.json file and import * as M and then add M as a provided value in a 'shared' module that you can import across your app. You then @Inject() it into whatever component you need so that you can M.AutoInit() during your lifecycle hooks. Doing this will prevent materialize from being imported several times. Here's a sample shared.module.ts file:
```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as M from 'materialize-css/dist/js/materialize';

@NgModule({
	imports: [
		CommonModule
	],
	declarations: [],
	providers:[
		{provide:'M', useValue:M}
	],
  	exports: [
		  CommonModule
	]
})
export class SharedModule { }
```
your component would look something like this (I'm using a materialize modal dialog box component):

```typescript
import { Component, OnInit, OnDestroy, ViewChild, AfterViewInit, Inject } from '@angular/core';
import * as M from 'materialize-css/dist/js/materialize';

@Component({
    selector: 'dialog-box',
    templateUrl: './dialog-box.component.html',
    styleUrls: ['./dialog-box.component.scss']
})
export class DialogBoxComponent implements OnInit, AfterViewInit, OnDestroy {
    @ViewChild('dialogBox') elementRef: any;
    materializeBinding: any;

    constructor(@Inject('M') private M: any) {}

    ngOnInit() {}

    open() {
        this.materializeBinding.open();
    }

    ngAfterViewInit() {
	this.materializeBinding = M.Modal.init(this.elementRef.nativeElement);
    }

    // ...other code omitted for brevity
}
```

**Comment by ermarkar** [comment] 2019-04-18 05:40
> > You'll get this behavior if you've included the materialize javascript more than once on the page.
> 
> If you're on angular and you can't use ngx-materialize (because it hasn't been updated to be compatible with materialize-css 1.0), and you need to M.Init() some components, remove materialize.min.js from your scripts in the angular.json file and import * as M and then add M as a provided value in a 'shared' module that you can import across your app. You then @Inject() it into whatever component you need so that you can M.AutoInit() during your lifecycle hooks. Doing this will prevent materialize from being imported several times. Here's a sample shared.module.ts file:
> 
> ```ts
> import { NgModule } from '@angular/core';
> import { CommonModule } from '@angular/common';
> import * as M from 'materialize-css/dist/js/materialize';
> 
> @NgModule({
> 	imports: [
> 		CommonModule
> 	],
> 	declarations: [],
> 	providers:[
> 		{provide:'M', useValue:M}
> 	],
>   	exports: [
> 		  CommonModule
> 	]
> })
> export class SharedModule { }
> ```
> 
> your component would look something like this (I'm using a materialize modal dialog box component):
> 
> ```ts
> import { Component, OnInit, OnDestroy, ViewChild, AfterViewInit, Inject } from '@angular/core';
> import * as M from 'materialize-css/dist/js/materialize';
> 
> @Component({
>     selector: 'dialog-box',
>     templateUrl: './dialog-box.component.html',
>     styleUrls: ['./dialog-box.component.scss']
> })
> export class DialogBoxComponent implements OnInit, AfterViewInit, OnDestroy {
>     @ViewChild('dialogBox') elementRef: any;
>     materializeBinding: any;
> 
>     constructor(@Inject('M') private M: any) {}
> 
>     ngOnInit() {}
> 
>     open() {
>         this.materializeBinding.open();
>     }
> 
>     ngAfterViewInit() {
> 	this.materializeBinding = M.Modal.init(this.elementRef.nativeElement);
>     }
> 
>     // ...other code omitted for brevity
> }
> ```

Hi,

I am including materializecss like

`import * as M from 'materialize-css/dist/js/materialize';`

in every component and using it like 

`M.Modal.init(this.elementRef.nativeElement);`

but not doing 
`constructor(@Inject('M') private M: any) {}`

this makes difference? Can you please explain little more ?

**Comment by VardhanMahajan** [comment] 2021-05-16 12:44
> You'll get this behavior if you've included the materialize javascript more than once on the page.

this worked! Thanks dude!
