### ISSUE TITLE
Consider removing the dependency on jquery

### ISSUE THREAD

**Issue by MackYoel** [Dogfalo/materialize#2301] opened 2015-11-15 16:33 UTC
Materialize is great, but could Materialize someday, not be linked to jQuery? this dependence leaves no options for users who do not intend to use jQuery.

**Comment by acburst** [comment] 2015-11-15 19:48
Its something we plan on doing in the future but because most of our components are written in jQuery it would be a long and arduous process at the moment.

**Comment by acburst** [comment] 2015-11-15 19:49
Also duplicate of #877

**Closed by acburst** 2015-11-15 19:49 UTC
