### ISSUE TITLE
Add time picker

### ISSUE THREAD

**Issue by mattkrick** [Dogfalo/materialize#959] opened 2015-03-19 17:01 UTC
I made a material design timepicker in jquery. I wrote it in stylus so I can't do a direct PR, but it'd be easy to just incorporate the css. If you'd like to use it, feel free or reach out if you need help.

Cheers
https://github.com/mattkrick/lolliclock

**Comment by Dogfalo** [comment] 2015-03-20 04:38
Duplicate of #473

**Closed by Dogfalo** 2015-03-20 04:38 UTC
