### ISSUE TITLE
datepicker height inside modal bugs when modal is smaller than datepicker height

### ISSUE THREAD

**Issue by buutqn** [Dogfalo/materialize#5160] opened 2017-08-29 20:45 UTC
![modal-1](https://user-images.githubusercontent.com/15644387/29842922-a7685bde-8ce0-11e7-91a8-0335ebc4faa3.jpg)
![modal-2](https://user-images.githubusercontent.com/15644387/29842921-a76500ce-8ce0-11e7-8f75-5300d2102914.jpg)
![modal-3](https://user-images.githubusercontent.com/15644387/29842923-a8043072-8ce0-11e7-8cde-8c504e4a1be1.jpg)

    <div id="modal-basic-info" class="modal">
        <div class="modal-content">
            <h4>Alterar Aluno</h4>
            <form class="row" method="post" >
                <div class="input-field col s12">
                    <i class="material-icons prefix">person</i>
                    <input id="alunonome" required name="alunonome" type="text" class="validate">
                    <label for="alunonome">Nome completo</label>
                </div>
                <div class="input-field col s12 l6">
                    <i class="material-icons prefix">person</i>
                    <input id="alunonomepeq" required name="alunonomepeq" type="text" class="validate">
                    <label for="alunonomepeq">Nome Identificação</label>
                </div>
                <div class="input-field col s12 l6">
                    <i class="material-icons prefix">event</i>
                    <input id="alunodatanascimento" required name="alunodatanascimento" type="text" class="datepicker">
                    <label for="alunodatanascimento">Data de nascimento</label>
                </div>
                <div class="center">
                    <button class="btn-flat waves-effect waves-light" name="alterar-dados" type="submit">Alterar dados
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
        </div>
    </div>

**Comment by tomscholz** [comment] 2017-08-29 20:48
Duplicate of #1032

**Closed by tomscholz** 2017-08-29 20:48 UTC
Labels: component:DatePicker
