### ISSUE TITLE
screensize for responsive tables

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#956] opened 2015-03-19 08:38 UTC
Great framework and the responsive tables are great, but it would be great to have a small-responsive and a med-responsive class.

Use case:
if a table is small enough for medium screens but too large for small screens.

**Comment by thecotne** [comment] 2015-03-19 18:50
to keep it simple it will be nice to have bootstrap like grid
xs sm md lg 
http://getbootstrap.com/css/#grid-options

**Comment by Dogfalo** [comment] 2015-03-22 20:50
Duplicate of #644

**Closed by Dogfalo** 2015-03-22 20:50 UTC

**Comment by Amonstyle** [comment] 2015-05-12 09:10
@thecotne i fixed like bootstrap with large size > 1200px
Demo http://jsfiddle.net/mxzuuknz/1/
