### ISSUE TITLE
input[type=text].validate+label bug when using a form prefix icon

### ISSUE THREAD

**Issue by Queatz** [Dogfalo/materialize#3021] opened 2016-04-09 23:01 UTC
The following form in a modal causes a horizontal scrollbar to appear:
```html
<div class="input-field col s12">
    <i class="material-icons prefix">edit</i>
    <input id="hubAbout" type="text" class="validate" [(ngModel)]="about">
    <label for="hubAbout">Enter description</label>
</div>
```

It's to do with `class="validate"`.
When disabling `width: 100%;` of `input[type=text].validate+label`  the scrollbar disappears.

With `width: 100%;`
![screenshot from 2016-04-09 15-54-56](https://cloud.githubusercontent.com/assets/540620/14406945/97be28da-fe6b-11e5-8eb0-b27343d8a4a4.png)

Without `width: 100%;`
![screenshot from 2016-04-09 15-54-39](https://cloud.githubusercontent.com/assets/540620/14406944/97a80820-fe6b-11e5-902d-86419996fbc1.png)

It's visible in the chrome inspector:
![screenshot from 2016-04-09 16-00-11](https://cloud.githubusercontent.com/assets/540620/14406966/39be7572-fe6c-11e5-97ac-90bfb85bc262.png)

**Comment by acburst** [comment] 2016-04-10 05:50
Duplicate of #3018. It is fixed on master

**Closed** 2016-04-10 05:59 UTC
