### ISSUE TITLE
Date picker initialization issue

### ISSUE THREAD

**Issue by shmshd12** [Dogfalo/materialize#5028] opened 2017-07-25 20:10 UTC
Initializing Date picker with true selectMonths isn't working as expected. Select months or years drop down is not showing up in the rendering.

Is there any issues with it? or am I missing anything? See the [Codepen](https://codepen.io/shmshd12/pen/XaJqXx).

![pickadate](https://user-images.githubusercontent.com/11484121/28591423-bad0011e-7196-11e7-9ef3-40d2d3dcdd53.png)

**Comment by tomscholz** [comment] 2017-07-25 20:29
Duplicate of https://github.com/Dogfalo/materialize/issues/5020

**Closed by tomscholz** 2017-07-25 20:29 UTC

**Comment by gusbemacbe** [comment] 2017-07-28 02:23
@shmshd12 , it is the class `input-field` which caused to hide the month and year. You have to remove `input field` or update the latest commit, using NPM and Grunt to compile the latest `materialize.js`.

**Comment by solkaz** [comment] 2017-08-09 21:20
@gusbemacbe removing the `input-field` class doesn't work for me

**Comment by gusbemacbe** [comment] 2017-08-09 21:59
@solkaz , it depends on the class' position. If your class without `input-field` has the same position outside a group, then it caused conflict.
