### ISSUE TITLE
Search bar issue

### ISSUE THREAD

**Issue by ShashankaNataraj** [Dogfalo/materialize#3152] opened 2016-05-12 01:33 UTC
On clicking the search bar at http://materializecss.com/navbar.html this is what is shown:

<img width="871" alt="screen shot 2016-05-12 at 7 02 05 am" src="https://cloud.githubusercontent.com/assets/650317/15201538/94887bda-180f-11e6-87a8-d7b7303eade5.png">

**Comment by acburst** [comment] 2016-05-14 21:54
Duplicate of 3161

**Closed by acburst** 2016-05-14 21:54 UTC
