### ISSUE TITLE
Material Box Relies on Z-Indexes Remaining Unused

### ISSUE THREAD

**Issue by Ecksters** [Dogfalo/materialize#2087] opened 2015-09-26 04:56 UTC
Because the z-index of a child caps at the parent element's index, if you attempt to use Material Box on an element inside an element with a z-index, the image will be covered by the overlay.

I made a manual fix for it in my case, but it's not quite nice enough for me to do a Pull Request:

```
// Animate image + set z-index    
 else {
      origin.css('left', 0)
      .css('top', 0)
      .velocity(
        {
          height: newHeight,
          width: newWidth,
          left: $(document).scrollLeft() + windowWidth/2 - newWidth/2,
          top: $(document).scrollTop() + windowHeight/2 - newHeight/2
        },
        {
          duration: inDuration,
          queue: false,
          easing: 'easeOutQuad',
          complete: function(){
                                doneAnimating = true;
                                origin.clone().attr("id", "materialbox-tempImage").appendTo("html");
                              }
        }
        ); // End Velocity
    }
```

The basic idea is that first off, you want to clone the image and append it to the HTML element, which hopefully hasn't had a z-index set on it, that way it becomes independent of its parents. The other change was the left and top positions need to be based on the window, rather than on the parent element now.

I think an ideal solution would be to clone the element into the overlay, but initially set its position to the exact location of the image(fixed, of course), and set the image's display to none temporarily, restoring it once the animation finishes.

**Comment by acburst** [comment] 2015-09-27 20:03
can you post some code where this bug occurs? it would help us to write into our test cases

**Comment by Ecksters** [comment] 2015-09-28 00:04
Just responding for now, but the test would simply consist of a div with z-index of 5, with the materialbox'd image inside of it. Because the div has a z-index of 5, the image, even when its z-index is set to 5000(or whatever it is), will never be larger than 5(the parent's z-index), so the overlay, which has an index of 999, will simply cover it up.

**Comment by ivanlaharnar** [comment] 2016-05-31 18:41
Any news on that? I have the same problem.

Ivan

**Comment by Ecksters** [comment] 2016-05-31 18:48
I couldn't get a test case for this, and as you saw above, I hacked a fix together for it. Perhaps if you can get a nice isolated test case they can resolve it.

**Comment by ivanlaharnar** [comment] 2016-05-31 22:18
Here is test example http://mink.si/materialize_test/ .
I couldn't get height z-index for image when I click on it that it will show in full size.

Regards, Ivan

**Comment by ivanlaharnar** [comment] 2016-06-13 06:19
No solution yet?

**Comment by tomscholz** [comment] 2017-04-02 23:57
Is this issue https://github.com/Dogfalo/materialize/issues/2734 a duplicate of this one?

**Comment by tomscholz** [comment] 2017-05-16 16:39
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Closed by tomscholz** 2017-05-16 16:39 UTC
Labels: component:Materialbox
