### ISSUE TITLE
Tapping on menu drop-down selects button on HTML page underneath it

### ISSUE THREAD

**Issue by iPhoneDevLog** [Dogfalo/materialize#4238] opened 2017-02-14 22:04 UTC
### Description
The materialize code was added to an HTML/CSS/JS project, Cordova produced an Xcode file, then Xcode installed it on my iPod touch. When I tap on long navbar drop-down menu in the upper right, it drops down to show the various options. If an option is covering a button on the page, then sometimes tapping the option selects the underlying button instead. If an option is covering a collapsible accordion button, then sometimes the accordion opens instead of the option executing. This only occurs on my iPod touch, not my desktop or Android devices. I am NOT accidentally touching the button underneath. 

### Repro Steps
Layout the steps to reproduce your issue.
1. In HTML page, in head tags, add scripts for jquery-3.1.0.min.js, materialize.js, materialize.min.css. 
2. In body, put < ul id="dropdown1" class="dropdown-content"> then list the options as normal list items, like: < li>< a href="pages/features.html">Features< /a>< /li> 
3. In body, add clickable content in upper right where the menu options could open. 
4. Make an Xcode project of it, such as through Cordova CLI, install it in an iOS device, tap on Menu, then tap on an option that is over a tappable element underneath. 

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV
This will not demo the issue. It only appears in an iOS device. Works great on desktop. 

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.
This issue cannot be shown via screenshots. It won't show tapping of option, for instance, but merely show the option names.

**Comment by zanozik** [comment] 2017-02-16 21:23
+1
This can also be reproduced by launching device toolbar in Google Chrome. Looks like this got broken in 0.98.0, worked just fine before that. Coding Microsoft style, eh?

**Comment by iPhoneDevLog** [comment] 2017-02-22 16:02
In addition, it appears that you have to click/tap on the text of the option. Tapping the blank spot to its right selects anything underneath the option, or nothing. Does the <li> need CSS of block, I wonder?

**Comment by gnicol-bzh** [comment] 2017-06-14 09:44
Looks like the bug I talk about here : https://github.com/Dogfalo/materialize/issues/3883

**Comment by tomscholz** [comment] 2017-06-14 10:06
Duplicate of #3883. Thanks @gnicol-bzh

**Closed by tomscholz** 2017-06-14 10:06 UTC
Labels: browser-bug, bug

**Comment by CatalinRadoi** [comment] 2021-03-19 08:42
Closed and unresolved.

**Comment by CatalinRadoi** [comment] 2021-03-19 10:01
OK guys, here is the fix, pretty complex stuff lol (is Dogfalo's code for ios13 but it fixes this also)
https://pastebin.com/GKix4xbm
