### ISSUE TITLE
class prefix

### ISSUE THREAD

**Issue by mantissa7** [Dogfalo/materialize#2296] opened 2015-11-14 22:17 UTC
All css styles should be prefixed to prevent css conflicts.

Like angular-material prefixed with <code>md-*</code>

**Comment by rodriguez-loic** [comment] 2015-11-28 10:33
I agree. Or add the possibility to do it easily.

**Comment by maxupeng** [comment] 2015-11-30 02:56
+1

**Comment by niekpocket** [comment] 2015-12-08 10:00
+1

**Comment by JamesMilnerUK** [comment] 2016-03-09 10:02
+1

**Comment by cristianurbano** [comment] 2016-05-05 23:58
+100

**Comment by colinmathews** [comment] 2016-06-20 02:48
+1

**Comment by jcapogna** [comment] 2016-06-20 05:46
Is there a way to make this without causing a huge headache for everyone with existing projects?

**Comment by rodriguez-loic** [comment] 2016-06-20 08:40
Sure, just duplicating selectors: `.row, .md-row` instead of `.row` for example.
But changes have to be both in css and js, and it's quietly impossible do it alone manually.

**Comment by speicus** [comment] 2016-07-09 20:12
The correct way to make this change without breaking anything would be to provide 2 builds: the primary one, with prefixes, and the legacy one, without them. Look to libraries like modernizr which allow users to make a custom build with custom class prefixes.

P.S. A CSS framework without prefixes is very much like a person who thinks he is alone while in fact he is in a crowded room. The awkwardness of the situation becomes apparent very, very soon. :) In a big project especially. :)

**Comment by monolithed** [comment] 2016-12-25 12:58
All css styles should be prefixed with a custom prefix. 
A good solution and alternative is Ant Design. You should look at their [solution](https://github.com/ant-design/ant-design/blob/master/components/back-top/style/index.less#L5):

```css
.@{prefix} {
    ...
}
```

It is needed to exclude any conflicts when someone can redefine the standard prefix (for example, is actual for browser extensions). So, the prefix should be customized too.

**Comment by tomscholz** [comment] 2017-04-03 00:08
In some way, a duplicate of https://github.com/Dogfalo/materialize/issues/1303

**Closed by tomscholz** 2017-04-03 00:08 UTC
