### ISSUE TITLE
select won't pass data on form submit

### ISSUE THREAD

**Issue by heltonteixeira** [Dogfalo/materialize#4221] opened 2017-02-11 17:52 UTC
I've a form with a select field properly initiated, but on form submit using POST method all fields pass data except the select field, but as soon I use the `browser-default` class the select field pass the data, if I submit the form with GET method it works as well, and I'm using PHP to process the form, not javascript.

I'm using jquery3.1.1, and tested it with Materialize 0.97.7 and 0.98.0

This doen't work, it just don't return any data.
```
`<select name="type" id="selectType">
    <option value="1" selected>Option 1</option>
</select>` 
```

This works, and return the `type: 1`.
```
<select name="type" id="selectType" class="browser-default">
    <option value="1" select>Option 1</option>
</select>
```

**Comment by cslingerland** [comment] 2017-08-02 15:13
Any progress on this one? this is a huge bummer for form functionality!

**Comment by tomscholz** [comment] 2017-08-12 17:40
Duplicate of #4562

**Closed by tomscholz** 2017-08-12 17:40 UTC
Labels: bug
