### ISSUE TITLE
Select doesn't work with optgroups

### ISSUE THREAD

**Issue by pietrofxq** [Dogfalo/materialize#1419] opened 2015-05-25 02:37 UTC
Changing the example from materialize home page:
```html
<div class="input-field col s12">
    <select>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Materialize Select</label>
</div>
```
to
```html
<div class="input-field col s12">
    <select>
      <optgroup>
       <option value="" disabled selected>Choose your option</option>
       <option value="1">Option 1</option>
       <option value="2">Option 2</option>
       <option value="3">Option 3</option>
     </optgroup>
    </select>
    <label>Materialize Select</label>
  </div>
```

When clicking on the select, there is this error on the console:
```Uncaught TypeError: Cannot read property 'top' of undefined  -- materialize.js:429```

```javascript
$.fn.scrollTo = function(elem) {
    $(this).scrollTop($(this).scrollTop() - $(this).offset().top + $(elem).offset().top);
    return this;
  };
```

**Comment by Dogfalo** [comment] 2015-05-25 04:00
Duplicate of #914

**Closed by Dogfalo** 2015-05-25 04:00 UTC
