### ISSUE TITLE
Syntax error on ScrollSpy

### ISSUE THREAD

**Issue by themakshter** [Dogfalo/materialize#2779] opened 2016-02-11 13:14 UTC
This is an interesting issue I am having. When I use the scrollspy function to initialise it, I have an error on the console "Syntax error, unrecognized expression" with the first heading reference.

I cannot reproduce it on [codepen](https://codepen.io/themakshter/pen/OMrwmJ/) but I can produce it on [JsFiddle](https://jsfiddle.net/themakshter/vzqLy7a4/). As you can see, the code is exactly the same but the jsfiddle has an error `Uncaught Error: Syntax error, unrecognized expression: a[href=#introduction]`. This also occurred on my own website when I opened a page I created in the latest build on chrome.

**Comment by CharlieIGG** [comment] 2016-02-11 21:10
Same problem here. Found a solution yet?

**Comment by themakshter** [comment] 2016-02-11 21:48
There are two different pull requests fixing this issue ([1](https://github.com/Dogfalo/materialize/pull/2721) and [2](https://github.com/Dogfalo/materialize/pull/2764)) so i guess one of them will need to get accepted.

**Comment by Rompei** [comment] 2016-02-12 12:32
@themakshter This problem is occurred when we use jQuery 1.5x or higher.
So you can reproduce the bug when you use jQuery from `https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js` (code pen)[https://codepen.io/anon/pen/adXdqr]

**Comment by CharlieIGG** [comment] 2016-02-12 19:52
Thanks @Rompei , however if I do $().jquery in my console, it indicates that my site has jQuery 1.12... Weird?

**Comment by themakshter** [comment] 2016-02-12 20:04
Hey @Rompei , thank you for answering. 

I am not sure if this is for 1.5x or higher. If you look at my codepen, it uses 2.1.3. It is possible that 2.2.0 had this breaking change.

**Comment by Rompei** [comment] 2016-02-12 22:38
@themakshter  @CharlieIGG 
I noticed this problem is appear when we uses latest jQuery not 1.5.x or higher.  I confirmed the error on jQuery 2.2.0 and 1.12.0, and it might be fixed on future jQuery, because there is the issue on [jquery-migrate](https://github.com/jquery/jquery-migrate/issues/140)

**Comment by Dogfalo** [comment] 2016-02-13 08:26
Merged #2764 to fix this.

**Closed by Dogfalo** 2016-02-13 08:26 UTC
