### ISSUE TITLE
Radio button and checkbox not working with with npm install materialize

### ISSUE THREAD

**Issue by Dsaint109** [Dogfalo/materialize#5136] opened 2017-08-21 18:02 UTC
When using npm install of materialize-css the radio buttons and checkboxes don't function dont work 
This is my code using the downloaded materialize
![24](https://user-images.githubusercontent.com/11745653/29531907-a0f7a3c0-86a2-11e7-9a10-3d0cd3b34150.PNG)
and this is it with npm install
![25](https://user-images.githubusercontent.com/11745653/29531934-bb944c7e-86a2-11e7-9853-d4202652d473.PNG)

this is the chrome console for the downloaded one
![screenshot 353](https://user-images.githubusercontent.com/11745653/29532040-2a74c0a6-86a3-11e7-9681-9bcda9e49ced.png)

and this is of the npm one
![screenshot 352](https://user-images.githubusercontent.com/11745653/29532027-21d5398a-86a3-11e7-9f94-6d18f440c991.png)

**Comment by Dogfalo** [comment] 2017-08-21 18:04
Duplicate of #5062

**Closed by Dogfalo** 2017-08-21 18:04 UTC

**Comment by Dsaint109** [comment] 2017-08-21 18:08
Thanks didn't see that
 but how come it works on the downloaded version of maaterailize
