### ISSUE TITLE
Date-picker will not open in jQuery 2.2

### ISSUE THREAD

**Issue by rouisinnocent** [Dogfalo/materialize#2883] opened 2016-03-07 03:19 UTC
Listen, I haven't investigated much on the issue, but here's the thing, I was trying out the date-picker component and it just wouldn't open, but I was using the exact same code written on the materialize website, so I messed around and discovered that the problem was the jQuery version, i was using the lastest one, and the date-picker would only work until 2.1.4.

[Working in 2.1.4](https://jsfiddle.net/1pn6bm4t/)

But then it would fail completely (and in a very frustrating manner if I may say so) in any 2.2 version

[Not working in 2.2.0](https://jsfiddle.net/9pj2cg1w/)

[Not working in 2.2.1](https://jsfiddle.net/pvpz00bc/)

Anyways, it may be something that I'm not aware of, but I thought I should bring it up.

**Comment by ramybenaroya** [comment] 2016-03-07 18:55
This has to do with the fact that in jquery > 2.2.0 native call to [`Element.focus`](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.js#L617) 
does not trigger [`handleFocusToOpenEvent`](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.js#L692)

**Comment by Dogfalo** [comment] 2016-03-08 03:43
Thanks @ramybenaroya for the information.
This issue is a duplicate of #2688

**Closed by Dogfalo** 2016-03-08 03:43 UTC
