### ISSUE TITLE
dropdown-button with inner element closes dropdown

### ISSUE THREAD

**Issue by agrisvv** [Dogfalo/materialize#4524] opened 2017-04-11 09:33 UTC
### Description
when place icon or other element inside dropdown button content, then dropdown-content opens and close.

### Repro Steps
Example dropdown button
 ```
<!-- Dropdown Trigger -->
 <a class='dropdown-button btn' href='#' data-activates='dropdown1'>
   <i class="material-icons">menu</i>
</a>
<!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
  </ul>
```

### Workaround
add 
``` 
&& !origin.find(e.target).length
```
```
// Add click close handler to document
        $(document).bind('click.'+ activates.attr('id') + ' touchstart.' + activates.attr('id'), function (e) {
          if (!activates.is(e.target) && !origin.is(e.target) && (!activates.find(e.target).length) && !origin.find(e.target).length ) {
            hideDropdown();
            $(document).unbind('click.'+ activates.attr('id') + ' touchstart.' + activates.attr('id'));
          }
        }); 
```

**Comment by tomscholz** [comment] 2017-04-11 10:42
Pleas post a codepen to illustrate the problem!
I am unable to reproduce what you mean.

**Comment by agrisvv** [comment] 2017-04-11 10:55
Try click on icon or text
http://codepen.io/agrisv/pen/GmKryO

**Comment by tomscholz** [comment] 2017-04-11 11:03
Duplicate of https://github.com/Dogfalo/materialize/issues/4409, https://github.com/Dogfalo/materialize/issues/4418  and https://github.com/Dogfalo/materialize/issues/4442
And fixed in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4

**Closed by tomscholz** 2017-04-11 11:03 UTC
