### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by Lis1us** [Dogfalo/materialize#2512] opened 2015-12-20 12:07 UTC
![109](https://cloud.githubusercontent.com/assets/16370123/11917914/e5fa761c-a72b-11e5-8383-766bc4a4266e.png)
![110](https://cloud.githubusercontent.com/assets/16370123/11917915/e5fd3e74-a72b-11e5-8eca-807586f488a2.png)

I use IE 11, why a hamburger icon don't work in fullscreen, but work in windowed? http://material.brideland.xyz/

**Comment by theAngryCoder** [comment] 2015-12-20 20:10
Can you please share you code? Looks like you have used the mobile nav example, which will give you the "hamburger icon" only when it is smaller than around 980px. Also looking at the screenshot makes me think that your menu is empty.

**Comment by Dogfalo** [comment] 2015-12-20 21:43
Duplicate of #701

**Closed by Dogfalo** 2015-12-20 21:43 UTC
