### ISSUE TITLE
materialize breaks spiderable for meteor projects

### ISSUE THREAD

**Issue by omin** [Dogfalo/materialize#1805] opened 2015-07-27 03:48 UTC
I've created a reproduction of the bug here https://github.com/OminStyle/meteor-materialize-spiderable-bug.
## Packages Used
- ongoworks:spiderable (https://atmospherejs.com/ongoworks/spiderable)
- dfischer:phantomjs (https://atmospherejs.com/dfischer/phantomjs)
- materialize:materialize (https://atmospherejs.com/materialize/materialize)
## Steps to Reproduce
1. Create a meteor project
2. `cd PROJECT-NAME/`
3. `meteor add ongoworks:spiderable dfischer:phantomjs`
   5.`meteor deploy PROJECT-NAME.meteor.com`
4. `curl PROJECT-NAME.meteor.com/?_escaped_fragment_=`
5. Confirm that <body> is not empty
6. `meteor add materialize:materialize`
7. `meteor deploy PROJECT-NAME.meteor.com`
8. `curl PROJECT-NAME.meteor.com/?_escaped_fragment_=`
9. <body> is now empty
## Results

I get the following error message on Modulus: 

`spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: 1, signal: null }`

You can use `curl` and add `/?_escaped_fragment_=` to the end of the url to mimic Googlebot.
- With materialize:materialize package http://spiderable-with-materialize.meteor.com
- Without materialize:materialize package http://spiderable-without-materialize.meteor.com

**Comment by OminStyle** [comment] 2015-07-27 05:06
Temporary fix is removing the package and loading CSS and javascript files in the header.

**Comment by paulbrab** [comment] 2015-08-25 03:04
+1 I just discovered this too. A combination of manually adding the files in the head and putting this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill 
in materialize.js just before 
```
var Waves = Waves || {};
var $$ = document.querySelectorAll.bind(document);
```

seemed to do the trick for me

**Comment by paulbrab** [comment] 2015-09-14 04:44
Any update on this?

**Comment by FelipeRosa** [comment] 2015-09-28 22:12
+1

**Comment by DanAncona** [comment] 2015-10-05 20:48
Just verified I'm having this problem too, using meteor deploy. Removed materialize from my project and spiderable is at least working. (although still not setting my opengraph tags correctly for some reason) With it in I'm getting errors that look a lot like the ones here -

http://stackoverflow.com/questions/25760039/meteor-spiderable-errors

**Comment by paulbrab** [comment] 2015-10-05 23:14
I believe this is caused by phantomjs not supporting bind() Maybe you could try my solution above until there is a proper fix? It does involve removing the materialize package and then including the materialize files manually. Hope this helps.

**Comment by paulbrab** [comment] 2015-10-27 22:55
Any updates for this issue? I'm surprised it's been left this long as it's a pretty important one in my opinion. Is causes errors when google is crawling which affects indexing your site.

**Comment by artem-russkikh** [comment] 2015-10-29 16:10
@paulbrab phantomjs(2.0.0) is crashing on my site that using materialize package.
Fixed problem by building phantomjs from master branch (http://phantomjs.org/build.html)
Maybe it helps someone

@esergion can you post a link on issue of phantomjs about fonts?

**Comment by esergion** [comment] 2015-10-29 19:40
Hi, sure.
Using GNU debugger I discovered that phantomjs crashing with
```
QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
```
traceback.
So, our issue was similar to https://github.com/ariya/phantomjs/issues/13090.
And seems like aria/phantomjs@5bef1af7186f25dec213c1dfeae624ad7dbc490d commit fixes this

**Comment by tomscholz** [comment] 2017-04-07 21:00
Has anyone encountered this problem again?
Anyhow, I will close this issue for now.

**Closed by tomscholz** 2017-04-07 21:00 UTC
Labels: bug, meteor
