### ISSUE TITLE
Responsiveness problem with the carousel

### ISSUE THREAD

**Issue by RouNNdeL** [Dogfalo/materialize#3859] opened 2016-11-03 17:22 UTC
If you navigate back the carousel (no_wrap has to be false) the click event on the carousel item is being prevented. It happens becausethe center parameter is negative and it is being subtracted from here: 
```javascript
 var diff =  (center%count) - clickedIndex; //This is in the carousel's click function
```
this results in a negative diff (not equal 0) which causes the click event to be canceled. I managed to fix it by changing the line referenced above to:
```javascript
var diff = Math.abs(center % count < 0?center % count + count:center%count) - clickedIndex;
```
I don't have time to setup a developing environment and submit a pull request addressing this issue, that's why i post it here

**Comment by acburst** [comment] 2016-11-05 03:13
I'm not sure exactly what bug you are talking about. There are multiple places where diff is calculated and it is crucial in some places where it should be negative.

From trying to reproduce this issue I did find a bug where when you clicked on an indicator it would also trigger the click event. I've stopped propagating the event so this did fix some issues with indicators if this is the issue you are talking about. Fixed in ec8226b.

If you are experiencing a different issue can you try describing it in more detail or providing a codepen to help reproduce it.

**Comment by RouNNdeL** [comment] 2016-11-05 08:40
Well, maybe my explanation wasn't clear enough. What you need to do to reproduce the bug is:
1. Setup a non-fullwitdh carousel that's wrapping around 
2. After it loads click any of the items on the left side of the first item
3. The carousel will scroll through to that item and every click event on that item will be prevented (event.preventDefault)

**Comment by acburst** [comment] 2016-11-05 19:18
I can't seem to reproduce this. What browser / OS are you using?

**Comment by RouNNdeL** [comment] 2016-11-05 21:17
Windows 7 and Google Chrome. Maybe it's caused by what I put in as the carousel items. I used the cards that reveal more content from your library

**Comment by RouNNdeL** [comment] 2016-11-05 21:20
I can record me reproducing the bug, but only with my phone so the quality won't be perfect

**Comment by acburst** [comment] 2016-11-05 22:19
Can you post a codepen recreating the carousel?

**Comment by RouNNdeL** [comment] 2016-11-05 22:24
Sure, I just dont have a URL to link it there

**Comment by RouNNdeL** [comment] 2016-11-05 22:26
Nvm, I found it on your page

**Comment by RouNNdeL** [comment] 2016-11-05 22:43
[There you go.](https://jsfiddle.net/4zm9au0n/) If you click on the image on the left the card wont go up. Put if you go to the  right and do a full circle the same exact image will now respond showing the card info.

**Comment by RouNNdeL** [comment] 2016-11-15 21:35
Any updates about this issue?

**Comment by tomscholz** [comment] 2016-12-15 17:31
I can reproduce the issue (Mac OSX 10.11.6 with Chrome v55.0.2883.95)

**Comment by bigrobsf** [comment] 2017-02-10 04:34
I have the same issue on Mac OSX 10.11.6 with Chrome v56.0.2924.87 (64-bit), Firefox Developer 53.0a2 (2017-02-09) (64-bit), Safari Version 10.0.3 (11602.4.8.0.1).

**Comment by NonameSLdev** [comment] 2017-04-13 18:58
Is anyone able to reproduce this on the new versions? It works for me (Windows 10 Chrome, Firefox)

**Comment by fega** [comment] 2017-04-16 00:40
@NonameSLdev also is working here in chrome, linux

**Comment by tomscholz** [comment] 2017-04-21 18:45
Closed due inactivity, feel free to reopen it if it is still necessary.

**Closed by tomscholz** 2017-04-21 18:45 UTC
Labels: awaiting reply, bug
