### ISSUE TITLE
Datapicker creates random grave accent (`) in Firefox

### ISSUE THREAD

**Issue by goyney** [Dogfalo/materialize#3142] opened 2016-05-09 19:19 UTC
![grave](https://cloud.githubusercontent.com/assets/1015040/15125119/39d2927e-15f9-11e6-8457-d511d09b8acf.jpg)

In Firefox, the datepicker causes a grave accent to appear right below the form field. The screenshot above was taken on the Materialize CSS website, but was initially discovered in our implementation.

The issue does not seem to affect Chrome.

**Comment by gonggle** [comment] 2017-01-02 10:35
Did you find out how to solve this?

**Comment by Dogfalo** [comment] 2017-01-02 15:59
I am not seeing this on Firefox 50.1.0. What version are you seeing this on?

**Comment by fega** [comment] 2017-04-11 05:10
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by goyney** [comment] 2017-04-11 14:14
Please reopen this issue. It is still an ongoing problem, even on latest Firefox. There's been no activity because we've been waiting for you to fix the issue.

**Comment by fega** [comment] 2017-04-11 14:24
@goyney, sure!

**Comment by DanielRuf** [comment] 2017-06-09 22:57
Duplicate of https://github.com/Dogfalo/materialize/issues/4793

**Closed** 2017-06-10 08:29 UTC
Labels: browser-bug, component:DatePicker
