### ISSUE TITLE
btn-floating not hiding uppon click mobile

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#898] opened 2015-03-12 10:20 UTC
Hi,

I have a Fab and when hovering it reveals 2 other fab's but when I click on it on my tablet, the buttons stay visible (until you click somewhere else) I tried setting the focus somewhere else. but no luck.
This doesn't happen on Desktop.

Could someone give me a fix / suggestion for fixing this issue?

**Comment by Dogfalo** [comment] 2015-03-12 17:20
touch devices have no :hover state, so this is why it is not working is you would expect.

**Comment by ryanbuiltthat** [comment] 2015-03-17 16:31
@Dogfalo what do you think would be the best workaround for that? Adding a callback with a delay to hide the buttons a few hundred ms after firing?

**Comment by mazzie14** [comment] 2015-03-28 21:58
Any ideas /updates about this??

**Comment by kampfkeks** [comment] 2015-03-29 00:29
Yeah adding a callback after a few seconds to hide again the fabs is propably your best bet.

**Comment by cskiwi** [comment] 2015-03-30 08:35
I added the following:

```javascript
        $(".sub-fab").click(function () {
            $(".fixed-action-btn").mouseleave();
            $(".tooltipped").mouseleave();
        });
```

**Comment by Dogfalo** [comment] 2015-04-08 20:45
Duplicate of #963 which has a better name/description.

**Closed by Dogfalo** 2015-04-08 20:45 UTC
