### ISSUE TITLE
Changing aspect ratio in Material box animation on phone in landscape orientation

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#502] opened 2015-01-21 13:47 UTC
If I turn my Nexus 5 sideways for landscape orientation, I can zoom in a picture (Material box) just fine it seems. As I zoom out (e.g. swipe to scroll or tap again) however, the transition changes the aspect ratio of the picture. It goes from ok to narrower than normal, but restores the correct ratio when the animation is done.

It does not occur while phone is in portrait orientation. There's some similar effect if you click and scroll a lot on a desktop computer sometimes, but barely noticeable.

Drop me a message if you need video proof.

**Comment by Dogfalo** [comment] 2017-02-02 16:21
Duplicate of #510

**Closed by Dogfalo** 2017-02-02 16:21 UTC

**Comment by CoDEmanX** [comment] 2017-02-03 15:01
As written in the other report, the issues are about two different problems.
