### ISSUE TITLE
Carousel with two or less items glitchy

### ISSUE THREAD

**Issue by Obermeijer** [Dogfalo/materialize#4346] opened 2017-03-14 09:37 UTC
### Description
When you have two or less carousel-items, sliding looks glitchy.

It looks like there's no item on the right side of the active carousel-item. This causes it to look very glitchy as soon as the active class switches to the next or previous carousel-item.

### Repro Steps
I've created a codepen http://codepen.io/anon/pen/oZeXLr with two items (and uncommented third item).

Slide to the left a bit and you'll notice the missing item, enable the third uncommented item and it works as expected.

### Screenshots / Codepen
When sliding to the left you can see there's no item on the right side of the current item.
<img width="1318" alt="screen shot 2017-03-14 at 10 29 47" src="https://cloud.githubusercontent.com/assets/5425782/23894161/57531620-08a1-11e7-83a7-1546c9a34c37.png">

**Comment by tomscholz** [comment] 2017-05-15 06:38
Duplicate of https://github.com/Dogfalo/materialize/issues/4679

**Closed by tomscholz** 2017-05-15 06:38 UTC
Labels: bug, component:Carousel
