### ISSUE TITLE
Icon Button in nav shifts down icon

### ISSUE THREAD

**Issue by retorquere** [Dogfalo/materialize#4061] opened 2017-01-03 18:18 UTC
When I add a raised button with an icon (http://materializecss.com/buttons.html) in a nav (http://materializecss.com/navbar.html) the icon shifts down; see the button in [this fiddle](http://jsfiddle.net/mgbed790/).

**Comment by tomscholz** [comment] 2017-01-03 22:00
I created a codepen cause your fiddle dosen't work for https://codepen.io/tomscholz/pen/YNzedG
The problem is that the icon has got the same height as the hamburger icon on mobile.

**Comment by acburst** [comment] 2017-01-04 03:31
This was fixed in 9fcc379dce10353b425b9c4c8f71484ffba2a6a1.

You can use our master version or wait until we release a new version.

**Closed by acburst** 2017-01-04 03:31 UTC

**Comment by retorquere** [comment] 2017-01-04 05:34
Can I install the master version using bower?

**Comment by retorquere** [comment] 2017-01-04 12:41
Should loading this stylesheet (from the commit you mentioned above) at the end fix this? It doesn't for me:

```
nav ul a.btn > .material-icons, nav ul a.btn-large > .material-icons, nav ul a.btn-large > .material-icons, nav ul a.btn-flat > .material-icons, nav ul a.btn-floating > .material-icons {
   height: inherit;
   line-height: inherit;
 }
 ```
