### ISSUE TITLE
Cannot Resolve darwin-x64-46_binding.node (404) when attempting to add package to project (Meteor) 

### ISSUE THREAD

**Issue by elliottshort** [Dogfalo/materialize#3460] opened 2016-08-04 11:52 UTC
The following dependency can't be resolved (404) 

> Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node": HTTP error 404 Not Found

**Comment by mitar** [comment] 2016-08-07 21:22
That is probably a dependency problem. Open an issue here: https://github.com/fourseven/meteor-scss

**Comment by pdramos1** [comment] 2016-08-12 20:44
@mitar , I don't think this is a dependency issue there. (I could be wrong though) . What I did to solve this was simply install meteor-scss first so I had the latest.. and then installed materialize second. Since the meteor-scss was installed everything was happy. The reason I don't think the issues is with meteor-scss the error is in calling the 3.2.0 version from within materialize. At least that's how I read it.

**Comment by zeta-o** [comment] 2016-08-28 01:26
Probably @mitar  has reason -> Since meteor 1.4.1+ (fourseven:scss 3.9.0+), we do not have prebuild binaries anymore. You are required to set up the required toolchain yourselves.

**Comment by zeta-o** [comment] 2016-08-28 13:53
I fixed the problem just like @pdramos1 suggested. Thank you!

**Comment by pdramos1** [comment] 2016-08-28 15:56
Glad it worked for you @zeta-o !

**Comment by Dogfalo** [comment] 2016-10-15 21:37
Duplicate of #3438

**Closed by Dogfalo** 2016-10-15 21:37 UTC
