### ISSUE TITLE
Tooltip Does Not Disappear When I Remove Item After Click

### ISSUE THREAD

**Issue by rafael-atrixdevelopers** [Dogfalo/materialize#4994] opened 2017-07-20 19:20 UTC
I created a button that has a tooltip, when I click the button it makes an ajax request and then the button disappears but the tooltip does not disappear too

Before Click button
![before_click](https://user-images.githubusercontent.com/30170023/28434819-39121adc-6d67-11e7-9199-4229cb42d471.png)

After Click Button
![after_click](https://user-images.githubusercontent.com/30170023/28434828-3fd2594a-6d67-11e7-8ffa-cb29868048c1.png)

I am using the remove () method of jquery

Is there any way I can make the tooltip disappear?

**
Using Materialize Version: 0.98.2
Chrome Version: 59

**Comment by tomscholz** [comment] 2017-07-20 19:27
Duplicate of #1911, #3566

**Closed by tomscholz** 2017-07-20 19:27 UTC
Labels: component:Tooltip

**Comment by BarshaLamichhane** [comment] 2019-05-15 11:40
hello this worked for me
$('.tooltipped').mousedown(function(){
			$('.material-tooltip').css("visibility", "hidden");
		})

**Comment by ananthsvpr** [comment] 2019-08-02 05:41
Materialize CSS always generate id for each tooltip, may be this is still in your DOM.
Find the element with tooltip-id and remove. I fix this issue with below code change onClick element, I use react-materialize 2.4.8
<div className="btn-container">
              <Button ref={element => this._remove = element} id="tooltipped" tooltip="Remove" onClick={ this._handleRemoveClick }>
                <Icon>highlight_off</Icon>
              </Button>
            </div>

_handleRemoveClick(event){
    let removeBtnId = this._remove._btnEl.dataset.tooltipId;
    window.$(`#${removeBtnId}`).remove();
  }
