### ISSUE TITLE
The order of definitions of column offset selectors is wrong

### ISSUE THREAD

**Issue by ancientdemon** [Dogfalo/materialize#2348] opened 2015-11-21 15:22 UTC
There is an issue with v0.97.3 \bower_components\materialize\dist\css\materialize.css where the .row .col.offset-l1 {...} .row .col.offset-l2 {...} are defined intermingled with definitions of .row .col.l1 {} row .col.l2 {} etc such that some of the offset definitions come before l definitions in the css. In versions before v0.97.3 these offset definitions always came after column width (l) definitions, which is correct.

The current issue causes the row .col.offset- definitions to be not effective in situations like below example

`<div class="row">`
`     <div class="col s12 m8 l5 offset-m2 offset-l3">`

Here is a an what happens shown in chrome dev tool window

![image](https://cloud.githubusercontent.com/assets/15957098/11319099/6224cb2a-9039-11e5-874e-11d900d450ba.png)

Instead of margin-left: 25%  being effective, the margin-left: 0 has taken precedence.

**Comment by uok** [comment] 2015-11-21 16:25
duplicate of https://github.com/Dogfalo/materialize/issues/2328 and already fixed with next release

**Comment by acburst** [comment] 2015-11-21 17:34
duplicate.

**Closed by acburst** 2015-11-21 17:34 UTC

**Comment by ancientdemon** [comment] 2015-11-21 20:25
Sorry about the duplicate folks. I am new to the github way of life. Will try to better in searching for existing issue before posting my next on. Keep up the good work. Thanks

**Comment by acburst** [comment] 2015-11-21 22:42
No problem! I appreciated the effort and detail in your issue
