### ISSUE TITLE
materilaize css tooltip not working correctly on ios

### ISSUE THREAD

**Issue by Gardezi1** [Dogfalo/materialize#2158] opened 2015-10-14 10:40 UTC
Hello I am facing a problem in ios. I have a tooltip when I click on it the message appears but it does not go aways I don't know what I am doing wrong. Can somebody tell me what is it that I am doing wrong ??

here is an image that I am sharing 

The page has been loaded but the tooltip message is not going 
   http://screencast.com/t/mvvZX4UZmgj

and when I move to another tab the tooltip of the previous tab remains 
  http://screencast.com/t/dTZpmfcR

can you please tell me what is it that I am doing wrong. Thanks

**Comment by mccraveiro** [comment] 2015-10-27 05:21
I've made a codepen reproducing this issue http://codepen.io/mccraveiro/pen/yYKWgM
It looks like there is no support for mobile tooltips as Materialize uses only mouse events. 
You could implement this yourself. Maybe a click event on the tooltip or a timer for closing the message.

**Comment by mambax** [comment] 2016-03-02 09:16
@yaennuuh is currently forking for just this purpose, should be done by end of day.

**Comment by corvuscornix** [comment] 2016-07-19 09:03
I would like to see this problem fixed as well. :)

**Comment by mambax** [comment] 2016-07-19 09:37
We fixed this problem locally (and ugly) by overriding the function from materialize and copy pasta of the code, introducing a timer to the tooltips. I can provide a pen if wanted (as I said, ugly but works for the moment).

**Comment by Dogfalo** [comment] 2017-07-29 17:03
See my comment here: https://github.com/Dogfalo/materialize/issues/1702

**Closed by Dogfalo** 2017-07-29 17:03 UTC
Labels: component:Tooltip
