### ISSUE TITLE
Can't select values after scrolling in select menu

### ISSUE THREAD

**Issue by justintech** [Dogfalo/materialize#2375] opened 2015-11-26 05:27 UTC
When I use the scrollbar where I have to scroll down to select a value it doesn't select it. The main website http://materializecss.com/forms.html for the first select has the same issue I'm having. If you scroll you cannot select any values but if you leave it as is and select one, it will select said value. Another way to select is by using the keyboard.

Anyone else have this issue? Is there a work around?

**Comment by acburst** [comment] 2015-11-26 18:44
Duplicate of #2309

**Closed by acburst** 2015-11-26 18:44 UTC

**Comment by m00k1e** [comment] 2016-04-21 20:26
Hello!

 

New message, please read <http://sklepprosport.pl/arrive.php?w>

 

hello@mookiecreative.com
