### ISSUE TITLE
New version causing grid issues

### ISSUE THREAD

**Issue by lordplagus02** [Dogfalo/materialize#2378] opened 2015-11-26 13:32 UTC
It appears that one of the versions post 0.97.1 has affected either grid offsets or center alignment in a way that has caused all of my columns that were center-aligned to all be left-aligned. It seems to me that the offset classes aren't working correctly.

**Comment by acburst** [comment] 2015-11-26 18:43
Duplicate of #2328

**Closed by acburst** 2015-11-26 18:43 UTC
