### ISSUE TITLE
Autocomplete doesn't complete the last character

### ISSUE THREAD

**Issue by guilhermemaranhao** [Dogfalo/materialize#5094] opened 2017-08-10 00:10 UTC
Hello guys,

I was searching for issues related to my problem and I thought this one could be duplicate:

https://github.com/Dogfalo/materialize/issues/4230

It was said that the related autocomplete problem was solved. I've downloaded the last materialize-sass gem version but it seems it wasn't fixed.

The problem I'm facing with is: I have the tag "notebook". the autocomplete works until "noteboo", when I enter the "k", the tag simply doesn't appear.

That's how I'm declaring my autocomplete component:
```javascript
$('.chips-autocomplete').material_chip({
            autocompleteOptions: {
                data: tagoptions.autoCompleteData,
                limit: Infinity,
                minLength: 1
            },
            secondaryPlaceholder: 'Adicione a tag',
            placeholder: '+Tag',
            data: tagoptions.data
        });
```
The tagoptions.autoCompleteData object is defined as:
```
{
  eraser:null,
  notebook:null,
  pencil: null
}
```
The tagoptions.data is an array of chips:
```
[{
  id,
  tag
}]
```
Is it a real problem or am I missing something?

Thank you,

Guilherme

**Comment by neutron92** [comment] 2017-08-12 17:55
same problem in node and meteor

**Comment by Dogfalo** [comment] 2017-08-15 00:14
What version? I cannot reproduce this on: http://materializecss.com/forms.html#autocomplete

**Comment by neutron92** [comment] 2017-08-15 19:29
materialize:materialize@=0.99.0

**Comment by guilhermemaranhao** [comment] 2017-08-17 16:47
Thank you, guys.

I'm using 0.97.8.

@neutron92 , did you solve it with this snippet?

**Comment by neutron92** [comment] 2017-08-17 17:46
i have this errors
```
materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7826 Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down".


    at materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7826
    at materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7830
    at materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7842
(anonymous) @ materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7826
(anonymous) @ materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7830
(anonymous) @ materialize_materialize.js?hash=38aa0de00bf1da3e83504deced815b530abaefa4:7842
global-imports.js?hash=5e0f0a71522c063bb881071904e7eeca01779ebd:16 Uncaught TypeError: Cannot read property 'Materialize' of undefined
    at global-imports.js?hash=5e0f0a71522c063bb881071904e7eeca01779ebd:16
(anonymous) @ global-imports.js?hash=5e0f0a71522c063bb881071904e7eeca01779ebd:16
app.js?hash=8d04954afed1b707ef74ab0f7fa58a663df0fea6:1 Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=8d04954afed1b707ef74ab0f7fa58a663df0fea6:1
```

**Comment by neutron92** [comment] 2017-08-25 10:22
same prob here

https://codepen.io/AlphaDx/pen/xgmXgw

**Comment by acburst** [comment] 2017-09-08 01:07
This should be fixed on the latest version

**Closed by acburst** 2017-09-08 01:07 UTC
Labels: component:Autocomplete
