### ISSUE TITLE
Allow HTML in select

### ISSUE THREAD

**Issue by dbnoble** [Dogfalo/materialize#2709] opened 2016-01-26 12:36 UTC
Honestly, the way the select element works is less than desirable. 

For instance, if I want an item to have a title such as "Awesome product" and underneath it have a subtitle such as "Brazen Tech Mfg", once it's selected, it will say "Awesome productBrazen Tech Mfg" in the "fake" `select` element.

It would be better if there was a way use HTML to customize the styled fake dropdown elements, but as of now, you're pretty much stuck with whatever you have inside `option` which isn't very flexible.

**Comment by TyrionGraphiste** [comment] 2016-01-26 13:34
The select component follows the native select element. W've added some others functionalities like icons and multiple selection by clicking on a optgroup for multiple select, but we have to follow the native element.

So actually we can't add a div in a option element, so why could we.

**Comment by dbnoble** [comment] 2016-01-26 14:38
The point is, the "fake" elements are simply `li` elements. You've already left "native" territory by adding icons. Just because you don't want people nesting HTML inside `<option>` doesn't mean there's no way to achieve it. You **can** pass html in string form through a data attribute, which is exactly how it's done in bootstrap for tooltips/popovers with HTML content when you can't specify the content at `init`.

I reworked the material_select function and it works PERFECTLY and took maybe 3 minutes.

All you have to do is pass each `<option>` tag these two things: 

1. A text value to show up when the menu is closed into `data-placeholder`

2. Your HTML content into `data-content`

https://gist.github.com/dbnoble/436456f45ca959b75123

Take a look at the gist, try it for yourself, and tell me this isn't a better way to do it.

**Comment by TyrionGraphiste** [comment] 2016-01-26 15:21
So let's do a pull request and maybe they will merge.

**Comment by dbnoble** [comment] 2016-01-26 16:21
https://github.com/Dogfalo/materialize/pull/2710

**Comment by dbnoble** [comment] 2016-01-27 01:44
Completed to make backwards-compatible and pull request submitted.

**Comment by tomscholz** [comment] 2017-08-13 23:01
Duplicate of #2305

**Closed by tomscholz** 2017-08-13 23:01 UTC
Labels: component:Select, has-pr, help-wanted
