### ISSUE TITLE
Slow Scroll with collection inside modal

### ISSUE THREAD

**Issue by mikejones3** [Dogfalo/materialize#1720] opened 2015-07-12 00:35 UTC
I have a decent sized collection inside a modal pop up and it is very slow scrolling through the collection when it is viewed inside of a modal.

**Comment by acburst** [comment] 2015-07-12 01:06
Can you post a codepen?

**Comment by mikejones3** [comment] 2015-07-12 02:39
Can I email you the code privately?

**Comment by acburst** [comment] 2015-07-12 03:04
yes

**Comment by mikejones3** [comment] 2015-07-12 03:19
What is your email?

**Comment by cabri89** [comment] 2016-08-12 13:48
Hello,

I have the same problem but just on Google chrome for mobile phone.

You have a solution ? 

Regards.

**Comment by tomscholz** [comment] 2017-04-01 13:47
I can't seem to reproduce it. I close this issue for now. If anyone posts a codepen, that is able reproduce the issue, we can reopen it.

**Closed by tomscholz** 2017-04-01 13:47 UTC

**Comment by cabri89** [comment] 2017-04-04 17:23
The problem is solve ^^ For why, I don't now ^^
