### ISSUE TITLE
autocomplete url?

### ISSUE THREAD

**Issue by CatalinRadoi** [Dogfalo/materialize#5314] opened 2017-10-30 10:38 UTC
I've checked the .js and I've seen no implementation for an autocomplete with url. Really? =)

**Comment by penguoir** [comment] 2017-10-30 12:02
Could you explain the expected behaviour?

**Comment by fnowacki** [comment] 2017-10-30 22:11
@penguoir I understand point of @CatalinRadoi's view. He want download data field in autocomplete from 3rd party source e.g. ajax. I got the same problem.

**Comment by bassie1995** [comment] 2017-10-31 08:55
This has been an issue for a long time, and there's already an issue on this. See https://github.com/Dogfalo/materialize/issues/4086...

**Comment by tomscholz** [comment] 2017-10-31 12:32
Duplicate of #4086 @Dogfalo Please close

**Closed** 2017-12-10 22:28 UTC
