### ISSUE TITLE
Select does not work on iOS properly

### ISSUE THREAD

**Issue by ahmetb** [Dogfalo/materialize#4315] opened 2017-03-03 21:40 UTC
### Description

`<select>` support does not properly work on iOS. When user taps on a select, the select view is a bit misplaced, there's a  textcursor on the placeholder (first) value, then when the user taps
the value is not displayed as selected on the select's rendered view while unfocused.

### Screenshots / Codepen

Screencast from iOS simulator:

![ae7sauapbz](https://cloud.githubusercontent.com/assets/159209/23569837/46f17d5a-0016-11e7-8b40-ba56de3d4182.gif)

I have the select extracted here: http://codepen.io/anon/pen/mWEyWL?editors=0010 but I can't seem to repro the codepen with iOS simulator. Any ideas what the problem on my setup might be? 

I don't have any custom CSS/JS at all, just this:

```
        $(document).ready(function() {
            $('select').material_select();
        });
```

**Comment by tomscholz** [comment] 2017-03-05 11:32
Duplicate of https://github.com/Dogfalo/materialize/issues/4306

**Comment by tomscholz** [comment] 2017-04-04 19:51
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/4413
https://github.com/Dogfalo/materialize/issues/4315
https://github.com/Dogfalo/materialize/issues/4306
https://github.com/Dogfalo/materialize/issues/3715
https://github.com/Dogfalo/materialize/issues/3171
https://github.com/Dogfalo/materialize/issues/630

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3790

**Closed by tomscholz** 2017-04-04 19:51 UTC
