### ISSUE TITLE
Pickadate not working with materialize 0.100.2 with the latest chrome update

### ISSUE THREAD

**Issue by ArunAthisamy-03** [Dogfalo/materialize#6320] opened 2019-03-29 18:54 UTC
Calendar window disappears immediately when the picker box is clicked.

Ex : https://codepen.io/mcolynuck/pen/XeZzMJ?editors=1010
chrome v73.0.3683.86

**Comment by yj7** [comment] 2019-03-30 12:05
Duplicate of #6312

**Closed** 2019-03-31 00:50 UTC
