### ISSUE TITLE
Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down".

### ISSUE THREAD

**Issue by yanickrochon** [Dogfalo/materialize#3905] opened 2016-11-10 19:45 UTC
Just got this after updating Meteor to 1.4.2.1 and Materialize to 0.97.8.

**Comment by moslemir** [comment] 2016-11-11 07:32
+1

**Comment by tomscholz** [comment] 2016-11-11 13:15
+1

**Comment by keyscores** [comment] 2016-11-12 20:00
@Dogfalo I can reproduce. This is NOT an issue with the Meteor update.

Seems like this is an issue with a Materialize SCSS definition in 0.97.8. Downgrading to 0.97.7 fixes this error. 

Anyone upgrading meteor versions is also prompted for package updates, such as materialize:materialize.

**Comment by Phixiys** [comment] 2016-11-14 22:24
How to downgrade? Mine will auto install latest materialize:materialize 0.97.8

Even if specify meteor add materialize:materialize@0.97.7

**Comment by tomscholz** [comment] 2016-11-14 22:37
@Phixiys 
You have to ru meteor add materialize:materialize@=0.97.7
You can read more about it here
https://atmospherejs.com/i/installing

**Comment by Phixiys** [comment] 2016-11-15 00:39
@Dogfalo Yeah, searched stackoverflow and found it. Thank's though.
:-)

**Comment by yanickrochon** [comment] 2016-11-15 01:51
Meh, the easiest way is to manually edit your `.meteor/versions` file :stuck_out_tongue: Then meteor will install the proper Materialize package automatically without updating. This can even be done running hot.

**Comment by tomscholz** [comment] 2016-11-15 15:11
https://github.com/Dogfalo/materialize/issues/3905#event-858604013 Yeah! we got a bug label. A solution is hopefully near!

**Comment by acburst** [comment] 2016-11-16 02:42
Can't seem to reproduce locally. I fresh installed Node, NPM, and Meteor.

I did run into some issues when trying to install the Materialize package fresh. But after I installed the fourseven:scss package first, installing Materialize went smoothly.

**Comment by kurapikats** [comment] 2016-11-19 02:53
I encountered the same error $medium-and-down... and downgraded materializecss to version 0.97.7. 
But now I got another issue: Failed to decode downloaded font: ...Roboto...
As seen here -> #2217

**Comment by charlesdagenais** [comment] 2016-11-21 02:56
submitted a pull request to correct this #3924

**Comment by keyscores** [comment] 2016-11-21 16:42
@acburst I did the same as you, and I definitely reproduce the same error.

@charlesdagenais  can you tell us a bit more about the fix?

**Comment by charlesdagenais** [comment] 2016-11-21 16:51
@keyscores Looks like the error happen when sass try to compile sass/style.scss  . The compiler can't resolve any variable, because they're not imported. style.scss is only used for documentation website style. Renaming it to _style.scss and correcting the import statement in ghpages-materialize prevent it from been compiled to css

![capture d ecran 2016-11-21 a 11 50 31](https://cloud.githubusercontent.com/assets/2420301/20491869/cab3b364-afe0-11e6-9863-0999fdc8ff5c.png)
![capture d ecran 2016-11-21 a 11 50 49](https://cloud.githubusercontent.com/assets/2420301/20491875/cd823322-afe0-11e6-9ee6-bd2f068d914a.png)

**Comment by tomscholz** [comment] 2016-11-21 17:31
@charlesdagenais @acburst  
Now I get 
```shell
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /client/css/index.scss: Scss compiler error: Undefined variable:
   "$small-and-down".
   
   /client/css/login.scss: Scss compiler error: ".forgot .login-row" failed to
   @extend ".row".
   The selector ".row" was not found.
   Use "@extend .row !optional" if the extend should be able to fail.
   
   /client/css/map.scss: Scss compiler error: Undefined variable:
   "$small-and-down".
```
=> Your application has errors. Waiting for file change.

**Comment by charlesdagenais** [comment] 2016-11-21 17:38
@tomscholz you forgot to rename /sass/style.scss  file to sass/_style.scss

**Comment by tomscholz** [comment] 2016-11-21 17:43
@charlesdagenais Thats true, but it didn't change anything :/

**Comment by charlesdagenais** [comment] 2016-11-21 17:55
@tomscholz Just tried your fork of the materialize package in my app and it's working perfectly fine. looks like the problem is in your index.scss and login.scss and map.scss

**Comment by tomscholz** [comment] 2016-11-21 18:11
@charlesdagenais Do you spot any errors?
https://gist.github.com/tomscholz/ae4b3894e3e7963888f7cffdb9c5a892 // map.scss
https://gist.github.com/tomscholz/61883623a63e49c6dcc59159589abc89 // login.scss (I tried to replace the screen variable with the pure values)
https://gist.github.com/tomscholz/9606216e9112f1d74d4cd1c5851f9ef3 // index.scss

**Comment by charlesdagenais** [comment] 2016-11-21 18:50
@tomscholz if you want to use variables in your custom scss files, you need to import them from the materialize package

**Comment by tomscholz** [comment] 2016-11-21 20:24
But then I end up with a huuuuge compiled css file! I guess we can now close this issue and the rest is my problem ;)

 

Von: charlesdagenais <notifications@github.com>
Antworten an: Dogfalo/materialize <reply@reply.github.com>
Datum: Montag, 21. November 2016 um 19:50
An: Dogfalo/materialize <materialize@noreply.github.com>
Cc: Tom Scholz <ts@scholzworks.com>, Mention <mention@noreply.github.com>
Betreff: Re: [Dogfalo/materialize] Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down". (#3905)

 

@tomscholz if you want to use variables in your custom scss files, you need to import them from the materialize package

**Comment by MuyBien** [comment] 2016-11-29 10:01
Hi everybody!
I have the same problem and I cannot find the style.scss file in my project directory.
Where are those files going from the .meteor directory ?

Thanks gor your help

**Comment by tomscholz** [comment] 2016-11-29 10:11
@MuyBien Clone the materialize repo into the /packages folder inside your project folder. 
Via shell:
```shell
cd /path/to/YOURPROJECTFOLDER
mkdir packages
cd packages
git clone https://github.com/Dogfalo/materialize.git
```
![bildschirmfoto 2016-11-29 um 11 04 36](https://cloud.githubusercontent.com/assets/20381749/20705586/c973f0d8-b623-11e6-8502-060828137d51.png)
Then open this file inside the materialize folder in your packages folder.
![bildschirmfoto 2016-11-29 um 11 06 08](https://cloud.githubusercontent.com/assets/20381749/20705613/e41bf49e-b623-11e6-8857-1e8491cfc2ed.png)
and change 
```javascript
  name: 'materialize:materialize',  // http://atmospherejs.com/materialize/materialize
```
to something like this:
```javascript
  name: 'tomscholz:materialize',  // http://atmospherejs.com/materialize/materialize
```
Then run:
```javascript
meteor remove materialize:materialize
meteor add tomscholz:materialize
```
 Than edit the style.scss

et voilà

**Comment by MuyBien** [comment] 2016-11-29 10:22
Huuuuuuuuuuuu OK!!!
Thanks ! And when your PR will be accepted I can run:

`meteor remove tomscholz:materialize`
`meteor add materialize:materialize`

**Comment by tomscholz** [comment] 2016-11-29 10:24
@MuyBien Yes ;D. Totally. You got it

**Comment by tomscholz** [comment] 2016-12-19 22:45
https://github.com/Dogfalo/materialize/issues/2217#issuecomment-268100489

**Comment by Dogfalo** [comment] 2016-12-23 22:54
Both PR have been merged, will be closing this issue for now unless further issues pop up.

**Closed by Dogfalo** 2016-12-23 22:54 UTC
Labels: bug
