### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by firelizzard18** [Dogfalo/materialize#5426] opened 2017-11-29 23:26 UTC
On the `v1-dev` branch, in [js/tabs.js on line 252](https://github.com/Dogfalo/materialize/blob/48a4eafd9d7164795e5a822946cc6a09bd33fc60/js/tabs.js#L252), there's a bug, as `options` is not a variable:

```js
if (window.innerWidth > options.responsiveThreshold) {
  this.options.swipeable = false;
}
```

It seems the convention is to assign `options` to `this.options` of the (tabs) instance, the solution would be to use `this.options` instead. Otherwise, `options` needs to be passed as a parameter. Corrected:

```js
if (window.innerWidth > this.options.responsiveThreshold) {
  this.options.swipeable = false;
}
```

**Comment by acburst** [comment] 2017-11-29 23:33
Duplicate of #5424

**Closed by acburst** 2017-11-29 23:33 UTC
