### ISSUE TITLE
HTML5 range slider bubble position not updated

### ISSUE THREAD

**Issue by MacGyer** [Dogfalo/materialize#5761] opened 2018-03-25 15:08 UTC
## Expected Behavior
When moving the slider, the bubble (`.thumb`) shall move with the range indicator like in the demo:
http://next.materializecss.com/range.html#html5

## Current Behavior
When calculating the range offset, the max and min values are `NaN`:
![image](https://user-images.githubusercontent.com/2939625/37876584-ca56b228-304e-11e8-8f06-91db84c9ea63.png)

Thus the bubble's position does not get updated correctly.

Markup:
![image](https://user-images.githubusercontent.com/2939625/37876597-059de3c4-304f-11e8-9da9-eea0115d7663.png)

## Your Environment
* Version used: 1.0.0-beta
* Browser Name and version: Chrome current
* Operating System and version (desktop or mobile): Win 10 Desktop

**Comment by acburst** [comment] 2018-03-25 23:38
I can't reproduce this issue. Can you create a codepen that can reproduce this?

**Comment by MacGyer** [comment] 2018-03-27 19:54
Couldn't reproduce with a codepen either. But the problem exists in my project.
Need to investigate further.
Trying to setup a demo page for you to check.

Thanks anyway for the great work, guys.

**Comment by MacGyer** [comment] 2018-03-30 09:06
Hi guys,

the problem occurs when the input's min and max attributes are omitted.
IMHO this is a valid use case as there are default if these atts are not set:
[MDN range input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)

It says: 

> By default, the minimum is 0 and the maximum is 100

Cheers

**Comment by acburst** [comment] 2018-04-02 20:20
Fixed in aeb99ba4

**Closed by acburst** 2018-04-02 20:20 UTC
