### ISSUE TITLE
Modal is not closing when using key Enter

### ISSUE THREAD

**Issue by acierpinski** [Dogfalo/materialize#2695] opened 2016-01-22 20:59 UTC
When you want to close a modal window with key #13 (return) (should be the primary action) it is opening another modal window in an endless loop.

Check it out at http://materializecss.com/modals.html

**Comment by Dogfalo** [comment] 2016-01-23 04:28
Duplicate of #2654

**Closed by Dogfalo** 2016-01-23 04:28 UTC

**Comment by ezeed** [comment] 2016-03-02 13:37
Same for me and when I was about to report the bug, I found this issue. This is a focus problem? the focus stay in the button and when you enter the key #13, another  modal is triggered in place of close the first. Is a viable solution fix the focus on display the modal?
