### ISSUE TITLE
Incorrect style for prefix icon on select

### ISSUE THREAD

**Issue by alexiolan** [Dogfalo/materialize#1934] opened 2015-08-19 08:53 UTC
![capture](https://cloud.githubusercontent.com/assets/12134913/9352265/961d4800-4668-11e5-8feb-65cd681ec672.JPG)

**Comment by carlosperate** [comment] 2015-08-19 13:22
Duplicate of https://github.com/Dogfalo/materialize/issues/853

**Closed by carlosperate** 2015-08-19 13:22 UTC
