### ISSUE TITLE
sass files for meteor package

### ISSUE THREAD

**Issue by Remownz** [Dogfalo/materialize#2651] opened 2016-01-13 20:31 UTC
please add the sass files to your meteor package.

**Comment by idmontie** [comment] 2016-01-29 18:30
Not a solution to this, but a workaround would be using the [poetic:materialize-scss](https://atmospherejs.com/poetic/materialize-scss) package.

**Comment by parthibanloganathan** [comment] 2016-02-10 00:16
Here's a work around I found. I your app is `myapp`, clone this repository into your Meteor app under a folder `myapp/packages`. Then you can modify the sass as you like. Namely, you can modify `sass/components/_variables.scss` to change default colors and what not.

Install [fourseven:scss](https://atmospherejs.com/fourseven/scss) to compile the sass you've modified.

Now modify the `package.js` file so that it uses fourseven:scss to recompile the sass.
1. Add `api.use('fourseven:scss');` in the `Package.onUse` function.
2. Load all the sass by adding the following to `api.addFiles`.
```
  api.addFiles([
    'dist/js/materialize.js',
    // Added custom
    'sass/components/_buttons.scss',
    'sass/components/_cards.scss',
    'sass/components/_carousel.scss',
    'sass/components/_chips.scss',
    'sass/components/_collapsible.scss',
    'sass/components/_color.scss',
    'sass/components/_dropdown.scss',
    'sass/components/_form.scss',
    'sass/components/_global.scss',
    'sass/components/_grid.scss',
    'sass/components/_icons-material-design.scss',
    'sass/components/_materialbox.scss',
    'sass/components/_mixins.scss',
    'sass/components/_modal.scss',
    'sass/components/_navbar.scss',
    'sass/components/_normalize.scss',
    'sass/components/_prefixer.scss',
    'sass/components/_preloader.scss',
    'sass/components/_roboto.scss',
    'sass/components/_sideNav.scss',
    'sass/components/_slider.scss',
    'sass/components/_table_of_contents.scss',
    'sass/components/_tabs.scss',
    'sass/components/_toast.scss',
    'sass/components/_tooltip.scss',
    'sass/components/_typography.scss',
    'sass/components/_variables.scss',
    'sass/components/_waves.scss',
    'sass/components/date_picker/_default.date.scss',
    'sass/components/date_picker/_default.scss',
    'sass/components/date_picker/_default.time.scss',
    'sass/materialize.scss',
    //
  ], 'client');
```

Change the name in `Package.describe` to something else like `name: 'materialize:materialize-custom'`.

Then run `meteor install materialize:materialize-custom` or whatever you named it.

To see a successful implementation of this, see my commit to a fork [here](https://github.com/parthibanloganathan/materialize-custom/commit/12817e8527d2eefa4330074f4f74e4fd59cf9a59)

**Comment by mitar** [comment] 2016-08-03 00:31
This issue is a duplicate of #1018.

**Closed** 2016-12-23 23:00 UTC
