### ISSUE TITLE
the last item in side-nav is hidden in Firefox

### ISSUE THREAD

**Issue by darkarchon** [Dogfalo/materialize#5123] opened 2017-08-17 18:38 UTC
## Expected Behavior

Then you open `#side-nav` you should see a scrolling panel and can scroll and see any item of this menu.

http://materializecss.com
http://materializecss.com/side-nav.html and this to, press the button **SIDE NAV DEMO**

## Current Behavior

When you have a side menu (#side-nav) bigger that window height of your browser, the last list item in Firefox browser (Android version to) is hiding from you))

## Possible Solution

...

## Steps to Reproduce (for bugs)

1. open Firefox and you need set browser height smaller then left sidebar menu.
2. then try to get the last menu item - **Themes *new**
3. the same thing is in mobile Firefox, at least on Android(try a landscape orientation)
4. even more, you see the penultimate item by 70%

## Your Environment

* Version used: current on web site and files v0.100.1
* Browser Name and version: Firefox 54.0.1 desktop, Firefox mobile 
* Operating System and version (desktop or mobile): Windows 10, Android v6, v5

**Comment by tomscholz** [comment] 2017-08-28 10:45
Duplicate of #2112

**Closed by tomscholz** 2017-08-28 10:45 UTC
Labels: component:SideNav
