### ISSUE TITLE
Collapsible Active (pre-selected) not working

### ISSUE THREAD

**Issue by hdwebpros** [Dogfalo/materialize#4519] opened 2017-04-10 21:31 UTC
### Description
Under "Preselected Section" on http://materializecss.com/collapsible.html is says to add `active` to the collapsible-header. That doesn't work. The 'active' class gets stripped out on load.

### Repro Steps
On Chrome, Chrome Incognito, Edge, and Firefox the page http://materializecss.com/collapsible.html shows the same effect.  Local instance of latest Materialize confirmed this.

http://codepen.io/anon/pen/WpVqKP 
*note: This is my first stab at a Codepen - be gentle*

**Comment by tomscholz** [comment] 2017-04-10 21:37
Duplicate of #4375
Fixed in b336331

**Closed by tomscholz** 2017-04-10 21:37 UTC
