### ISSUE TITLE
Click/Touch is not working on carousel item.

### ISSUE THREAD

**Issue by upreddy** [Dogfalo/materialize#4586] opened 2017-04-24 07:33 UTC
I want to use Fancybox on carousel images, Facybox will open image on touch/click on mobile devices. But materialize js preventing touch/click functionality in tap function (On mobile devices only). How can we use fancybox effects with materializecss?

**Comment by DanielRuf** [comment] 2017-04-24 07:47
Do not mix with other libraries/scripts which conflict with Materialize.

Materialize has its own MD spec lightbox http://materializecss.com/media.html

**Comment by upreddy** [comment] 2017-04-24 08:00
Thank you @DanielRuf . It's working fine. I am unable to zoom the image with MD spec lightbox. Other libraries like fancybox providing zoom, flip, rotate, etc..

**Comment by DanielRuf** [comment] 2017-04-24 08:04
Not sure if this should be possible by the MD spec.

Anyway, please fill out the issue template and provide a codepen so we can further discuss about this.

**Comment by DanielRuf** [comment] 2017-04-24 09:12
Afaik the click / touch event is captured by the carousel and not bubbling up / propagating.

**Comment by upreddy** [comment] 2017-04-24 09:17
If we comment e.preventDefault() line in tap() (line no. 7879 in materialize.js file), it will bubble up. I am using fancybox by commenting the same.

**Comment by DanielRuf** [comment] 2017-04-24 09:21
You mean https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L343?

This solves it and is the only needed change?

**Comment by upreddy** [comment] 2017-04-24 09:26
Yes. I am sorry to make you confused on line number.

**Comment by DanielRuf** [comment] 2017-04-24 09:57
No problem. You just mentioned the line number in the generated file, not in the actual source file of the component ;-)

**Comment by DanielRuf** [comment] 2017-05-22 05:57
Probably duplicate of https://github.com/Dogfalo/materialize/issues/4380

**Closed** 2017-05-22 08:07 UTC
Labels: component:Carousel, question, thirdparty
