### ISSUE TITLE
Decouple color variables and classes

### ISSUE THREAD

**Issue by bisubus** [Dogfalo/materialize#3743] opened 2016-10-07 08:02 UTC
Color variables and classes are packed into single file. This creates some design issues.

One issue is palette extension. Since the classes are generated from the palette in-place and they are generated with `@each` and not mixins, the only way to add additional colors or change existing ones is to paste `@each` blocks and run them again. In the case of changing existing colors this will result in dupe classes that should be treated with CSS cleaner.

Another one is using color variables outside of the framework (Web Components, Angular components). Importing `_color.scss` alone into component SCSS file to access colors with `color('red', 'base')` will result in ~30 Kb CSS overhead (unminified).

The suggestion is to divide `_color.scss` into `color/_palette.scss` (variables, functions, mixins that produce no output on import) and `color/_classes.scss`.

For compatibility reasons `_color.scss` may be kept in place:

```
@import "color/_palette.scss";
@import "color/_classes.scss";
```

**Comment by tomscholz** [comment] 2017-04-21 18:28
Duplicate of: https://github.com/Dogfalo/materialize/issues/3612
PR: https://github.com/Dogfalo/materialize/pull/4556

**Closed by tomscholz** 2017-04-21 18:28 UTC
Labels: enhancement, has-pr
