### ISSUE TITLE
Required option not working with 'materialized' selects?

### ISSUE THREAD

**Issue by neFAST** [Dogfalo/materialize#2536] opened 2015-12-23 08:25 UTC
Here is a demo page reproducing the issue: 
http://codepen.io/julienM/pen/mVEKRK

Submit once and you'll get the popup for the "browser default" <select>.
Then give a value to that <select> and submit again: no popup on the 2nd <select>
If you look at the logs:
An invalid form control with name='' is not focusable.

**Comment by TyrionGraphiste** [comment] 2015-12-24 09:47
Hi, I add the required attribute on the input when it's automatically generated. I'll synchronize the PR when I will have fixed another issue.
The fix is working on Firefox, but on Google Chrome, Opera there is the same issue you encountered.

On Safari and IE (< 10) there is simply no support.

**Comment by ferchoman09** [comment] 2016-02-24 22:43
I need 'The required' validation working in Google Chrome.

**Comment by stap123** [comment] 2016-10-09 18:50
This is also linked to #3440. I have posted a temporary workaround for anyone still struggling.

**Comment by neFAST** [comment] 2016-10-15 15:09
@stap123 Can you show a codepen demonstrating your fix?
I updated mine and, unless I misunderstood your suggestion, it doesn't work.
http://codepen.io/julienM/pen/mVEKRK

**Comment by Dogfalo** [comment] 2017-07-20 21:08
Fixed in dbdd869bc929cf124757eb22d3694dc5d746c7e0

**Closed by Dogfalo** 2017-07-20 21:08 UTC

**Comment by Jeroenkeesom** [comment] 2019-05-14 09:01
the problem is still here with V1.0.0, but when adding CSS to my own (s)css (as per Fixed in dbdd869) the issue is resolved. 
is this something i'm doing wrong?

**Comment by evansharp** [comment] 2020-03-26 22:31
Ditto the issue is still present. @JulienMaille codepen is exactly the issue I am encountering on v1.0.0.
