### ISSUE TITLE
Error using Materialize css with require

### ISSUE THREAD

**Issue by explorer2309** [Dogfalo/materialize#3667] opened 2016-09-16 22:13 UTC
I created a new project using durandal using its starter kit (http://durandaljs.com/get-started.html)

I then added materialize using bower (`bower install materialze`)

After adding materialize to require config of durandal

```
requirejs.config({
    paths: {
        'text': '../lib/require/text',
        'durandal':'../lib/durandal/js',
        'plugins' : '../lib/durandal/js/plugins',
        'transitions' : '../lib/durandal/js/transitions',
        'knockout': '../lib/knockout/knockout-3.1.0',
        'bootstrap': '../lib/bootstrap/js/bootstrap',
        'jquery': '../lib/jquery/jquery-1.9.1',
        'hammerjs': '../lib/hammer/hammer',
        'jquery.hammer': '../bower_components/materialize/js/jquery.hammer',
        'materialize': '../bower_components/materialize/dist/js/materialize'
    },
    shim: {
        'bootstrap': {
            deps: ['jquery'],
            exports: 'jquery'
        },
        'materialize': {
            deps: ['jquery', 'hammerjs']
        },
        'jquery.hammer': {
            deps: ['jquery', 'hammerjs', 'waves']
        }
    }
});

```

I end up in error - 
`Uncaught Error: Mismatched anonymous define() module: function ($, Hammer)`

Actually, every time I refresh, I end up with different errors, which seems to point me to something messed up with require. My question is - if everything works rock solid before adding materialize, how does adding it make things so flaky?

Am I doing something wrong?

**Comment by tomscholz** [comment] 2017-04-02 22:04
Is this a duplicate of https://github.com/Dogfalo/materialize/issues/3011, https://github.com/Dogfalo/materialize/issues/4012, https://github.com/Dogfalo/materialize/issues/923, https://github.com/Dogfalo/materialize/issues/1422, https://github.com/Dogfalo/materialize/issues/1773

Can you give feedback if some or all of these issues are duplicates? That would be pretty neat

**Closed** 2017-04-05 14:27 UTC
