### ISSUE TITLE
materializecss v1.0

### ISSUE THREAD

**Issue by onion878** [Dogfalo/materialize#5363] opened 2017-11-15 01:59 UTC
![1](https://user-images.githubusercontent.com/25260101/32814828-99ee8d64-c9eb-11e7-944a-ce15e0b0e202.png)

**Comment by DanielRuf** [comment] 2017-11-15 21:33
Can not reproduce. Please check the console of the developer tools in your browser.

**Comment by DanielRuf** [comment] 2017-11-15 21:34
Possibly related to https://github.com/Dogfalo/materialize/issues/5352

**Comment by Dogfalo** [comment] 2017-11-21 06:06
Duplicate of #5352

**Closed by Dogfalo** 2017-11-21 06:06 UTC
