### ISSUE TITLE
Sidenav is not clickable (greyed out)

### ISSUE THREAD

**Issue by itggot-arvid-nilber** [Dogfalo/materialize#4349] opened 2017-03-14 20:45 UTC
### Description
Hi. The sidenav doesn't work at all. It's just greyed out and nothing is clickable.

Have any of you had this issue before?

I have all the latest files.

### Repro Steps
When smaller width click on the menu icon.

### Screenshots / Codepen
https://gyazo.com/2602336c4713934aeeb8d8bcc8c668e8

http://codepen.io/anon/pen/gmxeBK

**Comment by tomscholz** [comment] 2017-03-15 15:40
Duplicate of https://github.com/Dogfalo/materialize/issues/3844 . You will find the solution there

**Closed** 2017-04-02 01:06 UTC
