### ISSUE TITLE
select multiple close on ipad

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#2319] opened 2015-11-17 12:36 UTC
if you open a multiple select on an ipad, you can select multiple options, but it is not possible to close it unless you open another select or set focus on an input field

**Comment by TyrionGraphiste** [comment] 2015-11-17 13:04
Hi,

I don't have issue on my iPad, can you itemize your environnement ?

**Comment by philipraets** [comment] 2015-11-19 08:07
I just went to http://materializecss.com and tried the different selects on ipad. The "normal" ones I can close by tapping on a disabled option, but the multiple select stays open.
Also if you just tap outside the selects, the selects stay open.

This is on an ipad retina with ios 9.1

On android, they close if you tap outside the selects.

**Comment by acburst** [comment] 2015-11-24 01:44
Yes, I've reproduced this on my iPad, I'm thinking we need to add some event listener for tap or look for some way to support touch device defocuses.

**Comment by rossrankin** [comment] 2016-11-25 10:28
This issue is still happening, it works fine on Android but iOS will not tap off.

**Comment by Thanood** [comment] 2016-11-25 11:17
The tap out is only reacting to `click` events which doesn't seem to be fired on iPad/iPhone.
This seems to work if you add a `touchstart` event handler or "redirect" `touchstart` to `click` (that is, fire a click event on touchstart events).

**Comment by lodow** [comment] 2017-01-27 11:09
I have the same issue on iOS. Do you have any update about it ?

**Comment by rossrankin** [comment] 2017-01-27 13:26
There's no proper fix but you can add the class 'browser default' to the input to get it working. 

This is explained about 1/3 of the way down this page: http://materializecss.com/forms.html

**Comment by tomscholz** [comment] 2017-07-08 19:56
Can anyone check if this issue is still present in`v0.99.0`?

**Comment by guicara** [comment] 2017-08-03 11:33
Yes, this issue is still present in `v0.99.0`.

**Comment by sokolmarek** [comment] 2017-08-13 20:02
Hey guys this code should fix the problem with multiple select and closing it on iOS devices.

```javascript
 $(document).on('touchstart', function (e) {
        let target = $(e.target);
        if (!target.is("span")) { //checking if you are tapping on items in multiple select or not
            $(document).trigger('click'); //if you are tapping outside multiple select close it
            $(':focus').blur(); //focus out for multiple select so you can choose another or the same (in case you have more multiple selects on page)
        } else {
            //nothing or fire another event
        };
    });
```

This works for me.

**Comment by Dogfalo** [comment] 2018-02-10 02:55
Fixed in v1-dev

**Closed by Dogfalo** 2018-02-10 02:55 UTC
Labels: component:Select
