### ISSUE TITLE
Method to remove `Toasts` manually?

### ISSUE THREAD

**Issue by hanfeisun** [Dogfalo/materialize#1591] opened 2015-06-25 08:03 UTC
I want to keep a toast visible until a custom event is triggered. I want to remove one of the "Toasts" manually in the callback of that event..

However, I didn't find a way to remove one toast manually in MaterializeCSS.

**Comment by Dogfalo** [comment] 2015-06-26 02:32
Duplicate of #1317

**Closed by Dogfalo** 2015-06-26 02:32 UTC
