### ISSUE TITLE
Error: Cannot find module './picker.js'

### ISSUE THREAD

**Issue by faebeee** [Dogfalo/materialize#4411] opened 2017-03-27 07:29 UTC
### Description
Hi,

I installed materializse-css via NPM to use it's api in my Vue components. But when I try to run it through browserify I get 
`Error: Cannot find module './picker.js' from '***/node_modules/materialize-css/bin'`

```
"materialize-css": "^0.97.8",
"browserify": "^13.1.0",
```

### Repro Steps

I created a repo to reproduce it [`git@github.com:faebeee/vueapp-skeleton.git`](https://github.com/faebeee/vueapp-skeleton/tree/materialize) use the branch `materialize`

**Comment by tomscholz** [comment] 2017-03-27 12:19
Duplicate of https://github.com/Dogfalo/materialize/issues/3139. Please close

**Closed** 2017-03-27 12:31 UTC
