### ISSUE TITLE
Floating Action Button doesn't close on mobile

### ISSUE THREAD

**Issue by supadupdip** [Dogfalo/materialize#1500] opened 2015-06-10 03:31 UTC
Looks like the method that the floating action button uses to be triggered is onmouseenter or mouse over and the mouse leave event to close. This seems to present an issue on mobile devices where upon triggering the action button it expands correctly but does not dismiss when another part of the screen is clicked or even when the action button is clicked. Should have some functionality to either manually close the action buttons or to dismiss when other activity is detected.

**Comment by Dogfalo** [comment] 2015-06-11 05:13
Duplicate of #963

**Closed by Dogfalo** 2015-06-11 05:13 UTC
