### ISSUE TITLE
width of navbar with sidenav not properly recalculated

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#4534] opened 2017-04-12 22:17 UTC
### Description
When opening the sidenav of a navbar, the width of the navbar is not recalculated.

### Repro Steps
Create a navbar with a sidenav, open the sidenav in a small view with vertical scrollbars due to long content.
You will see a gap on the right side.

Now make the window a bit wider, the gap grows.

### Screenshots / Codepen
https://codepen.io/anon/pen/BRaJeg

![image](https://cloud.githubusercontent.com/assets/827205/24981700/2fe45442-1fde-11e7-9a54-2bba0f0234ae.png)

![image](https://cloud.githubusercontent.com/assets/827205/24981725/40f75cde-1fde-11e7-9f1f-a45aa874e283.png)

**Comment by DanielRuf** [comment] 2017-04-12 22:18
See #4533 and https://codepen.io/anon/pen/gWOvYy, this works better with vertical scrollbars

**Comment by fega** [comment] 2017-04-13 13:18
Duplicate of #3453

**Closed by fega** 2017-04-13 13:18 UTC
