### ISSUE TITLE
Carousel-Item href or click event listener not being triggered.

### ISSUE THREAD

**Issue by SamWillson** [Dogfalo/materialize#4704] opened 2017-05-17 23:30 UTC
### Description
I am currently working on an app using carousel.
Below here is a general anchor tag in the carousel.
`<a class="carousel-item" id="carouselLink" href="show.html"><img src="assets/images/hosted/{}"></a>`
If you see the href is to a page called show.html. But when I click the image it just does not go to the page. So I added a click eventListener through jQuery. Even that is being not triggered. Is there any way I can add links to the carousel-item.

**Comment by DanielRuf** [comment] 2017-05-18 09:10
Please provide a codepen. Generally click should work when the image is in the center / selected.

**Comment by SamWillson** [comment] 2017-05-18 11:19
I did make a pen - https://codepen.io/sampan/pen/BROEdp .
The carousel was working there so I though wheres the problem then, I figured the problem. Dont worry, its still there.
The links works fine on computers. But they dont work on mobiles. I switched to mobile view and it the links stop working. When switch to desktop view, they start working. I checked mobile view on code pen, turns out they don't have any mobile support.

**Comment by DavisMiculis** [comment] 2017-05-19 07:19
Duplicate of #4380

**Comment by DanielRuf** [comment] 2017-05-19 08:04
Seems so. The change should be reverted.

**Comment by SamWillson** [comment] 2017-05-20 12:41
Actually yes. #4380 does solved my problem. Someone please merge/close/delete this issue. And sone should remove the line in materialize.js which e.preventDefault(). helps alot. Thanks.

**Closed** 2017-05-20 15:18 UTC
Labels: component:Carousel
