### ISSUE TITLE
(Request) Alerts for contextual feedback

### ISSUE THREAD

**Issue by jzetina** [Dogfalo/materialize#514] opened 2015-01-22 16:21 UTC
I guess toasts are a great way to give users feedback at some points, but I think it would be useful to have some static color alerts also, like the ones in http://getbootstrap.com/components/#alerts

**Comment by Dogfalo** [comment] 2015-01-22 17:09
Duplicate of #389

**Closed by Dogfalo** 2015-01-22 17:09 UTC
