### ISSUE TITLE
Material Select blinking on iOS

### ISSUE THREAD

**Issue by brandflownet** [Dogfalo/materialize#3479] opened 2016-08-09 12:13 UTC
I am trying to create my website in Material Design, however I found one issue with Material Select. It is  working fine on Windows/OSX/Android , however for some reason when I open Material Select component on my iPad and click on it, there is a blinking cursor showing from the Background of the Dropdown.

Screen [http://laesserundpartner.ch/files/cache/select.png](url)

**Comment by ziracmo** [comment] 2016-08-09 14:01
The screen doesn't work

**Comment by brandflownet** [comment] 2016-08-09 14:04
Copy paste URL to browser address bar, it will work

**Comment by TyrionGraphiste** [comment] 2016-08-09 14:05
It's a duplicate issue. There is the same on IE.

**Comment by ammichael** [comment] 2016-08-30 00:16
Can you link it? Couldn't find.

**Comment by Dogfalo** [comment] 2016-10-15 21:35
Duplicate of #630

**Closed by Dogfalo** 2016-10-15 21:35 UTC
