### ISSUE TITLE
DatePicker is alway opening

### ISSUE THREAD

**Issue by dracot25** [Dogfalo/materialize#2179] opened 2015-10-19 20:52 UTC
I don't know if it is a wrong behavor, but it is really annoying.
I'm using the version 0.97.1. When I click onto the date picker works well, but if I change of screen or I open another software or whatever, and I come back to my project, the DatePicker is fires up again without any click onto the input. I think this is because I'm steel in the input as a focus.

**Comment by Charpeni** [comment] 2015-10-22 15:36
Duplicate of #2067.

**Closed** 2015-10-22 15:39 UTC
