### ISSUE TITLE
background-color breaks Parallax

### ISSUE THREAD

**Issue by omin** [Dogfalo/materialize#1732] opened 2015-07-14 22:57 UTC
I'm trying to use Parallax on my landing page while having a sticky footer; however, I have light grey background and the sticky footer fills up the remaining space with white. In order to match this, I added light grey `background-color` to `<main>` but this breaks parallax.

**Comment by acburst** [comment] 2015-07-15 17:15
Can you post a codepen?

**Comment by OminStyle** [comment] 2015-07-15 17:37
Of course :)

https://jsfiddle.net/OminStyle/5hrpcp1j/

**Comment by acburst** [comment] 2015-07-19 23:36
The issue I think is with your flexbox styles

**Comment by OminStyle** [comment] 2015-07-20 05:01
The styles are from http://materializecss.com/footer.html.

**Comment by Cypher1** [comment] 2016-10-13 01:26
This still is an issue. Anyone have a fix?

**Comment by tomscholz** [comment] 2017-04-01 13:45
I can't seem to reproduce it. I close this issue for now. If anyone post a codepen that can reproduce the issue we can reopen.

**Closed by tomscholz** 2017-04-01 13:45 UTC

**Comment by Xandaros** [comment] 2019-12-06 02:44
I just ran into this issue. We had `background-color` set for html, body and main. Turns out, if you set a background colour on both html and body, it doesn't show properly: https://codepen.io/Xandaros/pen/MWYwRYy

Funnily enough, this seems to only affect the first parallax on the page (though I can't reproduce that behaviour in codepen). Took me absolute ages to debug.
Setting it on either html or body, but not both, also causes no issues.

**Comment by supergnaw** [comment] 2020-04-10 23:07
I also had this issue, but for all .parallax-container divs instead of just the first. I tried applying the background color classes to various things per this thread without success. The fix for me was changing the z-index of the .parallax-container because the background image of the .parallax-container was being shifted behind the parent div somehow. I hope this helps someone in the future.
