### ISSUE TITLE
CloseOnClick property in sideNav should only be applicable in small screen when menu is usually hidden.

### ISSUE THREAD

**Issue by ancientdemon** [Dogfalo/materialize#2520] opened 2015-12-21 19:29 UTC
Consider the following html

![image](https://cloud.githubusercontent.com/assets/15957098/11509371/bdf13336-982b-11e5-88eb-93bd8fae3916.png)

Here I have specified 'fixed' style which keeps the sideNav fixed for larger screens and it hides the sideNav for smaller screens. This works as expected. However, issues is that I want the sideNav to close upon clicking a menu option and hence I am also doing this in code.

![image](https://cloud.githubusercontent.com/assets/15957098/11509770/134a9550-982e-11e5-80a2-dac7ed9d12b7.png)

My expectation is that closeOnClick: true is only applicale to the small screen, where menu is usually hidden by default. I don't want the menu to close upon click in larger screens (since I have used "fixed" style). Therefore the logic in materialize-css javaScripts should be fixed to use closeOnClick: true will not affect the "fixed" behavior.

Due to its current behaviour in larger (non mobile) screens where hamburger icon is not visible, the closing of the menu means there is no way that user can get back to the menu again.

**Comment by Thanood** [comment] 2016-02-01 15:18
I agree with that. It would be really good if ```closeOnClick``` only closed a fixed menu if it's displayed on a small screen.

**Comment by ancientdemon** [comment] 2016-02-01 19:16
Related issue

fixed sidenav with closeOnClick enabled #1426

**Comment by jacek213** [comment] 2016-05-09 12:48
+1

**Comment by Nick-Riggs** [comment] 2016-06-16 20:15
This is resolved in this PR. Would be nice to see it merged: 

https://github.com/Dogfalo/materialize/pull/945

**Comment by chobo2** [comment] 2016-08-15 23:54
would like to see this fix as well. Makes no sense the way it is right now.

**Comment by RyanThomasMusser** [comment] 2016-08-16 00:11
+1

**Comment by tomscholz** [comment] 2017-04-18 11:00
Duplicate of https://github.com/Dogfalo/materialize/issues/1426

**Closed by tomscholz** 2017-04-18 11:00 UTC
