### ISSUE TITLE
Badges are not properly shown in collapsibles after commit "Added better support for multi line collapsible headers"

### ISSUE THREAD

**Issue by jeroenqui** [Dogfalo/materialize#5016] opened 2017-07-24 08:49 UTC
## Expected Behavior
Badges are properly aligned like this example in v0.99.0
https://codepen.io/jeroenqui/pen/vJYmea

## Current Behavior
Badges are not properly aligned
https://codepen.io/jeroenqui/pen/rzNmom

## Possible Solution
Fixing this commit:
https://github.com/Dogfalo/materialize/commit/aae7e6fda6edf640b6bfa012c386ec2cc0bfc643

## Steps to Reproduce (for bugs)
See the above examples

## Context
This happened when I was upgrading sources from v0.99.0 to v0.100.1

## Your Environment
* Version used: v0.100.1
* Browser Name and version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): Windows 10 Desktop
* Link to your project (if appropriate): -

**Comment by DanielRuf** [comment] 2017-07-24 21:16
The problem is that collapsible-header has now `padding: 1rem`. So far nothing wrong here.

**Comment by DanielRuf** [comment] 2017-07-24 21:17
![image](https://user-images.githubusercontent.com/827205/28545149-2a8786ca-70c6-11e7-850f-003b298fe1f6.png)

![image](https://user-images.githubusercontent.com/827205/28545161-3926251a-70c6-11e7-8c0b-9e33914331cf.png)

**Comment by acburst** [comment] 2017-07-24 22:59
Fixed in b3fe2a7b

**Closed by acburst** 2017-07-24 22:59 UTC
Labels: component:Badges
