### ISSUE TITLE
Select discrepancies inside a modal on version 0.97.6

### ISSUE THREAD

**Issue by w0rldart** [Dogfalo/materialize#3894] opened 2016-11-09 16:03 UTC
Trying to add a select dropdown inside a modal window, does not behave as expected, as it cuts to whatever the remaining height is left from it to the end of the modal.

Issue has been replicated on both latest version of Firefox and Chrome.

Don't know if there's a fix in 0.97.7 or 0.97.8 for this, but if there is, what is it and what are the guidelines to patch 0.97.6, as an upgrade is not plausible right now.

![control panel](https://cloud.githubusercontent.com/assets/673081/20144665/2ffd2f52-a695-11e6-89c4-138082e394fb.png)

**Comment by seanmavley** [comment] 2016-11-12 22:41
When you scroll down the content in the modal window, does the dropdown not show?

**Comment by Dmitrev** [comment] 2016-11-18 14:48
Same issue here. The problem is that `<ul>` that generates the actual dropdown should be placed outside the actual modal, so it can be viewed properly on top of the modal.

This cannot be worked around with CSS, the modal positioning needs to be refactored.

For now you can fallback to browser default inside a modal. Use the css-class `browser-default` on your select element

**Comment by AustP** [comment] 2017-01-23 23:09
I just ran into this issue as well. Not only does this happen with selects but the datepicker widget as well.

**Comment by fega** [comment] 2017-04-14 18:30
Duplicate of #1385

**Closed by fega** 2017-04-14 18:30 UTC
