### ISSUE TITLE
Adding an 'active' class to the header of a collapsible, does not make it 'active'

### ISSUE THREAD

**Issue by tdecoy** [Dogfalo/materialize#4513] opened 2017-04-07 14:50 UTC
Pretty straight forward:

http://materializecss.com/collapsible.html stipulates:

> **Preselected Section**
If you want a collapsible with a preopened section just add the active class to the collapsible-header. 

With an example of:

`<div class="collapsible-header active"><i class="mdi-maps-place"></i>Second</div>`

However, adding this does nothing. The "active" collapsible isn't active/expanded on page load. However, clicking it does expand it and adds the required 'active' class in the DOM.

Could it be that Materialize strips the class if pre-added?

**Comment by fega** [comment] 2017-04-07 16:20
This is visible in the documentation example

**Comment by tdecoy** [comment] 2017-04-07 19:06
What do you mean it's visible?

It isn't visible from where I'm sitting: https://i.imgur.com/RouPxt9.png

**Comment by fega** [comment] 2017-04-07 19:08
Sorry I didn't express what I tried, I should say

"This problem is visible in the documentation example"

**Comment by acburst** [comment] 2017-04-07 19:51
Duplicate of #4375

**Comment by tomscholz** [comment] 2017-04-07 19:55
Will be fixed with the next release

**Closed by tomscholz** 2017-04-07 19:55 UTC
Labels: bug

**Comment by alan19031216** [comment] 2018-06-20 00:57
<li class="active">
                   <div class="collapsible-header active"><i class="material-icons">face</i>User detail</div>
                   <div class="collapsible-body">
</li>

Don't forgot put "active" in first div class.
