### ISSUE TITLE
Materialize Multiple Select Bug (in mobile)

### ISSUE THREAD

**Issue by hklsk** [Dogfalo/materialize#3501] opened 2016-08-11 18:19 UTC
When user open the select box, the readonly input will become focus. Although the select drop down normally, user cannot dismiss the multiple select box tapping outside the select box.

Tested in safari iOS 9.3.3 and Chrome iOS

**Comment by imgntn** [comment] 2016-12-06 21:50
this is easily reproducible by visiting the multiple select demo from a mobile phone (iphone 5s in my case)

**Comment by Thanood** [comment] 2016-12-06 22:44
When I understand this correctly, this may be a workaround:  https://github.com/Dogfalo/materialize/issues/3790

Also, redirect touchstart events to trigger a click on iOS.
That is something like:
```javascript
$(document).on('touchstart', function(e) { $(document).trigger('click'); });
```

**Comment by b-z** [comment] 2017-04-06 07:32
+1, multiple select does not work on ios safari.
but demo works: http://materializecss.com/forms.html
: (

**Comment by b-z** [comment] 2017-04-06 07:36
hey all, 
**this bug has already been fixed in the newest version(2017/3/21).**

**Closed** 2017-04-06 07:42 UTC

**Comment by PortableStick** [comment] 2017-05-30 21:37
I have this problem on Materialize 0.98.2.  It's present on a project I'm working on, but I get the same thing when visiting the demo page on my iPhone.

**Comment by sokolmarek** [comment] 2017-08-13 19:56
Hey guys this code should fix the problem with multiple select and closing it on iOS devices.

`    $(document).on('touchstart', function (e) {
        let target = $(e.target);
        if (!target.is("span")) { //checking if you are tapping on items in multiple select or not
            $(document).trigger('click'); //if you are tapping outside multiple select close it
            $(':focus').blur(); //focus out for multiple select so you can choose another or the same (in case you have more multiple selects on page)
        } else {
            //nic
        };
    });`

This works for me.
