### ISSUE TITLE
Meteor.js: Use SASS library

### ISSUE THREAD

**Issue by artshostak** [Dogfalo/materialize#1867] opened 2015-08-06 22:16 UTC
The Meteor.js library uses the straight up .css stylesheet which doesn't allow control over any of the library's variables. Any chance a future release will begin to utilize the SASS library? Would be a huge improvement.

**Comment by Dogfalo** [comment] 2015-08-06 23:29
Duplicate of #1018

**Closed by Dogfalo** 2015-08-06 23:29 UTC
