### ISSUE TITLE
Cannot read property 'toast' of undefined

### ISSUE THREAD

**Issue by kmligue** [Dogfalo/materialize#1095] opened 2015-04-04 04:57 UTC
I am now on version 0.96.0 and i get this error:

```
Exception in delivering result of invoking 'login': TypeError: Cannot read property 'toast' of undefined
    at http://localhost:3000/client/views/login/login.js?ec848739a05f616b7effde4c60e042033392692d:25:16
    at Accounts.callLoginMethod.userCallback (http://localhost:3000/packages/accounts-password.js?3845cc71ad2dc1378b7d8cc4164a78359506dd40:89:21)
    at http://localhost:3000/packages/accounts-base.js?7c29db5c21a76726509bb6bb2a68a2b4b1ecf657:531:26
    at http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:801:19
    at loggedInAndDataReadyCallback (http://localhost:3000/packages/accounts-base.js?7c29db5c21a76726509bb6bb2a68a2b4b1ecf657:628:7)
    at null._callback (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:22)
    at _.extend._maybeInvokeCallback (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3860:12)
    at _.extend.receiveResult (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3880:10)
    at _.extend._livedata_result (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4964:9)
    at onMessage (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3725:12)
```

**Comment by ganySA** [comment] 2015-04-04 05:29
Hi

I assume this is meteor? Please have a look at  my post #1094 . This is because how the Materlialize namespace is defined.

You have a few options to fix this:
1) you remove the materlialize package and add the materlize files yourself into the compatibility folders (schlep)
2) you can duplicate the materialize code and make Materialize namespace a global or into your own functions (i am doing this for the meantime - its only really for toast)


Cheers

**Comment by Dogfalo** [comment] 2015-04-04 05:35
Duplicate of #1094

**Closed by Dogfalo** 2015-04-04 05:35 UTC

**Comment by kmligue** [comment] 2015-04-04 05:42
tnx @ganySA . I use the number 2 fix.
