### ISSUE TITLE
Select tag is not able to select after scrolling

### ISSUE THREAD

**Issue by genelim** [Dogfalo/materialize#2436] opened 2015-12-07 08:49 UTC
Used the Select form and every is working well except after the select tag scrollbar appears when more items is added.

After scrolling, it is not able to select anymore. 

Did the code in JSFIDDLE. What am I missing here?

http://jsfiddle.net/8rmjymtr/5/

**Comment by dennisdenden** [comment] 2015-12-07 08:57
Hi. I was having the same problem with this as well. Please provide a solution for it. Thank you

**Comment by TyrionGraphiste** [comment] 2015-12-07 09:35
First you missed to add the <div class="row"></div> after the div with id #modal1.
This issue is already known but not fixed yet, all options which are not visible can not be selected

**Comment by dennis1804** [comment] 2015-12-07 09:52
I kinda fixed it but i have no idea why.

Just added
```style
.dropdown-content     {max-height:300px !important;}
```

and it worked.

**Comment by genelim** [comment] 2015-12-07 10:03
Noted about the ID, Tyrion. Hoping for it to be fixed.

Dennis, what happen if the content is more than 300px? Is there a dynamic way to load it? Unless writing my own script to fix it first before the update

**Comment by dennis1804** [comment] 2015-12-07 10:06
idk, maybe it works with higher values as wel.

**Comment by ldidry** [comment] 2015-12-07 12:09
It seems to be a duplicate of #2309, isn't it?

**Comment by TyrionGraphiste** [comment] 2015-12-07 12:52
It is.

**Comment by genelim** [comment] 2015-12-08 01:21
Thank you for the redirect of #2309

**Comment by ldidry** [comment] 2015-12-08 02:07
You're welcome :wink:

**Comment by ProfNandaa** [comment] 2015-12-10 18:16
Do we close this then? Since #2309 was fixed by [8600af5](https://github.com/Dogfalo/materialize/commit/8600af568a548d6ac5a0e3f5ee3a24da0093c564)

**Comment by TyrionGraphiste** [comment] 2015-12-29 05:05
This issue isn't fixed in this example (tab result) : http://jsfiddle.net/TyrionGraphiste/ccw7ygLc/2/embedded/

If you resize the browser with a little height, you shouldn't be able to select an option by clicking. This isn't working for single select, but the case doesn't appears for multiple select.

**Comment by m00k1e** [comment] 2016-04-21 20:26
Hello!

 

New message, please read <http://www.italiangolfqld.com.au/tone.php?h1lps>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment] 2016-04-21 20:28
Hello!

 

New message, please read <http://sawmillcreekterriers.com/protest.php?5qj>

 

hello@mookiecreative.com

**Comment by fega** [comment] 2017-05-07 18:37
It looks fixed in the latest version

**Closed by fega** 2017-05-07 18:37 UTC
