### ISSUE TITLE
How to disable waves effects on mobile while scrolling / dragging?

### ISSUE THREAD

**Issue by xstortionist** [Dogfalo/materialize#4183] opened 2017-02-04 09:58 UTC
Is there a way to disable waves effects on buttons while scrolling down a page on a mobile device? To me, it looks like it may cause user experience issues, where if you click on a button and scroll down it may look like they have clicked button due to the ripple effect.

**Comment by Dogfalo** [comment] 2017-02-05 18:38
Duplicate of #4027

**Closed by Dogfalo** 2017-02-05 18:38 UTC
