### ISSUE TITLE
Allow combining of materialboxed and slider

### ISSUE THREAD

**Issue by MarkusH** [Dogfalo/materialize#1197] opened 2015-04-20 16:15 UTC
Right now, when clicking on an image inside a slider, not the actual image is resized but the placeholder image.

Version: Materialize v0.96.1

```html
<div class="slider">
    <ul class="slides">
        <li>
            <img class="materialboxed" src="http://lorempixel.com/580/250/nature/1"> <!-- random image -->
            <div class="caption center-align">
                <h3>This is our big Tagline!</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img class="materialboxed" src="http://lorempixel.com/580/250/nature/2"> <!-- random image -->
            <div class="caption left-align">
                <h3>Left Aligned Caption</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img class="materialboxed" src="http://lorempixel.com/580/250/nature/3"> <!-- random image -->
            <div class="caption right-align">
                <h3>Right Aligned Caption</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img class="materialboxed" src="http://lorempixel.com/580/250/nature/4"> <!-- random image -->
            <div class="caption center-align">
                <h3>This is our big Tagline!</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
    </ul>
</div>


<!--  Scripts-->
<script>
    $(document).ready(function(){
        $('.slider').slider();
    });
</script>
```

**Comment by Dogfalo** [comment] 2015-04-20 16:38
Duplicate of #543

**Closed by Dogfalo** 2015-04-20 16:38 UTC

**Comment by MarkusH** [comment] 2015-04-20 16:43
Ah, my bad. Thanks for pointing me to the right issue.
