### ISSUE TITLE
[Enhancement] Fixed action button with labels

### ISSUE THREAD

**Issue by Clemzd** [Dogfalo/materialize#3259] opened 2016-06-15 07:54 UTC
The fixed action button in the framework is very good and works well.
![image](https://cloud.githubusercontent.com/assets/4448250/16072029/e5d99502-32de-11e6-9c1d-4d827bdcfabe.png)

Unfortunately, it does not give the possibility to add labels and sometimes the action below buttons could be ambigious.

Here is an example in google calendar. In addition, it creates an overlay.
![image](https://cloud.githubusercontent.com/assets/4448250/16072082/431a243e-32df-11e6-9380-bd241c7f733c.png)

As a workaround, I've create a fixed action button which opens a dropdown. That does not respect google material design but it has a well rendering.

**Comment by Nohinn** [comment] 2016-06-15 11:11
You could apply as well a tooltip (from MaterializeCSS) to the buttons with the text you want to show.

**Comment by Clemzd** [comment] 2016-06-15 14:15
But to see the content of a tooltip on mobile you have to click on the button?
And if you click the action is launched?
So it can't work

**Comment by philipraets** [comment] 2016-06-15 14:25
Here are some suggestions:
#963 

I use this one:
[http://codepen.io/anon/pen/rxMXob](http://codepen.io/anon/pen/rxMXob)

**Comment by Nohinn** [comment] 2016-06-15 14:30
No, there's no need to click on it, you should put your finger on it like if you were doing a mousedown, and the tooltip will show without launching the action.
https://codepen.io/Nohinn/full/GqqqQL

**Comment by Clemzd** [comment] 2016-06-16 13:31
Oh nice, too bad I did not find that before. But I like this one : http://codepen.io/anon/pen/rxMXob

**Comment by tomscholz** [comment] 2017-04-03 10:11
Duplicate of https://github.com/Dogfalo/materialize/issues/963

**Closed by tomscholz** 2017-04-03 10:11 UTC
