### ISSUE TITLE
Collapsible .active header not working

### ISSUE THREAD

**Issue by NonameSLdev** [Dogfalo/materialize#4537] opened 2017-04-13 10:38 UTC
### Description
Collapsible `.active` selector doesn't work. Ever. More info from the codepen:
 > Excuse me for my messy code. The html is copied from the docs. Anyways, as you can see here, the "active" selector only works if I copy the exact same code from the materialize library and put it as if I implemented it now (the code in js is the code from collapsible.js). Try to comment the js out and see that it doesn't work. This is the exact same code from collapsible.js from the materialize library, no changes applied.

I checked and the open method in collapsible.js does run. When I ran collapsible.js manually it worked fine.

### Repro Steps
http://codepen.io/NonameSL/pen/pPoYop

**Comment by aminnairi** [comment] 2017-04-13 12:13
I confirm this bug happened to me as well as for others.

**Comment by bassie1995** [comment] 2017-04-13 12:17
Duplicate of #4375, they fixed it already.

For further reference, see the [other issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20collapsible).

**Comment by tomscholz** [comment] 2017-04-13 12:18
https://github.com/Dogfalo/materialize/issues/4519
https://github.com/Dogfalo/materialize/issues/4518
https://github.com/Dogfalo/materialize/issues/4513
https://github.com/Dogfalo/materialize/issues/4476
https://github.com/Dogfalo/materialize/issues/4468
#4375

**Closed by tomscholz** 2017-04-13 12:18 UTC

**Comment by NonameSLdev** [comment] 2017-04-13 12:38
@tomscholz Oh. Apologies.
