### ISSUE TITLE
Bug with the class on NavBar "navbar-fixed"

### ISSUE THREAD

**Issue by CodingWeb** [Dogfalo/materialize#5047] opened 2017-07-30 19:00 UTC
Good evening,

I have a bug on the NavBar Mobile Collapse, which appears when you add the class `"navbar-fixed"`, the left pane becomes all grayed out, and you can not select any link Below, and I've linked you live

You can see it in the screenshot below, and in the [**link**](http://dev-apprendreensemble.com/node_modules/), which leads directly to the bug
![bug](https://user-images.githubusercontent.com/12551504/28756003-d37be1c8-7566-11e7-9f8c-1eb9dab1ab1c.PNG)

And here is a screenshot without the class `"navbar-fixed"` there is no problem, so I guess the bug vient of the class `"navbar-fixed"`, I put a screenshot below.
![no-bug](https://user-images.githubusercontent.com/12551504/28755996-b5006354-7566-11e7-8b7f-2d38c10eb488.PNG)

You can see the bug, live on this [link](http://dev-apprendreensemble.com/node_modules/), with the code below.
```
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo">Logo</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a href="mobile.html">Mobile</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a href="mobile.html">Mobile</a></li>
            </ul>
        </div>
    </nav>
</div>

```

See you soon.

**Comment by DanielRuf** [comment] 2017-07-30 21:21
Try to move the sidenav ul outside of its wrappers.

**Comment by tomscholz** [comment] 2017-07-30 21:39
Duplicate of https://github.com/Dogfalo/materialize/issues/3844

**Closed** 2017-07-30 21:39 UTC

**Comment by CodingWeb** [comment] 2017-07-31 15:20
>  tomscholz marked this as a duplicate of #3844 18 hours ago

For what not to correct it since version 0.9.7 it has no way?

**Comment by DanielRuf** [comment] 2017-07-31 16:08
@tomscholz, myself and some others joined as contributors this year. The best solution has to be found but there are more things to be done than this. PR's are very welcome.
