### ISSUE TITLE
href button get white.

### ISSUE THREAD

**Issue by qblol** [Dogfalo/materialize#4344] opened 2017-03-14 08:52 UTC
### Description
href button get white when clicked rapidly and dragged

### Screenshots / Codepen
![screen shot 2017-03-14 at 3 39 35 pm](https://cloud.githubusercontent.com/assets/8578170/23892681/2e63e79e-08ce-11e7-9b59-cfcac94dc3ec.png)

**Comment by Supremex** [comment] 2017-03-17 13:02
Who even does that? And what is exactly the problem?

**Comment by tomscholz** [comment] 2017-03-27 15:00
Very old bug. No Fix avaliable. Duplicate of https://github.com/Dogfalo/materialize/issues/686

**Comment by tomscholz** [comment] 2017-03-27 15:01
Or lets just say, its the same problem

**Comment by DanielRuf** [comment] 2017-04-01 14:09
Clicking multiple times applies the wave effect multiple times and combines the white effect.

**Comment by DanielRuf** [comment] 2017-04-01 14:48
Please test #4472.

**Comment by DanielRuf** [comment] 2017-04-01 17:39
When moving left or right while clicking very fast starts a drag event. While dragging, the (last) ripples are still applied. The new PR should improve / fix this.

**Comment by tomscholz** [comment] 2017-04-07 19:52
Duplicate of https://github.com/Dogfalo/materialize/issues/2667

**Closed by tomscholz** 2017-04-07 19:52 UTC
