### ISSUE TITLE
Allow to programmatically init all the framework elements

### ISSUE THREAD

**Issue by 255kb** [Dogfalo/materialize#410] opened 2015-01-07 09:18 UTC
Hi, I am using Materialize with Meteor and since materialize.js file is loaded automatically and initialized before the content has been rendered some components does not work (waves for example). 

It is possible to "re-enable" such components as soon as the DOM element has been rendered using the Template.rendered function of Meteor, for example: 

    Template.tasks.rendered = function(){
        Waves.displayEffect();
     };

Maybe the doc could explain how to programmatically/manually enable all the framework components.

**Comment by Dogfalo** [comment] 2015-01-07 15:19
duplicate of #250

**Closed by Dogfalo** 2015-01-07 15:19 UTC
