### ISSUE TITLE
Parallax more smoother

### ISSUE THREAD

**Issue by ibrainventures** [Dogfalo/materialize#1220] opened 2015-04-23 10:47 UTC
Hi Team,

is it possible to make the parallax scrolling more smoother. On Browse like chrome and using the mousewheel the scrooling steps are much more wider, so the background picture is jumping with big steps.

It helps if the top Position of the parallax picture would 1/2 or 1/4 step top the top against the scrolling steps. .. 

As seen on 

http://www.trustami.com/trustami-widget/

the parallax background picture is much more smoother scrolled to the top.

**Comment by DaEckster** [comment] 2015-04-25 03:25
Using a smooth scroll plugin I was able to get it smooth, but then it got super laggy on Android devices, would love to see this issue addressed.

**Comment by Dogfalo** [comment] 2015-04-26 23:44
We didn't like the idea of controlling scrolling, but it's possible we may add it.
Duplicate of #740

**Closed by Dogfalo** 2015-04-26 23:44 UTC
