### ISSUE TITLE
Selecting scroll bar in IE 11 closes Select List

### ISSUE THREAD

**Issue by Only1MrAnderson** [Dogfalo/materialize#3733] opened 2016-10-05 15:51 UTC
When selecting the scroll bar in IE 11 the drop down closes. Only can scroll with wheel
http://jsfiddle.net/8rmjymtr/5/ - borrowed jsfiddle from another issue to highlight the problem,

**Comment by Romanulus** [comment] 2016-12-14 21:15
I can confirm, this is definitely an issue for me, too.
Not using multi-selects and doing away with this line (https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js#L3359) _kind_ _of_ solves the issue, but causes another when clicking away from an open select box.

**Comment by Romanulus** [comment] 2016-12-14 21:56
I've added this directly to materialize.js (which you should add to your own include/script override to not be horrible):

`      
$newSelect.on('focusout', function() {
  $(this).trigger('close');
});
`

Also in materialized.js I've updated the following binding to this:
`
      $newSelect.on('blur', function() {
        if (!multiple && !isIE()) {
          // Override: fixes IE select scroll closing issue, breaks multi-selects
          $(this).trigger('close');	
        }
        options.find('li.selected').removeClass('selected');
      });
`

Terrible hacks, but maybe someone else can see what is going on and make a more elegant fix/solution.

**Comment by fega** [comment] 2017-04-09 01:23
@Romanulus @AAAnderson7301  Could someone check if this is still an issue?

**Comment by RenaldasK** [comment] 2017-05-10 15:10
The issue is still present in IE11. I'm using v0.98.0

**Comment by adodoh** [comment] 2017-05-25 02:16
in materialize.js , find it >
-------------------------------------------------------
$newSelect.on('blur', function() {
    if (!multiple) {
       $(this).trigger('close');
      }
     options.find('li.selected').removeClass('selected');
  });


and append this >
-------------------------------------------------------
       //(1) mouse range
      var onMouseDown = function (e) { 
          // preventing the default still allows the scroll, but blocks the blur.
          // We're inside the scrollbar if the clientX is >= the clientWidth.
          if (e.clientX >= e.target.clientWidth || e.clientY >= e.target.clientHeight) {
              e.preventDefault();
          }
      };
  $newSelect.on('mousedown', onMouseDown);

      //(2) UL>LI 的 mouse click to close select
      options.find('span').on('click', function () {
          $newSelect.trigger('close');
      }); 
-------------------------------------------------------

try it

**Comment by Dogfalo** [comment] 2017-10-11 19:02
Fixed in v1-dev

**Closed by Dogfalo** 2017-10-11 19:02 UTC

**Comment by vonBarbarosa** [comment] 2018-07-02 14:08
hey @frostless, I'm currently struggling with this issue, and I think you won't find an exact commit, as @Dogfalo commented [here](https://github.com/Dogfalo/materialize/issues/901#issuecomment-328030490), they reimplemented this component, so probably it's not possible to simply copy the piece of code and paste it

**Comment by frostless** [comment] 2018-09-12 05:37
Many above methods work, but if we do e.preventDefault(); then we lose the browser typing context ability. I mean if you type a letter, the select wont go to the item anymore, any workaround with this?
