### ISSUE TITLE
Accessibility: Lack of `aria-*` and `role` attributes 

### ISSUE THREAD

**Issue by cvrebert** [Dogfalo/materialize#850] opened 2015-03-06 08:01 UTC
Other than the pickadate.js-powered datepicker, it doesn't look like any of the JavaScript widgets make use of the `role` attribute or `aria-*` attributes needed for proper web accessibility support.
Here's an overview: http://a11yproject.com/posts/getting-started-aria/

**Comment by Merovex** [comment] 2016-11-24 15:51
See rant in #1424

**Comment by Dogfalo** [comment] 2017-02-02 16:32
Duplicate of #1424

**Closed by Dogfalo** 2017-02-02 16:32 UTC
