### ISSUE TITLE
Select box list direction

### ISSUE THREAD

**Issue by seandawn** [Dogfalo/materialize#2402] opened 2015-11-30 22:10 UTC
Anyone know how I can force a select box to display downwards? At the moment I have dynamically generated div overlaying the main content about 1/3 from the top of the page. When the select box in the div is clicked the items flow upwards and are cut off by the top of the viewport. How can I force the select box to open downwards?

**Comment by seandawn** [comment] 2015-11-30 22:14
Here is a screenshot

<img width="424" alt="untitled" src="https://cloud.githubusercontent.com/assets/16085647/11486248/c22b8360-97af-11e5-8cb3-a2bcd2aa9fd6.png">

**Comment by acburst** [comment] 2015-12-02 00:35
Duplicate of #2241. This is fixed on master. You can either update to our unreleased master version or rollback and wait for our next release. Sorry about that.

**Comment by TyrionGraphiste** [comment] 2016-01-18 17:04
Hi, I included this in my PR. You can choose the direction of the opening dropdown.

**Closed** 2017-04-11 10:53 UTC
