### ISSUE TITLE
Feature Request: SASS for Meteor.js

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1018] opened 2015-03-27 17:14 UTC
Could you please provide an official `SASS` package on https://atmospherejs.com/materialize ?

Users could then override variables by creating (**for example**) a file named **client/materialize-override.scss** and still get updates...

You could make use of: https://atmospherejs.com/fourseven/scss

Also check: https://atmospherejs.com/grigio/materialize-sass

**Comment by dcworldwide** [comment] 2015-03-31 05:01
:+1 

I use fourseven's scss (libsass) package with materialise. 

Its less then ideal atm because the atmosphere materialize release does not include the scss files. It would be great to have scss files in the package.

I agree a seperate atmosphere package would be a more elegant design.

**Comment by laurentpayot** [comment] 2015-03-31 08:00
Yes, as it's not possible to change the primary and secondary color variables in the redish/greenish current package its only use is for testing, so that's not very useful. A package with the latests scss files and a way to override _varriables.scss would be SO cool...

**Comment by dhampik** [comment] 2015-04-01 13:20
:+1:

**Comment by mcoenca** [comment] 2015-04-11 11:23
Same Here, it would be great !
 Can help contribute if someone gives me a clue of where to start / look at. (Where is the repository or the folder for materialize:materialize meteor package ?)
It also breaks all the materialize sass mixins and functions.

**Comment by ryandeussing** [comment] 2015-04-29 19:01
:+1::

**Comment by daltonrenaldo** [comment] 2015-05-01 03:22
:+1:

**Comment by funkybunky** [comment] 2015-05-03 15:42
:+1:

**Comment by adamdawkins** [comment] 2015-05-09 14:29
:thumbsup:

**Comment by Visudare** [comment] 2015-05-12 20:14
+1

**Comment by ofstudio** [comment] 2015-05-16 16:41
+1

**Comment by Chun-Yang** [comment] 2015-05-18 15:22
+1

**Comment by dcworldwide** [comment] 2015-05-19 23:57
@Chun-Yang Thanks. I can't use your package though. Reasons are: 

Using https://atmospherejs.com/materialize makes sense as it will always have the latest materialize release. Your package will soon be out of date unless you continually maintain it. You should use a submodule to upstream instead. Or; you could simply change your package so that it contains only the upstream sass files. That means your package would be used in conjunction with the https://atmospherejs.com/materialize package.

**Comment by Chun-Yang** [comment] 2015-05-20 00:14
@dcworldwide Thank you for your feedback, I will update my package and use submodule. I do not think using materialize smart package is a good choice since it will import compiled css and js. Again, thank you.

**Comment by dcworldwide** [comment] 2015-05-20 00:24
OK i agree with you. In that case your package will work great

**Comment by ryandeussing** [comment] 2015-05-20 15:53
Thanks @Chun-Yang I'll have a look at your package!

**Comment by pistou** [comment] 2015-05-26 15:37
:+1:

**Comment by laurentpayot** [comment] 2015-05-28 15:04
@Chun-Yang nice package, working great for me! :+1:

**Comment by fabyeah** [comment] 2015-06-13 17:11
:+1:

**Comment by tdbs** [comment] 2015-06-15 23:02
:+1: This is a must

**Comment by bbshopadmin** [comment] 2015-06-25 20:43
+1

**Comment by artshostak** [comment] 2015-08-06 22:15
Are we any closer to getting SASS support on this official Materialize library for Meteor.js?

**Comment by MoeBadr** [comment] 2015-08-07 11:24
+1

**Comment by donwojtallo** [comment] 2015-08-09 08:29
+1

**Comment by afifsohaili** [comment] 2015-08-10 01:24
Someone has already made a package for this.
https://atmospherejs.com/poetic/materialize-scss

**Comment by elie222** [comment] 2015-08-19 05:59
+1

**Comment by boustanihani** [comment] 2015-08-31 13:28
In **Meteor 1.2** you could make use of ```@import "{}/file.scss"``` to allow users to override variables...

Check: https://quip.com/RXFlAk9Rc2xI 
The less and stylus packages now support cross-package imports! If you specify a file like 
```@import "{package}/file.less"``` (with the curly braces), it will load the file from that package. Use ```@import "{}/file.less"``` to load a file from your app.

**Comment by artshostak** [comment] 2015-08-31 18:36
That's a great addition to Meteor — but I don't think it solves anything in this case as the package doesn't actually contain the SASS files, just a single CSS output. Or am I missing something?
![screenshot 2015-08-31 11 34 02](https://cloud.githubusercontent.com/assets/6820356/9586910/8423c7ee-4fd4-11e5-8607-aa36b6d2b048.png)

**Comment by boustanihani** [comment] 2015-08-31 18:52
@artshostak yes this is the case now, but they could make one with sass and use the new feature to allow us to customize things :)

**Comment by elie222** [comment] 2015-09-02 13:20
There is a sass materialize package for meteor already. I recommend using
it. Search atmosphere for it

**Comment by boustanihani** [comment] 2015-09-02 13:43
I know, we would like to have an official one :bowtie:

**Comment by mitar** [comment] 2015-10-20 08:42
It would be really great to have a Meteor package where you could specify variables like colors and so on.

**Comment by elie222** [comment] 2015-10-20 08:54
There is one. You're using the wrong package

**Comment by mitar** [comment] 2015-10-20 08:56
You mean [poetic/materialize-scss](https://github.com/poetic/meteor-materialize-sass/)? The issue is that it is not recent. See this ticket: https://github.com/poetic/meteor-materialize-sass/issues/10

This is exactly the situation why there is this ticket and why 3rd party package is not enough. Because 3rd party package has to fix some issues to work with Meteor which are not merged upstream it is complicated to maintain it.

**Comment by elie222** [comment] 2015-10-20 09:14
Ah. Ok. I haven't upgraded the project I was using it on to 1.2 yet

**Comment by hydr4n7** [comment] 2015-12-05 08:06
:+1:

**Comment by ryparty** [comment] 2015-12-20 03:40
:+1:

**Comment by NitroBAY** [comment] 2016-06-06 21:22
Yes please, we should be able to have sass files to customize variables, and we could also remove unused imports in sass. Please implement that :D Don't hesitate on taking the code of unofficials plugins...

**Comment by elie222** [comment] 2016-06-06 23:30
There's another package that offers sass for materialise as mentioned above
I believe

**Comment by NitroBAY** [comment] 2016-06-07 07:09
That I use, but the official one have to include sass support

**Comment by Sntax** [comment] 2016-06-07 07:18
👍

**Comment by NitroBAY** [comment] 2016-06-19 13:08
5afb6000a seems to fix the problem :D

**Comment by NitroBAY** [comment] 2016-06-19 15:22
So I tried to use it as [poetic materialize](https://atmospherejs.com/poetic/materialize-scss) but it wasn't  working because package.js forgot to import a file so I fix package.js in #3280. Once the fork merged, all should working like with poetic, I test it.

**Comment by Dogfalo** [comment] 2016-06-19 20:31
Still need to add a few lines to the readme on how to use it in a meteor app, but other than that, the package should be working with Sass for the next release!

**Comment by NitroBAY** [comment] 2016-06-19 23:18
Yeah, as #3280 is forked now you just need to fix #3281 and it should be great. Thanks @Dogfalo

**Comment by NitroBAY** [comment] 2016-06-26 15:44
@Dogfalo so what's going on with #3281 bug ?

**Comment by mitar** [comment] 2016-08-03 00:50
Could anyone explain how to configure custom colors with Meteor? So how to set SCSS variables using Meteor?

**Comment by mitar** [comment] 2016-08-07 09:01
I figured it out. I changed in `package.js` of this package the `addFiles` line to:

```
api.addFiles(scssFiles, 'client', {isImport: true});
```

And then I just create a SCSS file in my app and do:

```
@import "{materialize:materialize}/sass/components/color";
$primary-color: color("blue", "lighten-2");

@import "{materialize:materialize}/sass/materialize";
```

**Comment by Dogfalo** [comment] 2017-02-02 17:06
Already been added!

**Closed by Dogfalo** 2017-02-02 17:06 UTC

**Comment by NitroBAY** [comment] 2017-02-05 13:15
@Dogfalo please it seems that the atmosphere package is somewhat broken as sass import **only** works if one install materialize from a local version fetched from the repo.

**Comment by Dogfalo** [comment] 2017-02-06 03:36
This was fixed in the newest version

**Comment by ninerocks** [comment] 2017-04-25 22:50
Having trouble overriding scss vars using materialize:materialize 0.98.2

I added this to my main.scss:

@import "{materialize:materialize}/sass/components/_color.scss";
$primary-color: color("blue", "lighten-2");

// import main scss file
@import "{materialize:materialize}/sass/materialize.scss";

But is doesn't seem to do anything, not even any errors.
