### ISSUE TITLE
Stuck tooltip on modal open

### ISSUE THREAD

**Issue by lordplagus02** [Dogfalo/materialize#2408] opened 2015-12-02 09:21 UTC
So I just found an issue whereby if you have a tooltipped link and it opens a modal, then you dismiss that modal, the tooltip sticks and doesn't go away.

**Comment by acburst** [comment] 2015-12-03 03:03
Have you tried on the latest version of master? And do you have an example of this not working? Because I tried a quick example on my local master version and it seems to be working.

**Comment by mikereeves** [comment] 2015-12-11 14:51
+1 

v0.97.3 Seems to work well in non-modal environments. The sequence of events:

1. Hover over icon with tooltip in Modal1 
2. Tooltip shows just fine with respective delay setting.
3. When icon is clicked to launch another modal (Modal2) from Modal1, the tooltip still remains in the main window.

I will try to get some screenshots, but also trying to understand the code inside tooltip.js to see if I can help fix.

Perhaps somewhere here that covers other than mouse in/out.

//Destroy previously binded events
      origin.off('mouseenter.tooltip mouseleave.tooltip');
      // Mouse In
      var started = false, timeoutRef;

**Comment by ManuelRiveraC** [comment] 2016-03-10 22:10
Any news?

**Comment by solo999** [comment] 2016-07-14 10:32
+1 for this issue. It is still actual

**Comment by brian-minter** [comment] 2016-08-05 20:49
I had the same issue and I think the problem was that I was initializing my tooltips more than once.  Since I fixed that, I haven't had any problems with it.

**Comment by tomscholz** [comment] 2017-07-20 19:25
Duplicate of #3764

**Closed by tomscholz** 2017-07-20 19:25 UTC
Labels: component:Tooltip
