### ISSUE TITLE
Materialize Select change event fires even if value did not change

### ISSUE THREAD

**Issue by DavidBanksNZ** [Dogfalo/materialize#4713] opened 2017-05-22 03:46 UTC
### Description
If the user selects the same value that was already selected, the change event should not fire.

### Repro Steps

JSFiddle showing the issue - open your JS console to see the messages logged.
https://jsfiddle.net/dgbnz/a26b35r1/3/

With the material select, pick the same value multiple times in a row - the change event fires every time. On the standard select it will only fire if a different value is chosen, which is the expected behaviour.

**Comment by penguoir** [comment] 2017-05-23 06:15
Why is this a problem? Couldn't you just add an `if` statement to your code?

**Comment by DavidBanksNZ** [comment] 2017-05-23 06:24
Yes, but why should I have to? Developers do not expect change events to fire if nothing actually changed... it's unexpected behaviour

**Comment by penguoir** [comment] 2017-05-23 07:35
Think about it like this. For you, it's quite simple to have nothing change if the same value is chosen. However, if someone else **does** needs an event when the same value is chosen, it will be incredibly difficult for that person to implement.

**Comment by DavidBanksNZ** [comment] 2017-05-23 07:51
OK I'm not sure if it's actually a bug or if this is intentional behaviour - if it's intentional it should be documented in the Guide. Instead I had to figure out why my Angular Form was getting marked dirty and read through the  implementation of material select to see why.

**Comment by tomscholz** [comment] 2017-08-12 17:12
Duplicate of #4562

**Closed by tomscholz** 2017-08-12 17:12 UTC
Labels: component:Select
