### ISSUE TITLE
_global.scss contains component code (make components more standalone)

### ISSUE THREAD

**Issue by bauer00** [Dogfalo/materialize#5539] opened 2018-01-11 01:18 UTC
## Expected Behavior
Components (ex. _buttons.scss) shouldn't use code from the _global.scss.

## Current Behavior
For example if I try to use the _buttons.scss as standalone component it extends from classes inside the _global.scss file (.z-depth), so the whole _global.scss file needs to be imported. After looking at the _global.scss file I've saw much code which I don't need if I'm using the components as standalone.

## Possible Solution
Split some code of the _global.scss to seperate files, like "Z-levels", "Pagination", "Breadcrumbs", "Parallax", etc.

## Context
I'm using the SASS version to use the promoted "more control over which components to include" (http://next.materializecss.com/getting-started.html). I've tried to use the buttons, but I can't use them without including the _global.scss.
I already have a complete layout with custom grid, etc. so some code of the _global.scss can maybe break my code. Also the _global.scss contains components code which I don't even use like for example pagination or breadcrumbs.

## Your Environment
* Version used: 1.0.0-alpha.3

**Comment by tomscholz** [comment] 2018-01-11 22:04
Duplicate of https://github.com/Dogfalo/materialize/issues/5024

**Comment by bauer00** [comment] 2018-01-12 07:22
Sorry I've missed that issue. I've searched for "_global.scss", but in #5024 it's called _globals.scss so I couldn't find it. This issue can be closed than.

**Comment by tomscholz** [comment] 2018-01-12 09:33
I've changed the title of my issue to global.scss. thanks for pointing that out :)

**Closed** 2018-01-16 21:15 UTC
