### ISSUE TITLE
Materialize Select is flickering again in Firefox

### ISSUE THREAD

**Issue by 0lmar** [Dogfalo/materialize#1509] opened 2015-06-11 06:32 UTC
When clicking on a "Materialize Select" in Firefox (v. 38.0.5) the select is flickering before opened. Works nicely in Chrome.

**Comment by Dogfalo** [comment] 2015-06-14 08:04
See https://github.com/Dogfalo/materialize/pull/1482

**Comment by ramijarrar** [comment] 2015-07-04 05:28
Still experiencing this on version 0.97.0

**Comment by carlosperate** [comment] 2015-07-25 16:41
Can confirm this is still an issue in Firefox. If can be seen in the http://materializecss.com/forms.html#select page as well.

**Comment by Dogfalo** [comment] 2015-08-08 17:58
Duplicate of #147

**Closed by Dogfalo** 2015-08-08 17:58 UTC
Labels: cross-platform-bug
