### ISSUE TITLE
sideNav is jittery on close in mobile 

### ISSUE THREAD

**Issue by pyrotechr** [Dogfalo/materialize#4035] opened 2016-12-27 08:21 UTC
I have a properly functioning sideNav that works on small, medium, and large screens as intended. 

The issue I have noticed is with sideNav slide-out in small screens. I have not tested this in medium screens (tablets) as of yet. When I slide the sidenav out by either pressing the button or sliding from the edge of the screen and then proceed to close (i.e. not clicking on the button or sliding back to close) the sidenav by pressing somewhere away from the sidenav ... I will then notice a jitter of the sidenav when scrolling on that page.

Not sure if this is clear enough for someone to try and re-create the above issue but someone else on gitter also faced the same problem.

**Comment by arpit1997** [comment] 2016-12-27 15:06
I don't know the reason for this problem but [here](https://github.com/arpit1997/PQusic/blob/development3/mysite/MusicApp/templates/MusicApp/homepage1.html) on this [repo](http://github.com/arpit1997/pqusic) you can find an implementation which seems to be solving your problem.
>I have a properly functioning sideNav that works on small, medium, and large screens as intended.
The issue I have noticed is with sideNav slide-out in small screens. I have not tested this in medium screens (tablets) as of yet. When I slide the sidenav out by either pressing the button or sliding from the edge of the screen and then proceed to close (i.e. not clicking on the button or sliding back to close) the sidenav by pressing somewhere away from the sidenav ... I will then notice a jitter of the sidenav when scrolling on that page.
Not sure if this is clear enough for someone to try and re-create the above issue but someone else on gitter also faced the same problem.

**Comment by pyrotechr** [comment] 2016-12-27 18:38
thanks for the help but I still couldn't get your fix to work for me.

```
      var x = $(window).width();
      console.log(x);
      x = x/2;
      $(document).ready(function () {
          $('.sidebar-collapse').sideNav({
              menuWidth: x,
              edge: 'right' // Choose the horizontal origin
          });
      });
```

I used that code from your repo and noticed the sidenav to still be jittery when i use `edge: 'left'` but when I use `edge: 'right'` the jitterness goes away and clicking away from the sidenav does not close the sidenav either

for reference i am using materialize 0.97.8

**Comment by arpit1997** [comment] 2016-12-27 18:45
versio does not seem to be a problem here. In my case i only tried only the right side sidenav.
>I used that code from your repo and noticed the sidenav to still be jittery when i use edge: 'left' but when I use edge: 'right' the jitterness goes away and clicking away from the sidenav does not close the sidenav either

The problem of sidenav not going away did not happened to me.
You can try in my application in the repo.
Can you provide any github link of your project?

**Comment by pyrotechr** [comment] 2016-12-28 04:19
So the whole jitterness in the menu thing can be recreated on the main site as well @ http://materializecss.com/side-nav.html

I managed to get rid of the problem on my project by setting 2 of the options to false...
```
$('.sidebar-collapse').sideNav({
    edge: 'left',
    closeOnClick: false,
    draggable: false
});
```
Now whenever i drag on an area outside the sideNav area to close it... there is no jitterness in scrolling.

**Comment by pyrotechr** [comment] 2016-12-28 04:19
I should probably mark this as close but because the same issue exists on the main site as well.. maybe someone can take a look at it

**Comment by ivanjuras** [comment] 2016-12-28 08:30
I've noticed the same thing, too. It's on the main site as well.

**Comment by SaeedPrez** [comment] 2017-02-09 20:36
The problem still persists as of today, `draggable: false` option removes the problem but also the functionality.

**Comment by fega** [comment] 2017-04-16 00:11
I cannot reproduce it, someone can provide a way to see what's happening? like a gif or video?  thanks

**Comment by pyrotechr** [comment] 2017-04-28 19:03
https://streamable.com/4opg1

**Comment by tomscholz** [comment] 2017-05-02 19:35
Duplicate of https://github.com/Dogfalo/materialize/issues/4082

**Closed by tomscholz** 2017-05-02 19:35 UTC
Labels: browser-bug, bug
