### ISSUE TITLE
Tabs tab indicator missing on load

### ISSUE THREAD

**Issue by joxmar** [Dogfalo/materialize#2102] opened 2015-09-29 17:38 UTC
I'm having issues with the tabs, the tab indicator is missing when the tabs are loaded, The first tab is the default and the tab text is colored as selected tab and displaying the correct content but the indicator is missing. There's only 2 ways to get the indicator to show:
1. When I start clicking on the tabs the indicator appears and then stays working correctly
2. When the tabs load and I re-size the window the indicator appears

this is what I have:

```
<div class="container">         
  <div class="row">
    <div id="rmt-rooms" class="col s12 m3">
     Some stuff
    </div>      

    <!-- tabs -->
    <div id="rmt-dialog" class="col s12 m9">
      <div class="card-panel">
        <div class="row">
          <div class="col s12">
            <ul class="tabs">
              <li class="tab"><a href="#roomType" class="active">Room Type</a></li>
              <li class="tab"><a href="#roomPhotos">Room Photos</a></li>        
              <li class="tab"><a href="#roomNumbers">Room Numbers</a></li>
            </ul>
          </div>
          <div id="roomType" class="col s12"></div>
          <div id="roomPhotos" class="col s12"></div>
          <div id="roomNumbers" class="col s12"></div>
        </div>                      
      </div>                        
    </div>  
    <!--End  tabs -->                       
  </div>
</div>
```

**Comment by gnicol-bzh** [comment] 2015-10-22 14:00
I have the same problem.

**Comment by evallgar** [comment] 2015-10-26 05:14
It also fails on OS X Firefox 41.0.2 and Safari 9.0.1

I dont think its a browser issue.

**Comment by loolooii** [comment] 2016-01-20 09:50
I have the same problem! Is there any fix for this?

**Comment by chifreaigle** [comment] 2016-01-20 11:29
This issue is hard to reproduce

**Comment by loolooii** [comment] 2016-01-20 11:51
@chifreaigle I have a tab somewhere inside another (main) tab, maybe that helps? Also, the class "active" is correctly set. Only left:x and top:y are set after actually clicking on a tab (which then shows the indicator color).

**Comment by chifreaigle** [comment] 2016-01-20 21:31
@loolooii  Yeah,i got the steps to reproduce the issue, when making a tab(secondary tab) inside an other tab(main tab) makes the indicator of the secondary tab invisible, as @joxmar said the only way to get it showing is by either resizing or selecting the tab,Here is an example 
https://jsfiddle.net/80jkvumd/

**Comment by julianctni** [comment] 2016-06-08 16:02
Just got the same issue. Tab indicator not showing, only after resizing the window. Is there any workaround or solution meanwhile?

**Comment by adamhammond** [comment] 2016-07-21 14:32
@julianctni for a quick fix, you could:

At the end of your event handler for $(document).ready, add the following:
`window.dispatchEvent(new Event('resize'));`

**Comment by Native-Coder** [comment] 2017-02-10 03:16
I can't do that because my tabs are in a modal. It makes the indicator the entire width of the tabs. (underlines all tabs end to end)

**Comment by Native-Coder** [comment] 2017-02-10 03:20
Nevermind, I just put @adamhammond 's one-liner in the modal::ready callback, and commented that it was a work around.

**Comment by mangakid** [comment] 2017-02-14 12:56
I had the same issue, also with the tabs in a modal, the solution I used was: 
$('#my-modal').modal({
        ready: function(modal, trigger) {
          $('ul.tabs').tabs();
        }
});

**Closed** 2017-02-14 21:07 UTC

**Comment by abraaoz** [comment] 2017-03-04 18:33
If you are using tabs inside "collapsible" elements, you must apply @adamhammond fix inside "onOpen" event, like this:
```javascript
$('.collapsible').collapsible({
	onOpen: function(el) {
		// https://github.com/Dogfalo/materialize/issues/2102
		window.dispatchEvent(new Event('resize'));
	}
});
```

**Comment by makindemayowa** [comment] 2018-02-12 16:31
This worked for me.    
$(document).ready(function(){
      $('ul.tabs').tabs();
    });

**Comment by dinho19sp** [comment] 2019-01-07 03:33
This worked for me, i'm using angular 6, this tab not work with route-outlet.. thanks
