### ISSUE TITLE
Improve support for multiple css frameworks

### ISSUE THREAD

**Issue by dcworldwide** [Dogfalo/materialize#1303] opened 2015-05-06 04:44 UTC
Materalize assumes that it is the sole css framework in use. For many projects, this is not the case. E.g. in our company, we use the Foundation for Apps flexbox grid with Materialize. Using the two frameworks together doesn't work without conflict issues. 

Can you please refactor the project to improve this?

As Materalize is already module, we are almost there. What is missing IMO is that we need to refactor the global.scss file so that it has minimal affect on html elements.

**Comment by sompylasar** [comment] 2015-05-16 18:08
Please consider the [BEM (Block-Element-Modifier) methodology](https://en.bem.info/method/) for structuring your CSS. It helps resolving many issues and style conflicts caused by CSS being a multitude of global variables.

General principle is a modular approach:
* Use unique block names to avoid conflicts with other styles in the page (both other libraries' and the user's own styles).
* Apply styles to classes only. No tag or identifier styling allowed. Users must structure the markup and add classes accordingly.

Basic example (`.mat-` being the library prefix that makes it somewhat unique amongst other libraries; better make it configurable in SASS bindings):
```
.mat-searchbox { /* (Block) searchbox styles */ }
.mat-searchbox__search-button { /* (Element) searchbox search button styling */ }
.mat-searchbox--rounded { /* (Modifier) rounded searchbox additional styling */ }
```

Please read more at [bem.info](https://en.bem.info/method/) and on the Internet.

Related: #949, #936.

**Comment by dcworldwide** [comment] 2015-05-20 00:26
:+1: a prefix makes sense to me. Not sure if there are other options..but i like it.

**Comment by truenorth** [comment] 2015-05-20 23:04
This would be lovely :+1:

**Comment by dtracers** [comment] 2015-05-24 01:50
:-1:

As someone who likes this library for its ease of use in css this would cause a bunch of ugly html code.
especially because it does do tag styling.

As an alternative solution why not add a class that then cancels every style used by this library.

ex
```
<h1>Styled by materialize</h1>
</h1 class="not-material">Not style by materialize</h1>
```
where in its css it has the below for every style rule.
```
h1:not(.not-material)  {
...
}

This is just as much work as requiring a class for every element that needs styling but is also allows the library to remain approachable.

**Comment by sompylasar** [comment] 2015-05-24 11:50
Resetting CSS rules is a bad practice that leads to making software that is
hard to maintain.

The practices of isolation and modularity are proven to solve conflicts in
large applications.

If you make a simple web page, you could be confused why you would need
such seemingly complex separation and longer class names over seemingly
simpler styling and shorter class names.

Unless Materialize targets only developers that make simple webpages, it
should allow the ones that make something bigger to use the future-proof
practices for structure, scalability and maintainability.
24.05.2015 4:51 пользователь "dtracers" <notifications@github.com> написал:

**Closed** 2017-04-03 16:44 UTC

**Comment by IIStevowII** [comment] 2019-02-12 18:28
Why is this feature request removed from the board?
