### ISSUE TITLE
Side menu width doesn't work

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#690] opened 2015-02-15 16:05 UTC
On documentation ```$('.button-collapse').sideNav({menuWidth: 240, activationWidth: 70});```

Even if I change the menuWidth to another value, it stays on 240px

**Comment by yowkah** [comment] 2015-02-15 23:00
Works for me although i have some CSS added.
for me the JS is:
```js

 $(function(){
 	$(".button-collapse").sideNav({menuWidth: 300});
 });

```

Can you place some excerpts of your UL's HTML and the html of your link that activates the sidemenu.
Also ( even though i assume you did) can you check if you put your javascript in a document ready function from jquery and if it is loaded in AFTER all the javascript from materialize?

**Comment by ventouris** [comment] 2015-02-16 09:17
```
<ul id="slide-out" class="side-nav full">
    <li class="no-padding">
      <ul class="collapsible collapsible-accordion">
        <li>
          <div class="collapsible-header"><span id="manager">{{headerstr["profile"]|safe}}</span><i class="mdi-navigation-arrow-drop-down"></i></div>
          <div class="collapsible-body">
            <ul>
              <li><a href="/">Home</a></li>
              <li id="login"><a href="/login">Login</a></li>
              <li><a href="#" onclick="logout()">Logout</a></li>
            </ul>
          </div>
        </li>
      </ul>
    </li> 
    .......(the same <li class="no-padding"> code for a few times)
</ul>

<div style="width:100%;top:0;left:0;background-color:black;height:45px;" class="valign-wrapper">
  <a href="#" data-activates="slide-out" class="button-collapse" style="color: white;"><i class="mdi-navigation-menu left">  Menu</i></a>
</div>```


```<script type="text/javascript">
    $(document).ready(function(){
      $('.button-collapse').sideNav({menuWidth: 340, activationWidth: 70, edge: 'right'});
    });
</script>```

But on CSS in Firebug:

```ul.side-nav.full, ul.side-nav.fixed {
    background-color: #fff;
    height: calc(100% + 60px);
    left: -250px;
    margin: 0;
    padding-bottom: 60px;
    position: fixed;
    top: 0;
    width: 240px;
    z-index: 999;
}
```

**Comment by yowkah** [comment] 2015-02-16 14:50
Okey i just can't seem to replicate the bug. When I use your code ( html converted to jade, but still), I can't recreate the problem within my own environment. Does the collapsing of the menu itself actually work? does the menu get placed on the right side?

for reference: my code.

```jade
html
	head
		meta(charset='utf-8')
		meta(http-equiv='X-UA-Compatible', content='IE=edge')
		title boilerplate
		meta(name='description', content='boilerplate')
		meta(name='viewport', content='width=device-width, initial-scale=1.0, minimum-scale=0.5 maximum-scale=1.0')
		meta(name='apple-mobile-web-app-capable', content='yes')
		meta(name='apple-mobile-web-app-status-bar-style', content='black-translucent')
		link(href='/public/stylesheets/application.css',rel='stylesheet' )
	body.side-nav-fixed
		ul#slide-out.side-nav.fixed
			li.no-padding
				ul.collapsible.collapsible-accordion
					li
						.collapsible-header
							span#manager
								|Menu Item Header
								i.mdi-navigation-arrow-drop-down
						.collapsible-body
							ul
								li
									a(href="/") Home
								li
									a(href="/") Login
								li
									a(href="/") Logout
		.valign-wrapper(style="width:100%;top:0;left:0;background-color:black;height:45px;")
			a.button-collapse(href="#" data-activates="slide-out")
				i.mdi-navigation-menu.left
					|Menu
		main
			block content
		script(src='public/js/scripts.js')
```

my scripts.js file contains all my javascript ( first jquery, then materialize, then personal code as last) so that personal code always gets loaded after all other dependencies. Also i have all my scriptfiles at the bottom of my page. If you can't seem to find the issue, can you try to upload your files to github or w/e so we can check them out?

**Comment by ventouris** [comment] 2015-02-16 15:43
Yes, the collapsing works without another problem. I have the website online in a test server. Maybe you can see it there. You will see that the width is 240px while I set it on the end on 340.

test domain: http://stage.ht-tools.eu

**Comment by yowkah** [comment] 2015-02-16 16:13
welll the first thing i found out is... your materialize.min.js doesn't contain the entire menuWidth attirbute. but it does contain both edge and activationwidth... can you try updating the JS of materialize and make sure you use the full version instead of the minified version?

**Comment by ventouris** [comment] 2015-02-16 17:45
I downloaded the latest version (0.95.2) from the website and now the collapse doesn't even open. It changes the whole page to a lower opacity, but that's all. I haven't uploaded to the test server the new version, but I don't have any error on the console :(

**Comment by yowkah** [comment] 2015-02-16 18:06
Okey, i just copied the sources from your test server and exchanged the materialize.min.js for the new one manually. So far, the weird thing for me is. It works with right, if i use the fixed class instead of the full class for the menu itself. ( yeah, i know right? weird shit, thats why i wasn't having the issue myself) i have to do some other stuff for a bit, ill get back to you in approx 3 hours. :)

**Comment by yowkah** [comment] 2015-02-16 18:22
Fixed it quite quick:

in sidenav.js file line 57 it has the following IF function:

```js
    //set to width
        if (options.menuWidth != 240) {
          menu_id.css('width', options.menuWidth);
          if (!menu_id.hasClass('fixed')) {
            menu_id.css('left', -1 * (options.menuWidth + 10));
          }
        }
```

It doesn't check the edge variable when giving the menu its left attribute.
To fix this:

replace this block with:

```js
        // Set to width
        if (options.menuWidth != 240) {
          menu_id.css('width', options.menuWidth);
          if (!menu_id.hasClass('fixed')) {
            if(options.edge === 'left'){
            	menu_id.css('left', -1 * (options.menuWidth + 10));
        	}else{
        		menu_id.css('right', -1 * (options.menuWidth + 10));
        	}
          }
        }
```

works for me now.

**Comment by ventouris** [comment] 2015-02-18 10:38
I found another bug on this....Even if the new JS fixes the width of the side menu, the new width is set only on the ul and not on the li tags.

**Comment by yowkah** [comment] 2015-02-18 14:35
this seems to be caused by the css rule:
```css
ul.side-nav.full li, ul.side-nav.fixed li{ width:240px;}
```

overwriting it seems to fix it for me. However, i don't have this width issue on my own page. even though on the page im testing your layout on, i seem to have it on both left and right side with both fixed and full nav. I will delve into it a bit deeper later on, but the temporary fix should do the job for you atm i hope ^^

**Comment by Dogfalo** [comment] 2015-02-18 21:06
Fixed in d098ffeab7519dc9a9af1acf9a1279859bfa0875

**Closed by Dogfalo** 2015-02-18 21:06 UTC

**Comment by ventouris** [comment] 2015-02-19 10:19
It hasn't been fixed. Actually, it has only for a part of it...When you load the page for the first time, it has "left:-350px" for width=340px...Even with the edge on the right...Then, when you click on the menu, you see the whole sidebar pass through the screen from left to right...After than, it stays on the right. But if you load the page, it is on the left again.

**Comment by DavidCRivera** [comment] 2015-03-10 23:01
I think this is related. I expanded my menu with:
```
$(".button-collapse").sideNav({menuWidth: 300});
```

But the problem I had was that on mobile when swiping the menu closed, it wouldn't close all the way, still sticking out some. Wasn't a problem on desktop with clicks instead of swipes. Looking into the code, I came across this starting at line 1831:

```
        }).bind('panend', function(e) {
          if (e.gesture.pointerType === "touch") {
            var velocityX = e.gesture.velocityX;
            panning = false;
            if (options.edge === 'left') {
              // If velocityX <= 0.3 then the user is flinging the menu closed so ignore menuOut
              if ((menuOut && velocityX <= 0.3) || velocityX < -0.5) {
                menu_id.velocity({left: 0}, {duration: 300, queue: false, easing: 'easeOutQuad'});
                $('#sidenav-overlay').velocity({opacity: 1 }, {duration: 50, queue: false, easing: 'easeOutQuad'});
                $('.drag-target').css({width: '50%', right: 0, left: ''});
              }
              else if (!menuOut || velocityX > 0.3) {
                menu_id.velocity({left: -240}, {duration: 300, queue: false, easing: 'easeOutQuad'});
                $('#sidenav-overlay').velocity({opacity: 0 }, {duration: 50, queue: false, easing: 'easeOutQuad',
                  complete: function () {
                    $(this).remove();
                  }});
                $('.drag-target').css({width: '10%', right: '', left: 0});
              }
            }
            else {
              if ((menuOut && velocityX >= -0.3) || velocityX > 0.5) {
                menu_id.velocity({right: 0}, {duration: 300, queue: false, easing: 'easeOutQuad'});
                $('#sidenav-overlay').velocity({opacity: 1 }, {duration: 50, queue: false, easing: 'easeOutQuad'});
                $('.drag-target').css({width: '50%', right: '', left: 0});
              }
              else if (!menuOut || velocityX < -0.3) {
                menu_id.velocity({right: -240}, {duration: 300, queue: false, easing: 'easeOutQuad'});
                $('#sidenav-overlay').velocity({opacity: 0 }, {duration: 50, queue: false, easing: 'easeOutQuad',
                  complete: function () {
                    $(this).remove();
                  }});
                $('.drag-target').css({width: '10%', right: 0, left: ''});
              }
            }


          }
        });

```

The problem area was the hardcoded '-240' values. I changed them to the hacky:

```
(options.menuWidth * -1)
```

That seemed to fix it. Seems like an easy fix, unless I'm missing something.

**Comment by Dogfalo** [comment] 2015-03-10 23:20
BTW, this is already fixed in master builds. `menuWidth` option fully works

**Comment by DavidCRivera** [comment] 2015-03-16 13:32
Ok, sounds good. Looking forward to the release!
