### ISSUE TITLE
long dropdown trimmed by viewport bottom edge

### ISSUE THREAD

**Issue by olivier67** [Dogfalo/materialize#960] opened 2015-03-19 18:24 UTC
I figured out how to avoid this problem with right and left edges. But with a long dropdown list, for example 24 hours, the bottom part of the list is trimmed and not accessible. See attached.
![dropdown](https://cloud.githubusercontent.com/assets/7541861/6737699/8682ad7c-ce6d-11e4-9c9b-218eec10150e.jpg)

**Comment by Dogfalo** [comment] 2015-03-22 21:30
Approximate duplicate of #780

**Closed by Dogfalo** 2015-03-22 21:30 UTC

**Comment by olivier67** [comment] 2015-03-22 21:39
Hello Alvin, I looked at other "duplicate" issues #780 and #903, but you don't provide any answer : in your opinion this dropdown issue is a normal user interface behavior ? Love your work but a bit confused about small details like this. Thanks.

**Comment by Dogfalo** [comment] 2015-03-22 21:41
There isn't an answer provided because it is not implemented yet.
