### ISSUE TITLE
material_select does not update display value after selected option has been changed by program

### ISSUE THREAD

**Issue by yangpu** [Dogfalo/materialize#1296] opened 2015-05-05 06:46 UTC
I have create an angular directive to initialize select control:

``` javascript
  SelectDirective = function($timeout) {
    return {
      restrict: 'A',
      link: function($scope, element, attrs) {
        return $timeout(function() {
          return $(element).material_select();
        }, 50);
      }
    };
  };
```

to create select control in jade:

``` jade
   .col.s6.input-field
      select#priority(md-select, ng-model='vm.priority')
         option(value='0') 0
         option(value='1') 1
         option(value='2') 2
         option(value='3') 3
      label(for='priority') Priority
```

The issue is that the select control doesn't update the display value when the priority value has been changed in controller. However, the priority value is changed according to the selected option value by mouse or key operation.

Is it possible to have a public method to select value in material_select? So that it's feasible to $watch ng-model value in directive to update the display value by the method.

**Comment by b1rdex** [comment] 2015-05-07 04:38
http://materializecss.com/forms.html

Updating/Destroying Select
If you want to update the items inside the select, just rerun the initialization code from above after editing the original select.

```
$(document).ready(function() {
    $('select').material_select();
  });

**Comment by yangpu** [comment] 2015-05-09 03:01
It looks nothing changed to re-initialize the select control after select options or value is changed.

**Comment by govindjhag** [comment] 2016-04-12 12:47
I am facing same problem

**Comment by freddy-daniel** [comment] 2017-03-20 05:30
Same issue in firefox we are not re-initializing.

**Comment by nesthor12** [comment] 2017-04-28 02:08
I am also experiencing the same problem. However, I think I found  a solution for this.

First set the value default option to empty string.

like this in HTML:
`<select` id="selectid">
	`<option` `value="">Select</option>`
        `<option` `value="1">1</option>`
`</select>`

and then in JS:
$("#selectid").find('option[value=""]').prop('selected', true);

**Comment by tomscholz** [comment] 2017-08-12 17:41
Duplicate of #4562

**Closed by tomscholz** 2017-08-12 17:41 UTC
Labels: bug, component:Select

**Comment by khullah** [comment] 2017-12-20 05:39
In AngularJS I solved with "track by $index"
