### ISSUE TITLE
Navbar-fixed and side-nav

### ISSUE THREAD

**Issue by Cedcomps** [Dogfalo/materialize#4972] opened 2017-07-16 09:02 UTC
Hello, just to say you can't mix both of them, or the **side-nav** can appear, but not clickable on link because it's about `z-index` present in **navbar-fixed** class who is contraignant

**Comment by tomscholz** [comment] 2017-07-16 10:45
Duplicate of #3844

**Closed by tomscholz** 2017-07-16 10:45 UTC
