### ISSUE TITLE
Select menus don't work if you press down and hold on an item, or click slowly.

### ISSUE THREAD

**Issue by SimHacker** [Dogfalo/materialize#4098] opened 2017-01-13 00:34 UTC
### Description
Triggering select menu buttons should respond to mousedown instead of click, just as popping down the menu does. 

### Repro Steps
Make a select with some options. Click to pop up the select menu (the material one, not the stock browser one). Move down and see the menu items highlighting under the cursor. Press the button down and hold it without releasing. Notice the menu pops down. Release the button. Notice nothing happens, the item is not selected. If you don't click quickly enough, the item is never selected. This makes menus very flaky for anyone who doesn't click really fast all the time. 

You can easily reproduce the problem here by clicking up a select, then pressing and holding or slowly clicking over an item, and see that the item is not selected: http://materializecss.com/forms.html#select

### Screenshots / Codepen
n/a

The fix is to change "click" to "mousedown" on line 541 of forms.js:

https://github.com/Dogfalo/materialize/blob/60592cda09d19b1fda0f3727e49495354e042ba4/js/forms.js#L541

The context:

      options.find('li:not(.optgroup)').each(function (i) {
        $(this).click(function (e) {
          // Check if option element is disabled
          if (!$(this).hasClass('disabled') && !$(this).hasClass('optgroup')) {
            var selected = true;

The second line should be:

        $(this).mousedown(function (e) {

After that change it works 100% reliably for me on all browsers now!

**Comment by donnisnoni** [comment] 2017-01-13 02:45
Maybe you must include init.js from materialize.com, you can find it on http://materializecss.com/js/init.js

**Comment by SimHacker** [comment] 2017-01-13 08:48
I have already solved the problem by applying the patch I gave above. I am running an older version of materialize, but the current version has the same bug. I don't understand how including init.js could solve the problem, because it does not define any mousedown handlers on the optgroup class, which is required to fix the bug. Clearly the handler should not be on the "click" event, because the "click" even never gets fired if you don't click fast enough, yet the menu pops down immediately on the mousedown event. Both the menu pop-down and the menu item select handler must be on the same kind of event handler, and the menu item selection handler should fire even if you click slowly, or press, hold for a while and release. Ignoring slow clicks is incorrect, frustrating behavior.

**Comment by Dogfalo** [comment] 2017-01-19 22:57
a press and hold is NOT a click and should not click the item. a long press is a standard behavior in basically every mobile OS.

**Comment by SimHacker** [comment] 2017-01-19 23:11
I disagree. The current behavior is not correct, and leads to missed menu selections, which is terrible. 

There is a continuoum between clicking and pressing and holding, and the problem is with quick clicks that are not quite quick enough, as well as pressing and holding, which is just the extreme case. The huge problem is with the edge case, between quick click, and a not-quite-quick-enough click. 

If you press and hold, or click quickly but not quick enough, the menu should not pop down on the "mousedown" event, but it does. 

And as I explained, the user has very little control of feedback whether they are making a press or a hold, because of the unpredictable timeout of a click, which depends on the platform, and how busy the system is at the time. 

Either fix the event handler that pops down the menu to respond to the click event, not the mousedown event as it currently incorrectly does, or fix the trigger event to respond to the mouse down event. 

The point, which I already explained, is that the action of popping the menu down must be on the SAME event as the action for selecting a menu item. Anything else in inconsistent, and makes the menus unreliable, flakey and unusable. 

It took me a long frustrating time to track down why the menus were not selecting the item I "clicked" on. It was because I was not clicking really really fast. I was not just pressing and holding. The threshold for determining a "click" is too low, and not under control, so it is important to properly parse the mouse events consistently so that when the user INTENDS to click, you don't IGNORE the click because it wasn't fast enough. 

You should re-open this bug.

**Comment by SimHacker** [comment] 2017-01-19 23:22
Please walk down to Newell-Simon Hall 3517 and ask my colleague Brad Myers to explain transition diagrams, which he touches on in these slides:

http://www.cs.cmu.edu/~bam/uicourse/05440inter/lecture10.models.pptx

Also see the paper he recommends:

William Buxton, "Lexical and Pragmatic Considerations of Input Structures," Computer Graphics, January, 1983, (17)1, pp. 31-37.
http://dl.acm.org/citation.cfm?id=988586
http://www.billbuxton.com/lexical.html

**Comment by Dogfalo** [comment] 2017-01-20 02:09
Unless I am mistaken, the behavior of the of the select menu items is the same as a regular link or button on any website. I tested this on android and a medium-fast click as you described will still activate the selection unless you mistakenly move your touch away from its origin before releasing.

**Comment by SimHacker** [comment] 2017-01-20 16:20
There are two processes going on, and both processes need to be triggered on the same kind of event. One process is showing and hiding the menu. The other process is selecting the menu item. 
It does not make any sense to talk about comparing the way pop up menus behave with the way regular links behave. Regular links are not like pop up menus. 

When you press down on a normal link, no menu pops up, and when you release on a link, no menu pops down. But menus are very different than links. When you pop up a menu, it temporarily shows an element that contains the menu items, and then pops it down at the end of the menu selection. There is an event that pops up the menu itself. In normal menus, this can either be a mousedown event, or a click event. Most normal menus can be popped up by either a mouse down event, or a click. There also an event that pops down the menu. Most normal menus pop the menu down on either the mouse up event if you popped the menu up by pressing and holding, or pressing and dragging, and pop the menu down on a click event (effectively the up event of a down/up pair) if you click the menu up. Most menus can support both modes of operation: clicking them up (press down, release quickly, move while not holding button down, press down, release quickly over menu item (the test if you are over the menu item MUST be made on the position of the up event). Also they must support being clicked up, then the mouse moving without pressing the button, then any combination of: pressing down, waiting any amount of time, possibly moving any amount of distance, and then releasing. 

You have NO CONTROL over the sequence and timing and position of the mouse events that the user might articulate. You MUST be able to handle all cases correctly without ignoring any events and acting unexpectedly. That means: click up, move, click down. Press down, move, release. Click up, wait, press down, move, release. All sequences of events are possible, and if you will try them with any professional implementation of pop-up menus, you will see that all sequences of events will properly select the intended menu item. 

Your implementation of menus only handles a very restricted subset of the possible events that the user may articulate. 

Your menus do not handle pressing down, dragging and releasing over a menu item to select the item, like normal menus do. 

Your menus do not handle clicking up, moving, pressing down, moving to a different item to reselect a different item, and then releasing over that item to select it.

The rule is that the item under the cursor when the button is RELEASED should be selected. If you press down inside a menu item, but then drag the cursor outside of the item, the feedback should properly reflect the fact that the item is selected upon mouse down, and deselected when the cursor rolls out of the item, and any other item you roll into while the button is down should be highlighted. Then when you release the button, if an item is highlighted, it is because the cursor is over it, so it will be selected. Or if no item is highlighted (because you are not over an item), then nothing happens. That is the ONLY case where nothing should happen: when you cursor is NOT over an item.

However, your menus IGNORE the case where the cursor is over an item of the menu while dragging between menu items, and then you release the button, if the time between pressing and releasing is so short that it is classified as a mouse click by the system. That is incorrect. The menu should not ignore the selection if you did not click fast enough, even though you are actually pointing at the item you want to select. No user would ever expect the item the are pointing the cursor at NOT to be selected when they actually say the highlighting implying that the item they were pointing at was selected, then released the button. Showing a highlight on the item under the cursor is the system's way of telling the users that the item will be selected when they release the button. By not selecting it, you have broken the implied contract with the user, and disappointed their expectations, and the will perceive the menus as unreliable, flakey and broken. 

Here is a step by step procedure for reproducing the problems with the demo that you have on the web site right now:

Go to this url on a desktop web browser like Chrome:

http://materializecss.com/forms.html

Scroll down to the "Select" section".

Look at the select labeled "Materialize Select". See the select under it labeled "Choose your option" which is underlined and has a down arrow on the right side. 

That is the select's pop up target area. 

Move the cursor over that area. Position the cursor exactly over the "Choose yhour option" label, so that it is exactly over the "o" in "your". 

Now PRESS the mouse button down (DO NOT RELEASE), and see that the menu pops up underneath the target area. Now move the cursor downwards. 

Notice that the web browser has gone into text selection mode, and that the "o" in "your" is selected, followed by all the characters below it, until the text under the current position of the cursor.

This is obviously incorrect behavior. Not what the user expects. No user would ever want to actually select the text beginning with the middle of the select label and continuing on to the text of several menu items below it. 

This problem is because you are popping up the menu on the mousedown event, but not properly canceling text selection, so the system goes into text selection mode, which is wrong. 

It is obvious that whoever implemented and tested these menus only thought about people ever using them by "clicking" them up, and never considered or tested the case that somebody might pop up a menu by pressing and dragging, just like most every professionally implemented menu on desktops like Windows, Mac, and even the ancient menus from the 1980's on various Unix and Xerox PARC systems did as documented in Brad Myers video tape, All The Widgets.

If you read any professionally designed user interface guidelines specification, like Apple's, they will document the state machine required to implement the menus, and that will include the ability to handle ALL of the possible edge conditions like this.

You can not just ignore all of these edge conditions because YOU not happen to ever pop up menus that way, because you can not control how your users do it, and you must be able to implement menus that are usable by people different than yourselves. People who can click faster. People who can not click as fast. People who press down, and then pause because something in the environment distracts them, and then continue to move the mouse to select from the menu. 

Menu tracking is NOT as easy as it seems on the surface at first glance. You will realize that if you watch All The Widgets, or read a well written user interface tracking specification, or the source code for any well written menu implementation. 

The problem described above is just one edge case you have not implemented properly, the first one I encountered, and that many of your users will encountered, that results in unexpected flakey and useless behavior. 

To compare with a normal menu implementation that implements selects correctly, go to this url:

http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

You will see the simple HTML that defines a select on the left, and the select it creates on the right. 

Point the cursor at the select on the right, and position it over the first "o" in "Volvo". 

Now press down on the button, and HOLD it. See that the menu pops up. Without releasing the mouse button, move the cursor down. See that it does NOT go into text selection mode. See that the menu item highlighting ALWAYS tracks the position of the cursor while the button is held down, and no matter where you point, and no matter what sequence and position of movement you make, if your cursor is over a menu item, THAT menu item will be selected, and when you move the cursor outside of a menu item, that item will deselect, and if you move the cursor over another item, the select highlighting will change to the other item you pointed to, and if you move the cursor outside of the menu so it is no longer pointing at an item, no item will be selected.

The highlighting implies a contract with the user: If the menu item under the cursor is selected, then that is the system's way of promising to the user that the item will be selected if they highlight the button. This is called "Selection previewing". This is a standard practice in user interface design. All menus do this, except for yours. Your menus lie to the user about what will happen if they release the button, by showing highlighting of the item under the cursor, but NOT selecting that item when they release the button, in some cases. This is terrible user interface design. It violates the "principle of least astonishment" by astonishing and disappointing the user by IGNORING their input when the EXPECT for it to do what they meant and select the item under the cursor when they release the button. 

https://en.wikipedia.org/wiki/Principle_of_least_astonishment

The scenario described above of selecting an item from a select menu by pressing, moving and then releasing the button in one "drag" gesture is but one of the modes of operation a menu should support, that yours don't. They should also support "click up" behavior as well. Both modes are compatible and interchangeable if the menus are properly implemented, which is the case with most system menus on Mac and Windows, and most selects and pop up menus in web browsers. 

In the "click up" scenario, which is what this bug report is actually about, your menus also track incorrectly, as I have already described. I should have originally submitted a more complete bug report that described all the edge cases you don't implement properly like I am doing now, but I was just trying to make them usable and stop ignoring selections, not necessarily behave like other standard menus. But now that I see that you don't understand how normal menus are expected to work, I am explaining exactly how they should in step-by-step detail, and I have given you links to the All The Widgets video that demonstrates how many different historical menu systems work so you can see them in action, as well as links to web pages that you can try in your own browser to see how built-in browser select menus and operating system supported menus work). 

When you "click up" a menu, the menu will appear on the screen immediately on the "down" event of the click, not waiting until the up event that completes the click, because at the time you receive the mousedown event at the start of the click, you have not yet received the mouseup event that completes the click, so you do not know whether or not you are going the user is going to click up the menu, or press and drag through the menu. So NEVER wait until the "click" to pop up the menu. Menus should always be popped up on mousedown events, never click events, because there should never be a delay in showing the menu associated with waiting for the up event that completes the click. That would make the user interface appear to be sluggish and unresponsive. 

So the "down" event on the select should ALWAYS immediately pop up the menu. If the following up event arrives in time for a "click" event to be generated, then that is fine, because the menu will be already shown on the screen. If the user presses and holds the button, or presses and moves the button, in that case it is necessary to have popped the menu up on the down event, because that is when the user wants to see the menu: immediately, not at the end of a delay.

Try this with the normal select menu on the last page I linked you to a few times, and you will see how it works. You can always select from the menu by either 1) click it up, move without holding the button down to point at an item, and click it down. 2) click it up, move without holding the button down to point at an item, then press the button down without releasing it, then move the cursor into a DIFFERENT menu item to RESELECT a different item -- you can roll between any number of items while holding the button down and the highlighting will ALWAYS show the selected item under the cursor (or no item if the cursor is not over the menu), and when you release the button, it will ALWAYS select the highlighted menu item under the cursor if any (which is where your menus break down and just ignore user input). And finally 3) Press the button over the select, then (with or without waiting) move the cursor down into the menu, see how the menu item under the cursor is ALWAYS highlighted and ALWAYS changes to the next item when you move out of one item and into the next, and ALWAYS when you point away from the menu it shows no highlighted item, and then when you release the button over a highlighted item, that item will ALWAYS be selected (which is where your menus incorrectly ignore the user input). 

Menus should NEVER show highlighting that implies they will select an item when the user releases the button, but then break that promise by ignoring the button release event. That is the main problem that I as reporting with this bug report, but as you can see, there are a whole lot of other problems with the mouse input event tracking state machine that you have effectively implemented. 

I realize that you are not using formal programming methods such as an actual state machine, and instead you are just implementing an informal effective virtual state machine by defining several different event callbacks with jquery. The problem with the state machine that you have implemented is that it does NOT take into account the many possibilities that users expect it to handle, and that all other professionally implemented standard system desktop and application menus implement. 

One way of explaining it that I attempted was that the event that pops down your menus is the mouse up event, while the event that triggers your menu item is the click event. But the mouse down event comes BEFORE the click event is fully recognized, because the system has to wait a certain amount of time to see if there is a mouse up event soon enough after the mouse down event. But the system sends the mousedown event immediately, and you have implemented a mousedown handler that immediately pops down the menu, without waiting to see if there is a click event that activates the selected menu item. 

The act of popping down the menu immediately on the mouse down event without waiting for the corresponding mouse up event that triggers the menu item causes the "click" event that you're waiting for to trigger the menu item to be CANCELED. It is never delivered. The menu item that was highlighted under the cursor that you pointed at is never triggered. Because by the time the click event comes along, the menu is no longer on the screen. 

The problem is that you can't reliably combine "click" tracking with "mousedown"/"mouseup" tracking in that way. It results in flakey unreliable menus, as we have here. 

Now I will walk you through the problem I am describing with your menus again. Go to this page:

http://materializecss.com/forms.html

Scroll down to the "Select" section".

Look at the select labeled "Materialize Select". See the select under it labeled "Choose your option" which is underlined and has a down arrow on the right side. 

That is the select's pop up target area. 

Move the cursor over that area. Position the cursor exactly over the "Choose yhour option" label, so that it is exactly over the "o" in "your". 

Now CLICK up the menu, by pressing and releasing the mouse button quickly, without moving the mouse.

You will see that the menu pops up by animating. Now you are still pointing the mouse button at the same place, but the pop-up menu is positioned over the select target, with the same header label "Choose your option" displayed in about the same place (a few pixels off) in a gray color, and the menu items below it. The menu header label is not selectable, which is ok. When you move the cursor down into the first menu item "Option 1" without clicking the button yet, that item is highlighted. See how you can move the cursor between active menu items, and the menu item under the cursor will always be highlighted, and when you move outside of the menu, no items are highlighted. The system has not gone into text selection mode. So far, so good. 

Now there are two ways in which this menu tracking can go wrong, and first I will describe one, then the other. Menus must be able to properly handle all of these cases without ignoring user input or going into text selection mode, not just a subset. 

Here is one obvious failure case you can trigger after clicking up a menu: point at the "Option 1" item, then click the button slowly (not as slow as a "press and hold", but not so quickly that the system interprets it as a click). Try it again and again, each time clicking for a little longer. When you click really fast, the item is selected. Now try selecting a different item next, so you can be sure if the menu selection was actually changed. Try clicking slightly slower. Some times the new menu item will be selected. Sometimes it won't. That depends on how fast you clicked. The difference between clicking fast enough and not clicking fast enough is very tiny, extremely hard for you to accurately measure with normal human perception. If you were to video tape the action and play it back frame by frame, you would be able to measure what the click threshold was, but that is IMPOSSIBLE for a human being to do, and it is terrible for a user interface to have such a fine hair triggered ambiguity between triggering a menu item and not triggering a menu item. That kind of behavior is perceived by users as flakeyness and unreliability. If you tried to summon an elevator by pressing the button, but the button ignored you if you didn't press quickly enough, you would think the elevator was broken. Elevators don't have signs telling people to quickly press the button instead of pressing and holding it, or specifying that it is necessary to press and release the button in under 200 millisecond or whatever the system defined timeout is. And users have no way of reliably articulating a 199 millisecond press versus a 201 millisecond press, or perceiving the difference. A press is a press. Whether it's slow or fast should never make a difference. Sleepy senior citizens with slow reflexes must be able to use the interface, just as well as teenagers with quick reflexes and lots of energy. But your menus make a hair-triggered distinction between clicking "quickly" and clicking "slowly". And they totally don't support pressing and dragging, or pressing, holding the button down while looking at the screen and waiting to see the menu pop up before deciding where to point next, or any of many common ways of using menus that are universally supported and expected to work across all platforms. 

One more time, this time making the click even slower so it's like a "press and hold". The timeout of a "press and hold" event is much longer than a click event, so this is an extreme edge case that will ALWAYS demonstrate what is wrong about your menu tracking, by ALWAYS ignoring the user input. Point at the select label, then press and hold the button, and wait one second while the menu animates up. Now, while continuing to hold the button down, move the cursor downwards towards the "Option 1". Notice how the system has gone into text selection mode, and the text between the menu label you clicked on, and the menu item under the cursor, is highlighted to show you that it will select that text when you release the button. CLEARLY this is incorrect behavior. The user NEVER wants to select the menu labels. Proper menus should always lock out text selection by canceling the down event so it does not bubble up to the page and initiate a text selection gesture. That means you HAVE to handle the down event, not the click event, because you can't cancel text selection in a click event, because by the time it happens it is too late, and you never even get a click event if there is enough time after the down event. 

And here is another case that your menus handle incorrectly: dismiss the menu if it's already popped up. Now point at the select label that says "Choose your option". Now click quickly or slowly, it does not matter, to pop up the menu. Now move down to point to an option (make sure it's not the last option you select, so you will be able to see if the selection changed or not). Now click slowly (not so slow as a "press and hold", but slow enough that the system does not interpret it as a click). You will notice that your menu pops down IMMEDIATELY on the down event that begins the click event. And then when the click event finally comes along, it happens after the menu is already popped down, but ignored. If you put debugging log statements in your code, like I did when diagnosing this problem, you will see that THE CLICK HANDLER IS NEVER CALLED, although the mousedown handler that pops down the menus is obviously called (which you can tell without a log statement because the menu pops down, but you should put a log statement in there anywhere to prove it to yourself). This is exactly the case that this bug report was describing, although it's only the tip of the iceberg. 

I don't know how much more detailed an explanation I can give you, to convince you that there really is a problem with the way your menus are tracking, that causes horrible usability problems, and violates the principle of least astonishment, and frustrates users, and makes your menus flakey and unreliable. I would never publish a web site that used such flakey menus, and I was horrified to discover this problem right before launching my own web site. But as this bug report shows, I was able to come up with a simple patch that at least prevented the flakey behavior, if not the normal expected behavior for all cases, and never accidentally went into text selection mode as I have described.

These menus really need their input tracking code to be totally overhauled by someone who pays attention and is aware of all the possible edge cases and sequences of events that might happen. It's not enough to make a flashy demo that looks good in a screencast but can't stand up against normal users in the real work. 

If you think this isn't necessary, and that the current implementation is fine, then please have a talk with Brad Meyers, who is a professor and user interface researcher at CMU, who has worked there for decades, who I used to work for, who has published many papers and video tape demos about user interface input tracking, and who has implemented many user interface input tracking state machine himself. He understands how deep and complex the issues actually are, that may appear simple and trivial to you on the surface. 

His web page is:
http://www.cs.cmu.edu/~bam

His office is in Newell-Simon Hall 3517.

Brad and I will also refer you to the work of Bill Buxton, specifically his paper "Lexical and Pragmatic Considerations of Input Structures," Computer Graphics, January, 1983, (17)1, pp. 31-37.
http://dl.acm.org/citation.cfm?id=988586
http://www.billbuxton.com/lexical.html

Brad produced the "All the Widgets" video tape in 1990 for the ACM CHI 1990 conference in Seattle, for the express purpose of documenting standard practices and showing historical user interface techniques, so people like you don't have to incorrectly re-invent the wheel again and again without realizing all the nuances and edge cases you are expected to handle, so I am sure he will be thrilled to help you and give you more citations and examples. 

https://www.youtube.com/watch?v=9qtd8Hc90Hw
This was made in 1990, sponsored by the ACM CHI 1990 conference, to tell the history of widgets up until then. Previously published as: Brad A. Myers. All the Widgets. 2 hour, 15 min videotape. Technical Video Program of the SIGCHI'90 conference, Seattle, WA. April 1-4, 1990. SIGGRAPH Video Review, Issue 57. ISBN 0-89791-930-0.

**Comment by SimHacker** [comment] 2017-01-20 16:59
If you still don't understand what the problem is, I will make a screencast that demonstrates it. Is this explanation that I have given you so far detailed and explicit enough, or should I made a screencast demonstrating the problem?

**Comment by Dogfalo** [comment] 2017-01-20 21:50
I see the scenario you are talking about now, thanks for the explanation. I was under the wrong impression that you were talking about mobile. In the future, please keep the discussion more focused on reproduction of the problem. The issue here was that I was misunderstanding problem not that I do not believe or know good UI practices.

**Comment by SimHacker** [comment] 2017-02-09 19:45
I am attempting to fix some of these bugs I have reported, but I am finding many problems about the code that could not possibly have been intentional, and cause unfortunate unintended consequences and inefficiencies. 

First of all, pressing the button down and dragging should NEVER go into text selection mode.

It is incorrect to for the handler to catch "click" events instead of "mousedown" events, because then it passes mousedown events if you click slowly or just hold the mouse down. In general, you should never handle "click" in this situation, because you miss the common case of slow clicks, and of pressing down and moving with the button down, which normal selects properly handle, but materialize selects do not properly handle, because they go into text selection mode. 

The obvious fix for that problem is to modify the "click" handler of the $newSelect element to actually handle "mousedown" instead of "click", and then to cancel the default behavior which is to start a selection. But then it also has to manually invoke a focus, because you are depending on the default behavior of the mouse down to set the focus (click does not set focus, mousedown sets focus, but you were improperly handling click, and just stopping the propagation, but not canceling the default behavior). 

The old incorrect code was:

https://github.com/Dogfalo/materialize/blob/76a6ee49dff4049e8bcbac6d05f886b3da521a60/js/forms.js#L612

        'click': function (e){
          e.stopPropagation();
        }

The correct code should be:

        'mousedown': function (e) {
          e.stopPropagation();
          e.preventDefault();
          e.target.focus();
        }

The stopPropagation prevents the event from bubbling up to the container.
The preventDefault prevents the text selection mode from being started if you move the mouse before releasing the button, but it also prevents the element from being focused.
the focus manually focuses on the element, which causes the dropdown to be shown.

Unfortunately this only partially fixes the problem. Properly implemented dropdowns, like the browser default dropdowns, should hide when you click on the label again after clicking them up. But your original implementation and this fix is not able to do that: it just keeps the menu up after you click again and again in the label. That is incorrect behavior, which you can verify by experimenting with any default browser select. If you are going to replace the default browser selects, you should be as compatible with the way they track as possible, because there is a very good reason they track that way, and users expect them to work that way, so you should not disappoint them by implementing non-standard behaviors. 

More work needs to be done in order to properly track the mouse so that the menus are shown and hidden at the proper time, in response dow mouse up and down events, instead of tracking "click" events which are dependent on the duration of the click. If you will try using normal browser selects, you will find that at no time is their behavior dependent on the speed that you click: they trigger on mouse down and up events, not click events. 

The mechanism for hiding the dropdowns from the screen when the user clicks is broken and very inefficient. You are handling a click event on the window, which is called for EACH DROPDOWN, and is called EVERY TIME the user clicks ANYWHERE on the page, no matter if the dropdown is hidden or not. So you are needlessly executing a lot of code every time the user clicks anywhere on the screen, and it makes it very difficult to implement the logic required to properly dismiss the dropdown under the right circumstances by tracking mouse up and down events, instead of clicks. Here is the broken code that is called far too frequently, for every click on the page, times every select on the page:

https://github.com/Dogfalo/materialize/blob/76a6ee49dff4049e8bcbac6d05f886b3da521a60/js/forms.js#L630

      $(window).on({
        'click': function () {
          multiple && (optionsHover || $newSelect.trigger('close'));
        }
      });

You should NEVER use $(window).on unless you really mean for EVERY select to ALWAYS handle that event no matter if it's shown or not. And you should not be tracking the "click" event, because that is time sensitive: instead you should be tracking both the "mousedown" and the "mouseup" events, but ONLY while that particular dropdown is shown, not all the time, and not for every dropdown. 

In a properly implemented select like the built-in browser selects, if the "mousedown" event is not over the dropdown, it dismisses the menu AND stops tracking both the mousedown and mouseup event on the window. You should only ever have one handler for mousedown and mouseup active on the window at a time, and only while a dropdown is tracking. Never leave that handler active, or else it will be called all the time, and cause a lot of inefficiency and slow down ALL event tracking on the page. 

You will see that normal built-in browser selects work this way: click one up, then move outside of the select and the label, then press the button down but don't release it. You will see that it hides the dropdown on that mousedown event. BUT if you press and HOLD the mouse down over a menu item while the dropdown is shown, you will see that it does NOT hide the dropdown, but it keeps tracking until you RELEASE the button. Then when the button is finally released, if it is over an item, then the item is selected and the dropdown is hidden. But if it is not over an item, no item is selected and the dropdown is hidden. 

More work still needs to be done to bring your materialize selects in line with the standard way all other normal selects work, but getting rid of "click" handlers, triggering on the correct mousedown and mouseup events, and preventing the browser from entering text selection mode are but the first few steps. 

I will continue to work on fixing these bugs, because the current behavior is unacceptable and I can not publish my web site until these bugs are fixed.

**Comment by Dogfalo** [comment] 2017-10-10 00:20
Fixed in v1-dev

**Closed by Dogfalo** 2017-10-10 00:20 UTC
Labels: bug, component:Select

**Comment by AnasOkasha-chambaam** [comment] 2020-04-24 19:15
hi,
I faced the same problem and solve it.
I think that the problem is that $('#the-id-of-select') does not give you the element so you cannot get its value. It gives you an array of all the elements with the id that you typed.
so $('#the-id-of-select').value will be undefined.
I used $('#the-id-of-select')[0] to specify the first select box and it solved the problem for me.
