### ISSUE TITLE
Materialize styles the "naked" HTML tags

### ISSUE THREAD

**Issue by siriniok** [Dogfalo/materialize#1984] opened 2015-08-31 21:28 UTC
Maybe, it don't looks like issue, but styling HTML tags by selectors like `input[type="checkbox"]` and `select` results in a lot of conflicts with other stylesheets. For example, when I use materialize with ember cli, it conflicts with stylesheets of QUnit (snapshot attached). As you can see, tests page is  absolutely  unusable.

![32f18ea6-4d36-11e5-9ac2-43ec4d6b846d](https://cloud.githubusercontent.com/assets/6921765/9590120/593c9d28-503b-11e5-9c13-d0a5afd28b7d.png)

Original issue: https://github.com/mike-north/ember-cli-materialize/issues/227

**Comment by carlosperate** [comment] 2015-08-31 21:54
This is a duplicate of https://github.com/Dogfalo/materialize/issues/1659
Please comment on that issue to be able to maintain the tracker organised.

**Closed by carlosperate** 2015-08-31 21:54 UTC

**Comment by gorg84** [comment] 2016-07-31 21:54
Commissioner for Justice
