### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by DetlefPeters** [Dogfalo/materialize#3466] opened 2016-08-05 14:28 UTC
Hello,

I work for a German software engineering company and like your implementation of the Material Design Guidelines very much.

For the moment, just one question.

Are you going to add toggle buttons to your solution, as described in
https://material.google.com/components/buttons.html#buttons-toggle-buttons
in the near future?

Best regards,
  Detlef

**Comment by bertvh** [comment] 2016-08-17 13:38
Would also be interested in this one.

**Comment by bertvh** [comment] 2016-08-17 13:38
Duplicate of #3347

**Closed** 2017-04-03 00:12 UTC
